### ISSUE TITLE
Disclosure FAQ: Should the answers be landmark regions?

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria-practices#1002]
Due to the DL, DT DD structure being changed to a DIV structure I believe the  example for disclosure widgets should also be updated. Happy to do this if approved.

Example Disclosure (Show/Hide) for Answers to Frequently Asked Questions
https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-faq.html

Related to:

Accordion Example: Restructure to remove `dl` element #815https://github.com/w3c/aria-practices/issues/815

**Comment by jnurthen** [comment]
DL, DD and DT seems like the right structure to me. The role is not being overridden in this example so can you explain the rationale to change it?

**Comment by Decrepidos** [comment]
@jnurthen just checking if it should be, as you point out the semantics are not being overridden, so in the old printing proof reading term STET :-) Leave it as it is.

**Comment by Decrepidos** [comment]
In relation to this 

What is the difference between this Example Disclosure (Show/Hide)

Example on this page
https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-faq.html#ex_label

and

Accordion Example
https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

I don't quite get why one can have simple aria-expanded and aria-controls only while the accordion also includes role region and a different structure. Both essentially do the same thing.

I suggest a role of region is needed on the ‘disclosure (show/hide) as well for consistency.

**Comment by accdc** [comment]
I'm in favor of adding role=region plus aria-labelledby to map back to the triggering element, especially to handle cases where show/hide controls like these are nested.

**Comment by mcking65** [comment]
Related to #954

**Comment by a11ydoer** [comment]
@accdc please add/record your suggestion based on the discussion at APG meeting on Oct. 26.

**Comment by accdc** [comment]
Hi,
In looking at the APG examples for disclosures, they look good to me and I don't think these need to be marked up as regions. Disclosures are a simpler concept than that of accordions, in that the interaction does not require multiple triggering elements in different locations, even if nested, so definitive grouping isn't really an issue. The option is still there if needed for complicated scenarios, but this is likely rare to occur.
