### ISSUE TITLE
Image Carousel Example: Use button elements for slide controls and make rotation control always visible

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1007]
Based on feedback in issue #971, revise the [Feb 7, 2019 version of the Auto-Rotating Image Carousel Example](https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190207/examples/carousel/carousel-1/carousel-1.html)
so the pause button is always visible and the slide controls are implemented with button elements.

### Preview Link

The revised carousel can be seen in the [issue1007-visible-pause-carousel branch](https://raw.githack.com/w3c/aria-practices/issue1007-visible-pause-carousel/examples/carousel/carousel-1/carousel-1.html).

**Comment by mcking65** [comment]
Now resolved with commit 0ba3c1c. Thank you @jongund!!
