### ISSUE TITLE
Develop example of alert dialog design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#101]
Develop example of the [design pattern for alert dialog](http://w3c.github.io/aria-practices/#alertdialog).

#### Links to WIP in Evan's repo:

* [Alert dialog](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/alertdialog.html)
* [Modal dialog](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/dialog.html)

**Comment by dfkaye** [comment]
@mcking65 - I had been working on an example of this pattern recently when I found this issue - would any of the code in the following gist suit your needs?

see https://gist.github.com/dfkaye/31939cd9fd3d00be68ffd5ab42622a35

**Comment by mcking65** [comment]
Consider whether we need a separate folder or can add this to the dialog example folder.

**Comment by mcking65** [comment]
All, please, test Evan's new code. Here are links to pages in the Rawgit view of Evan's repo:

* [Alert dialog](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/alertdialog.html)
* [Modal dialog](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/dialog.html)

**Comment by mcking65** [comment]
Evan, I really like the simplicity of the approach for this example -- a discard text function.

Rather than an alert when there is no text to discard, seems like it would better demonstrate good practice to mark the button disabled. To include an alert, perhaps we put a 100 character limit on the field and then warn the person when they get to 90 with an alert and another alert when they get to 100. I suggest reasonably low numbers so it doesn't take a long time to experience the alerts.

**Comment by annabbott** [comment]
[Modal Dialog Example](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/dialog.html) > HTML Source Code: all text is displayed in red instead of black, blue and red like in [Alert Dialog Example](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/alertdialog.html) > HTML Source Code.

**Comment by annabbott** [comment]
No other issues noted with Modal Dialog Example with FF 60.0.1 and Chrome 66.0.3359.181 on Win10. No screen reader testing performed.

**Comment by annabbott** [comment]
Tested with FF 60.0.1 and Chrome 66.0.3359.181 on Win10.

[Alert Dialog Example](https://rawgit.com/sh0ji/aria-practices/alertdialog-example/examples/dialog-modal/alertdialog.html) > Role, Property, State, and Tabindex Attributes > aria-describedby="IDREF": remove bullet as there is only one statement for that row.

**Comment by annabbott** [comment]
No other issues noted with Alert Dialog Example with FF 60.0.1 and Chrome 66.0.3359.181 on Win10. No screen reader testing performed.

**Comment by annabbott** [comment]
Note about "No screen reader testing performed." above: currently unable to get any audio from either JAWS or NVDA.....grrrrrr...........

**Comment by annabbott** [comment]
Tested with FF 60.0.1 and Chrome 66.0.3359.181 on Win10.

Per Matt's 6/8/2018 email: 
In particular, for the modal dialog page, test the scrolling of the second layer dialog by:
1. Activate the add delivery address button to open the Add Delivery Address dialog.
2. Activate the verify address button to open the second layer dialog.
3. Scroll through the content of the the Verification Result dialog.
Expected result: You cannot see the lower level add delivery address dialog as you scroll the verification result dialog. Or, if you can, it does not also scroll when the verification result dialog is scrolling.

Confirmed expected result.

**Comment by sh0ji** [comment]
> Modal Dialog Example > HTML Source Code: all text is displayed in red instead of black, blue and red like in Alert Dialog Example > HTML Source Code.

This appears to be an issue with [the latest editor's draft from master](http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html). It's likely a separate issue.

**Comment by mcking65** [comment]
With commit 9c2cfca, this issue is now complete and we are ready for final review.
