### ISSUE TITLE
Guidance request:  for 3.3  Alert dialog - to cover SC 2.2.1

### ISSUE THREAD

**Issue by spanchang** [w3c/aria-practices#1011]
I have often come across action confirmation prompts / error message confirmations dialogs that disappear too quickly and generally trigger the default action without permitting users to review the message and select the desired action.
This is an SC 2.2.1 error IMO.
Please consider incorporating guidance for 3.3 Alert and Message Dialogs that is similar to the guidance for 3.2 Alert that states:
"It is also important to avoid designing alerts that disappear automatically. An alert that disappears too quickly can lead to failure to meet WCAG 2.0 success criterion 2.2.3".
Thanks,
Sailesh

**Comment by sh0ji** [comment]
Thanks for the feedback, @spanchang. This seems like the same issue as #756. Alright if we close this and track it in there?

**Comment by sh0ji** [comment]
Closing this. @spanchang, feel free to reopen if you don't think #756 covers the same issue.
