### ISSUE TITLE
Listbox with dynamic number of options

### ISSUE THREAD

**Issue by caseyjhol** [w3c/aria-practices#1015]
I'm the lead developer for the [bootstrap-select](https://github.com/snapappointments/bootstrap-select) plugin (a JS plugin that replaces select elements), and I'm in the process of making it more accessible. I've loosely modeled the ARIA implementation after the example here: https://w3c.github.io/aria-practices/examples/listbox/listbox-collapsible.html (a listbox with `role="option"` children).

So, I'm updating `aria-activedescendant` to match the ID of the currently navigated item, and that works great with a small number of items. Example: you navigate to an option and the screen reader says "Plutonium: 2 of 26." However, bootstrap-select supports elements with thousands of options, but for performance reasons, only around a maximum of 40 options are ever in the DOM at a given time (this works seamlessly, and it still appears as if there are thousands of options to the end user). So, even though there are 1000 options, because only 40 are in the DOM, the screen reader says "Plutonium: 2 of 40" instead of "Plutonium: 2 of 1000." Is there anything I can do short of including all of the elements? Something along the lines of `aria-descendentcount="1000"` would be awesome, but obviously a bit of a fringe case. Thanks!

**Comment by jnurthen** [comment]
You should be able to use `aria-posinset` and `aria-setsize` for this. See the example at https://w3c.github.io/aria/#aria-posinset

**Comment by caseyjhol** [comment]
Awesome! That looks perfect for my scenario. Sorry I missed that.

**Comment by jnurthen** [comment]
no problem
