### ISSUE TITLE
Add site navigation example that uses disclosure buttons that show lists of links

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1028]
Develop an example of a site navigation system that uses disclosure buttons that show and hide simple lists of links that is similar to the site navigation provided on [www.usa.gov](https://www.usa.gov).

1. Each disclosure button is in the tab sequence and activating it adds a list of links to the tab sequence.
2. To facilitate comparison to other site navigation patterns, replicate the Mythical University site structure that is demonstrated in the [navigation menubar example](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html).
3. Wrap the site navigation in a navigation region.
4. Instead of making each hyperlink in the navigation load a new page, reload the example page and inject new content into a content landmark region that is displayed just below the navigation region. In the content landmark region, include a heading with text that matches the link that was executed and a paragraph of text.
5. When a link is executed, add aria-current="page" to that link and remove it from the link that previously had it.
6. When the example page initially loads, the "About > Overview" page content should be displayed in main and that link should have aria-current.

#### Preview Link for WIP

[View disclosure navigation menu example in the issue1028-disclosure-menu-example branch](https://raw.githack.com/w3c/aria-practices/issue1028-disclosure-menu-example/examples/disclosure/disclosure-navigation.html)

**Comment by mcking65** [comment]
See excellent discussion of design decisions in the conversation thread of pull request #1036.

**Comment by mcking65** [comment]
@@smhigley, I am done with editorial revisions to the issue1028-disclosure-menu-example feature branch.

You may want to review the test code. I added documentation for aria-current, which currently does not have a test. I also expanded the documentation for arrow keys, home, and end. Now, there are multiple rows with the same data-test-id, which is OK. However, it might be good to sanity check to make sure the testing covers all the documented behaviors.

My revisions to the accessibility features section were the most significant. They are worth a close read. I attempted to adjust wording and rationale to be understandable by a broader audience. I'm curious if you agree whether I achieved that objective.

**Comment by mcking65** [comment]
I am wondering if the checkbox for optional navigation keys should be unchecked by default. Given there are both side effects and extra code driven by the optional behaviors, shouldn't they be off by default?

**Comment by smhigley** [comment]
@mcking65 I cleaned up the git history and updated the w3c branch, then opened a PR here: https://github.com/w3c/aria-practices/pull/1070.

I addressed your comments on aria-current and the `package.json` changes on the PR. Thanks!

**Comment by mcking65** [comment]
Thank you thank you @smhigley !
