### ISSUE TITLE
Develop datepicker calendar grid dialog example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1046]
A common date input pattern includes an edit field for a date string with an adjacent button that opens a calendar overlay. The calendar enables users to choose a date, which closes the overlay and populates the edit field. Unlike a combobox datepicker, Both the edit field and the button that opens the overlay are in the page Tab sequence and the edit field does not include up/down arrow key support for opening the overlay.

This issue is for tracking development of an example of this pattern.

The edit field is a normal HTML input with type text. It has aria-describedby referencing a description of the date format. Optionally, it could include some input validation. 

The button that opens the overlay is a normal HTML button.

The overlay implements the modal dialog pattern, and the calendar inside the dialog is implemented using the grid pattern.

#### Preview Link for WIP

You can comment on work in progress in pull request #1054 and view the [example in the issue1046-datepicker-dialog branch](https://raw.githack.com/w3c/aria-practices/issue1046-datepicker-dialog/examples/dialog-nonmodal/datepicker-dialog.html)

**Comment by jongund** [comment]
@mcking65 so you want this dialog to be non-modal? Right now it is modal, so you want more of a disclosure pattern here.  The calendar just becomes part of the page, essentially not a dialog at all, but the gird just hides and shows itself with the button?

**Comment by abaksha-sc** [comment]
Is it "combobox" or not?
[This example](https://raw.githack.com/w3c/aria-practices/issue34-date-picker-examples/examples/combobox/aria1.1pattern/datepicker-combobox.html) from issue #34 says "yes", but your [link from head message](https://raw.githack.com/w3c/aria-practices/issue1046-datepicker-dialog/examples/dialog-nonmodal/datepicker-dialog.html) doesn't include role combobox.
I'm confused...

**Comment by jongund** [comment]
@abaksha-sc This example will NOT be using the combobox pattern.   
@mcking65 But for a non-modal dialog box once the keyboard focus is in the date picker grid it should stay in the grid until the grid is closed?

**Comment by abaksha-sc** [comment]
Sorry for my understandable question.
But I asked if datepicker should be implemented with "combobox" pattern in general.
I see two implementations of datepicker with different patterns and I am confused which one should be  used as example.
Or this thread is just about calendar grid?

**Comment by jongund** [comment]
@abaksha-sc There is no one way to implement a feature to pick a date.   The ARIA Authoring practices will have several examples illustrating different techniques, right now the goal for the next release will be hopefully three examples:

1.  A datepicker using a spin buttons (issue125)
1. A non-modal dialog using a calendar grid (Issue 1046)
1. A the ARIA 1.1 or ARIA 1.0 combobox pattern with a modal dialog box with a calendar grid (Issue 34)

**Comment by abaksha-sc** [comment]
@jongund , oh, that's great! Thanks you!

**Comment by mcking65** [comment]
Based on offline discussion, we have concluded this should be coded as a modal dialog rather than a non-modal dialog. Functionally, even for mouse users, it will behave as a modal, i.e., clicking outside the dialog closes the dialog. The only non-modal aspect is that the background does not get visibly dimmed. From a practical perspective, this is primarily a asthetic aspect of the implementation. So, using aria-modal="true" seems most appropriate.

I'm revising the top comment in the issue to reflect this decision.

**Comment by mcking65** [comment]
Complete with commit c55e152. @jongund, thank you very, very much for all your work on this!!
