### ISSUE TITLE
increase contrast for carousel text

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-practices#1063]
A user shouldn't have to hover over or focus text to be able to read it, as is currently the case when the white text appears over images that have a lot of light colors in them.  An overlay providing sufficient contrast ratio should always be visible.  One way to determine appropriate contrast levels for content whose brightness may vary depending on context might be to use an image that is the same color as the text to start with, and then increase the overlay opacity until the foreground to background contrast ratio meets targets.  The idea is that if the contrast ratio is met in that instance, then, no matter what image is used after that, it should meet or exceed the contrast ratio requirements.  That works, doesn't it?

**Comment by mcking65** [comment]
@robfentress

We are making [improvements to the carousel example](https://raw.githack.com/w3c/aria-practices/issue1007-visible-pause-carousel/examples/carousel/carousel-1.html) in PR #1018.
I think they address this concern.
Please comment in PR #1018 if you still have concerns.
