### ISSUE TITLE
drop aria-controls from components where controlled content immediately follows it

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#1068]
There will be a long term discussion of aria-controls in ARIA 1.3, 
https://github.com/w3c/aria/issues/995

but I think in the short term we could remove it from components where the controlled content immediately follows the controller.

[accordion](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html)

[Disclosure](https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure)

[maybe? Auto-Rotating Image Carousel](https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1/carousel-1.html)

etc...

**Comment by mcking65** [comment]
For reasons given in my [comment in issue 995](https://github.com/w3c/aria/issues/995#issuecomment-508850436), I do not think we should do this, and I'm closing.

@DavidMacDonald, if you disagree and would like broader discussion, please re-open this issue and I will add it to a meeting agenda. I'd be happy to have you join the discussion as well :)
