### ISSUE TITLE
Update section on providing accessible names and descriptions for ARIA 1.2

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1077]
* Add guidance on new label, legend, and fieldset roles.
* Names are prohibitted on caption, code, deletion, emphasis, insertion, paragraph, presentation, strong, subscript, superscript.
* Names will also be prohibitted on generic role when it is added to ARIA 1.2.

**Comment by jnurthen** [comment]
notes label, legend and fieldset are not necessary for 1.2

**Comment by mcking65** [comment]
Re-opening for blockquote, meter, and timer.
