### ISSUE TITLE
Develop example of the tree view design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#109]
The tree view design pattern is at:
http://w3c.github.io/aria-practices/#TreeView

@jongund has developed first versions of 4 examples that are merged into master. Remaining work includes:

- [x] treeview-1a.html: Implement [latest example template][template] and title as "File Selector Tree Example 1".
- [x] treeview-1b.html: Implement [latest example template][template] and title as "File Selector Tree Example 2".
- [x] treeview-2a.html: Implement [latest example template][template] and title as "Navigation Tree Example 1".
- [x] treeview-2b.html: Implement [latest example template][template] and title as "Navigation Tree Example 2".
- [x] Add the following note to File Selector Tree Example 1: 
> Some browser and assistive technology combinations may not compute or report correct nesting level and position information if it is not explicitly provided using <code>aria-level</code>, <code>aria-setsize</code>, and <code>aria-posinset</code>.
> If testing reveals support gaps, use explicit declaration of these attributes as demonstrated in File Selector Tree Example 2."
- [x] Add the following note to Navigation Tree Example 1: 
> Some browser and assistive technology combinations may not compute or report correct nesting level and position information if it is not explicitly provided using <code>aria-level</code>, <code>aria-setsize</code>, and <code>aria-posinset</code>.
> If testing reveals support gaps, use explicit declaration of these attributes as demonstrated in Navigation Tree Example 2.

[template]: https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html

**Comment by jnurthen** [comment]
Edit example 1a and 2a to provide a note to state that not providing the supplemental attributes may not be supported in some browser and AT combinations. if after testing it is determined that these are not supported then provide the attributes as shown in examples (1b or 2b - as appropriate)

**Comment by mcking65** [comment]
The to-do list in the first comment is now complete. Closing this issue.
