### ISSUE TITLE
Develop example of menu or menubar design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#110]
The menu or menu bar design pattern is at:
http://w3c.github.io/aria-practices/#menu

**Comment by a11ydoer** [comment]
pull request for menubar example was created and is ready for the review.

**Comment by michael-n-cooper** [comment]
I need to ask the editors to remove the extensive copyright statement 
and legalese from the pull request after approving, or you to update the 
pull request to remove it. It goes way beyond what we can put in a W3C 
publication without legal review.

**Comment by a11ydoer** [comment]
@michael-n-cooper Thanks for the comment. do you want me to remove all the copyright statement or leave some? do you have any copyright template I can refer to?

**Comment by a11ydoer** [comment]
I added revised menu bar examples.

**Comment by mcking65** [comment]
Opened issues #144 and #145 for review of the menubar examples.

@a11ydoer, thank you very, very much for your work on this issue!!

Closing this issue.
