### ISSUE TITLE
Set up Greenkeeper on aria-practices

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1101]
Configure [greenkeeper](https://greenkeeper.io/) for aria-practices.

To do:
- [x] The Greenkeeper github app is install for the w3c organization, but someone with admin settings needs to enable it for aria-practices. Route to enable:
    - [w3c](https://github.com/w3c/)
    - Settings
    - Installed Github Apps
    - GreenKeeper
    - Configure
    - Add aria-practices to list of repos
- [x] Configure steps can be made by someone with access to w3c/aria-pratices after that

**Comment by spectranaut** [comment]
@mcking65 Do you have admin access to the w3c, or can you ask someone to enable Greenkeeper?

**Comment by michael-n-cooper** [comment]
Thanks for the detailed procedure, Greenkeeper is now enabled for the aria-practices repo.
