### ISSUE TITLE
Develop example of the meter

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1105]
Develop an example of an implementation of the meter pattern using the new ARIA 1.2 meter role. It would be helpful if it illustrated a scenario where HTML meter is insufficient.

Related to #979.

**Comment by a11ydoer** [comment]
Example can be found here. 
https://rawcdn.githack.com/w3c/aria-practices/1f7d940ca9872ff2f240c65ce4520338fbdbd3c6/examples/meter/meter.html

**Comment by carmacleod** [comment]
Question: meter isn't keyboard interactive, so maybe it shouldn't have `tabindex="0"`?

**Comment by carmacleod** [comment]
Should probably have a visible label instead of using `aria-label`?

**Comment by scottaohara** [comment]
suggestions:
the meter has an aria-label of "disk usage" but as there's no way to infer that from the visual alone it'd be better to have visible text and use aria-labelledby.

changing the color of the meter as it approached max value / capacity would be another way to distinguish this from a progress bar.
