### ISSUE TITLE
Add roles to structural roles section: associationlist, associationlistitemkey, associationlistitemvalue, code, emphasis, strong, subscript, superscript, time

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#1106]
Based on the assumption these roles should not be used in practice, ie, their HTML equivalence should always be used, add the following roles to the APG 1.2 structural role section:

* associationlist
* associationlistitemkey
* associationlistitemvalue
* code
* emphasis
* strong
* superscript
* subscript
* time

**Comment by mcking65** [comment]
@a11ydoer, oops, right after I assigned James, I noticed you unassigned James ... confused. Should James not be assigned?

**Comment by jnurthen** [comment]
Now this is merged I can close it right?
