### ISSUE TITLE
Aria 1.1 combo box example 3 alt + down arrow prevents exploration

### ISSUE THREAD

**Issue by feerrenrut** [w3c/aria-practices#1126]
Context:
"Example 3: List with Inline Autocomplete" on page https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

Tested with FireFox 68.0.1

Pressing `alt+down arrow` to expand the combo box, automatically selects the first item. This then filters the list of options, the rest of the options in the combo box can no longer be explored.  The behavior of `down arrow` alone allows browsing these options in the way that I would expect.

**Comment by JAWS-test** [comment]
I wouldn't necessarily regard this as an error, because ALT+Down arrow is not part of the standard operation. The W3C Authoring Practices only says: "Alt + Down Arrow (Optional): If the popup is available but not displayed, displays the popup without moving focus" (https://www.w3.org/TR/wai-aria-practices/#combobox) and that's not the case here.

**Comment by feerrenrut** [comment]
I'm not complaining that "it isn't implemented", I'm complaining that it is, and the behavior isn't what I would expect. If this is supposed to serve as an example of for web developers of "how you do it" then I think the behavior should be right.

> "Alt + Down Arrow (Optional): If the popup is available but not displayed, displays the popup without moving focus"

My interpretation of this is, that because it is optional perhaps nothing will happen when I press `Alt + Down Arrow`. If something does happen, then the popup will be displayed, focus won't change. Because the spec does not mention the value changing on the text box, I consider this unexpected behavior. This stands out to me because it doesn't match the behavior of similar native controls, such as the run dialog in windows. 

Try the following example to see the difference: https://jsfiddle.net/ou4j0tnh/

**Comment by ZoeBijl** [comment]
Thank you for the report @feerrenrut, I’ll have a look.

**Comment by a11ydoer** [comment]
Hi @feerrenrut 

Above "list with inline autocomplete" example is upgraded into "[Editable combobox With List Autocomplete example](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-list.html)"

[Reference](https://w3c.github.io/aria-practices/#combobox)
"Editable Combobox with List Autocomplete: An editable combobox that demonstrates the autocomplete behavior known as list with manual selection."

I tested the key, Alt+ Down arrow, which is Option + Down arrow on mac and it bebaves as expected.  alt+ down arrow opens the list box without moving focus or changing selection.

**Comment by feerrenrut** [comment]
Thanks @a11ydoer
