### ISSUE TITLE
Aria is not defined

### ISSUE THREAD

**Issue by dalipkumar703** [w3c/aria-practices#1131]
Trying to implement combobox using html/css/javascript. But saying aria is not defined. any suggestion?
https://repl.it/@dalipkumar703/FairLameDebuggers

**Comment by jnurthen** [comment]
A few problems with your code:
- You need utils.js
- You need to remove the code which is trying to add event listeners on things which are not in the page. You only have example 1 but still have code for examples2 and 3

**Comment by dalipkumar703** [comment]
Thanks for guidance :) @jnurthen . It is working now.
