### ISSUE TITLE
example.js sourceCode.make() script strips ID attributes when generating HTML source code for example pages

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#115]
The code that is put into the example div is missing ID attributes.

**Comment by karlgroves** [comment]
+1 on this issue.

Just noticed it on examples/radio/radio.html. The `<h3>` element that should be referenced via `aria-labelledby` has no ID

**Comment by mcking65** [comment]
I assume here that you are talking about the scripts that generate the content for the HTML source section on the example pages. They are in [aria-practices/examples/js/examples.js](https://github.com/w3c/aria-practices/blob/master/examples/js/examples.js).

I believe Jon wrote that script so I am assigning this issue to him. 

@jongund, It would also be good to fix the comments in the example.js file as well.
