### ISSUE TITLE
Date picker spin button example broken in Safari

### ISSUE THREAD

**Issue by backwardok** [w3c/aria-practices#1151]
The [example for the `spinbutton` role](https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/datepicker-spinbuttons.html) works well in Chrome, but has a javascript error in Safari. 

On load, there's a SyntaxError: `The string did not match the expected pattern.` on this line in [spinbutton-date.js](https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/js/spinbutton-date.js):
```domNode.querySelector('[role="spinbutton');```

My guess is that Chrome is being generous with the selector here and Safari is breaking because it's technically an invalid selector. It should be `domNode.querySelector('[role="spinbutton]');` (it was missing the closing right bracket)

**Comment by JAWS-test** [comment]
Further problems at https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/datepicker-spinbuttons.html:
* When increasing the number for the day over 31, "NaN" is displayed.
* When decreasing number for the day below 1, the top number freezes at 31 and the two bottom numbers become negative.

**Comment by JAWS-test** [comment]
JAWS outputs: "To set the value use the Arrow keys **or type the value**", because normally free text input in spin button fields is possible. But not here. Maybe readonly has to be used? Or the text input is possible?

**Comment by backwardok** [comment]
Verified that the issue was not happening in Chrome, Firefox, and Edge, but is also happening in IE11. Working on a fix for this specific issue

@JAWS-test can you file separate issues for the other things you're finding?

**Comment by backwardok** [comment]
@JAWS-test made a fix for the issue with the NaN: https://github.com/w3c/aria-practices/pull/1154

**Comment by JAWS-test** [comment]
@backwardok 

> can you file separate issues for the other things you're finding?

https://github.com/w3c/aria-practices/issues/1155

Thank you so much for fixing the other problems so quickly!

**Comment by mcking65** [comment]
Thanks to @backwardok, this is fixed with commit e451c93!
