### ISSUE TITLE
Datepicker spinbutton example: JAWS instructions assume  text input is available

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria-practices#1155]
https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/datepicker-spinbuttons.html and http://w3c.github.io/aria-practices/examples/spinbutton/datepicker-spinbuttons.html:

JAWS outputs: "To set the value use the Arrow keys **or type the value**", because normally free text input in spin button fields is possible (e.g. for the HTML element <code>input type=number</code>). But not here. Maybe <code>readonly</code> has to be used? Or should text input always be made possible? Or is it a JAWS error?

Note: <code>readonly</code> for <code>input type=number</code> causes the whole element to be read-only, i.e. it cannot be operated using arrow keys

**Comment by mcking65** [comment]
This is a JAWS bug. JAWS is providing incorrect information. The implementation of the spin button structure and semantics are correct and contain all the semantics necessary for JAWS to provide correct information to the user. The JAWS code is assuming that spinners all have an edit field, which is not correct.

You are correct that aria-readonly is not appropriate because the value can be changed.

Closing as not for practices.

**Comment by patrickhlauke** [comment]
are there examples of spinners without edit field (assuming only in native apps, as `<input type="number">` seems to generally be implemented with an editable text field in browsers)?

**Comment by JAWS-test** [comment]
The ARIA specification makes it difficult for the screenreader here, because the HTML element spinbutton (input type=number) is always an input field with the possibility of free text input, but the corresponding ARIA element is not in every case. 

https://w3c.github.io/html-aam/ then says about to the HTML element:

> If implemented as a spin button, use WAI-ARIA mapping for spinbutton. 
> If implemented as a text input, use WAI-ARIA mapping for textbox.

But I don't understand how an input type=number should be a spin button and no text input. I also wonder how a user of assistive technology should correctly recognize the role of input type=number when mapped to text input?

**Comment by scottaohara** [comment]
the html `input=number` is a composite element with spin button capabilities and increment/decrement keyboard functionality.

i think the aria practices example is interesting, as it seems a combination of what i'd expect to be announced as a "picker" on iOS (as it visually resembles picker UIs) but with the addition of up/down arrows to increment and decrement like a spinbutton.
