### ISSUE TITLE
Avoid language changes in alert example

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria-practices#1163]
https://w3c.github.io/aria-practices/examples/alert/alert.html

The language change within live regions is generally or at least partially ignored by assistive technology. Therefore it should be avoided. The language change in the alert example suggests to web developers that this is an acceptable practice. 

I suggest to use a pure English text without language change in the alert example.

See: https://github.com/FreedomScientific/VFO-standards-support/issues/8, https://github.com/w3c/aria-practices/issues/1162,

**Comment by ZoeBijl** [comment]
Tested with VoiceOver and JAWS both of which handle this example just fine. If they’re not speaking languages it means that the speech synthesizers for those languages aren’t installed on your machine. If you find issues with other screen readers please re-open this issue with more details.

**Comment by JAWS-test** [comment]
For JAWS it is not true: https://github.com/FreedomScientific/VFO-standards-support/issues/8#issuecomment-527444298.  The language is output correctly while reading, but never in the live region. This is a well-known bug in JAWS

**Comment by JAWS-test** [comment]
To make matters worse, JAWS cannot output the Japanese and Korean characters at all. Instead, question marks are output with a comma between them. So this is really not a meaningful output. And JAWS doesn't know the language ko and only outputs "ko". Can you please reopen the ticket?

![alert](https://user-images.githubusercontent.com/52748763/65142917-08011300-da14-11e9-826f-962fab61d292.jpg)

**Comment by patrickhlauke** [comment]
do you have the relevant language packs installed in windows?

**Comment by JAWS-test** [comment]
@patrickhlauke: As I already wrote, the output is correct if the message is read with the arrow keys. The output is only wrong within the live region. And yes, this is a JAWS bug that has existed for years and is documented: https://github.com/FreedomScientific/VFO-standards-support/issues/8

**Comment by patrickhlauke** [comment]
well then it's a jaws bug. not a fault of aria practices...

**Comment by JAWS-test** [comment]
I never doubted it was a JAWS bug. I only think it would make sense if the examples in APG were designed to avoid as many mistakes as possible. I'm also wondering which screenreader simultaneously outputs the Latin, Japanese, and Korean characters correctly?

**Comment by ZoeBijl** [comment]
It’s correct that neither VoiceOver nor JAWS read all the languages in the live region. However, as Patrick said, this is not an ARIA Authoring Practices error.

None of the code in this example is invalid.

**Comment by JAWS-test** [comment]
@ZoeBijl The code isn't wrong, but it doesn't work. And I think it would be good if the APG contained code that is known to work best. This is not the case with the alert example for 2 reasons:
1. language change in live region is not output
2. unknown characters are not output. 

A developer who sees the example might therefore assume that it is not a problem to implement a live region with language change. But it is a problem.
Furthermore, AccName seems to have the problem that the lang attribute is not considered (https://github.com/w3c/accname/issues/56). Therefore, it is not only a bug of AT, but also a lack of specification. 

Translated with www.DeepL.com/Translator

**Comment by ZoeBijl** [comment]
This is no longer a productive conversation. Locking it.
