### ISSUE TITLE
datepicker has insufficient contrast

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#1170]
Consider bumping the icon color up to past 3:1 and the header and footer blue background to 4.5:1

![image](https://user-images.githubusercontent.com/2365411/64725673-134bc000-d4a3-11e9-808c-de13aa0aa217.png)

I suggest #008EA2 for the icon
and #005793 for the header and footer background.

They are fairly random value suggestions, but they at least pass.

**Comment by JAWS-test** [comment]
I have already noted most of the contrast problems: https://github.com/w3c/aria-practices/issues/1132

**Comment by ZoeBijl** [comment]
Fix for this is in PR: https://github.com/w3c/aria-practices/pull/1172
