### ISSUE TITLE
Recommend adding type="button" in Tabs examples

### ISSUE THREAD

**Issue by ptrin** [w3c/aria-practices#1184]
While using some code from [Example of Tabs with Automatic Activation](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) I noticed that the `<button>` tags don't have the `type="button"` attribute. The example should include the attribute since [the default behaviour is to submit a form](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes).

**Comment by ZoeBijl** [comment]
This is a good point. I don’t think it necessarily changes anything in the example. But it’s good practice to follow [the specification](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)! Will fix.
