### ISSUE TITLE
Question about the use of "menubar" role in navigation web menu example

### ISSUE THREAD

**Issue by kantoche** [w3c/aria-practices#1195]
Hi,

I'm surprised to notice the use of "menubar" role in navigation web menu example :
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html

According to WAI-ARIA spec, "the menubar role is used to create a menu bar similar to those found in Windows, Mac, and Gnome desktop applications" (https://www.w3.org/TR/wai-aria-1.1/#menubar) whereas the menu role "is often a list of common actions or functions that the user can invoke". The menu role seems more appropriate to enhance a web menu than the menubar role.

So, why did you choose the menubar role for this example?

**Comment by JAWS-test** [comment]
> Menubar: A presentation of menu that usually remains visible and is usually presented horizontally. https://www.w3.org/TR/wai-aria-1.1/#menubar

As far as I have understood, the difference between `menu` and `menubar` is as follows:
* menu: not permanently visible, therefore used for submenus, context menus, "aria-haspopup"-menus (e.g. https://w3c.github.io/aria-practices/#menubutton)
* menubar: permanently visible, used for menus where the menu items are visible. Can contain submenus with `role=menu`.

**Comment by kantoche** [comment]
You're right, I'm focusing on the purpose of the roles in the ARIA specification, but the way they work explains their use in the example.

**Comment by mcking65** [comment]
@JAWS-test is correct.

Widget roles describes semantics and expected interaction pattern. In some cases, the interaction is also dependent on a characteristic of presentation, such as persistence.

Menubars are persistent; they do not need another element to trigger their availability. A menu needs to be opened by or from another element.

Closing as answered. Feel free to reopen if this answer is not sufficient.
