### ISSUE TITLE
Accordion.js does not correctly trigger a subsequent accordion in IE11

### ISSUE THREAD

**Issue by jwheron** [w3c/aria-practices#1206]
We have a page going to production that uses Bootstrap tab panes and multiple accordions to break apart complex content into a process that (we hope) users will benefit from. During testing, a user (using IE 11) navigated to a subsequent tab and noticed that none of the accordions trigger. We later found that all accordions past the first one fail to trigger in Internet Explorer.

IE reports line 109 as producing an error (no "forEach" defined for the accordion prototype). In testing, I found that changing line 109 from:
`accordion.querySelectorAll('.accordion-trigger').forEach(function (trigger) {`
to
`Array.prototype.slice.call(accordion.querySelectorAll('.accordion-trigger')).forEach(function (trigger) {`
completely restored functionality.

**Comment by JAWS-test** [comment]
Do you mean the example at http://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html? For me it works with the keyboard and mouse in IE 11.

**Comment by ZoeBijl** [comment]
@jwheron do you mean to say you dropped APG code into production?

**Comment by mcking65** [comment]
Closing b/c APG task force has dropped IE support.
