### ISSUE TITLE
Update form landmark region example to make a label required for ARIA 1.2 requirements

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1208]
@mcking65 @jnurthen 

Based on changes to the `form` role in ARIA 1.2 the practices landmark documentation and examples need to be updated to make the label required.

**Comment by dotjay** [comment]
I believe this issue needs to be reopened, as I've found two pages of the APG that don't appear to have been updated to reflect the [ARIA 1.2 requirement of labels for form landmarks](https://www.w3.org/TR/wai-aria-1.2/#form).

The [relevant section of the Landmark Regions page](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/#aria_lh_form) says that `form` landmarks "should" have labels, and not "must". I've checked the repo in case changes are pending, but [the wording is the same](https://github.com/w3c/aria-practices/blob/f163e7af3b71f6cbeafc48067ee98f4644c25101/content/practices/landmark-regions/landmark-regions-practice.html#L277C46-L277C52).

<img width="968" alt="Image" src="https://github.com/user-attachments/assets/e8f545b1-9d53-4d43-8a6f-b13e3fc001df" />

The [Form Landmark Example](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/form.html) also uses the same wording, also [reflected in the repo](https://github.com/w3c/aria-practices/blob/f163e7af3b71f6cbeafc48067ee98f4644c25101/content/patterns/landmarks/examples/form.html#L84).

<img width="678" alt="Image" src="https://github.com/user-attachments/assets/fe9def89-d12b-4218-aa49-aed0ae83fb29" />

On both pages, the line: 
A `form` landmark **should** have a label to help users understand the purpose of the form.

Needs to change to read: 
A `form` landmark **must** have a label to help users understand the purpose of the form.
