### ISSUE TITLE
Toggle button shouldn't change the label.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#121]
Section 2.6 says this:

> Important: the label on a toggle button should never change when the state changes. In this example, when the pressed state is true, the label should not change to "Unmute"" or "Muted."

I understand that it is the "state" that is changing, but what is wrong with toggling between mute and unmute on the label, instead of having a button that says something like "mute, pressed"? I think a label swap is super easy to understand for developers and end users. Could this warning be overly academic?

**Comment by jnurthen** [comment]
To me a button that says "mute - pressed" means that the content is muted as the mute button is pressed. When you are changing labels what this actually means is that the content is NOT muted. This is super confusing.
Swapping labels is fine. If you want to go that route then it is NOT a toggle button, it is just a button. Doing this is fine but you should not add aria-pressed

We should clarify this in the document.

**Comment by mcking65** [comment]
Would changing the text as follows address this issue?

Toggle button: A two-state button that can be either off (not pressed) or on (pressed). To tell assistive technologies that a button is a toggle, specify a value for the attribute aria-pressed.
For example, a button in an audio player labeled “Mute” could indicate that sound is muted by setting the pressed state true. 
Important: it is critical the label on a toggle does not change when its state changes. In this example, when the pressed state is true, the label should remain “Mute” so a screen reader will say something like “Mute toggle button pressed”. Alternatively, if the design called for the button label to change from “Mute” to “Unmute,” the aria-pressed attribute would not be needed.

**Comment by DavidMacDonald** [comment]
Agree

**Comment by mcking65** [comment]
Changed the warning to use the above agreed upon text.
