### ISSUE TITLE
Update Naming and Describing section for new naming mechanisms

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#1212]
Add guidance on new label, legend, and fieldset roles.

( split from #1077  )

**Comment by zcorpan** [comment]
I see these roles in the aria spec that are not in aria-practices:

* `associationlist`
* `associationlistitemkey`
* `associationlistitemvalue`
* `blockquote`
* `label`
* `legend`
* `meter`
* `time`

`fieldset` is not currently in aria. https://github.com/w3c/aria/issues/875

**Comment by jnurthen** [comment]
The only ones which are likely to make ARIA 1.2 at this time are

- blockquote
- meter
- time

The rest are not currently in the stable branch of ARIA.
