### ISSUE TITLE
Combobox with dialog: is the dialog necessarily modal?

### ISSUE THREAD

**Issue by 0ddfell0w** [w3c/aria-practices#1215]
Should I extrapolate from the following quotations that combobox dialogs need to be modal, or is it only that the keyboard interactions (e.g. trapping focus) are the same as for modal dialogs?

> The dialog implements the keyboard interaction defined in the modal dialog pattern.
-[APG Combobox](https://www.w3.org/TR/wai-aria-practices#combobox)

and

> The roles, states, and properties for popup elements are defined in their respective design patterns [...] [Dialog Roles, States, and Properties](https://www.w3.org/TR/wai-aria-practices/#dialog_roles_states_props)

(where the link takes you to the states and properties expected of modal dialogs, including aria-modal)

Is there an expectation that the rest of the page will be inert when the dialog is expanded? Or would a non-modal dialog (#59 ) be appropriate? I understand there might be some hard to avoid ambiguity due to the non-modal dialog pattern is not complete.

**Comment by 0ddfell0w** [comment]
Given this note in the Dialog states and properties section, it would seem *very opinionated* to suggest that combobox dialogs should be modal

> NOTE
> Because marking a dialog modal by setting aria-modal to true can prevent users of some assistive technologies from perceiving content outside the dialog, users of those technologies will experience severe negative ramifications if a dialog is marked modal but does not behave as a modal for other users. So, mark a dialog modal only when both:
> Application code prevents all users from interacting in any way with content outside of it.
> Visual styling obscures the content outside of it.
> The aria-modal property introduced by ARIA 1.1 replaces aria-hidden for informing assistive technologies that content outside a dialog is inert. However, in legacy dialog implementations where aria-hidden is used to make content outside a dialog inert for assistive technology users, it is important that:
> aria-hidden is set to true on each element containing a portion of the inert layer.
> The dialog element is not a descendant of any element that has aria-hidden set to true.
- https://www.w3.org/TR/wai-aria-practices/#dialog_roles_states_props

**Comment by mcking65** [comment]
>Should I extrapolate from the following quotations that combobox dialogs need to be modal, or is it only that the keyboard interactions (e.g. trapping focus) are the same as for modal dialogs?

Only the keyboard behavior of trapping.

You are right that it would be far too opinioniated to suggest that comboboxes only open true modals. And, it would help if we had the non-modal pattern and examples.
