### ISSUE TITLE
Draft listbox design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#122]
The listbox pattern can be found at:
http://w3c.github.io/aria-practices/#Listbox

It is largely complete. Incomplete work includes:
1. 2 links in the notes to sections that have not yet been drafted.
2. There are several sentences that include "author should" language that should be revised to avoid normative sounding phrasing.

#### Requested reviews

- [x] Review by @jnurthen  
- [x] Review by @accdc 
- [x] Review by @annabbott

**Comment by mcking65** [comment]
@jnurthen, @annabbott, @a11ydoer, @accddc
James, Jemma, Ann, Bryan,

The list of changes I made in the master branch to the 
[listbox pattern](https://rawgit.com/w3c/aria-practices/master/aria-practices.html#Listbox) 
for this issue are described in my statement for commit 7cdb9f3.

Given these are all editorial changes, I have committed them in master and not added a feedback link in the document itself. Nonetheless, I want to ensure multiple task force members have reviewed them before I close this issue. Please follow the above link to master in rawgit and have a look. Thanks!!

**Comment by accdc** [comment]
The Listbox pattern looks good to me in the APG doc. I assume the Listbox demo though is still being worked on? It's not working at the moment in my browser.

**Comment by jnurthen** [comment]
Matt, I suggest changing
When screen readers present a listbox, they render the name, state, and position of each option in the list.
to
When screen readers present a listbox, they may render the name, state, and position of each option in the list.
I'm not sure the position is always rendered by a screen reader - adding may provides the ability to not always render the position in the list.

**Comment by jnurthen** [comment]
other than that looks good to me.

**Comment by annabbott** [comment]
Listbox Examples includes comment at top: "This example page is incomplete; it is not ready for review. When ready, feedback will be welcome in issue 123." Therefore I did not review the Examples page.

The APG page (http://w3c.github.io/aria-practices/#Listbox) looks good to me.
