### ISSUE TITLE
One of keyboard supports isn't working in role="feed"'s example

### ISSUE THREAD

**Issue by ianthedev** [w3c/aria-practices#1224]
In [`role="feed"`](https://www.w3.org/TR/wai-aria-practices/examples/feed/feed.html)'s [example](https://www.w3.org/TR/wai-aria-practices/examples/feed/feedDisplay.html), the `Control + End` key combo isn't working. You could add a CSS rule such as `.restaurant-item:focus { outline: 3px solid blue }` via dev tool to create a visual effect which helps you investigate the issue.

**Comment by ZoeBijl** [comment]
Can you tell us in which browser and OS this doesn’t work?

**Comment by ianthedev** [comment]
@ZoeBijl It's on Firefox 69 and Chrome 77 in Windows 7. The `Control + End` key combo is not bringing the focus to any feed article.

**Comment by ZoeBijl** [comment]
@ianbjacobs it shouldn’t. `Control + End` should move focus to the first focusable after the feed widget. Which in this example is a `select` element displayed in the top right corner. Could you please tell me whether that’s happening on your machine?

**Comment by ianthedev** [comment]
@ZoeBijl I guess I misunderstood the purpose of `Control + End`. I thought it moves focus to the last feed article. You're right, it should move focus to the `select` element in the top-right corner, and it does that for me correctly.

Could you help check whether `Control + Home` is working correctly? In this case, it is moving focus to the first feed article rather than to the "first focusable element before the feed".

**Comment by ZoeBijl** [comment]
Hmm, technically it’s the correct behaviour. But only in that there is no focusable element before the feed. [Line 70 of feed.js](https://github.com/w3c/aria-practices/blob/master/examples/feed/js/feed.js#L70) has the relevant code. I’ll change this to clear things up a bit.

Could you tell me your thought process behind your interpretation of the keyboard support and the example? Or point to the part that caused the confusion in the first place? I’d like to change that 👍.

**Comment by ianthedev** [comment]
I'm not sure how it should behave when there is no focusable element before the feed. But if the first feed article should be focused under such a situation, the spec needs to specify that to avoid future confusions.

The same solution could be applied to the `Control + End` if there is no focusable element after the feed.

**Comment by ianthedev** [comment]
I'm fine with that. Let's move the discussion there.
