### ISSUE TITLE
Reversion title and footer on example pages

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1225]
The string "WAI-ARIA Authoring Practices 1.1" needs to be changed to "WAI-ARIA Authoring Practices 1.2" in 2 places on every example page in the master branch:
1. In the title tag.
2. In the link in the nav element at the bottom of the page.

**Comment by spectranaut** [comment]
Should the links to 1.1 in the landmark example pages be updated as well? The links are all explicitly to aria1.1 instead of the editors draft, so they won't be incorrect.

[banner landmark page](https://w3c.github.io/aria-practices/examples/landmarks/banner.html)
