### ISSUE TITLE
ES6 support in ESLint

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1230]
@mcking65 @a11ydoer @ZoeBijl Getting errors using "class" for carousel 2 tablist exmples with Travis CI, seems like our eslint configuration needs to be modified to support es6 code, see error:
https://travis-ci.com/w3c/aria-practices/jobs/249986911

**Comment by nschonni** [comment]
I can't find the issue where the browser support range was raised, but I think it's not so much an ESLint issue as deciding to drop IE11 support from the examples (or add some transpiling to the build chain).
`class` won't run in IE11 which is why i think it's still limited to es5
