### ISSUE TITLE
Develop example of multi-thumb slider design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#124]
The multi-thumb slider design pattern is at:
http://w3c.github.io/aria-practices/#slidertwothumb

**Comment by jongund** [comment]
I can create an example for multi-thumb slider

**Comment by jnurthen** [comment]
This is ready for review... 
https://rawgit.com/jongund/aria-practices/slider/examples/slider/multithumb-slider.html

**Comment by mcking65** [comment]
With commit 84d3bd8, this example page is now complete and ready for task force review.
