### ISSUE TITLE
update combobox examples to use ARIA 1.2 pattern

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1244]
Develop 4 examples that match the proposed ARIA 1.2 combobox specification by making the following changes to existing examples.
And, eliminate all 1.0 and 1.1 examples.

move the following 3 examples to the /combobox directory and convert to the 1.2 pattern and :
/combobox/aria1.0pattern/combobox-autocomplete-both.html
/combobox/aria1.0pattern/combobox-autocomplete-list.html
/combobox/aria1.0pattern/combobox-autocomplete-none.html
Then remove the aria1.0pattern subdirectory.

Move the following to the combobox directory and convert it to the 1.2 pattern:
/combobox/aria1.1pattern/grid-combo.html
Then remove the /aria1.1pattern/ subdirectory.

**Comment by mcking65** [comment]
As part of Pr #1255, The 3 listbox popup examples are ready to review now:

1. [Combobox With Both List and Inline Autocomplete](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-both.html)
2. [Combobox With List Autocomplete](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-list.html)
3. [Combobox without Autocomplete](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-none.html)

Simon is working on the pattern text, and Jon is working on the grid popup example and tests.
