### ISSUE TITLE
Documentation for aria-practices's infrastructure

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1245]

**Comment by nschonni** [comment]
What type of infrastructure where you thinking about? Build, deploy, host, or something non-techincal

**Comment by spectranaut** [comment]
All of it -- build/deploy/host :) I started a wiki page here: [APG Infrastructure](]https://github.com/w3c/aria-practices/wiki/APG-Infrastructure)

**Comment by spectranaut** [comment]
done!

**Comment by carmacleod** [comment]
This is great, @spectranaut - thank-you!
