### ISSUE TITLE
update documentation on running regression test files

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1247]
@mcking65 @spectranaut The instructions for running a specific regression test file does not work in master (or any branch) any more.  It seems the match is now going into each test file and looking for the match string, but that is just a guess.   I don't want to guess anymore about how the regression test system works to run individual test files.   I am spending way more time on just trying to run a regression test file than working on examples.

Current instructions:
https://github.com/w3c/aria-practices/wiki/Regression-Tests-for-APG-Example-Pages

**Comment by jongund** [comment]
@spectranaut I made some edits to the wiki documentation, maybe Valarie can verify that the changes are correct.

**Comment by spectranaut** [comment]
This has been fixed, thanks @jongund :) I also added a second way to run a single test to that section!
