### ISSUE TITLE
Up arrow should scroll up to top in Grouped Listbox Example

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#1249]
From https://github.com/w3c/aria-practices/pull/1191#issuecomment-551170183

Steps:
1. Go to the [Listbox Example with Grouped Options](http://w3c.github.io/aria-practices/examples/listbox/listbox-grouped.html)
2. Focus the Listbox
3. Type `End` then `Home`
4. Now type `up arrow`

The list doesn't scroll up to show the Land category title - you have to use `PageUp`.

Up arrow should probably scroll to the top also.

**Comment by smhigley** [comment]
@carmacleod I don't think the group labels should receive focus, so my planned implementation is to only prevent the default arrow key scroll behavior if focus is actually moved. That way, up/down arrows will perform the default scrolling behavior in a case such as this (and also scroll the page as a whole, potentially).

Do you have any reservations about that solution?

**Comment by carmacleod** [comment]
@smhigley 
> up/down arrows will perform the default scrolling behavior in a case such as this (and also scroll the page as a whole, potentially).

Ah, right. I guess that's how PageUp and PageDown currently work (they scroll the control and then the page).

I think I would prefer that up/down arrows don't scroll the page - just the control - but I would be more comfortable asking the group what they think.

Note that if we do make a change in this area, the prose for the [keyboard interaction for the listbox pattern](http://w3c.github.io/aria-practices/#listbox_kbd_interaction) may have to be tweaked. It currently says:
> Up Arrow: Moves focus to the previous option. Optionally, in a single-select listbox, selection may also move with focus.

But if "scroll to show group name" behavior is added, the prose would have to allow for that case.

**Comment by mcking65** [comment]
In a listbox, only the selectable options should be focusable; the group labels should not be focusable. I support the proposed fix in #1294.

**Comment by ZoeBijl** [comment]
+1 to what Matt said.

**Comment by smhigley** [comment]
Merge it! 😁

**Comment by ZoeBijl** [comment]
> Merge it! 😁

Should we wait for the reviews? 🤔
