### ISSUE TITLE
Develop example of spinbutton design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#125]
The spinbutton design pattern is at:
http://w3c.github.io/aria-practices/#spinbutton

#### Link to Work in Progress

[View the example spinbutton in the feature branch](https://rawgit.com/w3c/aria-practices/issue125-add-spinbutton-example/examples/spinbutton/spinbutton.html)

**Comment by mcking65** [comment]
@gerardkcohen is working on this issue.

**Comment by eknowles** [comment]
@mcking65 is this not describing an input[type=number] ? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number apart from the page up/down large step function?

**Comment by mcking65** [comment]
@eknowles, yes, HTML input type number is mapped as a spin button. So, if the native html element meets your needs, do not make a custom ARIA spin button.

**Comment by jongund** [comment]
Matt,

My student and I are working on a spin button example.   If that is ok with you.

Jon

**Comment by mcking65** [comment]
@jongund, Gerard has already submitted #724.

**Comment by mcking65** [comment]
@gerardkcohen, do you have time this week to wrap up js and css for this example? I could help out with the documentation. Wondering if we can get it done soon. I would consider delaying release 2 a few days if so. We need time on calendar for working group review.

**Comment by mcking65** [comment]
When focus is in the spin button, it is capturing all key events. Can not tab out, cannot use modified keys like alt+d to go to addressbar, etc.

**Comment by gerardkcohen** [comment]
Hi Matt, I am currently on vacation until 7/23. I don’t think I will have
time to get through this, but I’ll give it a try. Sorry about the timing.

Gkc

**Comment by mcking65** [comment]
Closed with commit 8a3fea1.

The [new spin button example](http://w3c.github.io/aria-practices/examples/spinbutton/datepicker-spinbuttons.html) is in the editor's draft.
