### ISSUE TITLE
Revise combobox design pattern to reflect ARIA 1.2 requirements

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1250]
The [combobox specification in ARIA 1.2](http://w3c.github.io/aria/#combobox)
includes several changes. Revise the [APG combobox design pattern](http://w3c.github.io/aria-practices/#combobox)
to reflect these changes.

- [x] Revise intro to reflect the change that the input does not have to be a text box; it could be an input element that does not support editable text.
- [x] Revise description of popup trigger conditions to reflect the change from textbox to input for some implementations
- [x] Revise description of use cases to reflect change from textbox to input
- [x] Revise description of autocomplete behaviors to reflect change from textbox to input
- [x] Revise keyboard section to have an input section, with separate lists of interactions depending on whether the input is editable
- [x] Revise states and properties section so there is no mention of versioning. There is just one list of requirements. At the end, add a note about the 1.0 pattern using aria-owns instead of aria-controls stating it is supported for legacy reasons but advises authors to remediate the implementations that use aria-owns to use aria-controls.
- [x] Throughout entire pattern, ensure all mentions of textbox are either replaced with input, appropriately conditional, or removed.
This page in the ARIA wiki may be a useful resource:
https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues

**Comment by zcorpan** [comment]
> Throughout entire pattern, ensure all mentions of textbox are either replaced with input, appropriately conditional, or removed.

I generally used "combobox" instead, since that is the role that is applied to what would be the textbox.

**Comment by zcorpan** [comment]
> Revise states and properties section so there is no mention of versioning. There is just one list of requirements. At the end, add a note about the 1.0 pattern using aria-owns instead of aria-controls stating it is supported for legacy reasons but advises authors to remediate the implementations that use aria-owns to use aria-controls.

https://github.com/w3c/aria-practices/pull/1255/commits/d04fa9634f782af5fac24ba4d1a3c2223e120636

**Comment by zcorpan** [comment]
> Revise keyboard section to have an input section, with separate lists of interactions depending on whether the input is editable

I've made the editing-specific interactions conditional on whether the combobox is editable.

What should the interactions be when the combobox is not editable? Should this be modelled after how `<select>` behaves?
