### ISSUE TITLE
Menu pattern: Modify to support menubar menuitem elements that are not parent menuitems

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/aria-practices#1260]
Unless I'm misreading the actual ARIA spec, a `menubar` does not necessarily have to contain just `menuitem` elements that have their own submenu, but also standalone/"one off" `menuitem`s (and even `menuitemradio` and `menuitemcheckbox` elements) directly on the top level. 

(looking at the "Required Owned Elements" in https://www.w3.org/TR/wai-aria-1.1/#menubar)

So, the following would presumably be valid: imagine a menu bar with a "File" dropdown submenu, an "Edit" dropdown submenu, and "Help" which does NOT have a submenu, but triggers something like a modal dialog with help information directly?

```
<ul role="menubar">
  <li role="none">
    <button role="menuitem" aria-haspopup="true" aria-expanded="false" tabindex="0">File</button>
    <ul role="menu" aria-label="File menu" ...>
      <li role="none">
        <button role="menuitem" tabindex="-1">Open...</button>
      </li>
      ...
    </ul>
  </li>
  <li role="none">
    <button role="menuitem" aria-haspopup="true" aria-expanded="false" tabindex="-1">Edit</button>
    <ul role="menu" aria-label="Edit menu" ...>
      <li role="none">
        <button role="menuitem" tabindex="-1">Copy</button>
      </li>
      ...
    </ul>
  </li>
  <li role="none">
    <button role="menuitem" tabindex="-1">Help</button>
  </li>
</ul>
```

And if this is the case, wondering if it's worth/possible to provide an example of this, as well as changing the keyboard behavior write-up https://www.w3.org/TR/wai-aria-practices/#menu to NOT have the assumption that

> All items in the `menubar` have child submenus that contain multiple vertically arranged items.

and to change

> *Down Arrow:*
> When focus is on a `menuitem` in a `menubar`, opens its submenu and places focus on the first item in the submenu.

to only apply to `menuitem` in a `menubar` that *has a submenu*

**Comment by mcking65** [comment]
@patrickhlauke, agree with your interpretation of the specification. And, yes, we should make that adjustment to the pattern language.

Given our backlog, modifying the example would be pretty far down the list. However, PRs are always welcome.

**Comment by patrickhlauke** [comment]
Filed https://github.com/w3c/aria-practices/pull/1616 which, I believe, covers at least the theory/description part of this. Going to leave the "provide an example" part as an exercise for another day...
