### ISSUE TITLE
Focus problem when clicking on combobox dropdown button with mouse

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#1261]
Platform: Windows/Chrome (maybe others)
(part of functional review for PR https://github.com/w3c/aria-practices/pull/1255)

Steps:
1. Go to [Editable Combobox With Both List and Inline Autocomplete Example](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-both.html)
(Note that the link to this example will change after the PR is merged)
2. Focus the combobox, either by tabbing or with mouse
3. Type 'A' and observe combobox dropdown list of 5 US state names that begin with 'A'
4. Now, using mouse, click the drop-down button

The list appears and takes focus, but then it immediately loses focus and disappears because focus has been moved to the combobox text input. This looks very strange.

**Comment by carmacleod** [comment]
Same problem in:
- [Editable Combobox With List Autocomplete Example](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-list.html)
- [Editable Combobox without Autocomplete Example](https://raw.githack.com/w3c/aria-practices/issue1244-aria1.2-combobox-conversion/examples/combobox/combobox-autocomplete-none.html)

**Comment by LaurenceRLewis** [comment]
Just wondering 

In the table under the ‘Text’ heading with role combobox, the attribute column that includes aria-haspopup is set to “true”.  Because this example pops up a listbox, should this not be aria-haspopup=“listbox”?

 According to the specification;

`’The value of aria-haspopup matches the role of the popup container. ‘`

and

`’To provide backward compatibility with ARIA 1.0 content, user agents MUST treat an aria-haspopup value of true as equivalent to a value of menu.’`

https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

**Comment by carmacleod** [comment]
Oooh - good catch, @LaurenceRLewis !

That bug is not only in the example writeup, I see it in the example code as well.

The spec also says:
> Elements with the role combobox have an implicit aria-haspopup value of listbox. 

so maybe the cleanest fix is to delete `aria-haspopup` from any combobox example that has a listbox popup. Thanks!

**Comment by zcorpan** [comment]
The popup is behaving pretty strangely. It seems like it sometimes gets into a bad state where clicking the button opens and immediately closes again. Also the popup closes after "mouseout", which is annoying.

**Comment by JAWS-test** [comment]
> Platform: Windows/Chrome (maybe others)

In Windows: The problem also occurs with IE 11 and Firefox.

**Comment by mcking65** [comment]
@@LaurenceRLewis wrote:

> In the table under the ‘Text’ heading with role combobox, the attribute column that includes aria-haspopup is set to “true”. Because this example pops up a listbox, should this not be aria-haspopup=“listbox”?
> 
> According to the specification;
> 
> `’The value of aria-haspopup matches the role of the popup container. ‘`
> 
> and
> 
> `’To provide backward compatibility with ARIA 1.0 content, user agents MUST treat an aria-haspopup value of true as equivalent to a value of menu.’`
> 
> https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup


Removed unnecessary aria-haspopup declarations and supporting documentation with commit e51ad04.

**Comment by carmacleod** [comment]
I retested steps 2, 3, and 4 (above) using the examples in PR https://github.com/w3c/aria-practices/pull/1276:
* [Preview combobox autocomplete=both](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-both.html)
* [Preview combobox autocomplete=list](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-list.html)
* [Preview combobox autocomplete=none](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-none.html)

This problem will be fixed after PR https://github.com/w3c/aria-practices/pull/1276 is merged.

**Comment by mcking65** [comment]
Thank you @carmacleod, linking to #1276.
