### ISSUE TITLE
Combobox examples: Investigate cause of excess JAWS and NVDA verbosity

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1264]
Per review of #1255 by @smhigley:

- NVDA + Firefox: reads the page title four times almost every time you change options using the arrow key with the listbox open
- JAWS + Firefox: sporadically re-announces the listbox when arrowing through options.

These behaviors may be related to the fact that all option elements are mutated every time the user changes selection.

Investigate whether extra verbosity is caused by the combobox code, and if so, resolve.

**Comment by spectranaut** [comment]
@smhigley I assume this is a problem for all the listbox-autocomplete examples, or was it only for one of them?

**Comment by smhigley** [comment]
@spectranaut yup, all of them.

by the way, I believe I found the root cause -- would you (and @mcking65) like me to just add it to the #1255 PR?

**Comment by smhigley** [comment]
sorry, not quite all -- the one without autocomplete is ok

**Comment by smhigley** [comment]
Resolved this issue with commit in #1255: https://github.com/w3c/aria-practices/pull/1255/commits/ccd56b7bf239c85a191135fb8476ea0b3c4f6a78
