### ISSUE TITLE
Combobox Examples: Make compatible with touch-based screen readers

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1267]
In review of #1255, issues with iOS VO were discovered.

Test with iOS VO and resolve issues.

Edit: Specifically, from Sarah's review in #1255:
> iOS + VoiceOver: the "open" button did not work (didn't open the listbox, and sent the cursor back to the text input). I'd suggest either making the open button aria-hidden="true" tabindex="-1", or removing it altogether.

Reply from Matt:
> Surprising suggestion. How would touch users expand/collapse the combobox if it is not accessible?
> This is a widget that we should make touch compatible before APG 1.2 release. Opened #1267.

**Comment by a11ydoer** [comment]
using pointer events has been working well for touch issue. thanks, @jongund

**Comment by a11ydoer** [comment]
@jongund can you provide the example link? I could not find the example link from the issue 1255. Thanks in advance.

**Comment by jongund** [comment]
@a11ydoer There is a linked pull request #2086 to this issue, it contains the preview links for the changes.

**Comment by a11ydoer** [comment]
Example links
[Combobox Autocomplete: Both](https://raw.githack.com/w3c/aria-practices/combobox-pointer-events/examples/combobox/combobox-autocomplete-both.html)
[Combobox Autocomplete: List](https://raw.githack.com/w3c/aria-practices/combobox-pointer-events/examples/combobox/combobox-autocomplete-list.html)
[Combobox Autocomplete: None](https://raw.githack.com/w3c/aria-practices/combobox-pointer-events/examples/combobox/combobox-autocomplete-none.html)
