### ISSUE TITLE
radiogroup pattern omits semantic use of label element for radios

### ISSUE THREAD

**Issue by chrisdholt** [w3c/aria-practices#1286]
Currently, the radiogroup pattern documentation calls out both `aria-label` as well as `aria-labelledby` as valid visual labels for the individual radios grouped within it:

> Each radio element is labelled by its content, has a visible label referenced by aria-labelledby, or has a label specified with aria-label.

While likely not intentional, users unfamiliar with HTML semantics and implicit roles may not be aware that the `<label />` element satisfies this requirement and is valid. As far as I know, applying the `<label/>` element with a `for` attribute is still the best approach for labeling as it is supported by all modern browsers and all major assistive technologies for all form elements. I've lost the link, but I do know that several browser/screen-reader combinations do not provide as consistent results with `aria-label` and `aria-labelledby` when applied to inputs.

**Comment by JAWS-test** [comment]
You're right when it comes to HTML radio buttons. But in the example ARIA radio buttons are used. The use of label is then not allowed. The [validator](https://validator.w3.org) then says:  

> Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.

In my opinion, aria-label and aria-labelledby are well supported by modern browsers and screen readers.

**Comment by chrisdholt** [comment]
> You're right when it comes to HTML radio buttons. But in the example ARIA radio buttons are used. The use of label is then not allowed. The [validator](https://validator.w3.org) then says:
> 
> > Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.
> 
> In my opinion, aria-label and aria-labelledby are well supported by modern browsers and screen readers.

Sure - Examples are not fully inclusive of the spec though. Is the expectation that for *any* radio in radiogroup a label would be invalid? I’m not suggesting a change to the example but to broaden the specification to encapsulate that label is valid and supported - unless you’re suggesting that per the spec it is not.

**Comment by carmacleod** [comment]
This seems like part of https://github.com/w3c/aria-practices/issues/633

**Comment by mcking65** [comment]
Closing because label works only with HTML radios. Currently APG is scoped to ARIA patterns.

Note: in the future, we would like to expand APG to include HTML-only examples. Then, patterns would be modified accordingly.
