### ISSUE TITLE
Documentation for listbox-collabsible with invalid aria attribute

### ISSUE THREAD

**Issue by kahlan88** [w3c/aria-practices#1300]
In the doc at https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html:
`aria-haspopup="listbox"` - `listbox` doesn't seem to be a valid value for `aria-hadpopup`.

Should this be `aria-haspopup="true"`?

(As per docs at https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html.)

**Comment by JAWS-test** [comment]
Please look at: https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup: listbox is valid

**Comment by ZoeBijl** [comment]
> `listbox` doesn't seem to be a valid value for `aria-hadpopup`.

Could you tell us according to what `listbox` isn’t valid? Perhaps we can contact the author of that source/tool. The ARIA 1.2 working draft lists `listbox`  as a valid value for [`aria-haspopup`](https://www.w3.org/TR/wai-aria-1.2/#aria-haspopup). This is also the case in the latest recommendation (ARIA 1.1).

**Comment by kahlan88** [comment]
I was referring to this page https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html. Thanks for sending more detail, I can see all the valid options on the link provided @ZoeBijl
