### ISSUE TITLE
errors in region landmark example page

### ISSUE THREAD

**Issue by mulder21c** [w3c/aria-practices#1301]
While reading the documentation, I found something that looks like some error, it looks like this:

1. https://github.com/w3c/aria-practices/blob/e40866f7adbf79bf7aac9bd645525976abaf2bd0/examples/landmarks/region.html#L57-L65
  I think it is right that line 
    ```html
    <section aria-label="Coding Techniques">
    ``` 
    on line 63 should be 
    ```html
    <div class = "tab-content">
    ```
    and the tab is working when changed.

2. https://github.com/w3c/aria-practices/blob/e40866f7adbf79bf7aac9bd645525976abaf2bd0/examples/landmarks/region.html#L64-L100
    ```html
    ARIA Example: Using <code>section[aria-labelledby]</code> attribute
    ``` 
    seems to be 
    ```html
    ARIA Example: Using <code>div[role="region"][aria-labelledby]</code>
    ```

Would you please check the above?

**Comment by ZoeBijl** [comment]
Nice catch! Fixed in #1303.
