### ISSUE TITLE
Navigation menubar example: Clicking menu item scrolls page to top in Chrome

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria-practices#1307]
When I click on a [main menu item](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) in Chrome, the page is scrolled to the top of the page. Depending on the display size of my device, the menu is no longer visible. 

With Chrome on mobile device (Android) there is also the problem that after clicking on a menu item the font size of the menu items changes (they get much bigger).

Both problems do not occur with Safari, IE, Firefox.

Unfortunately I have not been able to find out the cause of the problems.

**Comment by carmacleod** [comment]
The "scroll to top" sounds like a missing event.preventDefault() on a repurposed anchor element.
Does the problem happen for you with [menubar2](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html)?

**Comment by carmacleod** [comment]
I was able to replicate the "scroll to top" behavior and provide a fix.
Here's a [preview link](https://raw.githack.com/w3c/aria-practices/issue1307-scroll-to-top/examples/menubar/menubar-1/menubar-1.html) if you would like to try it.

**Comment by JAWS-test** [comment]
> Does the problem happen for you with menubar2?

No. Thanks for fixing!

**Comment by a11ydoer** [comment]
@mcking65 I think we can close tihs issue.

**Comment by carmacleod** [comment]
@a11ydoer 
Is the Android problem fixed, too? I don't have an Android device. Here's what @JAWS-test said:
> With Chrome on mobile device (Android) there is also the problem that after clicking on a menu item the font size of the menu items changes (they get much bigger).

**Comment by a11ydoer** [comment]
[Navigation Menubar Test URL](https://htmlpreview.github.io/?https://github.com/w3c/aria-practices/blob/master/examples/menubar/menubar-1/menubar-1.html)

**Comment by jongund** [comment]
@a11ydoer 
This is the latest preview link that should be used for testing:
https://raw.githack.com/w3c/aria-practices/issue1357-navigation-menubar-js/examples/menubar/menubar-navigation.html 

I believe this issue was fixed along time ago, I don't see the reported behavior in the current example.
