### ISSUE TITLE
firefox quirk with date picker dialog

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria-practices#1311]
reviewing the [date picker dialog](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html) with Firefox, if i try to select a date, or attempt to activate the Cancel or OK buttons by using the <kbd>Space</kbd> key, the dialog quickly closes and then reopens.  I would expect the dialog to not reopen.

This issue does not occur when pressing the <kbd>Enter</kbd> key.  It also does not occur when using Chrome.

**Comment by mcking65** [comment]
I can repro this in the version on TR. However, I cannot reproduce it in the current editor's draft:
https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html

Scott, can you repro in the editor's draft?

**Comment by scottaohara** [comment]
@mcking65 in the link you provided the cancel and ok buttons work correctly, but the buttons to select a day of the week still have the issue.

Looks like it could be corrected by just having a single click event on the days, rather than a mousedown and keydown events.
