### ISSUE TITLE
Clear up the mess around the switch role mapping and ARIA attributes

### ISSUE THREAD

**Issue by MarcoZehe** [w3c/aria-practices#1327]
The switch role and associated ARIA state attributes are confusing and inconsistent.

1. The switch role maps to a toggle button in the AAM.
2. This is equivalent to using a button element with the aria-pressed attribute, as specified in the HTML-AAM.
3. However, the authoring practices and other sources state that, with the switch role, aria-checked should be used, not aria-pressed.

An example: `<span role="switch" aria-checked="true">Use dark mode</span>`.

This leads to stuff like "Use dark mode toggle button", followed by "not pressed checked" announcements in NVDA. The same with a toggle button would simply say "Use dark mode toggle button pressed".

There are two possible solutions:

1. Change the authoring practices and other reference material to reference aria-pressed and make it clear that a switch acts like a toggle, and that the toggle button semantics apply. This is the easier fix which does not require changes by user agents and assistive technologies. Firefox uses the aria-pressed attribute, Chrome kinda does both, but also inconsistently.
2. Require the switch role to be exposed as a checkbutton instead of a toggle button, similar to a checkbox role or the checkbox input. This would require changes to more parts of the different specifications, as well as user agents.

Filing the issue here because conceptually, I would think that option 1 is the easier path forward, and would mostly require changes in documentation and examples.

Also see [this NVDA issue](https://github.com/nvaccess/nvda/issues/9187) with even more discussion, and a possible, but very ugly, third way forward on this.

**Comment by JAWS-test** [comment]
Similar problems occur in JAWS. In addition, JAWS outputs the switch element as either a button or a checkbox:

* as a checkbox in the quick navigation and in the element overview
* as a button with tab navigation and when reading with the virtual cursor 

This is very confusing.

**Comment by jcsteh** [comment]
>     1. Change the authoring practices and other reference material to reference aria-pressed and make it clear that a switch acts like a toggle, and that the toggle button semantics apply. This is the easier fix which does not require changes by user agents and assistive technologies.

It's easier for browsers and AT, but there may be authors out there using it already according to the spec, and this change would be backwards incompatible for them. As tedious as it is to change browsers and AT, I'd argue that, given a workable option, it's more reasonable to make changes on the spec/browser/AT side than expecting authors to change their implementations.

**Comment by MarcoZehe** [comment]
After discussing it more, closing this one to not put the burden of fixing the mess on authors. Orca already has special handling for Switch, NVDA has a PR ready to go, and I am hoping JAWS will deal with this properly at some point, too, if it doesn't already in 2020.
