### ISSUE TITLE
Combobox Examples: In high contrast mode the drop down arrow disappears when the field is selected

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#1331]
Per [feedback in pull request 1276](https://github.com/w3c/aria-practices/pull/1276#issuecomment-586026624) from @ZoeBijl about the [combobox examples](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-both.html):

In high contrast mode the drop down arrow disappears when the field is selected:

![Selected combobox with missing arrow](https://user-images.githubusercontent.com/5457769/74488558-db69fe00-4ec2-11ea-9f2e-fb1fc4530ee1.png)

The select state within the dropdown is clear though:

![State combobox with three suggestions showing. There's a clear contrast difference between the selected item and the others.](https://user-images.githubusercontent.com/5457769/74488609-0b190600-4ec3-11ea-85ff-a9ea34ea4f53.png)

Recommendations from Zoe:

1. Add a `border-radius: .125em;` to the input.
2. Fix the disappearing drop down arrow.

**Comment by zcorpan** [comment]
The `border-radius` would be to make it look a bit nicer, but unrelated to high contrast, right?

**Comment by zcorpan** [comment]
With the change in #1336 it looks like this in Edge with high contrast on:

<img width="223" alt="Same as before, except the dropdown triangle is now visible." src="https://user-images.githubusercontent.com/244772/75791118-658fde80-5d6c-11ea-87b6-2fc277815dbd.png">

**Comment by smhigley** [comment]
It also works in Chrome & Firefox in high contrast mode in #1336 

![screenshot of dropdown with visible icon in high contrast mode](https://user-images.githubusercontent.com/3819570/75812597-5c3e4c00-5d43-11ea-9925-b1a4de683125.png)
