### ISSUE TITLE
[Treegrid] aria-posinset and aria-setsize aren't allowed on role="row"

### ISSUE THREAD

**Issue by diegohaz** [w3c/aria-practices#1340]
Looking into the [Treegrid example page](https://www.w3.org/TR/wai-aria-practices/examples/treegrid/treegrid-1.html), I noticed that rows have `aria-posinset` and `aria-setsize` attributes:

![Image showing a treegrid widget using aria-posinset and aria-setsize on its rows](https://user-images.githubusercontent.com/3068563/74895651-fd56fb00-5370-11ea-8a53-b99932758e5d.png)

This made me think that I should use those attributes to build my own treegrid widget. But a colleague pointed me out to the spec, and it seems that they're not allowed on the `row` role:

- https://www.w3.org/TR/wai-aria-1.1/#aria-posinset
- https://www.w3.org/TR/wai-aria-1.1/#aria-setsize

Looks like the alternative for rows are `aria-rowindex` and `aria-rowcount`? Should this be updated?

**Comment by JAWS-test** [comment]
posinset and setsize are allowed in the current ARIA version: https://w3c.github.io/aria/#row
