### ISSUE TITLE
Missing regression tests for button/button_idl.html and dialog-modal/alertdialog.html

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#1378]
`npm run regression-report` on current master (d8ad7915dcb08ed35d08aec61e90ef14d0c82781) gives

```
Examples without any regression tests:

button/button_idl.html
dialog-modal/alertdialog.html

...

ERROR - missing tests:

  Please write missing tests for this report to pass.
```

This makes it tricky to do a useful test review for PRs like #1120

**Comment by spectranaut** [comment]
Started PR with this work: https://github.com/w3c/aria-practices/pull/1424
