### ISSUE TITLE
Landmark Example update to make HTML technique first view

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1391]
In the ARIA landmark example, we should consider making the HTML technique the default technique instead of the ARIA technique.

[Main Landmark Example](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/main.html)

**Comment by carmacleod** [comment]
I agree.
So, for each landmark type, the "HTML Techniques" tab should be the leftmost (i.e. the "first") tab in the tablist, and it should be the selected tab.

**Comment by jongund** [comment]
@carmacleod 

Yes, it would be the first tab and it would be selected.

**Comment by guyhickling** [comment]
Also, given that the &lt;main&gt; element is the appropriate method for HTML5, and the div/role method is really only appropriate for HTML4/XHTML pages, would it be possible to add a sentence to this effect at the top of the tab panel for the ARIA method? Changing the order will certainly help, but saying it in text will explain it clearly.
