### ISSUE TITLE
multithumb-slider.html uses aria-label instead of alt

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#1393]
See https://github.com/w3c/aria-practices/issues/1346#issuecomment-592906995

I still get this error when running `npm run lint:html` locally. The markup is

```html
                  <img id="minPriceHotel"
                    src="images/min-arrow.png"
                    role="slider"
                    tabindex="0"
                    class="min thumb"
                    aria-valuemin="0"
                    aria-valuenow="100"
                    aria-valuetext="$100"
                    aria-valuemax="400"
                    aria-label="Hotel Minimum Price"/>
```

Why is this using `aria-label` and not `alt`?

**Comment by a11ydoer** [comment]
This is the updated [multithumb slider example](https://raw.githack.com/w3c/aria-practices/slider-multithumb-update/examples/slider/slider-multithumb.html) for now. It does not use any image element.
