### ISSUE TITLE
Tab Panel keyboard interaction

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#14]
_From @StommePoes on December 7, 2015 16:8_

The current guidelines for tab panel keyboard interactions have this
- "Up arrow - behaves the same as left arrow in order to support vertical tabs 
- Down arrow - behaves the same as right arrow in order to support vertical tabs"

Developers (for example at jQuery UI) seem to have taken this to mean "always make up/down arrows mimic left/right arrows in tab-panels", however what this does is prevent sighted keyboarders from scrolling the page. The only option is moving by an entire page with PageUp/PageDown, which is difficult to read blocks of text with, while seemingly offering little gain.

Can either the spec clarify that up/down arrows should only be hijacked IF these are vertical tabs, or better yet, leave them alone all the time? Whether a tab-panel has horizontal or vertical tabs seems to be a pure visual-design/CSS choice and shouldn't change how the things work, nor should these widgets remove current browser functionality by accident.

_Copied from original issue: w3c/aria#113_

**Comment by MichielBijl** [comment]
I wholeheartedly agree +1

This is however consistent with how radiobuttons work. How you escape those?

**Comment by MichielBijl** [comment]
_From @StommePoes on December 7, 2015 16:16_

I have never, ever had radios so long that I could not read them all.

As I move down a list of radios, my screen moves with me, if somehow one did manage to make a longer-than-one-page-full of radios.

Plus anyone who does such a thing is probably evil and trying to make me cry.

Tab panels however quite often have long panels where the page has not scrolled down enough before I landed onto the tabs. I should be able to scroll the screen down without moving focus to continue reading a current panel without switching panels or losing my reading place with a full page jump.
A popular place to see tab panels is real estate pages, where each tab has mostly text or images, rather than focusables/form elements.

One option I heard was to always make panels focusable so users could tab to a panel where all arrows go back to normal, but the information scent there is low, it would have to become a popular and well-known thing. There's little natural way to indicate it, but I feel it could be an option.

**Comment by MichielBijl** [comment]
What I mean is if you reach the last radio button and you press an arrow key. Like on this page: http://dir.agosto.nl/accessibility/radios-text.html. The result in Safari 9 is that if the user reaches the last radio button and presses the down key; the page scrolls. If the user then presses the up key, it must go through all radio's again before scrolling up.

**Comment by MichielBijl** [comment]
_From @StommePoes on December 7, 2015 16:21_

That's true for radios, and more often I'm in a form where the next or previous thing is a focusable-by-tab. If the first/last item in a form is a radio field then yeah, I'd have to get out of them or to the end of them to scroll the page.

As it is, the example page would be a keyboard trap... or I'd have to resort to pageup/down, which works but not nicely.

**Comment by MichielBijl** [comment]
Not saying that is a solution, just comparing results :)

**Comment by MichielBijl** [comment]
_From @StommePoes on December 7, 2015 16:23_

To make them more comparable, I think you'd have to change the text underneath as you arrow through the radios.


...actually not a bad test idea.

**Comment by MichielBijl** [comment]
That is a very good point. Crap.

**Comment by MichielBijl** [comment]
_From @jnurthen on February 10, 2016 17:24_

Now tablist supports aria-orientation we should really suggest that for horizontal tabs we only use left/right to switch tabs and leave up/down to the browser and for vertical tabs use up/down and leave left/right to the browser (although I'm not sure what harm it would do to allow left/right)

**Comment by MichielBijl** [comment]
@jnurthen am I correct in saying that there is no mention of `aria-orientation` in the [tab panel design pattern](http://w3c.github.io/aria/practices/aria-practices.html#tabpanel)?

Also, what would happen if you have vertical tabs whose content is longer than the window height? You'd still need arrow keys to scroll. Should we recommend setting `tabindex=0` to the active tab panel so that users can scroll using arrow keys?

**Comment by MichielBijl** [comment]
_From @jnurthen on February 16, 2016 15:19_

You are correct. Tablist didn't support it in aria 1.0.

**Comment by MichielBijl** [comment]
_From @jnurthen on February 16, 2016 17:3_

> Also, what would happen if you have vertical tabs whose content is longer than the window height? You'd still need arrow keys to scroll. Should we recommend setting tabindex=0 to the active tab panel so that users can scroll using arrow keys?

This would be a hole in the design pattern. My thought is that this is a rare case but yes - I guess we could specify that. If the tab panel is a div with overflow that would automatically become tabbable in FF anyway (although not in all other browsers)

**Comment by MichielBijl** [comment]
_From @StommePoes on February 16, 2016 19:34_

I've been setting my panes (unless there's a direct first-child focusable inside) to tabindex=0 so far. It works for me, but would like to know if that's doable for everyone else everywhere. *normally* we don't want to make non-interactives focusable...

**Comment by MichielBijl** [comment]
I offered to build the tab widget for the user testing session thing during CSUN (as proposed by Ian Pouncy). This could be a thing we can test with real people. And I think we should, given that we're writing the book on how to do it. 

I'll see if I can get the widget done somewhere this week. There is already an issue for it here on GitHub.

**Comment by MichielBijl** [comment]
_From @StommePoes on February 17, 2016 8:36_

oooh! user testing!!  Grab some random person from the street too-- someone not working in the (dis)ability space. Hotel staff. Restaurant servers. Whatever.

**Comment by MichielBijl** [comment]
Related issue: https://github.com/w3c/aria/issues/206

**Comment by MichielBijl** [comment]
_From @jnurthen on March 8, 2016 0:34_

I missed this when editing the tab stuff (perils of multiple issue tracking systems) but I will get to this in the near future.

**Comment by mcking65** [comment]
I will make sure this is clear when I work on issue #40, then I will close this one too.

**Comment by mcking65** [comment]
This issue is addressed in commit 424776b and can now be viewed in master at:
http://w3c.github.io/aria-practices/#tabpanel

@StommePoes, feedback is welcome!

**Comment by StommePoes** [comment]
w00ts, great stuff!

"When a tabbed interface is initialized, One tab panel "
Typo capital "O"

"End: Moves focus to the last tab."
If Home is optional, shouldn't End be as well? Both or none?

"When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is often either the first focusable element inside the tab panel or the tab panel itself."

This sounds good, although as a developer reading this it looks like the next-focusable-in-tab-order is *optionally* (because of the word "often") one of either the panel itself or a first-focusable inside. Is that okay, from a developer's point of view, to have the next-focusable-in-tab-order be whatever's next-focusable outside/after the whole tabs-and-panel setup instead (further down the page)? 

I think as a user, I have no particular expectations here (though if focus outline is removed by the developer because the panel, while receiving focus, isn't actually an interactive, maybe I'd get lost via violation of <a href="https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-visible">WCAG 2.4.7</a>). As a developer I would want to know whether that was okay, or if focussing on a focusable-less panel was more of a "should" (or a "must").

Otherwise, looks ok. Still not sure about the use case of the longer-than-my-screen vertical tabs-- I haven't seen one yet. I do have a netbook small enough that, at my ginormous font size, fixed sidebar elements do get clipped at the bottom sometimes (so I would have a better chance than most of running into such a thing).  Maybe that should be revisited if vertical tab-panels start appearing in the wild more.

**Comment by mcking65** [comment]
Issue is now fully resolved with commit aeab2e1457868976c6b7f09a3b183410dc364ff5
