### ISSUE TITLE
Date Picker Dialog Example in IE11

### ISSUE THREAD

**Issue by slhenry** [w3c/aria-practices#1414]
Not working in IE 11.1217 and NVDA 2020.1

per [this tweet](https://twitter.com/Harnamsin/status/1265487873362604032)

Ref: https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/datepicker-dialog.html
if not changed from https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

**Comment by a11ydoer** [comment]
Hi @slhenry Thanks for filing the issue. 
Here is related [PR1362](https://github.com/w3c/aria-practices/pull/1362) which is very close to finish. I am metioning @curtbellew and @carmacleod the reviewers for this example as well as @mcking65 for his info.

**Comment by mcking65** [comment]
@a11ydoer, we have dropped IE support.If this is unintentionally fixed, that'd be nice. However, I suspect there are quite a few aspects of this example that are not IE compatible. Closing as won't fix.

**Comment by a11ydoer** [comment]
Thanks @mcking65 
I sent the update to the orginial requestor, Harnam.
