### ISSUE TITLE
Firefox crashing when interacting with Date Picker Combobox example when using JAWS or NVDA

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1440]
Steps:
1. Either NVDA or JAWS running
2. Browser: Firefox 78.0.1, or Beta (79.x) or Developer edition (79.x)  (note: Problem does not appear in ESR 68 Version)
3. Open https://w3c.github.io/aria-practices/examples/combobox/combobox-datepicker.html
4. Using the mouse, click on the combobox (the dialog opens)
5. Type down arrow (focus moves to today, July 7th, in the calendar)
6. Type up arrow (the calendar automatically switches to June 2020, focus moves to June 30th, and then FF crashes)

[Date Picker Combobox Example](https://w3c.github.io/aria-practices/examples/combobox/combobox-datepicker.html) 

NOTE: This problem does not seem to exist in the current [Modal Dialog Version of the Date Picker](https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html).

Information on what changes:

When focus moves to a new date:
* tabindex is updated for the grid cells
* focus is set on the new date

When focus moves to a new month:
* DOM nodes associated with the grid cells are updated:
   * Text content is updated with new date
   * The `data-date` attribute is updated with the new date
   * Tabindex is updated
   * Last row may or may not be hidden depending on the number of days in the new month
   * Live region for the month and year are updated
   * Focus moves to new date

Things I have tried to see if it makes any difference, and so far it has not:
* Switched from using innerHTML to textContent to update date girdcells
* Use `.tabIndex` property instead of `setAttribute('tabindex', value)`
* disabled the hiding of the extra cells for shorter months, it using the CSS `visibility` property

**Comment by JAWS-test** [comment]
Firefox 78.0.1 always crashes, as follows
* with NVDA 2020.1 only when switching to a new month
* with JAWS 2020.2004.66  every time you switch to another day

It does not matter whether the datepicker is opened with the mouse or keyboard

**Comment by carmacleod** [comment]
@jongund 
> NOTE: This problem does not seem to exist in the current Modal Dialog Version of the Date Picker.

The [Date Picker Dialog Example](https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html) crashes for me immediately after opening the dialog when I use JAWS in FF 78.0.1.
My JAWS version is 2019.1912.1 ILM.

Interestingly, I cannot get the DP _Dialog_ example to crash using NVDA/FF 78.0.1. However, the grid navigation keys don't work the same way, and so the automatic page switching doesn't happen.

The DP _Combobox_ example crashes for me every time following the above steps and using either JAWS or NVDA.

**Comment by jongund** [comment]
Issue is probably related to [bug report 1650590](https://bugzil.la/1650590).

**Comment by carmacleod** [comment]
Also related to [bug report 1650348](https://bugzilla.mozilla.org/show_bug.cgi?id=1650348).

**Comment by jongund** [comment]
@carmacleod 
I added our issue to their bug.

**Comment by a11ydoer** [comment]
@jongund @carmacleod I confirmed both bugs were resolved and fixed. I am closing this issue.
