### ISSUE TITLE
Document High Contrast Mode(HCM) and Mobile compatibility for APG examples

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#1459]
Potential place to add the info is ARIA APG coverage report.
https://raw.githack.com/w3c/aria-practices/master/coverage/index.html

**Comment by carmacleod** [comment]
List of examples that were previously noted to have WHCM issues: https://github.com/w3c/aria-practices/issues/1132#issuecomment-534418273

**Comment by a11ydoer** [comment]
Thanks @carmacleod I am merging this issue with https://github.com/w3c/aria-practices/issues/1460
Jon was 2min faster than I am. ;-)
