### ISSUE TITLE
Tabs on region page seems broken

### ISSUE THREAD

**Issue by hans2103** [w3c/aria-practices#1461]
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html

The tabs on this page seems broken. On other pages you can click on a tab to open it. This page has both tabs open.

**Comment by carmacleod** [comment]
@hans2103 
The problem seems to be fixed in the latest code: https://w3c.github.io/aria-practices/examples/landmarks/region.html
If you agree, then please close this issue. :)
