### ISSUE TITLE
The calendar selected date (when it doesn't have focus) is indicated by light blue which fails 1.4.11

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#1478]
![image](https://user-images.githubusercontent.com/2365411/88932463-1c28ba00-d24c-11ea-8f78-cf88ad1b4e37.png)

There is a graphical representation of the selected date. It is represented by light blue and it doesn't have a 3:1 contrast to indicate that it is selected to who have low vision or color disabilities.
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

### SOLUTION
Consider turning the selected date to inverse (dark background with light text).

https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html

**Comment by carmacleod** [comment]
Thank-you, @DavidMacDonald!
WCAG 2.1 issues are starting to trickle in. :)
Non-text contrast is sometimes very difficult to solve, but this one was very simple. Thanks for the suggestion.

**Comment by jongund** [comment]
@carmacleod 
Maybe we should use a shade of dark gray when the gridcell date does not have keyboard focus.

**Comment by mcking65** [comment]
@carmacleod, thank you for the fix!!
