### ISSUE TITLE
Fix radiogroup example

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#148]
See https://github.com/w3c/wcag/issues/251 for details.

**Comment by mcking65** [comment]
I do not think this is a valid issue because I think that w3c/html-aria#30 is a valid issue and that <ul> and <li> should be able to be used for radiogroup and radio.

**Comment by MichielBijl** [comment]
Hmm, okay. Should we close this then? Or add an editor’s note?

**Comment by MichielBijl** [comment]
The bug in “ARIA in HTML” is fixed, so closing this.
