### ISSUE TITLE
Example code on code example pages doesn’t include IDs

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#149]
For whatever reason the script that generates the example code on our code example pages doesn’t include `id`’s. This is causing confusing for readers.

For example, the [slider example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/slider/slider-1.html) misses all the `id` attributes and thus has `aria-labelledby` attributes that seemingly point to nothing.

**Comment by MichielBijl** [comment]
Just tested this locally and there it does show. So it doesn’t seem to be something in example.js.

**Comment by mcking65** [comment]
You're looking at TR instead of master. Look at slider here:
http://w3c.github.io/aria-practices/examples/slider/slider-1.html

This was a bug but we fixed it in issue #115.
