### ISSUE TITLE
Draft guidance on aria-expanded

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/aria-practices#15]
_From @MichielBijl on December 7, 2015 17:19_

More information (will type out here): https://gitter.im/w3c/a11ySlackers?at=5638b28edcafd1f0750840d9

_Copied from original issue: w3c/aria#115_

**Comment by jnurthen** [comment]
This sounds like a spec issue not an APG issue.

**Comment by mcking65** [comment]
Spec seems fairly clear to me. Nevertheless, once we are through with example implementations and look at all the examples that use aria-expanded, we may want to circle back to this issue, re-read the discussion,  and see if we need additional guidance on aria-expanded.

**Comment by zcorpan** [comment]
Can you paste here the relevant discussion from the chat?

**Comment by mcking65** [comment]
This issue is covered by #254 and the guidance is in the PR for 254.
