### ISSUE TITLE
Carousel slide titles can show in heading list when their slides are hidden

### ISSUE THREAD

**Issue by blueblots** [w3c/aria-practices#1514]
From carousel example here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html

If a screen reader opens a heading list and the carousel automatically moves to the next slide, then the heading list will show the heading for the slide that was showing originally and not the slide that is currently showing.

![issue](https://user-images.githubusercontent.com/63152708/92305688-60148a80-ef81-11ea-8d77-4010f79507c2.png)

If I were to jump to the slide title that is highlighted in the screenshot at that moment then nothing happens and I only have the page title read to me, rather than focusing on the carousel. I tested this with the Orca screen reader.

Is there a widely accepted way to get around this without providing separate screen reader content, or is this just a limitation of heading lists.

**Comment by mcking65** [comment]
I don't think the heading lists are dynamic in any of the screen readers. That is, once the list is generated by the screen reader, I don't think the screen reader is monitoring to find out if it should change an already displayed list. There is nothing stopping the screen reader from making an element list dynamic, but it is such an edge case that it is probably not important.

It is good for screen reader users to enable settings for reduced motion in their operating system. It helps with issues like this.

Hope this helps.
