### ISSUE TITLE
Develop example of tabs design pattern where selection does not follow focus

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#152]
We have one [example implementation](http://w3c.github.io/aria-practices/examples/tabs/tabs.html)
 of the 
[tabs pattern](http://w3c.github.io/aria-practices/#tabpanel)
 where selection follows focus. That is, as the user moves focus in the tablist, the selection also moves and the tabpanel content for the selected tab, which is also the focused tab, is automatically displayed.

This issue is to create an example implementation where selection does not follow focus. In this implementation, as the user moves focus in the tab list, the selection will not move and the content of the tab panel will not change. To display the new tabpanel, the user presses enter or space on the focused tab.

It would be useful for the two implementations to be on separate example pages so it is easier to link to them separately from the text of the APG section that describes considerations for deciding whether selection should or should not follow focus.

**Comment by MichielBijl** [comment]
This is fixed in https://github.com/w3c/aria-practices/commit/eb142978fbe432c1ffdcb00e040b3cf51ed3641d which is in the [tabs branch](https://github.com/w3c/aria-practices/tree/tabs).

- [ ] Review by @mcking65 
- [ ] Review by @jnurthen

**Comment by mcking65** [comment]
Work for this issue is now complete with merges for pull #269. Reviews are being tracked in issue #279.
