### ISSUE TITLE
Inconsistent use of name

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#153]
The title of the document says “WAI-ARIA Authoring Practices 1.1” while the first line of the introduction says “WAI-ARIA Authoring Practices Guide”. We all refer to the document with its acronym APG.

Can we change the title of the document to “WAI-ARIA Authoring Practices Guide 1.1”?

**Comment by michael-n-cooper** [comment]
I prefer not to change the name, it's easier for continuity and and I think the current title is "clean", notwithstanding the colloquial name we also have for it. If you do decide to change it, I'll need special pings next time we publish as the Webmaster will have to change some things and I'll have to remember to tell him.

**Comment by mcking65** [comment]
I am fine with keeping the name and cleaning up inconsistencies within the document itself. I do agree that the title without the word "guide" is a bit more clean.

**Comment by mcking65** [comment]
@MichielBijl
 
Does commit 7666b54 adequately address this inconsistency?

If this is an acceptable solution, then I will also fix the title tags and links in the footer in example pages.

**Comment by MichielBijl** [comment]
@mcking65 yes this works for me, I would’ve rather seen it the other way around, but at least it’s consistent now. Thanks!
