### ISSUE TITLE
Disclosure pattern support escape key when used with a popup list of links

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1571]
Add to the disclosure pattern at least an optional use of the escape key to close a popup list of links and return focus to the controlling button.   This would save keyboard only users time from having to tab out of the list to close the container element.  It seems like this is something keyboard only users would also expect for something that looks like a pull down menu.

**Comment by JAWS-test** [comment]
Do you mean the example https://www.w3.org/TR/wai-aria-practices-1.2/examples/disclosure/disclosure-navigation.html? The use of ESC is already implemented there

**Comment by jongund** [comment]
@JAWS-test 
I meant in the design pattern.
[https://w3c.github.io/aria-practices/#disclosure]

**Comment by jongund** [comment]
Closing because is now supported.
