### ISSUE TITLE
Develop navigation menubar example that overloads parent menuitems with a navigationn target

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#159]
Note 4 in the keyboard section of the 
[menu design pattern](http://w3c.github.io/aria-practices/#menu)
reads:

> Although it is recommended that authors avoid doing so, some implementations of navigation menubars may have menuitem elements that both perform a function and open a submenu. In such implementations, enter and Space perform a navigation function, e.g., load new content, while Down Arrow, in a horizontal menubar, opens the submenu associated with that same menuitem."

That is, parent menu items, especially those in a menubar, can be overloaded to both execute a link and open a submenu.

Per discussion in the 
[November 14, 2016 authoring practices task force meeting](https://www.w3.org/2016/11/14-aria-apg-minutes.html), @accdc raised this as an important pattern as did @terrill in his 
[comment on issue 145](https://github.com/w3c/aria-practices/issues/145#issuecomment-260213854).
The conclusion was that we should have an example that demonstrates this menuitem overloading practice because it is so common on the web and failing to provide an example will lead people to invent their own ways that may not be accessible.

The proposal is to have example 2 of the [navigation menu examples](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html) 
demonstrate this behavior. Specifically:

1. The following menuitems would open a page when enter or space is pressed or when clicked:
    * Research 
    * Outreach 
    * Arts and Culture 
2. The submenus for those menuitems would open either on hover or when focused and down arrow is pressed.

**Comment by a11ydoer** [comment]
@mcking65 @jongund @jnurthen 

Is this within the goal of December public working draft of ARIA Practices?

**Comment by mcking65** [comment]
@a11ydoer 
I consider it nice to have for the December publication if it is relatively small amount of work. No worries if you can not contain it.

**Comment by a11ydoer** [comment]
@jongund 
This is old issue. do you think we can close the issue?

**Comment by jongund** [comment]
@a11ydoer 
This is still an unresolved issue, ARIA currently does not have a good way to inform users that a widget has two different purposes, in this case following a link or opening a popup menu.

**Comment by JAWS-test** [comment]
I think it would be good if there is a way to mark a menu item with a submenu so that it can be identified whether it can only be activated to open a submenu or whether a function can be triggered in addition to opening the submenu (e.g. a page opened). Even if this is often not visually obvious, it would be good if this could be perceived with AT.

**Comment by carmacleod** [comment]
I don't think we should do this. I think that https://github.com/w3c/aria-practices/pull/1614 shows a better way to do this.
Closing.
