### ISSUE TITLE
Draft switch design pattern

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/aria-practices#162]
Add guidance on how to code a switch (as opposed to a checkbox). Articles on this:

[When to Use a Switch or Checkbox](http://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/)

#### Preview of branch with work in progress

[Switch pattern in switch branch](https://rawgit.com/w3c/aria-practices/switch/aria-practices.html#switch)

**Comment by mcking65** [comment]
Yes, this should have been in the plan for the CR release so adding it to that milestone.

**Comment by mcking65** [comment]
Thanks to @jongund, we now have a 
[Switch pattern in the switch branch](https://rawgit.com/w3c/aria-practices/switch/aria-practices.html#switch).

This is ready for task force review.

**Comment by annabbott** [comment]
No issues noted.

**Comment by mcking65** [comment]
Closed by #1891
