### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by leandro2222** [w3c/aria-practices#1679]
the webpage: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/grid-combo.html

has the link inside: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/js/grid-combobox.js

that is broken. i believe that the right url would be: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/js/grid-combo.js

**Comment by carmacleod** [comment]
Thanks, @leandro2222 !
It turns out that link has already been fixed in the current version of the ARIA Practices Guide:
https://w3c.github.io/aria-practices/examples/combobox/grid-combo.html

**Comment by mcking65** [comment]
Closing as already fixed.
