### ISSUE TITLE
Decide how we want to visually mark up examples

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#1684]
Most of the APG code examples are simply marked up with `<pre><code>...</code></pre>`. ReSpec adds a bunch of syntax highlighting and draws a simple grey box around each code block.

However, in section [8.2 Using aria-valuetext](https://w3c.github.io/aria-practices/#range_related_properties_using_aria-valuetext), and in the upcoming section [9.1.1 Remediation Use Cases for Headings](https://raw.githack.com/w3c/aria-practices/issue259-aria-level-guidance/aria-practices.html#aria-level_heading_role_remediation), the `<pre><code>` boxes plus the example's explanatory sentence(s) are wrapped together in a `<div class="example">`, which causes ReSpec to draw a light greenish-yellow box around the whole thing, with a darker greenish-yellow vertical strip on the left. The simple grey box style is retained for the actual code block(s) within the "example" div.

This seems inconsistent with all of the other code examples in the APG. But maybe it's ok? For example, in 9.1.1, it may help to tie several related code blocks together. However, in 8.2, the colored box with the strip only contains a single code block, so I'm not sure whether it's serving any particular purpose there? (or maybe having the "For example, ..." sentence within the same colored box as a single grey boxed code block is helpful? Not sure).

After https://github.com/w3c/aria-practices/pull/1109 is merged, I really would like others' opinions on whether it's ok to have these 2 code samples look different than the rest of the code samples in the APG (i.e. should we do nothing?). Or should we remove the wrapper `div.example`? Or should we wrap all examples with their introductory sentences in `div.example` elements?

**Comment by a11ydoer** [comment]
@jesdaigle I am tagging you because I assume APG redesign project will take care of this issue. If not, please let me know.

**Comment by mcking65** [comment]
addressed by new site design
