### ISSUE TITLE
a requirement is missing

### ISSUE THREAD

**Issue by tliawi** [w3c/aria-practices#1750]
under "Javascript and CSS Source Code" you list only three
&nbsp;&nbsp;&nbsp;&nbsp;CSS: listbox.css
&nbsp;&nbsp;&nbsp;&nbsp;Javascript: listbox.js
&nbsp;&nbsp;&nbsp;&nbsp;Javascript: listbox-scrollable.js
there needs to be a fourth: Javascript: utils.js
else it doesn't work.

**Comment by jnurthen** [comment]
dup of https://github.com/w3c/aria-practices/issues/842
