### ISSUE TITLE
Provide some exceptions in landmarks section

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#1751]
While https://www.w3.org/TR/wai-aria-practices-1.1/#general-principles-of-landmark-design effectively encourages landmark usage it occasionally encourages usage which adds noise to the page

An example of this is a page (which uses landmarks effectively) which launches a modal dialog. That modal dialog is outside of the landmarks of the page (as expected) but does not need to contain a landmark itself. This should be clarified in the landmarks section.

**Comment by mcking65** [comment]
Resolved by #2818
