### ISSUE TITLE
Combobox date picker doesn't seem to open grid with keyboard without a screen reader

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#1760]
It works with JAWS running to press the down arrow to open the date picker, but not with the down arrow if a keyboard user is not using a screen reader.

![image](https://user-images.githubusercontent.com/2365411/107793895-cec1f500-6d24-11eb-9859-80fefed90a95.png)

https://w3c.github.io/aria-practices/examples/combobox/combobox-datepicker.html

SOLUTION
Not sure best way to open the picker with keyboard (either down arrow or ENTER or SPACEBAR). But let's make a decision and provide a way to open the date picker with keyboard without a screen reader running.

**Comment by JAWS-test** [comment]
On my Windows PC Alt+Arrow down and Arrow down works in Firefox and Chrome and without screen reader

**Comment by carmacleod** [comment]
@DavidMacDonald 

<kbd>Down arrow</kbd> and <kbd>Alt+Down arrow</kbd> open the grid for me, too. Tested without screen reader in Windows Chrome, FF and Edge, and Mac Chrome, FF and Safari. Please try again, and consider closing this issue.
https://w3c.github.io/aria-practices/examples/combobox/combobox-datepicker.html

Regarding <kbd>Enter</kbd> and <kbd>Space</kbd>, please see the [Keyboard Interaction section of the combobox design pattern](https://w3c.github.io/aria-practices/#combobox-keyboard-interaction) for an explanation of what those keys are expected to do in an editable combobox.
