### ISSUE TITLE
Review section on roles that have presentational children

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#178]
Please review this new 
[section describing roles that automatically make their children presentational.](http://w3c.github.io/aria-practices/#children_presentational)

#### Requested Reviews

- [x] Review by @jongund 
- [x] Review by @annabbott

**Comment by annabbott** [comment]
Looks good

**Comment by mcking65** [comment]
Closing this issue as reviews are now complete. If anyone later comes to this issue from the publication on w3.org because they have feedback, please feel free to re-open the issue.
