### ISSUE TITLE
Remove dependency "npm-merge-driver"

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#1789]
See #1766

When running `npm audit fix --force` it changes the version for `npm-merge-driver` to `^0.0.0`, which seems weird at first. Changing it back to `^2.3.6` and running `npm audit` again it finds 7 low severity vulnerabilities.

I'd like to get `npm audit` to report 0 vulnerabilities and keep it there. Until `npm-merge-driver` gets a new version, I suggest we drop this dependency.

**Comment by zcorpan** [comment]
This dependency was introduced in #1316.

@nschonni @jesdaigle @mcking65 thoughts?

**Comment by mcking65** [comment]
Bummer ... merge-driver seems like a super useful utility. Are there no safe options? Fixing merge conflicts from dependabot PRs by hand seems like another painful bit of overhead.

**Comment by nschonni** [comment]
@mcking65 I don't think the Dependabot PRs have the same problem as the GreenKeeper ones, as it automatically rebases or can recreate PRs through it's `@` commands.
I think the use case now is more for local developers merging and rebasing their branches, but I haven't really tested doing that much without the merge-driver.

I pinged someone from the NPM side to see https://github.com/npm/npm-merge-driver is going to get some updates or not

**Comment by zcorpan** [comment]
`npm-merge-driver` has not had any new commits since March 2020, and it's [incompatible with package-lock.json version 2](https://github.com/npm/npm-merge-driver/issues/26).

I still suggest we remove this dependency.
