### ISSUE TITLE
Use pointer events instead of mouse events

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#1799]
Following up on what we learned about [pointer events](https://www.w3.org/TR/pointerevents/) from the slider example updates for touch screens and touch-based ATs. Special thanks to @patrickhlauke for his guidance, and to @jongund for the slider example updates, which included switching to pointer events.

We need to:
- list all examples that still use mouse events
- decide which order to update them in (one at a time!)
- for every instance of the word "mouse" in code, tests, comments, the example prose, or even in the pattern description, consider whether "mouse" needs to be changed to "pointer", or perhaps "mouse and other pointer-based input devices", or similar (depending on whether in code or doc).
- review each updated example and retest in all the places (including mobile/touch) and with all the ATs

[Caniuse data for pointer events](https://caniuse.com/?search=pointer%20events).
[MDN documentation for pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events).

**Comment by nschonni** [comment]
Might also want to create a project in https://github.com/w3c/aria-practices/projects with @spectranaut script

**Comment by a11ydoer** [comment]
@carmacleod  can I close this issue since we implemented this at slider examples? Thanks for your consideraiton.

**Comment by carmacleod** [comment]
@a11ydoer 
> @carmacleod can I close this issue since we implemented this at slider examples?

Nope. :)

This issue isn't about slider. It's about carousel and combobox and treeview and toolbar and datepicker and menubar and listbox and maybe other examples as well. We need to find all the places, fix them all, and retest. :)

**Comment by a11ydoer** [comment]
@carmacleod oh, I see the last bullet point from you. I updated the issue title so that we can easily understand the issue scope.
