### ISSUE TITLE
Update warning in slider design patterns/fix broken link

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#1800]
The warning in the [slider](https://w3c.github.io/aria-practices/#slider) and [multi-thumb slider](https://w3c.github.io/aria-practices/#slidertwothumb) design patterns needs to be updated to the latest wording from the new color slider example page.

Also, the Horizontal Slider Examples link in the [slider](https://w3c.github.io/aria-practices/#slider) design pattern needs to be changed from:
https://w3c.github.io/aria-practices/examples/slider/slider-1.html
to:
https://w3c.github.io/aria-practices/examples/slider/slider-color-viewer.html

and maybe change the link text to "Color Viewer Slider"?

**Comment by jongund** [comment]
@carmacleod 
I updated the warning message is both the thermostat and multithumb slider branches to match what is in color viewer slider.

**Comment by carmacleod** [comment]
This is about the warning note in the Slider Design Pattern itself in the top-level index.html file.
I don't see that note updated in any of the slider PRs.

Here are the 2 design pattern links. They both have the old note:
- [slider design pattern](https://w3c.github.io/aria-practices/#slider)
- [multi-thumb slider design pattern](https://w3c.github.io/aria-practices/#slidertwothumb)

Also, the link in the first pattern still points to slider-1.html and it needs to point to slider-color-viewer.html.

I also noticed that you renamed "Horizontal Slider" to "Color Viewer Slider" in the examples/index.html (but not in the top level index.html). You may want to change the top level index.html design pattern example links to have the new name and link.

**Comment by jongund** [comment]
@carmacleod 

Here are the links to Preview Links in PRs:
* [Preview multi-thumb slider in PR#1758](https://raw.githack.com/w3c/aria-practices/slider-multithumb-update/examples/slider/slider-multithumb.html)
* [Preview slider thermostat in PR#1755](https://raw.githack.com/w3c/aria-practices/slider-thermostat-update/examples/slider/slider-thermostat.html)

**Comment by carmacleod** [comment]
@jongund 
My bad - I forgot that the top-level filename was called `aria-practices.html`, and I was calling it `index.html`. I've edited my previous comment.

So I created PR to show what I mean. Please review! :)

Also note that after #1755 is merged, we will also need to update `slider-2.html` to `slider-thermostat.html` in aria-practices.html (and change "Three thermostat control sliders" to "Two thermostat control sliders"),

and after #1758 is merged, we will need to update `multithumb-slider.html` to `slider-multithumb.html` in aria-practices.html.

**Comment by a11ydoer** [comment]
@jongund @carmacleod @mcking65  I reviewed the change one more time. it is ready to be merged.

**Comment by a11ydoer** [comment]
#1803 PR is merged and closed. @jongund @carmacleod and @mcking65
