### ISSUE TITLE
HTML Validator does not allow role="presentation" or role="none" on SVG elements

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1828]
I am trying to add role="presentation" or role="none" to the SVG elements in the [Slider Thermostat](https://raw.githack.com/w3c/aria-practices/slider-thermostat-update/examples/slider/slider-thermostat.html) example in pull #1755, and I am getting html linting errors that these roles are not allowed on the SVG element:

```
Error: "file:/home/runner/work/aria-practices/aria-practices/examples/slider/slider-thermostat.html":58.13-58.84: error: Bad value “presentation” for attribute “role” on element “svg”.
Error: "file:/home/runner/work/aria-practices/aria-practices/examples/slider/slider-thermostat.html":81.13-81.83: error: Bad value “presentation” for attribute “role” on element “svg”.
```

The same error is generated for `role=none` on the SVG element.

**Comment by nschonni** [comment]
I think the upstream bug is https://github.com/validator/validator/issues/1096

**Comment by jongund** [comment]
@nschonni 
How do we get this fix for role on SVG in our linter?

**Comment by nschonni** [comment]
Errors/warnings can be suppressed in https://github.com/w3c/aria-practices/blob/main/.vnurc. I'd probably point to the upstream tracking bug as a comment or point to this issue and leave it open till the upstream is fixed

**Comment by jongund** [comment]
@nschonni 
I tried to add something to the `.vnurc` file in my pull request, but that doesn't change the error:
https://github.com/w3c/aria-practices/commit/bcbdeed933575ae3f32f41687c6dff414df7cc3f

Sorry I am not familiar with the VNU validator configuration, who can add the regex statement to allow the `role` attribute on SVG elements and what file needs to be changed and in which branch?

**Comment by jongund** [comment]
@nschonni 
Thank you for the help, that fixed it.
