### ISSUE TITLE
Editorial refinement for editor menubar example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#183]
For [editor menubar example](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html):

- [x] Fix title tag and page title
- [x] Fix heading structure and organization to match template
- [x] remove extra regions
- [x] Add nav element to end of page
- [x] Resolve language phrasing and clarity issues
- [x] Add scope attributes and row headings to role, state, property and tabindex tables.

**Comment by a11ydoer** [comment]
Great. Thanks so much! @mcking65
