### ISSUE TITLE
Update alert example to current template

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#185]
The [alert example page](http://w3c.github.io/aria-practices/examples/alert/index.html) needs to be updated to use the current 
[example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html).

**Comment by MichielBijl** [comment]
This is fixed in https://github.com/w3c/aria-practices/commit/9f3209e450a58d6eb1d247862563a400bf724753.
