### ISSUE TITLE
Getting error: .husky/pre-commit: line 2: .husky/_/husky.sh: No such file or directory

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1855]
@nschonni 

I am getting the following error after creating a new branch when I commit:
.husky/pre-commit: line 2: .husky/_/husky.sh: No such file or directory

What do I need to do?

**Comment by nschonni** [comment]
@zcorpan updated it to a newer version in https://github.com/w3c/aria-practices/pull/1756
Not sure what other changes might be required

**Comment by jongund** [comment]
@nschonni 
@zcorpan 
So what should I do?
I have a new branch `slider-valuetext` for changes to the examples using `aria-valuetext`, and I cannot even commit to the repository.

**Comment by jongund** [comment]
@nschonni 
@zcorpan 
@mcking65 
Look for some guidance here on what should be my next step?
Is pushing new branches to the APG repository broken?

**Comment by jongund** [comment]
The `npm install` seemed to fix the problem.

**Comment by zcorpan** [comment]
Seeing this now -- apologies for the delay, but good that `npm install` fixed it!

As noted in https://github.com/w3c/aria-practices/pull/1756#issuecomment-779812215 the update had breaking changes, so with the current `main` you need the new version of husky (which `npm install` does).
