### ISSUE TITLE
Accordian guidance and examples using summary/details

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1856]
Currently we do not have any guidance or examples using the html `details/summary` elements.

**Comment by mcking65** [comment]
summary/details works perfectly for disclosures, but how do you get heading semantics equivalent to the accordion pattern?

**Comment by basher** [comment]
> summary/details works perfectly for disclosures, but how do you get heading semantics equivalent to the accordion pattern?

It's a shame that we cannot nest a heading inside the summary, so for that reason, I still prefer to use the ARIA example.
