### ISSUE TITLE
Review editorial changes to breadcrumb pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#186]
Updated [Breadcrumb Pattern](http://w3c.github.io/aria-practices/#breadcrumb) to:

* Remove "author should" language from states and properties.
* Clarify labeling.
* Fix minor grammar/editorial issues.

#### Status of Requested Reviews

- [x] Review by @MichielBijl   
- [x] Review by @jnurthen

**Comment by MichielBijl** [comment]
I’ll review this/next week. Thank you Matt!

**Comment by jnurthen** [comment]
This is good to go.

**Comment by MichielBijl** [comment]
I concur, looks good to me 👍
