### ISSUE TITLE
ARIA datepicker example (contrast too low)

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/aria-practices#1862]
In the ARIA practices [datepicker example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html), the contrast of the 14px `h2` (month year) and the hint text "Cursor keys can navigate dates" is 4.1:1 - blue should be a bit darker so it meets 4.5:1.

**Comment by JAWS-test** [comment]
It's already fixed at https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html (4,7:1)
