### ISSUE TITLE
Review updates to breadcrumb example page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#187]
Make the following updates to  the [breadcrumb example page](http://w3c.github.io/aria-practices/examples/breadcrumb/index.html):

- [x] Implement the current [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html).
- [x] Shorten title to "ARIA Breadcrumb Example"
- [x] Fix typo "markedup "
- [x] Add visual decoration separators via CSS (so they are not announced by SRs)

**Comment by danieldafoe** [comment]
Is there an example of one of the example pages implemented with the new template?

**Comment by MichielBijl** [comment]
@danieldafoe you mean like an actual page where this is implemented?

**Comment by danieldafoe** [comment]
When I cloned the repo and wanted to follow the new template given, I just wanted to see an existing page that has implemented the new template (page structure) that should be followed. As a reference, say.

Hopefully that's clear enough.

**Comment by MichielBijl** [comment]
Ahh, the [tabs example](http://w3c.github.io/aria-practices/examples/tabs/tabs.html) uses the new template although it’s missing the “Accessibility Features” section.

**Comment by danieldafoe** [comment]
Thank you! I'll refer to that in the future.

And no, go right ahead. I'll take a look at yours once completed as well so I know for next time. Thanks for the help.

**Comment by MichielBijl** [comment]
This is fixed in https://github.com/w3c/aria-practices/commit/4648a41260c2d7a63fe86ba99e78c7dfea50eff4 & https://github.com/w3c/aria-practices/commit/b00aeb6acada77fcdc6bebc2bb0aea033011aa93 in [the breadcrumb branch](https://github.com/w3c/aria-practices/tree/breadcrumb).

There is [pull request for this issue](https://github.com/w3c/aria-practices/pull/266).

- [ ] Review @mcking65 
- [ ] Review @jnurthen

**Comment by mcking65** [comment]
I added 3 more commits; please have a look.

I see one more issue that I didn't touch. The separators are made with the content property so they are still announced by screen readers. I think an image would be much better so we can get rid of the unnecessary screen reader verbosity. If we don't do this, then we should change the accessibility properties subsection. However, I strongly believe those separators are pure decoration, especially since we have the list structure.

**Comment by MichielBijl** [comment]
Last issue fixed in https://github.com/w3c/aria-practices/pull/283.

**Comment by mcking65** [comment]
OK, I think all issues are resolved. @jnurthen, please take alook and comment if you agree. If yes, we can close.

**Comment by getaccessibility** [comment]
Ideally the current page "Breadcrumb" can be a plain text instead of anchor as it is current page. Is it wantedly coded in anchor tag as aria-current is used ?

**Comment by MichielBijl** [comment]
@getaccessibility it is knowingly done as it’s one of the requirements for aria-current.

**Comment by jnurthen** [comment]
Looks good to me

**Comment by mcking65** [comment]
OK, looks like this review is complete. Thanks @MichielBijl for making this example!
