### ISSUE TITLE
Review editorial revisions to button design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#188]
Made editorial revisions to the [button design pattern](http://w3c.github.io/aria-practices/#button) to:

* Fix multiple instances of future tense being used instead of present tense or incorrect tense in subjunctives.
* Remove multiple instances of normative or implicit normative wording where "must", "should" or "may" were used.
* Fixed format of keyboard section.

#### Status of requested reviews

- [x] Review by @jnurthen 
- [x] Review by @annabbott

**Comment by annabbott** [comment]
Suggestion: 
"When the action associated with a button is unavailable, the button has aria-disabled set to true."
Add a statement like:
"Inactive or disabled buttons should appear greyed out and receive focus,"

**Comment by jnurthen** [comment]
Looks good.

**Comment by mcking65** [comment]
@annabbott, 

Typically, disabled buttons are not focusable. If you have the HTML `<button disabled>My button</button>`, browsers will remove that native html button from the tab sequence. 

Wwe put a note about sometimes bucking this practice in the context of toolbars that manage focus. We could consider a similar note here. So, I have raised an issue for it.

**Comment by mcking65** [comment]
This review is now complete.
