### ISSUE TITLE
Default to running AVA as headless?

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#1885]
I was working on implementing a way to run AVA as headless, and later found that it is already possible:

https://github.com/w3c/aria-practices/wiki/Regression-Tests-for-APG-Example-Pages#running-tests

> To run in firefox headless mode:
> ```
> $ CI=1 npm run regression 
> ```

I have read these docs before but somehow missed this.

Would it make sense to change the default to run tests as headless, and opt in to non-headless with e.g.

```
$ DEBUG=1 npm run regression
```

?

**Comment by mcking65** [comment]
@zcorpan 
Would this change only the experience when running tests locally, i.e.,  Firefox windows would no longer open/close? Seems like it would be an improvement.

@jongund , what do you think?

**Comment by zcorpan** [comment]
Correct.

**Comment by jongund** [comment]
@zcorpan @mcking65 
I don't see a problem with the change, since the browser opening and closing doesn't really contribute to understanding the test results.
