### ISSUE TITLE
breadcrumb example file name change from index.html to breadcrumb.html for Example Index page.I have updated the roles to include roles in ARIA 1.2, including `meter` role.

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#1886]
The problem with the breadcrumb example not being indexed is the use of the file name "index.html" for the example, all files with "index.html" are ignored in the indexing scripts.  So the file name needs to change to something like "breadcrumb.html".

_Originally posted by @jongund in https://github.com/w3c/aria-practices/issues/1859#issuecomment-831964303_

**Comment by a11ydoer** [comment]
@jongund can you confirm tht whether I can close this issue?

**Comment by a11ydoer** [comment]
The changes were merged.

**Comment by jongund** [comment]
In the main branch breadcrumb example is still using `index.html`.

I there a pull request to make the change to the main branch?
