### ISSUE TITLE
Updates needed for button example page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#189]
The [button example page](http://w3c.github.io/aria-practices/examples/button/button.html) 
needs the following changes.

- [x] Update to use the current [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html)
- [x] Make the toggle button with anchor instead of span.
- [x] Drop the 3rd "show alert" button example.
- [x] Remove the "non-compliant" example or change it to follow the pattern; the task force has agreed to not include anti-patterns.
- [x] Change the title to "Button Examples"
- [x] Fix misspellings.
- [x] Task force decision on whether a note discouraging use of role button in favor of html buttons is warranted. If yes, agree on a wording.

**Comment by annabbott** [comment]
If the task force has agreed to not include anti-patterns, then the non-compliant pattern "a element with href="#"" should be deleted.

**Comment by mcking65** [comment]
I am not comfortable with the wording of the following note so I am removing it for now, and I am adding a task to the above checklist to address this point.

>Note: When using HTML, use the button element. 
>It is recommended that authors not re-purpose other elements to create buttons. 

If we are going to have a note like this, the note should either include a crisp statement of rationale or link to an explanation.

**Comment by jongund** [comment]
Does the mute button need to change the accessible when it toggles from pressed to unpressed (e.g. mute to unmute)?

**Comment by mcking65** [comment]
@jongund wrote:
>Does the mute button need to change the accessible when it toggles from pressed to unpressed (e.g. mute to unmute)?

No, in fact, the design pattern explicitly warns people not to do that. We may want to remind of them of that on the example page in the properties table.

**Comment by mdahamiwal** [comment]
The first button example "Print Page" doesn't specify `tabindex` and is not part of tab order.

**Comment by mdahamiwal** [comment]
@mcking65, can you review the fix?

**Comment by jnurthen** [comment]
@mdahamiwal thanks.

**Comment by mcking65** [comment]
1. Make the toggle button with anchor instead of span.
2. Drop the 3rd "show alert" button example.

**Comment by jnurthen** [comment]
Resolved in 3/13/2017 meeting not to add a note discouraging button role

**Comment by mcking65** [comment]
@jongund, while working on editorial clean up, I noticed that the svg for the toggle is inline but not part of the example div. Since it is a part of the example, it should either be inside that div, which might be distracting to people reading the html, or in an svg file. I sort of prefer the latter for both clarity and consistency with other examples.

**Comment by jongund** [comment]
Fixed

**Comment by annabbott** [comment]
Under Toggle Button, the following statement is present:
Mute button uses a a element.
Suggested edit:
Mute button uses an a element.

**Comment by jongund** [comment]
I moved the SVG to an external file

**Comment by mcking65** [comment]
All updates are now complete and being reviewed in issue 316. Closing.
