### ISSUE TITLE
Enforce beautify standards and validate code to catch mistakes

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#19]
_From @MichielBijl on January 13, 2016 0:8_

As noted by Karl Groves: [we should enforce beautify standards and require that all PR's pass the validity checks](https://github.com/w3c/aria/issues/174#issuecomment-171105153).

As this only affects the practices, I propose we add a separate README.md in there (as to not litter the main README).

@jnurthen noted that because we need to write stuff that is ARIA 1.1/2.0 it might not validate. Still, validating the code to catch other error should be mandatory.

_Copied from original issue: w3c/aria#202_

**Comment by MichielBijl** [comment]
Related issues: https://github.com/w3c/aria/issues/88, https://github.com/w3c/aria/issues/95, and https://github.com/w3c/aria/issues/131

**Comment by MichielBijl** [comment]
_From @jnurthen on January 13, 2016 1:29_

What do you mean by validate? We have requirements to use aria 1.1 features which may not be implemented in any validator.

**Comment by MichielBijl** [comment]
Good point. Still, if you go through the code in https://github.com/w3c/aria/issues/174 you'll see _a lot_ of errors not related to aria (1.1). All current examples now actually validate in the nu validator.

But we should allow for errors and warnings related to ARIA 1.1/2.0.

**Comment by MichielBijl** [comment]
@jnurthen I started on [a README and EditorConfig file](https://github.com/w3c/aria/tree/feature/editorconfig/practices). I've included an exception for warnings/errors related to future ARIA stuff. Does this seem fair to you?

**Comment by MichielBijl** [comment]
I have added [research on the use of js-beautify](https://github.com/w3c/aria/blob/feature/editorconfig/practices/tests/Beautification%20test%20results.md#test-2-js-beautify).

**Comment by MichielBijl** [comment]
Part of this was an [EditorConfig file, that is now provided](https://github.com/w3c/aria/issues/131).

**Comment by MichielBijl** [comment]
_From @handcoding on April 7, 2016 16:47_

For @MichielBijl and others—

On the subject of the [EditorConfig file](https://github.com/w3c/aria/issues/131), can I make a request for an _indent_size_ that’s larger than 2?

For those of us with spatial-acuity issues (like me), an indent size of only 2 can make it hard to tell which lines of code share the same indention level. Would anyone be open to an indent size of, like, 4-ish?

**Comment by MichielBijl** [comment]
@handcoding sorry, I wasn't aware of that. I don't mind the 4 spaces indent. I prefer 2 spaces, but if 4 spaces is easier to read for more people; I'm fine with it.

**Comment by MichielBijl** [comment]
@handcoding: I have set indent_size to 4 in https://github.com/w3c/aria-practices/commit/20cfaa586170ee9ac725c289ffb7fd3939861254

I still need to indent the entire document to this new format, but haven't come around to that.

**Comment by mcking65** [comment]
Closing this issue based on discussion in August 15, 2016 meeting and the work that is happening in issue #12.
