### ISSUE TITLE
Demos of the tabs widget use the `hidden` attribute for inactive panels. Does that conform to the spec of the attribute?

### ISSUE THREAD

**Issue by ianthedev** [w3c/aria-practices#1920]
In a discussion with someone about tabpanels hidden by the `hidden` attribute causes an issue of a jQuery plugin, he pointed out that [the HTML spec of the `hidden` attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute) says the attribute shouldn't be used for tabs:
> The hidden attribute must not be used to hide content that could legitimately be shown in another presentation. **For example, it is incorrect to use hidden to hide panels in a tabbed dialog,** because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar. It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked hidden, it is hidden from all presentations, including, for instance, screen readers.

But [WAI-ARIA's official demos of the tabs widget](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) use the `hidden` attribute for inactive tabpanels. I'm not sure if that conforms to the spec of the `hidden` attribute. Any advice would be appreciated.

**Comment by JAWS-test** [comment]
I think this is a bug in the HTML specification. Hidden tabs should be hidden for all users, also if a screen reader is used.

**Comment by ianthedev** [comment]
> 
> 
> I think this is a bug in the HTML specification. Hidden tabs should be hidden for all users, also if a screen reader is used.

Thanks. Maybe I was not clear enough. The main concern is whether it is wrong to use `hidden` for inactive panels.

**Comment by JAWS-test** [comment]
>  for inactive panels.

What do you mean by inactive? Not visible: then hidden should be ok.

**Comment by ianthedev** [comment]
> 
> What do you mean by inactive?

I mean not visible. The problem is that the [spec of the `hidden` attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute) says "it is incorrect to use hidden to hide panels in a tabbed dialog".

**Comment by JAWS-test** [comment]
@ianthedev Yes, and I think that the HTML specification is wrong at this point and therefore an issue should be opened there rather than here

**Comment by ianthedev** [comment]
@JAWS-test I see. Could you please provide the hyperlink of the repository? I searched but couldn't find an appropriate one.

**Comment by JAWS-test** [comment]
https://chromiumbugs.appspot.com

**Comment by JAWS-test** [comment]
https://github.com/whatwg/html/issues/new
