### ISSUE TITLE
Example of the select-only combobox incorrectly selects an option after visual focus is moved followed by clicking any other place

### ISSUE THREAD

**Issue by ianthedev** [w3c/aria-practices#1922]
The [example of the select-only combobox](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) has an incorrect behavior. The steps to reproduce are:
1. Open the listbox popup either by using mouse or keyboard
2. Use the `Up` or `Down` key to move the visual focus to any of the options
3. Use mouse to click any other place of the document and cause the listbox popup to close
4. The combobox now incorrectly has a selected option

I was expecting clicking any other place of the document to simply close the listbox, just like how pressing the `Esc` key works, without selecting any option.

**Comment by JAWS-test** [comment]
This is not a bug in my opinion, but perfectly correct, as in accordance with the behavior of a native HTML `<select>`

**Comment by ianthedev** [comment]
I think such a behavior is fine for native HTML `<select>` because the value is always taken over when navigating the list of options of `<select>` and the value is not discarded, like you said.

However, one of the **Accessibility Features** of select-only combobox explicitly states that it does not follow the same approach:
> Navigating the list of options does not set the value of the input. This gives screen reader users, who need to navigate among the options to perceive them, the ability to explore options without losing the current value of the input.

**Comment by ianthedev** [comment]
Well... after a close inspection, I found that the **Accessibility Features** also states:
> The value is set when users press `Space`, `Enter`, or `Tab`, or when focus moves out of the combobox.

So I guess the behavior does conforms to the "**_or when focus moves out of the combobox_**", literally?
