### ISSUE TITLE
Review editorial revisions of alert design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#194]
The [alert design pattern](http://w3c.github.io/aria-practices/#alert) had several instances of language like "author should" that sounded normative. 

commit cade0cc2fdf21774777166aef5faafc58f9dc7e7
includes changes to the introduction section of the design pattern to eliminate them.

#### Status of request reviews

- [x] Review by @jnurthen

**Comment by jnurthen** [comment]
I don't like the change to the last line adding the work compliance - I have an aversion to the word :). I would prefer to word it as
" Frequent interruptions inhibit usability for people with visual and cognitive disabilities, which may lead to the content failing to meet <a href="http://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-postponed.html">WCAG 2.0 success criterion 2.2.4</a>."

Other than that it is good.

**Comment by mcking65** [comment]
@jnurthen, 

I agree; it is good to avoid the word "compliance" in this guide. I originally put it in because repetition of the "failure to meet" phrasing was awkward. I have instead changed it to:

>Frequent interruptions inhibit usability for people with visual and cognitive disabilities, 
>which makes meeting the requirements of WCAG 2.0 success criterion 2.2.4 more difficult.

**Comment by mcking65** [comment]
This review is now complete.
