### ISSUE TITLE
Add Coverage Report to index generation for GitHub Pages

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1975]
Simon, 

Can you add generating the coverage report report script: `script/coverage-report.js` 
So when github pages are updated the coverage report is also updated and included: `coverage/index.html`

This was requested by the group at 13 July APG meeting.

**Comment by a11ydoer** [comment]
taging @zcorpan to notify. 

Once this work is done,  I will add coverage report link to Wiki and README. Please ping me for the update. Thanks, Simon.

**Comment by zcorpan** [comment]
I'm not currently working on APG. @jesdaigle can you reassign, please?
