### ISSUE TITLE
Develop example of tabs design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#20]
_From @MichielBijl on January 13, 2016 12:32_

The [Tab Panel design pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel) ~~has been reviewed and is ready for development~~ will be reviewed on February 29th.

_Copied from original issue: w3c/aria#204_

**Comment by MichielBijl** [comment]
Work on this is in [MichielBijl/tabpanel](https://github.com/MichielBijl/tabpanel).

**Comment by MichielBijl** [comment]
_From @mcking65 on February 22, 2016 4:17_

I do not see any record of a tabpanel pattern review, and I do see a lot of problems with the design pattern itself. This is on the APG agenda for 22 Feb.

**Comment by MichielBijl** [comment]
_From @mcking65 on February 22, 2016 4:43_

Some of the substantive (non-editorial) Issues in the current tabpanel design pattern characteristics table include :

1. The only interaction model described is where selection follows focus in the tablist. With such tablists, as the user moves focus in the tablist, the active tab changes, the selection state moves with focus, and the content of the tabpanel changes. There are tablists where the active tab does not change as the user moves focus in the tablist. This is usually the case if an expensive operation, such as a pageload, is required to pull in the new tabpanel content. If selection does not follow focus, the user needs to press a key, such as enter or space, to change the active tab.

2. There are several unconventional key commands mentioned. CTRL+UP is captured by all Win screen readers so would not be useful to those users. ALT+Del, as described, suggests a destructive operation on an element that is not focused. I don't think that is a good idea. Supporting the del key when focus is inside the tablist would be better.

3. The issue of horizontal vs vertical orientation is not adequately addressed. ARIA 1.1 supports orintation on tablists. ARIA 1.0 did not.

**Comment by MichielBijl** [comment]
Hmm, the wiki does list it as reviewed. I should've checked that. We'll discuss it today and we can move this along. I have left out all the ctrl support in my current version, as @jnurthen had said those are likely to be removed.

**Comment by mcking65** [comment]
Michiel's implementation of tabs where select follows focus is at:
http://w3c.github.io/aria-practices/examples/tabs/tabs.html

It is ready for review.
