### ISSUE TITLE
What's the reasoning behind "If visual focus is on the last option, visual focus does not move." for Select-Only Combobox widgets?

### ISSUE THREAD

**Issue by ianthedev** [w3c/aria-practices#2024]
Select-Only Combobox widget has the following requirements for [its Listbox Popup](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html#kbd_label_listbox) for when pressing the `Down Arrow` key and the `Up Arrow` key, respectively (emphasis added):

> If visual focus is on the last option, visual focus **does not move**.

> If visual focus is on the first option, visual focus **does not move**.

I cannot think of a logical reasoning behind such requirements.

Such requirements are also inconsistent with non-Select-Only Combobox widgets (examples in the second unordered list on [this page](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html)) and [menus](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html), in which pressing the said keys in the same situations moves the focus or visual focus to the option on the opposite end.

Any advice would be appreciated.

**Comment by mitchellevan** [comment]
This is a good question. The page answers it here:

> The following example... demonstrates a single-select combobox widget that is functionally similar to an HTML `select` element

Is this sufficient?

**Comment by ianthedev** [comment]
@mitchellevan Yes. Thank you very much.
