### ISSUE TITLE
aria-modal not working on mobile webview

### ISSUE THREAD

**Issue by uxsi** [w3c/aria-practices#2030]
the elements in page outside the modal dialog are also focusable on mobile screen reader

https://user-images.githubusercontent.com/4378939/131075640-1bb7edec-4efb-4c3d-b7e1-e392c1b59365.MP4

**Comment by mcking65** [comment]
This is a bug in VoiceOver support for the aria-modal property, not a butg in the APG example. We will cover this in the aria-at project.
