### ISSUE TITLE
[Listbox] Pattern does not include guidance on aria-expanded but example does

### ISSUE THREAD

**Issue by dballesteros7** [w3c/aria-practices#2031]
The [Collapsible Listbox](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html) example has guidance on how to use aria-expanded with a listbox but this is attribute is not mentioned in the pattern for Listbox.

This seems like a common use case that could be documented in the Listbox pattern. Also it would help with the confusion from #1318 and #618.

**Comment by mcking65** [comment]
We have deprecated the collapsable listbox pattern in APG 1.2 because it is better served by the new select-only combobox pattern.

See https://www.w3.org/TR/wai-aria-practices/examples/combobox/combobox-select-only.html
