### ISSUE TITLE
Tab key behavior Menubar pattern is not clear

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#2044]
I was working with a developer who was looking at the menubar pattern in the APG and the description of the behavior of the `tab` key was not clear to him.  Basically it was not clear that the menubar was just one tab stop on the page was not clear.

**Comment by a11ydoer** [comment]
Jon will help to point out the text which causes ambiguous meaning.

**Comment by a11ydoer** [comment]
It would be great if we can find that whether radio group or tool bar will have the same problem

**Comment by a11ydoer** [comment]
from james,  "just from looking, it is different. In menubar it's at the end of the pattern, and in toolbar it's up front and the first thing in the pattern"

**Comment by a11ydoer** [comment]
resolution: using tool bar pattern info for the menu bar consistently will be a good improvment.

**Comment by jongund** [comment]
Update `menubar` to use the `toolbar` keyboard interaction description for tab/shift tab.
