### ISSUE TITLE
Add git hook and CI for updating the coverage and quality report page

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#2061]
Similar with what is done for `example/index.html`, this file should be generated if any related files are touched. A diff check should also be done if something is skipped locally with a check in CI.

- [ ] Identify the files that should trigger a generation/CI check
- [ ] Create script in `package.json` to call `node scripts/coverage-report.js`
- [ ] Add git hook similar to https://github.com/w3c/aria-practices/blob/45e9a6c4b19ea03356a9aa1cda8c8eaaf3272015/package.json#L73-L76
- [ ] Add new CI job similar to https://github.com/w3c/aria-practices/blob/main/.github/workflows/examples.yml, but the existing `coverage-report.yml` is doing a different job right now

**Comment by mcking65** [comment]
The coverage and quality report is now published as part of APG in content/about/coverage-and-quality/coverage-and-quality-report.html. It should be updated with every commit to main.

It would be very helpful if the generated report page include the date it was last generated under the heading "About These Reports".

The first paragraph under the heading could be:

>These were reports were updated on monthName, dayNumber, yearNumber.
