### ISSUE TITLE
Should tab panels activate on focus?

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#21]
_From @becka11y on January 18, 2016 22:38_

Currently a tab panel activates when the associated tab gets focus.  This is not efficient for keyboard users as they must (potentially) wait for the panel content to load before moving focus to the next tab/tab panel.  Many designers would prefer to have the user activate the tab to make the tab panel load and display.  This is an easy addition to the current behavior.  Just remove the phrase that indicate that the tab is activated on focus.  It basically makes the tab panel behave more like an accordion.
I have made the changes in the attached pdf.  I also quickly modified the existing example from the Open Ajax Alliance to demonstrate this behavior.
[ARIA_TabPanelAccordion.html.zip](https://github.com/w3c/aria/files/95089/ARIA_TabPanelAccordion.html.zip)
 
[ARIA_TabPanelAlternative.pdf](https://github.com/w3c/aria/files/95084/ARIA_TabPanelAlternative.pdf)

_Copied from original issue: w3c/aria#206_

**Comment by MichielBijl** [comment]
Why should users wait for panels to load? I don't think navigation is blocked in anyway while tab panels load? Here is an example of [tab panel navigation in the OS X Settings.app](https://www.youtube.com/watch?v=Maa73HqDsSw).

**Comment by MichielBijl** [comment]
_From @becka11y on January 19, 2016 14:4_

I should have been specific that this is about web pages with significant content in the panel.  Most developers use AJAX to load a page and will start the load as soon as the tab panel receives focus and is activated (per the current spec).  Generally, the user has to wait for the load to complete before they can move focus to the next tab. This can be very tedious if the panel you want is a fair distance from the current focus.  FWIW - JAWS expects the space/enter press to activate a tab panel and load the contents.

**Comment by MichielBijl** [comment]
> Most developers use AJAX to load a page and will start the load as soon as the tab panel receives focus

Fair enough.

>  Generally, the user has to wait for the load to complete before they can move focus to the next tab.

That seems to be unnecessary behaviour? Is there any reason navigation is disabled? Loading of a tabpanel should not be connected to the ability to navigate tabs. Browsers and their tabs don't show this behaviour. It does not make sense to me, but that might just be me.

> This can be very tedious if the panel you want is a fair distance from the current focus.

Agreed, that is why it doesn't make sense to disable navigation until a particular tabpanel is loaded.

> FWIW - JAWS expects the space/enter press to activate a tab panel and load the contents.

VoiceOver does the same thing if you navigate with the VO-keys.

I'm rather unfamiliar with Windows, so don't know the specifics of interaction, but the “Taskbar and Start Menu Properties” settings window on Windows 7 looks like a tabbed interface. That also activates on focus.

So I would conclude that there is a difference between screen reader and keyboard navigation, correct?

**Comment by MichielBijl** [comment]
_From @klown on January 19, 2016 15:14_

Another technique that I have seen involves how long the user dwells on a tab.  That is, if they repeatedly and quickly arrow left/right, then the tabpanels associated with each tab they traverse do not display.  But, if they stop on a tab, then its panel is shown.  Note that this behaviour occurs in the absence of any AT.

An example is OS X's "Security and Privacy" system preferences, and its "General", "FileVault", "Firewall", and "Privacy" tabs.

**Comment by MichielBijl** [comment]
I've recorded a new video that shows [tab activation in OS X' Security and Privacy system preference](https://www.youtube.com/watch?v=iRmX-GvFeXI). Hope that one shows what Joseph and I refer to more clearly.

**Comment by MichielBijl** [comment]
_From @klown on January 19, 2016 15:50_

FWIW, jQuery tab panels use the display-on-dwell technique:
http://jqueryui.com/tabs/

**Comment by MichielBijl** [comment]
_From @becka11y on January 19, 2016 15:52_

So, the title change to this issue implies that I want to change the behavior - I am only asking to make the additional behavior a part of the guide.  This gives implementors  the option to implement either behavior.

**Comment by MichielBijl** [comment]
Excuse me @becka11y, I figured the new title better matches the discussion. Was I wrong? I can revert it if you want. That said, the example you included is inconsistent with both OS X and Windows, correct? I don't see how that would be an improvement on the current situation.

Would an alternative text like this be acceptable?

> Left Arrow - with focus on a tab, pressing the left arrow will move focus to the previous tab in the tab list and activate that tab **after a short delay**.

**Comment by MichielBijl** [comment]
_From @jnurthen on January 19, 2016 16:6_

+1 to allowing different behaviours.
This is a performance optimization too. Requiring each tab to be requested
places additional load on the server. Sometimes these tabs contain
computationally expensive information. As such we must not request them
unless the user requires them.

Oracle uses this model today (load tabs on request - via space/enter). This
was done at the request of our peformance group. I suspect other business
software vendors would require this too for similar reasons.

**Comment by MichielBijl** [comment]
@jnurthen wouldn't the delay before activation achieve the same thing? It seems to me that this would create inconsistent behaviour between native applications and website implementations, no?

**Comment by MichielBijl** [comment]
_From @klown on January 19, 2016 16:15_

Having thought about it a bit more, while the activate-on-dwell is another way to go, it wouldn't work well for someone with a motor impairment.  The dwell time would need to be lengthened to accommodate such a user.  They might prefer to use the navigate-and-confirm technique that @becka11y  and @jnurthen describe.

**Comment by MichielBijl** [comment]
That is certainly true. That would mean a deliberate inconsistency between native and web. What is the group's stance on that?

**Comment by MichielBijl** [comment]
@becka11y we will be doing some user testing at CSUN with tab panels. We plan to do one where they activate on focus, and one where you manually activate them via enter/space.

**Comment by MichielBijl** [comment]
_From @becka11y on February 20, 2016 14:28_

Great! I will be at CSUN, I'll look you up. Although I still don't think this should be a one or the other decision but up to the author to determine and document for users.

**Comment by MichielBijl** [comment]
_From @mcking65 on February 22, 2016 4:57_

I am with Becky and James, authors need to be able to do it either way. 

And, I think the delay idea sounds absolutely horrible for all kinds of reasons!

JAWS and other screen readers do not necessarily expect enter/space to be used. JAWS supports both models. All screen readers should. 

Here is how I advise developers to make the distinction. This works with most screen readers.

1. aria-selected=true indicates which tab is active (displayed in the tab panel).

2. If moving focus in the tablist changes the active tab, selection should follow focus.

3. If moving focus in the tablist does not change the active tab, selection should only change when enter or space is pressed and a new tab is made active.

**Comment by MichielBijl** [comment]
_From @mcking65 on February 22, 2016 5:2_

Michiel, I thought the CSUN idea was to A/B test 2 approaches to accordian:

A. Accordian built with tabbed interface.

B. Accordian built with simple show/hide expandable sections.

**Comment by MichielBijl** [comment]
@mcking65 what I discussed with @IanPouncy is that I will make two versions of the tab interface:

A. select tab panel on focus move in the tablist

B. select tab panel via enter or space on a tab

I know there is also a accordion A/B test, but not sure how those will differ. As for the delay before activating a tab, that is how it's done in OS X. If we were to support both models, would we have to differentiate between the two?

**Comment by MichielBijl** [comment]
_From @StommePoes on February 22, 2016 10:3_

"JAWS and other screen readers do not necessarily expect enter/space to be used. JAWS supports both models. All screen readers should. "

I only get JAWS stating anything about enter/space when panels are not written to the current Practices spec. That is, I'll hear it on a tab panel at work where they made each tab focusable and I can "tab" to them and cannot arrow to them. But I won't hear it on my panels which only have one focusable tab at any given time.

"+1 to allowing different behaviours."
Only if you insists and require that however the thing works is stated for users (honestly this would be good for all current widgets, not just widgets with multiple ways they work).

I really hate playing around with some of these widgets, unable to guess the correct seemingly random set of magic keystrokes that make these things work. This is partially because the web has taught me (and many others) that it is different than desktop applications. I don't double click the web, and I have traditionally tabbed to things styled like tab panels. While I currently now know to use arrow keys, that is because I am a developer and not a normal person. And we are building for normal people more than for people who read ARIA specs as bedtime stories.

**Comment by jnurthen** [comment]
@MichielBijl Is this going anywhere? Can we close this? The APG tab pattern states that tabs may or may not auto activate.

**Comment by MichielBijl** [comment]
Oh has that been changed? If so, we can close this.

**Comment by mcking65** [comment]
The design pattern text is flexible and allows for both auto-activation and manual activation. We will include both in the example implementations. Closing this issue.
