### ISSUE TITLE
Scrollable code blocks not keyboard accessible

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria-practices#2114]
This problem exists in pretty much every page in the ARIA practices. Because there is no line wrap on code examples, the lines can get wider than the width of the box. This is especially true on smaller / zoomed in screens. When this happens, the `code` element gets a horizontal scrollbar. When that happens, there is no way to scroll that region using just the keyboard.

Ideally, the code element becomes focusable as soon as it overflows. Firefox does some magic to do this, but unfortunately it's the only major browser that does this. I think the most elegant solution is to add a resize listener that checks for this, and if it happens sticks a `tabindex=0` on the `code` element.

**Comment by Malvoz** [comment]
> Ideally, the code element becomes focusable as soon as it overflows. Firefox does some magic to do this, but unfortunately it's the only major browser that does this.

Sounds like a Chromium regression, see https://chromestatus.com/feature/5231964663578624.

**Comment by scottaohara** [comment]
Don't think there's been a regression, rather than Chromium has been updated within the last couple weeks to allow for focusable scrollable elements, which wasn't the case at the time Wilco filed the issue.   This _is_ still an issue with Safari though.

**Comment by mcking65** [comment]
@a11ydoer @WilcoFiers 

Can we close this issue? Is it resolved in the current site implementation?

**Comment by WilcoFiers** [comment]
@mcking65 Yes, this looks like it has been resolved.
