### ISSUE TITLE
Example index page has duplicate landmark

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria-practices#2115]
This page has a `nav` at the top and bottom of the page, both with the same "ARIA Practices" name. Both of them, containing just the one link to the ARIA practices document:
https://w3c.github.io/aria-practices/examples/

Granted, those are two identical landmarks. Still, ARIA practices says not to use duplicate landmarks. Would using a header and footer be more appropriate for this?

**Comment by mcking65** [comment]
APG guidance is that if two navigation regions are identical, they should be named the same. This is not common, but it is important. A good example might be a pagination that is repeated above and below the thing being pagenated.

That said, this index page will soon be in the new redesign template, which will remove this issue for the index page. It will have header and footer.

Our prototype IA for the APG redesign is here:
http://wai-aria-practices.s3-website-us-east-1.amazonaws.com/index/

We are going to begin the process of migrating to the redesign template after we publish APG 1.2 as a Note during the week of Nov 15.

**Comment by WilcoFiers** [comment]
Thanks for the clarification Matt.
