### ISSUE TITLE
GitHub Pages build is failing

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#2130]
Last few merges into the main branch has been failing like https://github.com/w3c/aria-practices/runs/4201998770?check_suite_focus=true#step:3:44
Looking at the upstream actions/checkout repo, it seems like this can be caused if the PAT token being used as a repo secret `GH_TOKEN` has expired or been revoked.
I think this was your token @michael-n-cooper that is used instead of the built-in token to get around the branch rules to push to `gh-pages`

**Comment by michael-n-cooper** [comment]
I updated the token and it seems to have fixed the issue, let me know if not.

**Comment by mcking65** [comment]
Thank you, thank you @michael-n-cooper for the fast fix, on Sunday no less!! It is indeed working!

**Comment by nschonni** [comment]
Thanks @michael-n-cooper. I think this was the same problem as https://github.com/w3c/aria-common/issues/72, but I think you rolled back that deploy setup
