### ISSUE TITLE
Overly verbose section permalinks for screen reader users

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-practices#2159]
A recent change has altered the format of section permalinks within the APG.  Here's a sample:

```
<h2 id="x3-design-patterns-and-widgets">
	<a class="self-link" href="#aria_ex" aria-label="Permalink for Section 3."></a>
	<bdi class="secno">3. </bdi>
	Design Patterns and Widgets
</h2>
```

This is extremely frustrating for screen reader users.  When navigating by heading, e.g. to find a specific design pattern, they hear:

1. the repetition of "Permalink for ..."; and
2. the repetition of the section number (once in the link and once after it).

For example, here is some sample NVDA speech output when pressing 3 repeatedly to move through the "Design Patterns" section:

> Permalink for Section 3.1  link    3.1 Accordion (Sections With Show/Hide Functionality)  heading    level 3
> Permalink for Section 3.2  link    3.2 Alert  heading    level 3
> Permalink for Section 3.3  link    3.3 Alert and Message Dialogs  heading    level 3
> Permalink for Section 3.4  link    3.4 Breadcrumb  heading    level 3

That's a total of 13 syllables before the user hears the design pattern name.

#### Suggested Fix

Just make the entire heading a link, which is a WCAG-compliant and user-friendly permalink pattern.  I.e.:

```
<h2 id="x3-design-patterns-and-widgets">
	<a class="self-link" href="#aria_ex">
		<bdi class="secno">3. </bdi>
		Design Patterns and Widgets
	</a>
</h2>
```

CC @mcking65 / @sinabahram

**Comment by howard-e** [comment]
> A recent change has altered the format of section permalinks within the APG.

Seems to be a changed introduced with https://github.com/w3c/respec/pull/3874

**Comment by jscholes** [comment]
@howard-e Thanks, I filed https://github.com/w3c/respec/issues/3898.  Is there anything that can be done within the APG directly to fix this in the meantime?

**Comment by sinabahram** [comment]
Chiming in to express support and bump urgency on fixing this.

**Comment by jnurthen** [comment]
@sinabahram  https://github.com/w3c/respec/pull/3899 doesn't address the verbosity but at least reverses the order so the header comes first

**Comment by michael-n-cooper** [comment]
I've updated the TR Note to be as generated after the w3c/respec#3899 landed so the permalinks are now at the end of the headings.

**Comment by mcking65** [comment]
Fixed
