### ISSUE TITLE
Aria examples suddenly disappeared

### ISSUE THREAD

**Issue by mbgower** [w3c/aria-practices#2165]
I was just working with a trii-state checkbox and one minute it was working and the next it was 404.
It looks like a number of examples have suddenly become unavailable.

Try connecting to either of the examples under checkbox https://www.w3.org/TR/wai-aria-practices-1.2/#checkbox

**Comment by jnurthen** [comment]
works for me. Maybe it was a temporary glitch somewhere. @mbgower please close if this is resolved.

**Comment by JAWS-test** [comment]
The problem exists since yesterday, e.g. also at https://www.w3.org/TR/wai-aria-practices-1.2/#menu.

**Comment by jnurthen** [comment]
> The problem exists since yesterday, e.g. also at https://www.w3.org/TR/wai-aria-practices-1.2/#menu,

I can access the menu examples fine too.

> https://www.w3.org/TR/wai-aria-practices-1.2/examples/slider/slider-1.html

I don't think this one is linked from the document any more - the slider examples have been renamed

> https://www.w3.org/TR/wai-aria-practices-1.2/examples/carousel/carousel-1.html 

nor this - the carousel examples are renamed too.

**Comment by jnurthen** [comment]
Do you maybe have a cached version of Aria practices? The note got published yesterday so was updated. Can you try shift+reloading?

**Comment by JAWS-test** [comment]
@jnurthen That was the cause. Thanks. 

@mbgower I think the ticket can be closed
