### ISSUE TITLE
Date Picker Dialog Example faulty keyboard navigation

### ISSUE THREAD

**Issue by mjcarsjens** [w3c/aria-practices#2170]
The [Example Date Picker Dialog](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html) has some inconsistensies in usage with regards to the documented keyboard navigation.
The specific issue is with the `Page Up` and `Page Down` navigation (same goes for usage with `Shift`).

The documentation specifies the following (quote from `Page Up` documentation, same goes for the other cases):

_Sets focus on the same day of the same week. If that day does not exist, then moves focus to the same day of the previous or next week._

When focussing in the first week of a month and pressing `Page Up` or `Page Down` to a month where that same day of the week does not lie in that month the `inactive` date from the previous month is selected instead (same for last week of the month). While pressing `Enter` does in fact select that date, however it behaves weirdly when pressing for example the `Left Arrow` or `Right Arrow` key. This changes the date to respectively the last day of the previous month or the second day of the current month instead of moving to the next or previous day. This can be seen when for example pressing `Page Down` when December 1st 2021 is focused. 

Furthermore, when focussing a day in the 6th week of a month, for example January 30th 2022, and pressing `Page Up` or `Page Down` (and moving to a month with less than 6 weeks) no day is focussed anymore, causing the `Page Up`, `Page Down` and arrow keys to resume their default browser behaviour instead of navigating the datepicker dialog.

**Comment by jnurthen** [comment]
This is resolved in ARIA 1.2 - we no longer show inactive days in months
