### ISSUE TITLE
Date Picker Dialog: aria-selected on button

### ISSUE THREAD

**Issue by mjcarsjens** [w3c/aria-practices#2171]
The `button` tags in the dialog grid have implicit role `button`. The documentation states that the button corresponding to the selected date has to have the `aria-selected` attribute set to `true`. However, `aria-selected` is not actually an available attribute on the `button` role ([w3 documentation](https://www.w3.org/TR/wai-aria-1.1/#aria-selected), [mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected)).

This can possibly result in assistive technologies not being able to properly determine the selected date and will result in errors in linters.

**Comment by a11ydoer** [comment]
Hi @mjcarsjens 

I just want to make sure that you are looking at the most recent [Date Picker Dialog example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/dialog-modal/datepicker-dialog.html) since the example does have button on date grid.
