### ISSUE TITLE
typo in section 3.6

### ISSUE THREAD

**Issue by koalie** [w3c/aria-practices#2173]
(Relaying verbatim the feedback received via the W3C website comments mailing list):

> I think that there is a typo at the beginning of the second paragraph of the section "[3.6 Carousel (Slide Show or Image Rotator)](https://www.w3.org/TR/wai-aria-practices-1.1/#carousel)" in the sentence :
> "Ensuring all users can easily control and are not adversely effected by slide rotation is an essential aspect of making carousels accessible."
> "Effected" should be "**affected**" because the sentence implies that the slide rotation should not negatively change (or affect) the way the users navigate a website.

**Comment by carmacleod** [comment]
Thanks, @koalie - easy fix! :)
