### ISSUE TITLE
Use native button

### ISSUE THREAD

**Issue by toplizard** [w3c/aria-practices#2198]
Isn't it cleaner approach to just use the button element instead of the link element? I tried this my self and It works just as good, and I don't need to add tabindex or role.

**Comment by JAWS-test** [comment]
Do you mean example https://w3c.github.io/aria-practices/examples/button/button.html?

It is always better to use HTML than ARIA. This is also explicitly requested. But: If it doesn't work, ARIA can be used - and that's what the examples are for.

See: https://w3c.github.io/aria-practices/#no_aria_better_bad_aria, https://www.w3.org/TR/using-aria/#rule1

**Comment by mcking65** [comment]
Please provide more specifics. Closing. Feel to re-open if you have additional questions.
