### ISSUE TITLE
Use `role=button` for buttons on button/button_idl examples

### ISSUE THREAD

**Issue by straker** [w3c/aria-practices#2199]
The page https://www.w3.org/TR/wai-aria-practices-1.2/examples/button/button_idl.html uses a `div` and an `a` element as buttons, but both omit the use of `role=button` making them incomplete examples and missing the button styles.

**Comment by JAWS-test** [comment]
> The JavaScript for the example buttons on this page uses the IDL Interface defined in ARIA 1.2. The purpose of these examples is to illustrate how to use ARIA Attribute Reflection and provide a test case for browser and assistive technology interoperability. Specifically, the role and ariaPressed attributes are accessed using dot notation instead of setAttribute() and getAttribute()

ARIA role and attribute are available, if the browser supports it.

**Comment by straker** [comment]
Gotcha. Thanks for the clarification.
