### ISSUE TITLE
Definition of Internationalizable

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#22]
_From @MichielBijl on January 26, 2016 10:16_

What is the definition of internationalizable as used in [APG: A.1.2 Requirements](http://w3c.github.io/aria/practices/aria-practices.html#requirements)?

_Copied from original issue: w3c/aria#226_

**Comment by MichielBijl** [comment]
“anything that seems like crap, drop it”

**Comment by jnurthen** [comment]
I vote to drop all of A.1.2.
The requirements for ARIA are ancient history now.

**Comment by michael-n-cooper** [comment]
+1 to dropping from APG. However, the content is useful explanatory 
content we might want in educational materials (likely non WG-developed 
resources). Therefore, I suggest a ping to the WG saying "we're removing 
this, harvest it from back versions if you care" just so the removal 
doesn't go unnoticed.

**Comment by MichielBijl** [comment]
Noted. Will get this done this week.

**Comment by mcking65** [comment]
Completed with commit eabf6ca5a102af42f876ff4856e92c85b735cecd
