### ISSUE TITLE
Is the menu design pattern suitable when informations are mixed with action?

### ISSUE THREAD

**Issue by mlegait** [w3c/aria-practices#2201]
Hello,

I'm struggling with a widget that seems quite common to me. By the way, we can find it here on github.

When a user is connected, usually we can see his avatar and sometimes his name next to it. When we click on it, it opens a div that mixes information with actions. Information could be the user name, his number of points, his badges, ... And the actions could be to edit his profile, to logout, ...
So I was wondering what is the best design pattern to implement in this case. Should it be a menu? Or I see that it's a combobox here in github. 

Thank you very much for your help 🙏

**Comment by JAWS-test** [comment]
A combobox should allow the input of text and alternatively the selection of an element. A combobox is a form element, i.e. it is used to enter a value, which is submitted together with the form. So wouldn't be so appropriate for your element (and I haven't found on github that it is marked as a combobox).

I think a button (with aria-expanded or aria-haspopup) would be better:

- https://www.w3.org/TR/wai-aria-practices-1.2/#menubutton (if you only use menu items)
- https://www.w3.org/TR/wai-aria-practices-1.2/#disclosure
- https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal (if the dialog opened by the icon should be modal)

**Comment by mlegait** [comment]
Thank you very much for your quick answer 😄 

It's strange indeed for the github implementation. Because it has the role button but the Chrome Accessibility devtools says that it has the role combobox 😲 
![Image_0117_1427_54](https://user-images.githubusercontent.com/19664438/149777953-1f28deb3-9db9-4384-b090-4cd8b1c13d95.png)
But that's not the point here.

So, if I understand correctly, since the open section is not a modal and since the section contains information in addition to the menu items, I should use the **disclosure pattern**, right?

**Comment by JAWS-test** [comment]
> So, if I understand correctly, since the open section is not a modal and since the section contains information in addition to the menu items, I should use the disclosure pattern, right?

Yes, that's how I would look at it. But you can still wait for answers from others. By the way, HTML is sufficient for this: details and summary (as on GitHub, only without ARIA roles and ARIA attributes).

The role combobox seems to be a Chrome bug due to summary in conjunction with role=button and aria-haspopup. However, it has no effect on screen reader output (tested with JAWS and NVDA), since the button is correctly output as a menu button

**Comment by carmacleod** [comment]
In case it's helpful, here's the Carbon Design System's guidance for Profile menus: https://v11.carbondesignsystem.com/patterns/disclosures-pattern/#profile-menu

**Comment by mlegait** [comment]
@JAWS-test @carmacleod Thank you very much for your answers. They helped me a lot 😄
