### ISSUE TITLE
Link going to 1.1 version

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#2202]
From Twitter

https://twitter.com/stevefaulkner/status/1483380604133687299?s=21

**Comment by ZoeBijl** [comment]
How can we fix this?

**Comment by jnurthen** [comment]
@michael-n-cooper The specifics - https://www.w3.org/TR/wai-aria-practices/ needs to link to the same doc as https://www.w3.org/TR/wai-aria-practices-1.2/

**Comment by ZoeBijl** [comment]
I was wondering if that was something in the repo or if it’s a task for Michael; seems to be the latter ✨.

**Comment by a11ydoer** [comment]
Michale is working on this issue.

**Comment by michael-n-cooper** [comment]
Webmaster has updated the reference.

**Comment by a11ydoer** [comment]
I was about to mention you, @stevefaulkner. It seems that you are already in the know about this. - hint from your hooray emoji
