### ISSUE TITLE
Review editorial changes to spinbutton design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#222]
The [spinbutton design pattern](http://w3c.github.io/aria-practices/#spinbutton) 
needed several significant changes to be consistent with APG editorial guidelines.

Please review the pattern to check for typos, misspellings, etc.

The changes are listed in the below linked commit statement.

**Comment by jnurthen** [comment]
I made some comments in the commit. I have no idea how that well that works with a screen reader though  - let me know if it is a problem and I'll make them in another way.

**Comment by mcking65** [comment]
I found 3 of 4 comments for which I received notifications and made changes in commit 3cb1a81.

I did not find this one in the commit:
>A spinbutton can't have anything other than numbers in it IMO. 
>Even AM and PM are not allowed in a normal spinbutton.

Did you remove it?

The language mentioning AM and PM were part of the original text. I would assume that this is something that could only be done in a custom spinbutton as opposed to a native range input.

**Comment by jnurthen** [comment]
Yes. I removed it as I noticed that.

**Comment by mcking65** [comment]
@jnurthen, thanks for the help!
