### ISSUE TITLE
Disclosure pattern seems to be missing link to hybrid example

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#2220]
https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure

I notice that the hybrid example doesn't seem to be included in the disclosure section (or menu section) or any of the examples.
https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation-hybrid.html 

SEE ALSO for some thoughts on a couple of other examples:
https://github.com/w3c/aria-practices/issues/2152

**Comment by a11ydoer** [comment]
Hi @DavidMacDonald 

APG Working group published [version 1.2] disclosure pattern (https://www.w3.org/TR/wai-aria-practices-1.2/#disclosure) and here is [APG 1.2 hybrid example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/disclosure/disclosure-navigation-hybrid.html)

**Comment by a11ydoer** [comment]
APG discssed the issue 2152 and it was assigned to @mcking65

**Comment by a11ydoer** [comment]
The issue was closed with sharing new APG 1.2 Publication link.
