### ISSUE TITLE
Review File Directory Treeview Example Using Declared Properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#224]
This issue is for collecting feedback on and tracking editorial revisions to the 
[File Directory Treeview Example Using Declared Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html).

As of Feb 13, all editorial cleanup is complete.

#### Required updates

- [x] Issue #367: File Directory Tree View examples: modifier keys are not correctly handled 
- [x] Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by RichMorin** [comment]
- "arial-level" -> "aria-level"
- "aria-posinset and" -> "aria-posinset, and"
- "browser compuuted" -> "browser-computed"

**Comment by mcking65** [comment]
@RichMorin, thank you for the feedback.

The issues you reported, and more, are fixed in the latest editor's drafts of the four treeview examples at:

1. http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html
2. http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html
3. http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html
4. http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html

**Comment by annabbott** [comment]
In the Keyboard Support section, currently the following is listed:
Home Moves focus to first node.
End Moves focus to the last node that can be focused without expanding any nodes that are closed.

Question: does Home expand any nodes that are closed?

**Comment by MichielBijl** [comment]
@annabbott it does not, it only sets focus.

**Comment by annabbott** [comment]
@MichielBijl so I think it should state "without expanding any nodes that are closed." in all examples.

**Comment by MichielBijl** [comment]
Agreed, both <kbd>End</kbd> and the arrow keys list that too.

**Comment by mcking65** [comment]
Two more issues that need to be resolved before we can complete this review:

1. Issue #367: File Directory Tree View examples: modifier keys are not correctly handled 
2. Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by mcking65** [comment]
This issue is now dependent on issues #365 and #385.

**Comment by mcking65** [comment]
All feedback has been addressed except for the need to disable the default focus ring and implement custom focus in css, which is being tracked by issue #404. Closing this issue.
