### ISSUE TITLE
Review updates made to link example page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#228]
The [Link Examples page](http://w3c.github.io/aria-practices/examples/link/link.html) 
needs the following updates.

- [x] Restructure content to use the current [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html)
- [x] Change the page title to "Link Examples".
- [x] Update title tag.
- [x] Fix misspellings.

#### Requested Reviews

- [x] Review by @jongund 
- [x] Review by @annabbott 
- [x] Review by @shirsha

**Comment by mcking65** [comment]
The pattern says that shift+f10 opens the link context menu. Our examples do not have a context menu to open the link in a new tab, etc. Should we include this feature?

**Comment by MichielBijl** [comment]
Might be worth it to at least implement a keyboard shortcut for “open in new window”. On macOS this would be <kbd>cmd+enter</kbd>. Regardless of whether we implement the context menu.

**Comment by mcking65** [comment]
@michiel, I created issue #275 to address the adding of context menu with keyboard shortcuts. I don't think we should do one without the other. I assigned this to the release 2 milestone.

**Comment by mcking65** [comment]
@annabbott, @jongund, 

Question: does link #4 disappear in high contrast mode?

**Comment by jongund** [comment]
Matt,

The link 4 example will disappear it uses a CSS background image technique.

This is a common practice of social media links.

Jon

**Comment by jongund** [comment]
For the context menu to open link in a new window or new tab.  Is there any other markup that needs to be added to the link like: aria-haspopup, aria-expanded and/or aria-controls.

I am assuming the context menu follows the ARIA menu pattern.

Jon

**Comment by shirsha** [comment]
Example#3 doesn't have focus.

Thanks,
Siri

**Comment by shirsha** [comment]
If a link takes to another webpage(outside the current website) , should they be informed through the screen reader text.

Thanks
Siri

**Comment by mcking65** [comment]
@jongund wrote:
> For the context menu to open link in a new window or new tab.  Is there any other markup that needs to be added to the link like: aria-haspopup, aria-expanded and/or aria-controls.

No. 

As with menubutton, aria-controls and aria-expanded are not necessary.

While it would not be incorrect to add aria-haspopup, all links already have context menus so there is no value in doing so. 



> I am assuming the context menu follows the ARIA menu pattern.

Yes.

**Comment by mcking65** [comment]
@jongund wrote:

> The link 4 example will disappear it uses a CSS background image technique.

OK, that's what I thought. I wonder if we should flag that example as not recommended and put a note for the reason? Thoughts?

**Comment by mcking65** [comment]
@shirsha wrote:

> Example#3 doesn't have focus.

You mean, the focus ring disappears when link 3 gets focus? What browser? Others seeing this?

**Comment by mcking65** [comment]
@shirsha wrote:

> If a link takes to another webpage(outside the current website) , should they be informed through the screen reader text.

Some sites have such a policy, but that is not needed for accessibility. Some sites use an icon to indicate that, and if they do, they should make sure that icon is accessible. One thing I did at IBM was to make it more screen reader friendly by having the accessible text that represented that icon appended to the end of the link text even though the icon preceeded the link. But, again, that is not core to this pattern.

Now, you might be thinking of a WCAG technique that suggests that links should indicate whether they open a new window. While that is not an essential aspect of this pattern, we could have a note that references it from the design pattern. We reference WCAG in a few other places.

**Comment by shirsha** [comment]
@mcking65 wrote:
You mean, the focus ring disappears when link 3 gets focus? What browser? Others seeing this?
When I tabbed to Example #3, I can't see focus around it. This is in Internet Explorer 11.

![linkfocus](https://cloud.githubusercontent.com/assets/7432373/22790496/03bc1e8a-eeac-11e6-9106-fb5ad3b2303a.png)

**Comment by annabbott** [comment]
When using only the keyboard, the link for Example 3 gets an odd and unexpected indication of focus:
![issue 228_example 3 odd unexpected focus indicator](https://cloud.githubusercontent.com/assets/18404249/23175440/ffc0ea7c-f824-11e6-8701-957b1e4f4394.jpg)

**Comment by MichielBijl** [comment]
@annabbott I’ll fix that a bit later today.

**Comment by annabbott** [comment]
Confirmed fixed

**Comment by mcking65** [comment]
All reviewer feedback has been addressed. Closing to complete the review process.
