### ISSUE TITLE
Draft homepage copy for APG redesign

### ISSUE THREAD

**Issue by s3ththompson** [w3c/aria-practices#2282]
This issue is a placeholder for homepage copy edits ahead of the launch of the new APG homepage: https://wai-aria-practices2.netlify.app/

@mcking65 is planning to provide edits, as a pull request to [index.html](https://github.com/w3c/aria-practices/blob/main/index.html) or as a comment below.

**Comment by shawna-slh** [comment]
See [Navigation first page #34](https://github.com/w3c/wai-aria-practices/issues/34)
