### ISSUE TITLE
Draft about page copy for APG redesign

### ISSUE THREAD

**Issue by s3ththompson** [w3c/aria-practices#2283]
This issue is a placeholder for about page copy edits ahead of the launch of the new APG homepage: https://wai-aria-practices2.netlify.app/about/

@mcking65 is planning to provide edits as a comment below, in order to determine the most appropriate means to integrate them into the source (either via a new file in this repo or as a transform).

**Comment by shawna-slh** [comment]
See  [About page content #33](https://github.com/w3c/wai-aria-practices/issues/33)

**Comment by mcking65** [comment]
The new [about page](https://www.w3.org/WAI/ARIA/apg/about/) has been shipped.
