### ISSUE TITLE
Two state checkbox example size seems incorrect / not accessible on mobile

### ISSUE THREAD

**Issue by aplotno** [w3c/aria-practices#2287]
The checkboxes on mobile breakpoints seem to shrink to less than 44px in height which makes it confusing to have as an example because the target itself isn't compliant with 2.5.5: Target Size (Chrome browser on desktop and mobile)

Link:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-1/checkbox-1.html

On mobile:
![Mobile](https://user-images.githubusercontent.com/64718638/162967451-e3afa3a9-ad73-44c1-b043-3013b970b3c2.png)

On desktop:
![Desktop](https://user-images.githubusercontent.com/64718638/162967483-271b9716-e4a5-463b-bfe5-59bf8e1a3f0a.png)

**Comment by a11ydoer** [comment]
please check the latest example : https://www.w3.org/TR/wai-aria-practices-1.2/examples/checkbox/checkbox.html

**Comment by aplotno** [comment]
Understood, outdated link. And also the point about this not being a responsive library.
