### ISSUE TITLE
Review updates to horizontal slider example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#229]
The following updates have been made to the 
[horizontal slider example page](http://w3c.github.io/aria-practices/examples/slider/slider-1.html): 

- [x] Change page title to "Horizontal Slider Example".
- [x] Fix page title tag.
- [x] Revise to use current [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html)
- [x] Write an introductory description.

#### Reviews Requested as of March 11, 2017

- [x] Review by @annabbott  
- [x] Review by @jongund 
- [x] Review by @shirsha

**Comment by jongund** [comment]
These should be fixed now with the latest pull request, including JSCS issues

**Comment by MichielBijl** [comment]
Thanks Jon! This issue is fixed in: https://github.com/w3c/aria-practices/commit/3b8c118a03730b2f3f89205f8f121db76c8b4dac

**Comment by mcking65** [comment]
@jongund, did you have a reason for adding tabindex in the JavaScript rather than putting it into the HTML?

**Comment by jongund** [comment]
I updated the source code to include tabindex in the html code and also improved visual focus styling by including style to the rail

**Comment by annabbott** [comment]
Looks good.

**Comment by shirsha** [comment]
Working fine with keyboard, JAWS 18 in IE11 and NVDA screen reader in Firefox.

Can you add aria-valuetext=“STRING” so that screen reader can know what slider they are on while changing the values? 
Ex: aria-valuetext="RED RGB value".

**Comment by mcking65** [comment]
Thank you @shirsha.

> Can you add aria-valuetext=“STRING” so that screen reader can know what slider they are on while changing the values?
> Ex: aria-valuetext="RED RGB value".

That would be redundant with the slider label. The valuetext property is for making the value itself meaningful. In this case, the number 0 to 255 is meaningful.

Screen reader users can hear the label of the focused item at any time with their screen reader command for reading the current element.

**Comment by mcking65** [comment]
Team, we have completed updates and the review process for this example. It is now ready for the next heartbeat publication. Thank you!

**Comment by ctomczyk** [comment]
It doesn't work with Talkback/Android 6.0.1. Basically, I can tap on slider, but using up/down volume to change the slider has no effect. Same reported by someone else on iOS.

**Comment by mathalete** [comment]
@ctomczyk 
Same on VoiceOver iOS 10.3.2 (14F89). 
The role of slider and corresponding attributes seem to be exposed correctly to the Accessibility tree. Whilst the instruction is to swipe up and down to move the slider is announced, VO doesn't facilitate this.
Looks like a iOS VO bug.
