### ISSUE TITLE
Collapsible Dropdown - blink when clicking twice

### ISSUE THREAD

**Issue by Mikilll94** [w3c/aria-practices#2292]
Go to this website: https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html

Click on the dropdown and then click again. The dropdown should close, not blink.

![dropdown_bug](https://user-images.githubusercontent.com/17653648/163624358-3cc91254-9b76-4b71-aa06-c5d67525ec67.gif)

**Comment by charmarkk** [comment]
See comment in #2293.
