### ISSUE TITLE
Listbox - unexpected behavior when hitting spacebar

### ISSUE THREAD

**Issue by Mikilll94** [w3c/aria-practices#2293]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html

1. Focus the listbox.
2. Hit spacebar -> the listbox is opened
3. Hit spacebar again -> nothing happens

What the spacebar is supposed to do? It is not documented.

**Comment by mcking65** [comment]
This is a problem in the 1.1 APG. In the 1.2 APG, we deprecated this example and replaced with with the select-only combobox pattern:
https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html
