### ISSUE TITLE
Non-Modal Dialog needs to specify how move should work

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#23]
_From @jnurthen on February 2, 2016 21:34_

The non-modal dialog http://w3c.github.io/aria/practices/aria-practices.html#dialog_nonmodal defers to the drag and drop section for how to move the dialog. I'm not sure moving a window is the same as drag and drop so we should really specify something different here.

_Copied from original issue: w3c/aria#241_

**Comment by MichielBijl** [comment]
Also, touch support.

**Comment by jnurthen** [comment]
Pretty much every pattern needs to be reviewed for that.

**Comment by MichielBijl** [comment]
Agreed. Related: https://github.com/w3c/aria-practices/issues/8

**Comment by mcking65** [comment]
Captured this issue in a comment in issue #59, which is for drafting this design pattern. Closing this issue.
