### ISSUE TITLE
Review updates to vertical slider example page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#230]
The following changes have been made to the 
[vertical slider example page](http://w3c.github.io/aria-practices/examples/slider/slider-2.html):

- [x] Change page title to "Slider Examples with aria-orientation and aria-valuetext"
- [x] Make page title tag and H1 consistent.
- [x] Revise to use current [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html)
- [x] Write an introductory description.

#### Reviews Request as of March 11, 2017

- [x] Review by @annabbott 
- [x] Review by @jongund 
- [x] Review by @shirsha

**Comment by jongund** [comment]
These issues should be fixed now, including JSCS errors, in the latest pull request

**Comment by MichielBijl** [comment]
Thanks Jon! This issue is fixed in: https://github.com/w3c/aria-practices/commit/3b8c118a03730b2f3f89205f8f121db76c8b4dac

**Comment by annabbott** [comment]
Looks good.

**Comment by shirsha** [comment]
It is working fine with keyboard only and with NVDA screen reader in Firefox.
With JAWS 18,17, in IE11  for the two horizontal sliders, it is not reading all the values when using up and down arrow.
It is working fine with right and left arrow.

Thanks,
Siri

**Comment by mcking65** [comment]
Thank you @shirsha, yes, there are some JAWS bugs to report.

**Comment by mcking65** [comment]
All required reviews are complete and issues addressed. Thank you Team!

**Comment by a11ydoer** [comment]
![Thermostat with focus on vertical bar- adjustable doesnot work with swipe up or down](https://user-images.githubusercontent.com/14183123/104240921-74323200-5422-11eb-9676-5aba1447a69e.PNG)

In iOS mobile device, thermostat vertical bar, temperature adjustment does not work with gesture. Touch has a little big of lag but adjustment works.
