### ISSUE TITLE
Spec versions in related W3C specs

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria-practices#232]
As I prepared for 2016-12-14 publication, I came across some links to W3C specs that don't seem to quite meet future-proofing. They are in a section of the examples called "Related W3C Specs".

http://www.w3.org/TR/WCAG/ refers to a versionless version of WCAG, which currently loads WCAG 2.0 but may not in the future. The link text says WCAG 2.0, however. Either the link should go expressly to WCAG 2.0, or the link text should not include a version indicator.

Same for http://www.w3.org/TR/wai-aria, https://www.w3.org/TR/wai-aria-practices/, and to some extent for http://www.w3.org/TR/html5 which is semi-versionless, and some of the others.

I can fix them if you want but don't know if you want versionless URIs with link text to match, or versioned URIs with link text to match.

**Comment by mcking65** [comment]
They are just example links; it doesn't matter much where they point. But, I can make them more useful by future proofing.

**Comment by mcking65** [comment]
Fixed with dd0245f. Simple, relatively inconsequential editorial change so closing without further review.
