### ISSUE TITLE
"View the mailing list archive" link is not visually distinguishable from the text block in APG hompage

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#2327]
"Mailing Lists
The APG Task Force uses the public-aria-practices@w3.org mailing list ([view the mailing list archive](https://lists.w3.org/Archives/Public/public-aria-practices/)) for email discussion. Meeting announcements, agendas, and links to minutes are sent to the mailing list. While GitHub issues are the preferred place to discuss APG content, the mailing list is available to anyone who would prefer to communicate with the APG Task Force via email."

<img width="873" alt="indistinguishable mailing list link" src="https://user-images.githubusercontent.com/14183123/168968230-0a38361b-7935-450b-93ff-59146713609d.png">

**Comment by a11ydoer** [comment]
The solution may be moving the link at the end of the paragraph with some spacing. (Visual mock-up attached below.)
![distinguishable mailing list link design](https://user-images.githubusercontent.com/14183123/168967737-37f7dfc3-4dbe-4df0-82d8-7b742762acd6.png)

**Comment by shirsha** [comment]
This issue is raised as a part of https://github.com/w3c/aria-practices/pull/2323

**Comment by mcking65** [comment]
May be partially addressed by #2379
