### ISSUE TITLE
Custom Checkboxes Incorrectly Work with Enter Key on Checkbox Example (Two State) & (Mixed State)

### ISSUE THREAD

**Issue by pauljadam** [w3c/aria-practices#233]
Native checkboxes only work with the spacebar key not the enter key. The custom control should mimic native behavior there right?

http://w3c.github.io/aria-practices/examples/checkbox/checkbox-1/checkbox-1.html

The authoring practices say spacebar key:
http://w3c.github.io/aria-practices/#checkbox
Keyboard Interaction

When the checkbox has focus, pressing the Space key changes the state of the checkbox.

On the Checkbox Example (Mixed State) demo the native checkboxes only work with the spacebar key but the custom work with enter key also, http://w3c.github.io/aria-practices/examples/checkbox/checkbox-2/checkbox-2.html

This seems confusing and incorrect.

Can we please have it only work with the spacebar key?

The authoring practices are my go to source for instructing clients on how to built an accessible ARIA widget. Thanks!

**Comment by mcking65** [comment]
@pauljadam pauljadam 

You are right; there is inconsistency here.

When feasible, some patterns use a super set of behaviors from native platforms. But, in this case, I observe that, at least on Mac and Windows, enter does not activate a checkbox.

I have added this question to the task force agenda.

**Comment by mcking65** [comment]
Per discussion in Jan 23 teleconference, @jongund will remove the enter key behavior.

**Comment by mcking65** [comment]
@pauljadam, 

Again, thank you for the feedback. This is now fixed.
