### ISSUE TITLE
Make note about new location of WAI-ARIA patterns more prominent in Shortened TR Docs

### ISSUE THREAD

**Issue by hlee-cb** [w3c/aria-practices#2332]
This is a very small issue, but it seems as of this morning that the old WAI-ARIA Patterns document was emptied of content [old document](https://www.w3.org/TR/wai-aria-practices-1.1/), except for the abstract which points to the more [up-to-date version](https://www.w3.org/WAI/ARIA/apg/patterns/).

I had the old version bookmarked and nearly had a heart attack this morning when it appeared to be completely empty. As the old document is still the first result returning from a search for "WAI ARIA authoring practices",  I think the note pointing to the new resources should be bolded or made more prominent in some way.

**Comment by joe-watkins** [comment]
Is there a plan for URL redirects for `1.2` examples that have been around for a while? 
https://www.w3.org/TR/wai-aria-practices-1.2/examples/dialog-modal/dialog.html

How does one access the old `1.0` and `1.1` references? 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

**Comment by mcking65** [comment]
@mbgower mentioned that we could also change the 1.2 and 1.1 docs at the top where they point to latest. Currently, "Latest" and "Latest Editor's Draft" both point to out-of-date locations, putting people into a loop if they don't read further down in the doc.

**Comment by thibaudcolas** [comment]
Came here to report the same thing – this is particularly confusing because (as far as I can tell), the document’s title is the same as before, and it’s still the #1 search result for "aria authoring practices" (presumably because no redirects or canonical rel links have been set up, see #2335).

**Comment by mcking65** [comment]
This issue was addressed by the fixes to #2335:
* The shortened TR docs now redirect to the new APG site
* The dated versions have a modal dialog popup telling the user the doc is out of date and referencing the new APG site
