### ISSUE TITLE
would like to have an "editors draft" version of APG glossy microsite available

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#2347]
https://www.w3.org/WAI/ARIA/apg/patterns/

I often use the feature "latest editors draft" when looking up things. Would like a link to "latest editor's version" of this glossy pattern depot, in addition to the latest stable draft. Otherwise I'd probably just keep using the previous layout.
https://w3c.github.io/aria-practices/

**Comment by mcking65** [comment]
@DavidMacDonald 

The editor's draft on github pages is just a build of the main branch. The new site will be updated very soon after each merge to main.

We will soon be sunsetting the github pages build; it will just point to the new site.

So, the production version is always going to be the latest. We are done with long publication processes that make an editor's draft necessary. This should make life simpler for everyone and reduce confusion.
