### ISSUE TITLE
Home Page has more than two lines of centered text

### ISSUE THREAD

**Issue by shirsha** [w3c/aria-practices#2351]
There are more than two lines of centered text. Ex: content under the "Get Involved", "Join the Task Force", and
"Contribute via Github".
Centered text, decreases readability and affects users with tunnel vision. There are a lot of usability studies on avoiding centered text.

**Comment by mcking65** [comment]
@shirsha it looks like a PR that may have fixed this has been merged ... As this is a visual change, could you please verify for me?

**Comment by shirsha** [comment]
This is fixed
