### ISSUE TITLE
Guidance on usage of Authoring Practices Guide vs. editor’s drafts

### ISSUE THREAD

**Issue by thibaudcolas** [w3c/aria-practices#2356]
Separately to – #2332 I’d like to request a few changes on the [APG About page](https://www.w3.org/WAI/ARIA/apg/about/) based on my first-time experience:

- The Introduction section is very long. All of it seems like valuable information but I had a hard time feeling motivated to read it all. Could it be structured into further sub-sections with their own headings, to make it easier to scan the contents?
- In the past I’ve always sent people towards the [1.3 editor’s draft](https://w3c.github.io/aria/). Could there be a section on the About page (perhaps under Change History?) or elsewhere to clearly state how this document differs from 1.3? Perhaps link to the 1.3 editor’s draft with the appropriate caveats.

**Comment by mcking65** [comment]
Related pull requests:

* The editor's draft on github.io has been sunset by #2419 and #2639.
* The introduction is being rewritten by #2558.

**Comment by mcking65** [comment]
All feedback addressed by above referenced issues.
