### ISSUE TITLE
Focus / hover color for Sortable table header buttons has insufficient contrast

### ISSUE THREAD

**Issue by gradyat** [w3c/aria-practices#2359]
In the [Sortable Table Example](https://www.w3.org/WAI/ARIA/apg/example-index/table/sortable-table.html) on the new WAI APG site, the focus / hover text color has low contrast with the focus / hover background color (1.1:1) and fails 1.4.3 Contrast (Minimum).

<img width="733" alt="Screenshot showing the Sortable Table Example with the Last Name column header button focused with white text and light blue background" src="https://user-images.githubusercontent.com/35243100/170573622-63cc1ed2-bb89-401c-a5cf-21165fea8908.png">

**Comment by mcking65** [comment]
Related to w3c/wai-aria-practices#105. Will be closed by the fix to that issue.
