### ISSUE TITLE
please add a link to github open issues and file an issue in ARIA practices doc 

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria-practices#236]
it would be useful to provide links to
https://github.com/w3c/aria-practices/issues/
and
https://github.com/w3c/aria-practices/issues/new

in a prominent position in the spec.

**Comment by mcking65** [comment]
@stevefaulkner 

We currently have a link to the issues in the "Status of this document" section where we solicit feedback, which seems to be the conventional place. Do you have another suggestion?

I was wondering if we might do something like add another section titled "Providing feedback on this document".

**Comment by mcking65** [comment]
@stevefaulkner, these are now on all example pages with the completion of issue #536.

Closing as done. Feel free to reopen if this does not resolve the issue.
