### ISSUE TITLE
update note on modal dialog to reflect best practice

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria-practices#237]
> When a dialog opens, focus is typically set on the first focusable element. 
http://w3c.github.io/aria-practices/#dialog_modal

While this may be typical it is not good for a range of users including screen reader and magnifier users, when a dialog contains large amounts of content and the first focusable element is at the bottom of the dialog. Suggest providing more specific advice around where focus should be. Suggest focus be set on the dialog itself <div role=dialog tabindex=-1> or on the dialog title (heading).

**Comment by mcking65** [comment]
@stevefaulkner 

Thank you for this feedback; good scenario to address. I updated the checklist of changes for the pattern in issue #42 to make sure that is included.

Focusing on the heading or first paragraph works well. But, focusing on the dialog itself can be confusing for both screen readers and screen reader users.

**Comment by mcking65** [comment]
Closing per update to issue 42. Please re-open if this is not adequate.
