### ISSUE TITLE
Icons for Tree View and Treegrid are swapped on the WAI APG site

### ISSUE THREAD

**Issue by matatk** [w3c/aria-practices#2381]
The icons used to represent Tree View controls and Treegrid controls appear to be the opposite way around, on the following pages:

* https://www.w3.org/WAI/ARIA/apg/patterns/
* https://www.w3.org/WAI/ARIA/apg/patterns/treeview/
* https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/

BTW really liking the new WAI site, especially the "no ARIA is better than bad ARIA" section; keep up the good work :-).

**Comment by mcking65** [comment]
We saw this repro briefly, but can no longer reproduce. we will watch to see if this happens again over the next day or so.

**Comment by mcking65** [comment]
@a11ydoer please verify if this can be closed. Thx!

**Comment by a11ydoer** [comment]
@mcking65 I checked all the mentioned examples. Folder icons and arrow icons present the chosen status correctly. If file directory is open, the folder has the open folder icon.

**Comment by a11ydoer** [comment]
done.

**Comment by mcking65** [comment]
@a11ydoer 

I don't understand your comment ... the icons that this issue is about are the images that represent the treeview and treegrid patterns in the cards on the [patterns page](https://www.w3.org/WAI/ARIA/apg/patterns/).

This issue is not about the icons used in the file directory tree example.

Re-opening just to be sure you have validated the correct content.

**Comment by a11ydoer** [comment]
Thanks for the opportunity to check those card images on the [pattern page](https://www.w3.org/WAI/ARIA/apg/patterns/), @mcking65 
In the screen shot, the Tree view pattern shows the image of folder icon with a hierachy. On the right of Treeview pattern, the treegrid pattern shows the image of hierarchical structure of email conversations we showed in the APG treegrid example. 
![treeview and treegrid pattern card images](https://github.com/w3c/aria-practices/assets/14183123/99ab90af-e49a-4579-8ce7-c4a41361194a)

@matatk  Can you confirm whether these are the same images you refered to in the issue?

**Comment by matatk** [comment]
Just checked the three links in my original post, and the images are the correct way around now; thanks.
