### ISSUE TITLE
Include skipto.js to the examples/js folder for wai-aria-practices compatibility

### ISSUE THREAD

**Issue by evmiguel** [w3c/aria-practices#2387]
Currently, the wai-aria-practices script, which formats the examples for APG, depends on the files in the `examples/js` folder. The script copies over the *.js files in that folder to make the Jekyll site.

What's currently missing is the `skipto.js` file, which is being referenced [in this portion of the code ](https://github.com/w3c/wai-aria-practices/blob/f575cd9f80d5e5950091964731094426b7f95ebb/scripts/pre-build/library/loadExamples/loadExamples.js#L79), which was previously `jumpto.js`. As a result, the build script fails. 

`skipto.js` was added to a location in the wai-aria-practices repo which can be overwritten [(in this PR)](https://github.com/w3c/wai-aria-practices/pull/131). Would it be possible to copy over `skipto.js` to this repo's `examples/js` folder to fix the build script? 

cc: @jongund

**Comment by richnoah** [comment]
@evmiguel clearance given by Task Force to move skipto.js to this repo.

**Comment by evmiguel** [comment]
@richnoah thank you. The build is failing on copying the file over. Is this something that @jongund or @howard-e can help me with?
