### ISSUE TITLE
Possible error in 3.1 HTML5 Sectioning Elements

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#239]
The table lists the following as default landmark role for `section`:

> `region` when it has an accessible name using `aria-labelledby` or `aria-label`

As @stevefaulkner said in a thread opened by @matatk [1]:

> section always maps to region, it is only announced by AT when it has an accessible name.

Should we change this to reflect the ARIA spec and ARIA in HTML document?

[1] https://github.com/w3c/html-aria/issues/64

**Comment by mcking65** [comment]
I think it is the core AAM that conflicts with the ARIA spec. Assistive tech should not have to do extra checking to see if  a region really is a landmark. The intent we had when making region a subclass of landmark and making name required was to make it so only named sections are regions.

I see @Joanmarie is a step ahead of me and raised w3c/aria#513, which is the path I support.

**Comment by MichielBijl** [comment]
Yes, I discussed this a bit with @Joanmarie during/after today’s APA call. 

Changed wording in my original post a bit.

**Comment by mcking65** [comment]
w3c/aria#513 was closed and that means the text in the guidance is correct as written; no conflict.
