### ISSUE TITLE
retire - put health warning on WAI-ARIA Primer 1.0

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#24]
_From @stevefaulkner on February 9, 2016 16:40_

The WAI-ARIA Primer https://www.w3.org/TR/wai-aria-primer/ document is stale/dead, not worked on for 6 years, includes incorrect outdated information. But there is no way to know this. yet it is still being referenced by current documents (refer to https://github.com/w3c/wcag/issues/158)

Strongly suggest putting a health warning on the document and pointing to documents that contain current information.

_Copied from original issue: w3c/aria#249_

**Comment by MichielBijl** [comment]
_From @richschwer on February 9, 2016 17:13_

I support this. It is old and I think ARIA is ubiquitous enough now that we don't need to do anything with it.

**Comment by MichielBijl** [comment]
_From @edouard-lopez on February 10, 2016 9:0_

Most of the web dev probably don't know what ARIA is but a character in a TV show or a song. Having a primer or similar resource to give an overview and some tips is a good thing.

Working in this for years might give you the impression that accessibility is widespread. But it's still not the case.

So providing an alternative would be better.

**Comment by MichielBijl** [comment]
_From @richschwer on February 10, 2016 23:52_

If we need a Primer I think it should be taken on by EO at this point.

**Comment by MichielBijl** [comment]
_From @jasonkiss on February 11, 2016 0:1_

Whomever is responsible for producing it, I concur that a simple primer doc would be good. Most devs I talk to still haven't heard of ARIA, or if they have, they don't know what it is.

**Comment by MichielBijl** [comment]
_From @mcking65 on February 11, 2016 8:19_

Remember, We put the primer content into the APG … 

 

In the APG introduction, we have a link to a “background on WAI-ARIA” appendix, which has a bunch of the primer content … not yet updated.

 

So, I think you can retire the primer and point to the APG.

 

Looking it again, we may want to make a mod to the abstract of the APG to explicitly include this purpose if the group wants to continue in this direction.

 

Matt

**Comment by MichielBijl** [comment]
This was [discussed during the ARIA editors call](https://www.w3.org/2016/02/17-aria-editors-minutes.html#item02).

**RESOLUTION: publish ARIA primer and practices 1.0 as abandoned, strip content, redirect shortnames if possible**

**Comment by MichielBijl** [comment]
@michael-n-cooper is this something you need to do? Can we assign it to you?

**Comment by michael-n-cooper** [comment]
Yes, assign this to me, that had slipped off my plate.

**Comment by mcking65** [comment]
This is done.
