### ISSUE TITLE
Change HTML5 to HTML

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#240]
Section 3 is the only part of the APG to mention HTML5. Should we change this to HTML?

**Comment by mcking65** [comment]
As far as i know, it is the only section where what is said about html is also not true about html 4. The html elements discussed in section 3 were new in html 5.

**Comment by MichielBijl** [comment]
As far as I know you can still apply ARIA to HTML 4, so `<div role="banner">` would do the same in HTML4 as in HTML5? In any case, HTML5 has been in REC for 2 years now. I wonder if mentioning the version is really necessary.

Don’t care too much one way or the other, I just noticed it :).

**Comment by jongund** [comment]
I think it is important to mention HTML5 when it makes a difference.   There are new elements in HTML5 that generate ARIA landmarks, this was not true for HTML4.   Since we are a W3C working group I think we should try to highlight changes and there are big changes in from HTMl5 from HTML4.

**Comment by MichielBijl** [comment]
Fair enough 👍.
