### ISSUE TITLE
Pull Requests no longer have Netlify Preview Links

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2416]
The action that generates a PR comment with a Netlify preview link for the PR branch is no longer working. None of the current pull requests have a Netlify preview link.

**Comment by richnoah** [comment]
@mcking65 this is a product of the PR Preview Bot running.  It overrides the Deploy Preview.  We are not sure of the source but it does not run for all users.  We have identified that the PR Preview Bot tends to run on PRs that you and Jon Gunderson create.  Will have to investigate the source of the PR Preview Bot before determining a resolution.

**Comment by mcking65** [comment]
@richnoah 
this is still an issue.

**Comment by mcking65** [comment]
No longer issue
