### ISSUE TITLE
Reorganize patterns and examples to reflect site architecture

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2418]
This issue documents one portion of the [reorganize repository project](https://github.com/w3c/aria-practices/projects/42).

#### Objective
Build a content tree containing the home page, patterns, examples, and index. The practices and about sections of the site will be handled in subsequent steps.

#### Directory Structure
* "content" directory at root level: This will hold all content in a tree that matches the IA of the web site. It has subdirectories for:
    * patterns
    * index
    * shared (for js, css, scripts that need to be referenced by multiple resources. Did not name "common" because we have not yet eliminated aria-common)
* There will be a directory for each pattern that contains:
   * A file for the pattern, e.g., "accordion-pattern.html". Originally considered naming "index.html" but decided a more specific file name could avoid confusion with bulk file operations.
   * An examples directory for the examples.

#### Plan
1. Create subdirectories for patterns under /patterns directory. Note: name the pattern directory the same way it is named in w3c/aria-practices/examples/. For example, the modal dialog pattern directory should be named "dialog-modal", not "dialogmodal". If the new pattern directory name differs from the path name in the currently published wai/aria/apg, add a note about the need for pattern redirect in the redirect notes comment below.
2. For each pattern, create a pattern file from content in aria-practices.html, e.g., `/content/patterns/accordion/accordion-pattern.html`. Copy content from respec file into the new pattern file and edit as needed.
3. In each pattern subdirectory, create an examples directory and move the example files into that directory.
4. Move shared js and css into shared directory.
5. Edit example html files to fix references and minimize scripted content transformation (instructions in comment below).
6. Reconfigure regression tests to run test against examples in new location (regression-tests.sh)
7. Update create-gh-project.js to use new examples location.
8. Update reference-tables.js to use new pattern and example locations and create output in `/content/index/generated-content-index.html`
9. Update coverage-report.js to use new pattern and example locations and create output in /content/about/coverage-reports/
10. Update github actions to utilize new locations
11. Modify build process to:
    * pull pattern content from new pattern content files;
    * pull example content from new example locations;
    * pull index content from new index location;
    * Stop making content additions or modifications to patterns, examples, and index.
13. Configure redirect for pattern if the pattern URL will be different from the URL for that pattern when the WAI site was launched (e.g., for modal dialog because the directory name changed from dialogmodal to dialog-modal.
14. Configure redirect for  examples since they are no longer in the examples-index path.

**Comment by mcking65** [comment]
@richnoah @alflennik 
I started work in PR #2417.

I'd like to discuss this PR and how to divide up the work on it during Tuesday's meeting.

**Comment by mcking65** [comment]
## Editing example files

Following are instructions for plan step:

>5. Edit example html files to fix references and minimize scripted content transformation.

There are 29 pattern subdirectories in the `/content/patterns` directory.

As of July 26, when writing these instructions, work to revise the example files for the following two patterns in the '"move-examples" branch has already ben completed:
1. accordion
1. alert

Note that the following two pattern subdirectories do not contain subdirectories for examples:
1. alert-dialog (the example for this pattern is under dialog-modal because it uses the same js and css as other modal dialog examples)
1. window-splitter (this pattern does not yet have examples)

As of July 26, the following steps need to be performed for the examples contained in the other 25 patterns.

Here are the work items to complete for each `/content/patterns/PATTERN_NAME/examples/EXAMPLE_NAME.html` file within those 25 pattern subdirectories:

1. In the `head` element, edit href and src attributes for the `Core js and css shared by all examples`:  change path prefix from `../` to `../../../shared/`
1. Delete the following two list items from the `<ul>` in `<nav aria-label="Related Links" class="feedback">` (please leave the other list items in place):
   1. `<li><a href="../../#browser_and_AT_support">Browser and Assistive Technology Support</a></li>`
   1. `<li><a href="https://github.com/w3c/aria-practices/issues/new">Report Issue</a></li>`
1. Edit href of all links to the design pattern. The new href should be `../pattern-PatternName.html`. Note there may be two or more links to the design pattern.
1. In the list of similar examples, if any of the examples belong to a different pattern, edit href of those links. The current href is of form `../other-pattern-name/example-name.html`. The new form would usually be `../../pattern-name/examples/example-name.html`.
1. If there are links to any other patterns, revise the links to those patterns.
1. Delete the string " | WAI-ARIA Authoring Practices 1.2" from the title tag content.
1. On line after `<h1>` element, add a line with `<h2>About This Example</h2`
1. Delete the unnecessary `<nav>` element that follows the `</main>` tag.

Note: Since we are not yet migrating the practices and other content, do not edit the href of links to any practices-related content. Those will continue to be resolved by the site build script.

**Comment by mcking65** [comment]
## Notes for redirect planning

This comment should be edited as we make changes that will drive need for redirects.

* All examples are moving from `/wai/aria/apg/examples-index/EXAMPLE_NAME.html` to `/wai/aria/apg/patterns/PATTERN_NAME/examples/EXAMPLE_NAME.HTML`
* The pattern name in the path for the modal dialog pattern is changing from `/dialogmodal/` to `/dialog-modal/`
* The pattern name in the path for the menu button pattern is changing from `/menubutton/` to `/menu-button/`

**Comment by mcking65** [comment]
Based on discussion in today's meeting, I changed the plan to name the pattern files using the form `/content/patterns/PATTERN_NAME/PATTERN_NAME-pattern.html`, e.g., `/content/patterns/accordion/accordion-pattern.html`.

I have now created stub pattern files for all 30 patterns in the "move-examples" branch used for PR #2417.

I have started making notes about needs for redirects in a comment above.

**Comment by mcking65** [comment]
@a11ydoer, the "move-examples" branch is now ready for you to edit example files. 

`git Checkout move-examples` and follow the instructions in [this comment above](https://github.com/w3c/aria-practices/issues/2418#issuecomment-1196155827), and then commit with the "`-n` option. The `-n` option will skip all checking, which is necessary because this branch fails all checks. Then push the changes so they show up in #2417.

Make sure you pull just before you push, just in case we happen to be working at the same time. I will only be working on the pattern files. @alflennik  is focused on scripts and actions. You are the only person working on the example files, so we should easily be able to avoid conflicts.

**Comment by mcking65** [comment]
@alflennik 
I am thinking about the site build scripts and wondering whether increasing the scope of PR #2418 might actually simplify scripting and reduce risks associated with this restructuring.

Consider processing for the following two links in this file: [aria-practices/grid-pattern.html at move-examples](https://github.com/w3c/aria-practices/blob/350823ea5b2c6732052f862231c7ee8256edb69b/content/patterns/grid/grid-pattern.html)

On line 29, there is a same page link: `<a href="#kbd_general_within">manages focus movement inside it</a>`

On line 109, there is a link that looks like a same page link (`<a href="#kbd_common_conventions">Key Assignment Conventions for Common Functions</a>`), but that link is actually to practices content that PR #2418 is not yet moving out of aria-practices.html.

The current plan is to move the practices content in a separate PR. So, for PR #2418, the site build script will need to reliably distinguish between the above links to modify the href of the link on line 109 but not modify the href of the link on line 29.

Does this introduce unnecessary complexity? Typically, we reduce risk by keeping PRS scoped more narrowly, but since this PR is already enormous, would it be less risky to expand the scope of this PR and move practices content at the same time?

**Comment by mcking65** [comment]
@a11ydoer 

Note that I just revised the step related to the "about this example" section my [comment about editing example files](https://github.com/w3c/aria-practices/issues/2418#issuecomment-1196155827).

I also went ahead and did the work for the breadcrumb example because I saw need to change the name of the example file and wanted to reference it from the pattern.

I won't touch any other examples until we coordinate. Again, I recommend pushing after each time you complete the changes for one example file. That will help ensure we don't run into problems. I am pushing after each pattern is complete. Patterns are now half done.

**Comment by a11ydoer** [comment]
> 3\. Edit href of all links to the design pattern. The new href should be `../pattern-PatternName.html`. Note there may be two or more links to the design pattern.

@mcking65 update on documentation - The new href should be '../PatternName-pattern.html', not '../pattern-PatternName.html'.

**Comment by a11ydoer** [comment]
@mcking65 I finished the example file update till radio group pattern. Next pattern which will be updated is the slider pattern. I plan to work on the rest example file update tonight.

**Comment by alflennik** [comment]
Hi @mcking65, I looked at the two links you pointed out. If you look on the [published version of the page](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) you can find the link on line 29 by searching for "manages focus movement inside it" and you can find the link on line 109 by searching for "Key Assignment Conventions for Common Functions". In the current version of this page, neither of the links is a same page link - both link to other pages on the site. So I'm a little bit confused when you say one is a link to another page and another is a same page link. I think the confusion emphasizes the need for the links to actually work, so I would definitely advocate that we try to find a way to make sure as many as possible of the links remain functional. Does that help resolve anything?

**Comment by a11ydoer** [comment]
@mcking65 @alflennik I am working on the rest of examples files this morning. I will let you know two when all are completed.

**Comment by a11ydoer** [comment]
@alflennik @mcking65 I finished all the example file updates. Please feel free to work on the "move-examples" branch.

**Comment by mcking65** [comment]
Note: After reviewing #2450, I updated step 11 in the plan with more detail.

Previously, step 11 was:

>11. Modify build process to pull pattern content from new pattern file and example from new example location

Now, step 11 is:

>11. Modify build process to:
>    * pull pattern content from new pattern content files;
>    * pull example content from new example locations;
>    * pull index content from new index location;
>    * Stop making content additions or modifications to patterns, examples, and index.

**Comment by mcking65** [comment]
@alflennik 

I want to move treview-1a and treview-1b examples up a level so the directory structure is consistent with other patterns. However, several of your PRs include fixes to example pages, so I'm going to wait till we merge your PRs into move-examples.

Moving the treeview examples might re-break a few things, e.g., regression testing for them. So, we'll need to circle back on that. I figure that is easier than me moving them now and potentially creating need to rebase some of your work.

**Comment by mcking65** [comment]
Steps 1 through 5 are now complete except for above mentioned changes to two of the treeview examples.

**Comment by alflennik** [comment]
> I want to move treview-1a and treview-1b examples up a level 

After discussing this in the working group meeting we decided to tackle this last after the other PRs have been merged into the `move-examples` branch.

**Comment by mcking65** [comment]
@alflennik @s3ththompson 

The patterns, examples, and practices are now all moved out of aria-practices.html and all links across content, (e.g., patterns to practices and vice versa) should be in good shape now.

Next steps:
* Apply css to patterns and practices (also noted in #2424)
* Include card images for patterns and practices in the new content tree (also noted in #2424)
* Create content/patterns/patterns.html and content/practices/practices.html
* Make Netlify preview work for the move-examples branch

**Comment by mcking65** [comment]
@alflennik @s3ththompson 

Note that I have created #2487 and #2488 and assigned to @alflennik. Now that I am done with content edits and link updates, I think we are ready for those two tasks. Note that we will also need to track the need for redirects for those two changes as well.
