### ISSUE TITLE
Develop example of table design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#242]
Develop an example page to demonstrate the pattern described by the section coming from issue #90.

**Comment by mcking65** [comment]
The only thing left to do on this example is the CSS for the ARIA table in the ex1 div. Any takers?

**Comment by MichielBijl** [comment]
@mcking65 I’ll pick up this one. For what it’s worth, we don’t yet have an example for [Advanced Data Grid](http://w3c.github.io/aria-practices/examples/grid/advancedDataGrid.html).

**Comment by mcking65** [comment]
Thank you Michiel. Advanced data grid will be part of release 2. We can't get it done for the current milestone. I left in the stub just to help people be more aware of our plan to include it.

**Comment by jongund** [comment]
I will work on the styling of the table examples

**Comment by jongund** [comment]
@mcking65 

Added CSS styling to table

**Comment by mcking65** [comment]
Work on this example is now complete. Closing and starting review process.
