### ISSUE TITLE
Create new pages for practices content

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2424]
This issue is part of the [Restructure repository Project](https://github.com/w3c/aria-practices/projects/42).

In the new content tree, create a page for each section of aria-practices.html that serves as a source of a practices section page in the web site.

**Comment by mcking65** [comment]
Discussion point: Should we consider having a directory for each practice in the content tree? That would give the option of later having a practice that includes multiple files. It would more closely mirror the structure of the patterns and about branches of the tree.

**Comment by mcking65** [comment]
#2417 will resolve this issue.

As of today, the practices are moved out of aria-ppractices.html and are in the move-examples branch in a practices subdirectory in the new content tree. All links to practices are updated.

@alflennik, the next steps for practices are:

* Apply css to the practices files in the new content tree
* Put the images for the practices cards into the practice subdirectories of the practices directory
* Build content/practices/practices.html (perhaps in a manner similar to the way the index is built)

**Comment by alflennik** [comment]
Sounds good @mcking65!
