### ISSUE TITLE
Checkbox examples should not repeatedly toggle while holding down spacebar

### ISSUE THREAD

**Issue by sivakusayan** [w3c/aria-practices#2425]
I notice that in [Checkbox Example (Two State)](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox.html), focusing a checkbox and holding down the spacebar key repeatedly toggles the checkbox. This does not happen with [native HTML checkboxes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox). I wonder if this could be an issue for people with motor disabilities.

If my intuition is correct and this is an issue, the fix should be simple - we just need to add an [event.repeat](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat) check in the [onKeyDown listener](https://github.com/w3c/aria-practices/blob/45e9a6c4b19ea03356a9aa1cda8c8eaaf3272015/examples/checkbox/js/checkbox.js#L35).
_If we really care about parity with native HTML checkboxes, this logic should probably be done in a `keyup` listener, though._

**Comment by mcking65** [comment]
Thank you @sivakusayan  for the fix!

**Comment by mcking65** [comment]
Re-opening because this applies to both two-state and mixed state checkbox examples. Will be closed by #2722.

**Comment by mcking65** [comment]
Resolved for remaining checkbox example with #2722.
