### ISSUE TITLE
Why is the Disclosure FAQ widget not an Accordion?

### ISSUE THREAD

**Issue by gaurav5430** [w3c/aria-practices#2445]
Is there a reason that the disclosure FAQ widget discussed here : https://www.w3.org/WAI/ARIA/apg/example-index/disclosure/disclosure-faq.html , does not use an Accordion, and instead uses individual disclosure buttons?

**Comment by JAWS-test** [comment]
There are no HTML elements or ARIA roles for accordion

I.e. an accordion is always nothing else than several disclosures one after the other. Thus the FAQ widget is also an accordion.

**Comment by gaurav5430** [comment]
Sure, that makes sense. My question was more towards why do we not use the [Accordion ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/) for Disclosure FAQs

**Comment by JAWS-test** [comment]
The accordion pattern is used for the FAQ (because it is the same)

**Comment by JAWS-test** [comment]
I think the differences are allowed implementation variants in each case.

hidden is rendered as display:none. Whether there is a semantic difference, I cannot say. There is a cryptic hint about hidden in the HTML specification that suggests there might be a difference. But I do not think it is relevant

> The [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden) attribute must not be used to hide content that could legitimately be shown in another presentation. For example, it is incorrect to use [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden) to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar.

https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute
