### ISSUE TITLE
Clarity wanted regarding menu design pattern

### ISSUE THREAD

**Issue by jmtes** [w3c/aria-practices#2470]
In the **Keyboard Interaction** section of the [Menu Design Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu/) , several of the bullet points mention arrow key wrapping, e.g.

> `Home`: If arrow key wrapping is not supported, moves focus to the first item in the current menu or menubar.

My question is: what exactly _does_ arrow key wrapping refer to? A [Google search for the exact phrase](https://www.google.com/search?q=what+is+%22arrow+key+wrapping%22&rlz=1C5CHFA_enUS965US965&ei=PncaY9P5J9e7qtsPosCuQA&ved=0ahUKEwjTkJ-wqYb6AhXXnWoFHSKgCwgQ4dUDCA4&uact=5&oq=what+is+%22arrow+key+wrapping%22&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgATIFCCEQoAEyBQghEKsCOgoIABBHENYEELADOgUIABCiBDoHCAAQHhCiBEoECEEYAEoECEYYAFDCBFjuHGDAImgBcAF4AIABgAGIAfABkgEDMC4ymAEAoAEByAEIwAEB&sclient=gws-wiz) only turns up results that match what's on the pattern.

I think it would be great to outline what exactly this means on the pattern itself in an aside or something along those lines.

**Comment by JAWS-test** [comment]
It is explained immediately in the lines above what it is, for example:

> Right Arrow: When focus is in a menubar, moves focus to the next item, **optionally wrapping from the last to the first**.

**Comment by jmtes** [comment]
My bad, it wasn't clear to me that that was the same concept! Thank you!
