### ISSUE TITLE
aria-autocomplete Both and aria-activedecendant question

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria-practices#2473]
I am querying the need for using aria-activedecendant on a Combobox that uses aria-autocomplete set to Both.

Because the whole value is populated, for example typing C inserts the first option California into the input, and this is announced, and navigating the Listbox populates the value into the input, why is aria-activedecendant needed?

I have copied the APG aria-autocomplete both Codepen and removed aria-activedecendant. The combobox value is announced as I would expect without setting aria-activedecendant.

**Updated APG example for demonstration**
- CODEPEN [combobox-autocomplete-both (sans aria-activedecendant)](https://codepen.io/Deafinitive/pen/PoeNdzG)

**Questions**
- Is this expected behaviour?
- Does the pattern break if aria-activedecendant is not set for autocomplete both?

**References**
- APG 1.2 [Editable Combobox With Both List and Inline Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-autocomplete-both.html)
- CODEPEN [combobox-autocomplete-both by Captain Anonymous including aria-autocomplete](https://codepen.io/pen)

**Comment by mcking65** [comment]
Without aria-activedescendant, screen reader users won't know that there are multiple values available or how many because the screen reader is not aware of the listbox or the position of the currently selected item in the listbox.

**Comment by LaurenceRLewis** [comment]
Now you mention it @mcking65  I notice the difference where the number of list items is announced when aria-activedecendant is present. 

With aria-activedecendant the number of options is announced and works on Desktop Windows running JAWS or NVDA and macOS / Voiceover. However on iOS / Voiceover the number of items is not announced, and on Android / Talkback the number of list items is announced with and without aria-activedecendant.
