### ISSUE TITLE
Switch example using HTML button clashes with website CSS

### ISSUE THREAD

**Issue by yatil** [w3c/aria-practices#2474]
The example on this page shows white text on white background: https://www.w3.org/WAI/ARIA/apg/example-index/switch/switch-button.html

Make sure that your examples are properly encapsulated and use higher specificity.

**Comment by yatil** [comment]
FWIW, I attempted to use the fork and edit functionality on the page and as these pages use HTML instead of the WAI markdown templates, I did not feel confident to make changes. It also looked like it referenced external files and I was not willing to dig through the repository.

**Comment by yatil** [comment]
Hello? Is someone maintaining this repository?

**Comment by mcking65** [comment]
@yatil 

APG TF meets tomorrow. would help to know which text is white on white.

**Comment by yatil** [comment]
The example. The switches on the page. Both text and the switches under the "Environmenal Controls" heading are somehow white on the white background.

**Comment by yatil** [comment]
Just looking at the discussion. You can just prefix your button with a class and override the template code.

**Comment by mcking65** [comment]
The fix for this is planned to go live this Thursday.
