### ISSUE TITLE
Radio buttons v Action buttons

### ISSUE THREAD

**Issue by CaroRob** [w3c/aria-practices#2484]
What is the argument for using a list of radio buttons, rather than a list of action buttons....on one screen.
Using the premise that fewer clicks is better - why would we not simply list 3, 5 or even 7 action buttons, clearly labeled, and organized vertically? Users could skip the Continue or Next or Submit action button and go straight to the next screen. 

I see that Nick Begich from UX Planet and at least one other place say Radio buttons are for options, they are not commands/actions but no one seems to explain why. The exclusivity is even more reason to stick with the action rather than obviously checkboxes which would not work as actions. 

So much on radio buttons v. drop downs and checkboxes differences. Hardly anything on why they should not be used as actions. The only thing I can think of is that sometimes you might have several sets of radio buttons on a screen and then they would need to be submitted. 

Perhaps the question is why not multiple action buttons instead of radio buttons if only asking one question per screen? Is there a reason for this design decision - particularly interesting given the statistics of people using mobile devices to complete forms now.

**Comment by JAWS-test** [comment]
I agree with you, but which pattern in ARIA APG are you referring to? I have not found a pattern that violates your statement.

**Comment by mcking65** [comment]
Hi @CaroRob 

Assuming the intent of elements, whether radios or command buttons, is perceivable and understandable, I don't think this topic raises accessibility concerns.

If you have questions or feedback regarding any of the relevant APG patterns or practices, please feel free to re-open this issue.
