### ISSUE TITLE
Why isn't listbox shown with expanded/collapsed implementations?

### ISSUE THREAD

**Issue by mbgower** [w3c/aria-practices#2489]
The humble `select` element is awesome for a lot of list-of-choices scenarios, but as you know, they tend to be avoided in design systems due to the difficulty styling them.
I was about to direct a team to the [Listbox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/) pattern for what I would describe as a spiffed up select component, then discovered that none of the examples seem to start collapsed (as is typical of a select, and as this team had designed), and there does not seem to be any keyboard operator listed for opening and closing.
At first I thought an expanded/collapsed listbox was intentionally not part of the pattern, but then I confirmed that `aria-haspopup` can take a listbox value. So obviously it's an intended experience.
I'm guessing this is the result of a complex widget, and you are only documenting the expand/collapse behaviour under button? But I was concerned there is no cross reference to it.
If I can better understand how the pattern is intended, I'd be happy to help contribute to a revamp of this. As it stands, I'm pretty sure I'll immediately get questions if I just direct a team here.
Thanks!

**Comment by mcking65** [comment]
We have deprecated collapsable listbox in favor of select-only combobox.
Deprecated pattern:
https://www.w3.org/WAI/ARIA/apg/example-index/listbox/listbox-collapsible.html

New pattern:
https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html

**Comment by mbgower** [comment]
Great, thanks. That looks thorough!
I would not have thought of looking under "Select-only combobox" for that. I wonder if it would be useful to have a more typical index with cross-references to ARIA preferred terms, rather than just what is essentially a list of patterns? For example, if someone is looking for Select, or Listbox, they get SeeAlso refs to Select-only combobox. It would take some work with synonym rings and controlled vocabularies, but might be worth it to make content more findable. Maybe EO could help with that? If it's considered of value/importance, I might be able to contribute.

I note you're preserving select' keyboard entry-typing speed for skimming to options, which I like, but it's also a technical failure of 2.1.1 Keyboard, since it involves timing. Do you have any thoughts on how you'd like Keyboard timing tweaked in a WCAG 3 world?

**Comment by mbgower** [comment]
I'm closing the issue, but feel free to comment!

**Comment by mcking65** [comment]
@mbgower wrote:

>I wonder if it would be useful to have a more typical index with cross-references to ARIA preferred terms, rather than just what is essentially a list of patterns? For example, if someone is looking for Select, or Listbox, they get SeeAlso refs to Select-only combobox. It would take some work with synonym rings and controlled vocabularies, but might be worth it to make content more findable. Maybe EO could help with that? If it's considered of value/importance, I might be able to contribute.

To some extent, the index by states and properties does provide this.

Nevertheless, we have discussed doing much more with the index page over time, and would welcome contributions to that effort.

> I note you're preserving the native select element's keyboard entry-typing speed for skimming to options, which I like, but it's also a technical failure of 2.1.1 Keyboard, since it involves timing. Do you have any thoughts on how you'd like Keyboard timing tweaked in a WCAG 3 world?

Please explain the failure. It might deserve an issue if there is a failure.

Keep in mind that the type-ahead scrolling in lists is not an essential function; it is a convenience with particular benefit to people who can not easily visually skim. There are many other ways to scroll that do not have any time-out characteristics, including first-letter, arrow key, and page down/up. If type-ahead without timeout is considered by the author to be an essential function, that that is supported by any combobox that includes an text input.

**Comment by mbgower** [comment]
> Please explain the failure. It might deserve an issue if there is a failure.

I don't think it's the APG's problem to resolve this, but here is what I believe is a long-standing problem with the default `Select` keyboard operation, which is required to meet this wording:

> All [functionality](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html#dfn-functionality) of the content is operable through a [keyboard interface](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html#dfn-keyboard-interface) without requiring specific timings for individual keystrokes,

We've all encountered the Country select input, where you have to choose your country from the alphabetical list. If you live in Saint Helena, you press the "S" and get there in a keystroke. Anyone can press a letter to orient there. If you live in South Africa, you can quickly press the letters "So" and it's only one more keystroke. But what if you cannot press letters at a speed which the browser requires for it to consider this a 'string'? You get moved to Saint Helena, then to Oman.

Clearly, there is functionality based on specific timing of individual keystrokes, and clearly the ability to jump through hundreds of choices rapidly is something of significant value to users.

Some argue that the ability to skip choices by character strings is a convenience not a requirement. But the wording of the SC is not "essential functionality". It's just functionality.

It's similar to the debate about whether a date input's calendaring is a function or a convenience. I've heard repeated argument about whether an inaccessible calendar constitutes a failure if the user can just enter the date directly into the field. I appreciate both sides of the argument.
 
In the case of the select, it would be conceptually simple to remove the timing: just accept any keypresses while in a select as part of a string until the user presses Space, Enter or an arrow. One could even introduce an Esc to reset the string.

In the case of the ARIA pattern, the ability to skip to choices based on keyboard timing is not listed as 'Optional'. As such, it seems to document a 'requirement' for keyboard timing. The easy way out is probably just to list it as optional. On the other hand, doing so now reduces the functionality of the ARIA widget compared to the native Select.

Hence my comment on your thoughts. Since WCAG 3 is underway and most existing requirements will be revamped, it would be good to get input on whether functionality should focus on ability to complete an action or try to establish criteria that pushes for qualitative equivalent facilitation. The former is a lot easier to complete, and from that perspective, the keyboard timing in the `select` is not a failure.
