### ISSUE TITLE
Identify examples where the charCode property of keypress event is used

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#249]
The charCode proprety of [keypress](https://developer.mozilla.org/en-US/docs/Web/Events/keypress) 
is deprecated. This may be the reason that focus is trapped in the tree view examples when using later versions of Firefox as described in issue #223.

To facilitate plans to remove dependency on the charCode property of keypress event, Identify the examples that depend on it.

**Comment by a11ydoer** [comment]
@mcking65  keypress code is located at menubar examples - menuitmeaction.js and menuitemlinks.js I would be able to fix this if I am assigned to the work. Jon has already fixed "key press" in button example.

**Comment by mcking65** [comment]
Menubutton fix is in commit 50a45b30f9a26803ada319dee9926e48ee81996e

**Comment by mcking65** [comment]
Now, the only place where we still have this problem is in the menubar examples.

**Comment by mcking65** [comment]
This issue is now resolved as follows:

1. Fixed for menubutton example in commit 50a45b30f9a26803ada319dee9926e48ee81996e
2. Fixed for treeview examples in:
    *  commit 69a36ff777ed3d003023efb5c368b84bd68387ed 
    * commit 0d6b2d0f9cc3af62241c98fbcdfc490418902a0e
3. Fixed for menubar examples in commit bbc4c097b6efce2904fdac5416606ca3a50c8949

@jongund, thank you very much for all your work on this!!
