### ISSUE TITLE
Rename tab panel design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#25]
_From @MichielBijl on March 7, 2016 18:31_

In the March 7th APG call we decided to rename the tab panel design pattern. Its current name (tab panel) is weird, considering it refers to just a part of the design pattern.

Suggestions:

- Tabs
- Tabbed interface

_Copied from original issue: w3c/aria#286_

**Comment by mcking65** [comment]
Changed the section name to "
Tabs" and made some other minor editorial improvements.
commit 15a2578e34a360f3fb2d31e61302702bf0c70fa8
