### ISSUE TITLE
Badge (state indicator) pattern

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria-practices#2507]
Controls are often adorned with a "badge" indicating (a change of) status/state.

Typical examples:

- The notification badges on social media showing new content/posts which may be reached via the control where the badge seems to be attached.
- A shopping cart, with a badge showing the number of items it contains.
- A clickable list of colleagues in a remote-productivity front-end, each colleague with a badge that indicates their availability

None of this is particularly complex to do, but the exact implementations which work reliably, and within the expectations of AT users is non-obvious (to me anyway). 

This issue is a call for some examples showing a working badge implementation with any relevant aria attributes, indicating how the control and the badge are associated.

Very often, this is implemented by "hacking" the accessible name so that it includes the state info as a suffix, something like
`elem.setAttribute("aria-label"´, "recent posts" + (notificationCount > 0 ? " " + notificationCount + " unread" : " all caught up" ));`

One conceptual problem I see with hacking state into the accessible name is that it takes us away from the principle that the name uniquely identifies the element. Maybe this is acceptable to some, but it feels dirty. It's a hack.

This issue is a call for some examples showing a working badge implementation with any relevant aria attributes, indicating how the control and the badge are associated, and how the state information is exposed.

Some questions that APG guidance might answer (I do not know all the answers to these questions):

- To what extent is it acceptable to 'hack' the accessible name of an element, so that the name includes the badge state?
- What is the preferred DOM relationship between the control and the badge? Siblings? Parent-Child?
- Should the badge have a distinct role? Which one?
- How do I decide if a state change (expressed in a badge) should be reported via a live region?
- Should the badge get focus distinct from the control that it is associated with?
- What ARIA might reliably associate a control with a badge? (I assume that `aria-details` may be viable, when that is fully formed).
- Are there cases where a badge might seem suitable, but better solutions are available? (e.g. non-operable content?)
- Is there ARIA (such as aria-valuetext) which seems viable, but should be avoided when making badges?

**Comment by mcking65** [comment]
Does a badge indicate state? Or is a badge a form of visual shorthand?

A link to a shopping cart that contains 2 items is functionally identical to a link to a shopping cart that contains 0 or 4 items. 

Is it reasonable to consider a badged shopping cart link as short form expression for a link to a shopping cart that is named according to how many items it contains?

**Comment by mcking65** [comment]
Task force guidance:

* Including information conveyed by a badge in the accessible name is consistent with the [purpose of an accessible name](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/).
* Accessible name serves the user better than description or details based on the intent of the badge and the intent of accessible name.
* Accessible name serves the user better than a new state because states cannot include content; they are boolean or tokens.
* Names are fully controlled by the author.

**Comment by JAWS-test** [comment]
I think it's a pity that it was closed so quickly. Badges are widely used and I think it makes sense to think about it a little longer. Sometimes there are two badges at a link or button, whose meaning is visually explained by color, icon or position. If I put all this information into the AccName, it becomes very long. WCAG SC 2.4.6 says that labels should be concise and meaningful. This is no longer the case if I have extensive badge information in the AccName.

**Comment by brennanyoung** [comment]
@JAWS-test that is certainly another thing that bothers me about piggybacking on the accessible name.
It does seem that when `aria-details` is finalised, it will be a better option. (The APG advice can then change to reflect this.)

For now, I am happy with the concrete guidance given after the task force chat. Thank you so much for providing the transcript! I found the argumentation persuasive. 

Placement of the advice in the APG docs about naming (rather than creating a whole new pattern) is acceptable to me.
