### ISSUE TITLE
Should tabs component example HTML markup include ARIA properties by default?

### ISSUE THREAD

**Issue by basher** [w3c/aria-practices#2540]
I'm wondering why the [tabs component example](https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic.html) has `aria-` and `role` attributes baked into the HTML, rather than those attributes being added programatically via JavaScript.

Similarly, the `is-hidden` class on the `role="tabpanel"` content containers is also present in the HTML.

Surely, with JavaScript disabled (or failing in some way), this component would
(a) not behave as a tabbed interface at all and may mislead AT users, and
(b) all content would be unavailable, except in the 1st tabpanel.

Wouldn't it make more sense to remove all these attributes from the initial HTML payload, and progressively enhance the markup via JavaScript?

**Comment by JAWS-test** [comment]
Most ARIA patterns work only with Javascript. A browser with JS disabled would not be able to display most pages correctly. Therefore, since WCAG 2.0, it is no longer assumed that JS is disabled.

**Comment by basher** [comment]
> Most ARIA patterns work only with Javascript. A browser with JS disabled would not be able to display most pages correctly. Therefore, since WCAG 2.0, it is no longer assumed that JS could be disabled.

I'm not sure I fully understand?

Are you saying that because we no longer assume that JS could be disabled, it's OK to bake the ARIA directly into the HTML?

**Comment by JAWS-test** [comment]
> Are you saying that because we no longer assume that JS could be disabled, it's OK to bake the ARIA directly into the HTML?

JS can probably be disabled, but those who do will no longer be able to use most pages and most ARIA patterns. 

I think the effort to build a page to work completely without ARIA and JS and then enrich it via JS ARIA functions is very costly. Of course this can be done, but it doesn't have to be.

**Comment by basher** [comment]
I'm _"old-school"_. ;)

I prefer a progressive enhancement approach, where core functionality is provided by semantic HTML that is "uncluttered".

Without JS, all the tab content can simply be visible on the page, and behave as normal "flow" content.
The tab "buttons" can be replaced by links that anchor down to each content section.

The amount of JS required to construct the ARIA attributes is really not very much extra effort.

**Comment by mcking65** [comment]
@basher wrote:

> I'm _"old-school"_. ;)
> 
> I prefer a progressive enhancement approach, where core functionality is provided by semantic HTML that is "uncluttered".
> 
> Without JS, all the tab content can simply be visible on the page, and behave as normal "flow" content. The tab "buttons" can be replaced by links that anchor down to each content section.
> 
> The amount of JS required to construct the ARIA attributes is really not very much extra effort.

In the past, the APG task force has discussed the tradeoffs related to developing examples that use this approach of progressive enhancement that relies on js and developing examples that bake some ARIA in to the static HTML.

In today's world, there are no strong accessibility reasons for recommending either approach. In practice, the mix of js injected attributes verses staticly coded attributes is dictated by other factors, e.g., the UI framework.

Thus, the decision about which approach to prefer in the APG has been based on APG objectives. A primary objective of APG is to help a wide audience understand the purpose and intent of ARIA attributes.

There a lot of APG readers who can understand simple HTML code but would struggle to understand how js is dynamically transforming HTML. Even experienced front-end engineers can more easily understand how the ARIA is being used if they can easily inspect static HTML. This has been the primary reason for the prevalence of staticly declared ARIA in APG examples.

If you don't find this explanation satisfactory or have other related questions, please feel free to re-open this issue.
