### ISSUE TITLE
Draft guidance on range related properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#255]
This section will cover:

- [x] aria-valuemax
- [x] aria-valuemin
- [x] aria-valuenow
- [x] aria-valuetext

**Comment by spectranaut** [comment]
These native html elements have the analogous attributes: `<input type=range>` and `<progress>` and `<meter>`.

`<meter>` has more attributes that aria can express - we can just ignore them.

**Comment by zcorpan** [comment]
We realized that `meter` role is not part of ARIA 1.1. @mcking65 this section thus shouldn't cover `meter`, correct?

**Comment by spectranaut** [comment]
Here is a draft PR for this issue: https://github.com/w3c/aria-practices/pull/1000

**Comment by mcking65** [comment]
@zcorpan commented:

> We realized that `meter` role is not part of ARIA 1.1. @mcking65 this section thus shouldn't cover `meter`, correct?

Correct. When we add the meter role to ARIA 1.2, we will revise and have a different version of this for the APG 1.2 branch. As I recall, we may have just merged meter to ARIA 1.2, so an issue related to this should be coming soon.

**Comment by a11ydoer** [comment]
This issue is merged to [PR1279](https://github.com/w3c/aria-practices/pull/1279). 
I am closing this issue.
