### ISSUE TITLE
Link broken on https://www.w3.org/WAI/ARIA/apg/patterns/

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#2568]
from https://www.w3.org/WAI/ARIA/apg/patterns/
The link to landmarks goes to https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/ which is broken

**Comment by a11ydoer** [comment]
I am closing this issue since it will be taken care of by [issue 192](https://github.com/w3c/wai-aria-practices/issues/192)

**Comment by a11ydoer** [comment]
The broken link was fixed.
