### ISSUE TITLE
Seeking advice on what pattern to follow for a "ToggleGroup"

### ISSUE THREAD

**Issue by joshuawootonn** [w3c/aria-practices#2579]
Hello there.

I am trying to understand what pattern I should follow for a "ToggleGroup" like these two examples: 

<img width="393" alt="CleanShot 2023-01-09 at 08 26 48@2x" src="https://user-images.githubusercontent.com/20950876/211331073-49f50974-8c36-49f2-ba86-bb1df836512d.png">

Different UI kits (in react) follow different patterns.

- Radix
    - Sortof a radio group pattern, but selection doesn't follow focus. And the parent element has `role="group"` instead of `role="radiogroup"`
    - https://www.radix-ui.com/docs/primitives/components/toggle-group
- Ant Design
    - Follows the radio group pattern, but always behaves as an element in a toolbar. (Arrow key on the last element focuses the next input)
    - https://ant.design/components/radio
- Material UI 
    - Just puts buttons in a `role="group"` and styles them differently
    - https://mui.com/material-ui/api/toggle-button-group/
    
    
    
### Is the selection style arbitrary for this component? 

If your toggle button is in a tool bar and changes text alignment it might be jarring to have the entire body of text change alignment over and over as you move through your toggle button.

But in the same vein, if you are filling in a google form with standard information for an event you are joining, you would probably expect this input to behave like a radio button.

Thinking about this: https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_selection_follows_focus

### What pattern should this component follow?     

Thanks 🙏🏼

**Comment by JAWS-test** [comment]
https://www.w3.org/WAI/ARIA/apg/example-index/toolbar/toolbar.html have also a

> Sortof a radio group pattern, but selection doesn't follow focus

**Comment by joshuawootonn** [comment]
> Because ARIA is designed to inform assistive technologies about UI semantics and behaviors, not styling, the alignment toggles provide the following keyboard support described in the [radio group design pattern.](https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/)

This line was particularly clarifying for me. Thank you @JAWS-test
