### ISSUE TITLE
https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/ and 404 https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation 

### ISSUE THREAD

**Issue by ChrisLoiselle** [w3c/aria-practices#2598]
The https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/ page has a reference that leads to a 404 https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation

**Comment by mcking65** [comment]
@ChrisLoiselle 

We apologize for the interruption in availability and any problems that may have caused.

We have been aware of the problem. We broke the links to 14 pages last Wednesday. We just completed a major restructuring of the content repository, and these slipped through the testing. We now understand were the gap in our automated testing is that allowed that to happen.

We thought we might be able to land the fix last Thursday. Unfortunately, it is not landing until tomorrow.

We have automated testing to avoid broken links, but need to do more work to ensure this particular problem does not repeat. Fortunately, the kind of structural changes that created the problem are behind us for now.

**Comment by shawna-slh** [comment]
Thanks for the report @ChrisLoiselle It is now fixed.

(p.s. Hi! :-)

**Comment by ChrisLoiselle** [comment]
@shawna-slh  hi! Hope all is well :)

**Comment by ChrisLoiselle** [comment]
@mcking65 no worries, great work as always!
