### ISSUE TITLE
Aria Landmarks Page has broken links

### ISSUE THREAD

**Issue by gericci** [w3c/aria-practices#2600]
The page "https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/" presents broken links to all Aria Landmarks Examples

**Comment by mcking65** [comment]
@gericci 

We apologize for the interruption in availability and any problems that may have caused.

We have been aware of the problem. We broke the links to 14 pages last Wednesday. We just completed a major restructuring of the content repository, and these slipped through the testing. We now understand were the gap in our automated testing is that allowed that to happen.

We thought we might be able to land the fix on Thursday. Unfortunately, it is not landing until tomorrow.

We have automated testing to avoid broken links, but need to do more work to ensure this particular problem does not repeat. Fortunately, the kind of structural changes that created the problem are behind us for now.

**Comment by shawna-slh** [comment]
Thank you for the report @gericci The links are now working.
