### ISSUE TITLE
TOC pinning broken

### ISSUE THREAD

**Issue by yatil** [w3c/aria-practices#2601]
In certain viewport sizes, the TOC is pinned to the top but fills the whole horizontal space, making it hard for users to read the content.

This is likely due to the mixed used of em-based media queries (for the general site template) and px-based media queries (for styles specific to the aria practices guide).

Here’s a video of the behavior:

https://user-images.githubusercontent.com/58862/217782877-83d28bb4-ee49-46bc-9938-0229389ef385.mp4

**Comment by mcking65** [comment]
@alflennik 

I think we may have another report of this issue in #2669.

Do you have a PR for the fix? Do I recall correctly that this is a quick fix?

**Comment by alflennik** [comment]
@mcking65 thank you for putting this back on our radar, I was under the impression that we had already fixed all the media queries to use the same em values as the template but in this case we're still using a px value. Yes, the linked issue #2669 is the same as this one.

**Comment by a11ydoer** [comment]
@mcking65 I confirmed that pinned TOC was fixed.
