### ISSUE TITLE
ARIA Authoring Practices Guide (APG) considered to be a mandatory specification or just a recommended example?

### ISSUE THREAD

**Issue by nfxpnk** [w3c/aria-practices#2607]
Hello, community!

Is the Navigation Menubar Example https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/ provided in the ARIA Authoring Practices Guide (APG) considered to be a mandatory specification or just a recommended example for creating accessible navigation menus using ARIA technology?

How should I treat this pattern? Is it a **strict specification** or **just a recommended use case** that might have adjustments? 

According to the ARIA Authoring Practices Guide 1.1, it is described as a guide providing **a set of recommended practices** for creating accessible rich internet applications using ARIA technology.

Thank you.

**Comment by nschonni** [comment]
The "Read this first" section at the top of the page talks about this https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/#support-notice-header

**Comment by nfxpnk** [comment]
@nschonni Thank you. I thought this was referring to the existing **code** as an example, not to the pattern description. So that is the answer to the main question? 
`The code in this example is not intended for production environments.`
Should I treat that pattern description as strict specification or just a recommended use case?

**Comment by StommePoes** [comment]
This is an opinion and it's a few years out of date:

The patterns in the APG are attempts to create stable examples of how widgets should work interactively. Some patterns are more stable (supported and work) than others. Many have large issues on mobile (the patterns focus on keyboard and mouseclicks, leaving occasional problems on touchscreens for example).

For specifically the menubar, the important part to note isn't so much the code section, but the part under CAUTION. This part was added because developers thought "if I have a menu with dropdowns, I should follow the menubar pattern" and this is not true simply because a developer has a menu with dropdown functionality. Consider the original idea for "menubars" was based on desktop computer applications (think... photoshop. Or the menu at the top of your desktop browser). The pattern attempts to follow those kinds of menus.
Developers have argued for a few years now on whether navigation menus on websites (which have a different interaction history than application menus) should use the menubar pattern or not.

Where I am out of date is whether the web in general has made a consensus on this. I was generally against menubars for navigation menus, but for them on web-page widgets such as a menu in a rich-text-editor (let's say you were making a github-type web application).

The important thing: IF you choose to use the menubar pattern, ensure it follows the behaviour and uses the roles and states correctly!

**Comment by nfxpnk** [comment]
@StommePoes 

Thank you.

>The important thing: IF you choose to use the menubar pattern, ensure it follows the behaviour and uses the roles and states correctly!

Can you please help me to understand:

If I will add just small addition to https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/ implementation on my website.

Pressing TAB, Shift+TAB will go through all items of top navigation menu.
Pressing TAB will do the same as Right arrow key now.
Pressing TAB+Shift will do the same as Left arrow key now.

Would it be a mistake? Is it allowed?

**Comment by StommePoes** [comment]
(And yes, you may be running across the issue I touched on earlier: webpage navigation menus have a different interactive history. Users have, in the past, always Tabbed through each menu item. So this is, even today, likely what they expect. It may not occur to them that they can move in with Tab and switch to Arrows. There's nothing visually telling a sighted keyboard user that they can do this. They have to play around with it and figure it out.

Proponants of menubar patterns feel that the benefit of being able to quickly exit the menu with the Tab key outweighs the confusion a user will have without any visual clue as to how the menu works. And if your menu is as simple as the example page you linked to, indeed, people generally figure it out.)

**Comment by StommePoes** [comment]
> Would it be a mistake?

Yes. I should have said this first off. 

> When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item. Because menubar and menu elements are composite widgets as described in the practice for [Keyboard Navigation Inside Components](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_general_within), Tab and Shift + Tab do not move focus among the items in the menu. Instead, the keyboard commands described in this section enable users to move focus among the elements in a menubar or menu.
from https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

This is the section you, as a developer, want to read. It will state the allowed roles and states, but also allowed/expected keyboard events for the widget pattern.

**Comment by nfxpnk** [comment]
> By adding Tab as well, keyboarders must always do the Thousand Tabs of Death (and so Arrows offer nothing helpful, really).
But we can just simply press the End key, which will bring the focus to the very last item of top navigation.

**Comment by nfxpnk** [comment]
> Yes. I should have said this first off.

But in that way behavior of navigation with menubar + Tab will be just like on this example: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/

I just want to understand, if we have valid functionality for Disclosure Navigation, why we can't do the same for navigation with menubar.

**Comment by nfxpnk** [comment]
I did an analysis of random popular websites. Such as Nike, Apple, Amazon, Ebay, Target etc. And my rough estimate is that only 1-2% of popular sites use menubar for top navigation.

**Comment by mcking65** [comment]
@nfxpnk asks:

>How should I treat this pattern? Is it a strict specification or just a recommended use case that might have adjustments?

There are really two separate questions here:
1. Is the menubar pattern appropriate for my use case?
2. If I use the menubar pattern, can I make adjustments to it?

Let's cover each in detail.

#### 1. Is menubar appropriate for my use case?

As Nick pointed out, the first bit of guidance the APG provides to help you with this question is:

>Caution! Before considering use of the Menubar Pattern for site navigation, it is important to understand:
>* The menubar  pattern requires complex functionality that is unnecessary for typical site navigation that is styled to look like a menubar with expandable sections or “ fly outs ” . 
>* A pattern more suited for typical site navigation with expandable groups of links is the Disclosure Pattern.

If you are confident the complex functionality (i.e., all the keyboard features of menubar) are advantageous for your specific use case, and you have the ability to build and maintain it, then it might be a good fit. This is not normally the case for most web sites.

There are some types of sites, e.g., google docs, where menubar is really advantageous. In such sites, users spend a lot of time using the site, they need to use the functionality in the menus very frequently within the course of a single visit, and there is a cohort of users for whom efficient keyboard access is essential.

There are other types of business applications where navigating among the pages and functions of the application meet these same criteria. Typical consumer sites do not.

The APG task force plans to add a site navigation practices section to provide more information about choosing among the many patterns that are suitable for site navigation. In the meantime, we've added the caution note to help reduce confusion.

#### 2. If I use the menubar pattern, can I make adjustments to it?

@StommePoes wrote:

>The important thing: IF you choose to use the menubar pattern, ensure it follows the behaviour and uses the roles and states correctly!

This is spot-on. There is some latitude, which is described on the pattern page. Going beyond what is defined by the pattern is likely to cause problems. to successfully deviate from the pattern, you need a deep understanding of all relevant technologies complemented by a ton of AT/Browser testing capabilities. In that sense, the APG is a specification of what "should" work.

In the [read me first](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/#mobile_and_touch_support), the APG explains how a role is a promise. If you use the menu and menubar roles, you are telling assistive technologies and their users what to expect. If you use them without meeting those expectations, it creates problems ... lots of problems.

One expectation with menu is that tab gets you out. So, as @StommePoes says, changing that is a mistake. Please, please do not make a menu where you can tab from one menuitem to another! Strictly follow the keyboard interactions defined by the pattern. Imagine if some websites decided to invert how your mouse scroll wheel works or require double clicks on buttons or something like that. The roles used on widgets are intended to convey information about the way widgets work.

I hope this answers your questions.

**Comment by nfxpnk** [comment]
@mcking65 Thank you very much for such a detailed answer to my question!
I didn't expect my question will get so much attention.

P.S. Interesting thing, I can't find a site that uses menu, menubar correctly for navigation, just like in the example [Navigation Menubar Example](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/). It seems that this approach is not used very often at all.

**Comment by mcking65** [comment]
You're welcome.

Right, it is a rarely used pattern. Currently it is most visible in sites like Google Docs, Quip, and apps built with technologies like electron. The low usage is primarily driven by complexity and inconsistent screen reader support. The evolution of various technologies and practices are trending in directions that will eventually diminish those barriers to adoption. In the future, the return on investment calculation could change significantly for some site developers.

Closing this question as answered; please feel free to re-open if needed.
