### ISSUE TITLE
Why is aria-expanded removed on closed Actions Menu Button?

### ISSUE THREAD

**Issue by ksparrow-8x8** [w3c/aria-practices#2623]
As per [Actions Menu Button Example Using element.focus()](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions/):
`The aria-expanded attribute is removed when the menu is closed.`

[MDN says that the default value for aria-expanded is undefined](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded), which means "The element does not own or control a grouping element that is expandable." Shouldn't the Actions Menu Button always own the dropdown?

Is this a mistake? If not, what is the reasoning behind removing `aria-expanded` rather than using `aria-expanded="false"`?

Thanks!

**Comment by mcking65** [comment]
See #697, #2808, and #2834.

The short answer is that omitting aria-expanded=false was intentional but the task force is reversing its previous guidance as described in the related issues. Since this is addressed by other issues, closing as duplicate.
