### ISSUE TITLE
Infrastructure: HTML validator paths are outdated

### ISSUE THREAD

**Issue by howard-e** [w3c/aria-practices#2637]
Following the restructure of the repository, the current HTML validator being used is pointing to now absent paths. From `package.json`:

```
"vnu-jar": "java -jar node_modules/vnu-jar/build/dist/vnu.jar --filterfile .vnurc --no-langdetect --skip-non-html aria-practices.html index.html examples/"
```

`aria-practices.html index.html examples/` should be `content/`. This change has been addressed in #2617. But new warnings have been introduced: https://github.com/w3c/aria-practices/pull/2617#issuecomment-1429944933

**Comment by howard-e** [comment]
Looking again at the log, it seems the only new (and non-zero blocking) error is:

`example-usage-warning.html":8.9-8.11: error: Element “p” not allowed as child of element “summary” in this context.`

Should this be updated or suppressed? cc @alflennik @mcking65

**Comment by alflennik** [comment]
@howard-e I looked into this an left a comment in the PR!
