### ISSUE TITLE
Review long description disclosure example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#264]
The example of a 
[disclosure for an image long description](http://w3c.github.io/aria-practices/examples/disclosure/disclosure-img-long-description.html) 
Is ready for review.

#### Requested reviews

- [x] Review by @jnurthen 
- [x] Review by @annabbott 
- [x] Review by @jongund

**Comment by annabbott** [comment]
Looks good.

**Comment by jnurthen** [comment]
Good for me

**Comment by jongund** [comment]
Updated the visual disclosure indicator to use an image instead of entity value

**Comment by mcking65** [comment]
@jongund, @jnurthen, @annabbott 

I have some more questions and possible issues.

1. Because the image uses aria-labelledby, Screen readers read the entire label twice. It seems to me that the visible text is not really an image label, but is instead a caption. I think the image label should be shorter and represent the nature of the image. This makes me wonder if this shouldn't be a figure with a figcaption?
2. Is this image a graphical representation of some kind? I am guessing that is not a table. If it is a graph of some kind, maybe it should have `aria-label="Chart Detailing Napoleon’s 1812 Russian campaign"`.
3. The disclosure is labeled details. But, it exposes a table of data. Seems like a better label would be "Chart Data".

Thoughts?

**Comment by jongund** [comment]
Matt,

Thank you for the feedback, let me make a mother try at the example.

Jon

**Comment by annabbott** [comment]
In the Role, Property, State, and Tabindex Attributes section for aria-expanded="false":
CSS attribute selectors (e.g. [aria-expanded="false"]) synchronize the visual states with the value of the aria-expanded attribute. 
Suggested edit to match noun/verb usage:
CSS attribute selector (e.g. [aria-expanded="false"]) synchronizes the visual states with the value of the aria-expanded attribute. 

Same section for aria-expanded="true":
CSS attribute selectors (e.g. [aria-expanded="true"]) synchronize the visual states with the value of the aria-expanded attribute.
Suggested edit to match noun/verb usage:
CSS attribute selector (e.g. [aria-expanded="true"]) synchronizes the visual states with the value of the aria-expanded attribute.

**Comment by annabbott** [comment]
In the Keyboard Support section:
Space or
Enter 	
Activates the disclosure button, which toggles the visibility of the long description. 

Only Enter toggles the visibility. Space blinks the visibility, but doesn't leave it open in order to read.

Using FF and keyboard only to navigate.

**Comment by mcking65** [comment]
@jongund, @annabbott, @jnurthen, I think the team should take one final look at this before we wrap up the task force review process of this one.

**Comment by annabbott** [comment]
Typo in the heading above the table::
Currently is:
"Data for Charles Minars's Chart of Naploean's Invasion of Russia"
Corrected typo::
"Data for Charles Minars's Chart of Napolean's Invasion of Russia"

**Comment by annabbott** [comment]
I'm totally confused! I thought the long description was to be a translation of the French included in the image. I don't see any long description - just the table that follows the image.

**Comment by annabbott** [comment]
Also, there is no alt text for the image.

**Comment by mcking65** [comment]
@annabbott, I wonder what you are looking at. There is definitely alt text and the the figcaption includes the translation of the French from wikipedia.

I fixed the typos. Please have another look.

**Comment by annabbott** [comment]
Ok, the example page is entirely different than it was 3 days ago! Now I see the alt text, the figcaption plus the edit you did for the typo. Looks good now.

**Comment by mcking65** [comment]
The task force review process for this example is now complete. Thank you Team!! Closing this issue.
