### ISSUE TITLE
Link to Latest Draft points to current APG

### ISSUE THREAD

**Issue by joe-watkins** [w3c/aria-practices#2641]
How does one access the latest Draft? http://w3c.github.io/aria-practices/

All roads lead to the current APG? https://www.w3.org/WAI/ARIA/apg/

**Comment by a11ydoer** [comment]
Hi @joe-watkins 
Indeed, all roads lead to the current APG site! ;-) The goal of the ARIA APG Taskforce is to provide timely ARIA examples, and as such, the group has decided to no longer use a versioning system. If any changes are made, they will be reflected weekly in accordance with the publication schedule.

**Comment by a11ydoer** [comment]
The response was provided.

**Comment by joe-watkins** [comment]
@a11ydoer Is there a summary / changelog to track that would go along with the weekly publication schedule? Short of monitoring commits, how can one keep up-to-date with big changes? e.g. APG Combobox Pattern moving from 1.1 to 1.2

Also, is there a formal post about this change somewhere we can point folks to? tnx :)

**Comment by a11ydoer** [comment]
@joe-watkins 

Thank you for asking such a great question. I understand the significance of having a summary or change logs to keep track of changes, which can assist developers. Currently, the change log information is available in the About section of the APG website at https://www.w3.org/WAI/ARIA/apg/about/#changehistory. However, this information tends to become outdated rapidly. Therefore, we have raised [an issue with the W3C WAI template repository](https://github.com/w3c/wai-aria-practices/issues) to automate the process, as ARIA APG uses the W3C WAI template.

**Comment by mcking65** [comment]
@joe-watkins 
It's important to note that the "editor's draft" that was on github.io has been frozen since last July. So, it was already significantly out of date. All content that was in the editor's draft is in the new APG site, so it had nothing left to offer.

**Comment by joe-watkins** [comment]
Wonderful :) Thanks so much @a11ydoer @mcking65 !!
