### ISSUE TITLE
Landmark Pattern Page Missing so the Landmark Pattern URL returns 404

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#2645]
The following URL should be a landing page and not a 404 error.
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/

This would allow a URL link now that could be easily updated later when the landmarks session is updated.

It should be forwarded to the current link for the landmark pattern:
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html

**Comment by mcking65** [comment]
Rather than referring to a page under examples, a better long term fix is to add the missing page. I have created a draft in #2670.

Once we land the pattern page, we can rework the practices and example pages to better match the new site architecture.
