### ISSUE TITLE
Review FAQ disclosure example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#265]
The example of using a 
[disclosure for answers in a FAQ](http://w3c.github.io/aria-practices/examples/disclosure/disclosure-faq.html) 
is ready for review.

#### Requested reviews

- [x] Review by @jnurthen 
- [x] Review by @annabbott 
- [x] Review by @a11ydoer

**Comment by mcking65** [comment]
Seems to me it would be better if we preserve and expose the definition list semantics by putting the button role on a span inside of the `dt` element instead of having role button on the `dt` element. If we don't do this, then we should have role presentation on the `dl` element.

**Comment by annabbott** [comment]
Looks good.

**Comment by jnurthen** [comment]
The dl, dd and dt are troubling me. 
I'm not sure we need both the Definition list semantics AND the hide/show with the aria-controls relationship. Indeed - the DT without a DD (when it is hidden) bothers me as it implies a relationship which is not present in the page at that time. 
I think this warrants further discussion in the meeting on monday.

**Comment by mcking65** [comment]
Maybe the content that is controlled by the disclosure (the answer to the question) should be in a `div` inside the `dd` so that the `dd` is always present. Both for structure and fall back, I kind of like the `dl` semantics.

**Comment by jongund** [comment]
Created a pull request to address the use of entities for displaying state and changed FAQ example to use DIV elements instead of DL/DT/DD elements

**Comment by mcking65** [comment]
@jongund, I thought the outcome of the meeting discussion was to keep the `dl` since this is a list of questions. To do this, we put the question button inside of the `dt` and the element controled by that button inside of the `dd`.

I included these remarks in my review of PR #282. 

In the PR, everything is a div, which gives 0 semantic structure except for the intervening button elements.

**Comment by jongund** [comment]
Matt,

OK.   It wasn’t clear to me from the issue discussion what the group decided, but I can add it back in and use the button element and make a new pull request.

Jon

**Comment by jongund** [comment]
Matt,

I have created a new pull request:

  1.  Restored the use of DL/DT/DD in FAQ example and use button element for toggling each FAQ
  2.  Updated long description to use figure caption and changed the SPAN to a button element, updated the labeling of the button element, not sure about suggested changes to the ALT text for the image.  Maybe discuss on call.

Jon


From: Jon Gunderson <jongund@illinois.edu<mailto:jongund@illinois.edu>>
Date: Tuesday, February 14, 2017 at 8:32 AM
To: w3c/aria-practices <reply@reply.github.com<mailto:reply@reply.github.com>>, w3c/aria-practices <aria-practices@noreply.github.com<mailto:aria-practices@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [w3c/aria-practices] Review FAQ disclosure example (#265)

Matt,

OK.   It wasn’t clear to me from the issue discussion what the group decided, but I can add it back in and use the button element and make a new pull request.

Jon

**Comment by annabbott** [comment]
Correct typo in first paragraph:
The following example demonstrates using the disclosure design pattern to create a set of frequently asked questions where the answers may be independently shown or hidiven. 
Suggested edit:
The following example demonstrates using the disclosure design pattern to create a set of frequently asked questions where the answers may be independently shown or hidden.

**Comment by annabbott** [comment]
Correct typo in Role, Property, State, and Tabindex Attributes > aria-expanded="false":
Indicates that the container controlled by the disclosure button is hidiven . 
Suggested edit:
Indicates that the container controlled by the disclosure button is hidden .

**Comment by annabbott** [comment]
In the Keyboard Support section:
Space or
Enter
Activates the disclosure button, which toggles the visibility of the answer to the question.

Only Enter toggles the visibility. Space blinks the visibility, but doesn't leave it open in order to read.

Using FF and keyboard only to navigate.

**Comment by annabbott** [comment]
Enter and Space now toggle visibility = fixed.

**Comment by a11ydoer** [comment]
I am also hesitant to use DL,DT and DD for this example. My understanding for these tags are for listing "data" like a data table instead of using table tag. This FAQ example seems to be that they are rather the list of questions.  We have a[ FAQ example](http://www.library.illinois.edu/hpnl/faq/) using bootstrap library.

**Comment by a11ydoer** [comment]
I agreed with advantages of semantics by using dl, dt and dd (ex: how many items in the list and skip to the list item if a user wants) so we are closing this issue as it is.

**Comment by mcking65** [comment]
Team, Thank you for all the feedback on this Example. All task force reviews are now complete, and I am closing the task force review process.
