### ISSUE TITLE
Obsolete gh-pages branch: Feedback on redirect presentation and code quality

### ISSUE THREAD

**Issue by yatil** [w3c/aria-practices#2651]
https://w3c.github.io/aria-practices/ produces a span soup that is worth a full meal. I understand that this is not glamorous work, but it is a little embarrassing.

[Found via Twitter.](https://twitter.com/lloydi/status/1640816526944026625)

**Comment by lloydi** [comment]
And given the amount of ids that are present in the markup, this is clearly something that has been automated. As such, would it not have made more sense to dynamically create a server-side redirect (.htaccess or whatever) that would silently point people in the right direction for each link instead of providing the (almost) list?

**Comment by yatil** [comment]
Yeah, redirects on GitHub are complicated, but honestly for this case a meta refresh redirect would be sufficient. It can surely be better handled than whatever this is.

**Comment by mcking65** [comment]
A PR that would improve the situation is welcome!!!

With so many high impact issues in the APG Task Force backlog, the primary objective for this change was get the job done as fast as possible. This is a surface that should soon have zero traffic. It is already very low. In other words, it is little more than a stopgap backstop to help in situations where people have not updated inbound links.

It was scripted b/c there are 74 html files in the gh-pages branch that needed to have redirect info. Most of the others are in the examples/ tree and contain a single link. The index.html represents the old TR doc, and each of the links represents one of the H2 or H3 headings in that doc.

**Comment by yatil** [comment]
If you let me know where to send my invoice for learning how this repository works and make the necessary changes, I’m happy to contribute a Pull Request.

**Comment by yatil** [comment]
🤷‍♂️
