### ISSUE TITLE
Sticky position in Nav blocks content when using larger browser displays

### ISSUE THREAD

**Issue by heidi-jungel** [w3c/aria-practices#2669]
The page contents nav blocks content and it is really hard to read the contents.
As a low vision user, it is almost impossible to use these pages without having to into the inspect tool and set a display:none on these. It looks like it forces the position:sticky

**Example code Reference**
```<nav class="box nav-hack sidebar standalone-resource__sidebar " aria-labelledby="sidebar-header">...</nav>```

**Environment Details:**
Mac OS 12.6.4
Chrome v112.0.5615.49 (Default Appearance - Font size: Very Large; Page Zoom: 110%)
Mac OS Display: Scaled - Larger Text

It also does this in Safari:
Safari v16.3 (17614.4.6.11.6, 17614)
Default Accessibility Setting: Never Use font size smaller than 18

**Screenshot:**
![image](https://user-images.githubusercontent.com/12895478/230180347-10946a54-3aa8-40c8-9db6-291c6ab173a3.png)

**Comment by heidi-jungel** [comment]
I was not able to find this in the code when forking this repo, but will be more than happy to dig into the code and help fix this (I am a developer myself).

**Comment by mcking65** [comment]
@heidi-jungel 

Is this the same issue described in #2601?

**Comment by heidi-jungel** [comment]
Much apologies for the delay, @mcking65, I missed this message.  Yes, this looks like the same issue.  I will close this so we do not have duplicates around.
