### ISSUE TITLE
Skipto needs to be updated to version 5.1.4

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#2677]
There is an issue with with Firefox browser when calculating the accessible name for a heading that includes an IMG element. 
The bug has been fixed in version 5.1.4, not sure how to push the change to the APG template.

You can see the Firefox bug by opening the SkipTo menu in the [Patterns Page](https://www.w3.org/WAI/ARIA/apg/patterns/).  The names of headings that include images are prefixed with `-Moz-alt-content`.   NOTE: This only happens in Firefox browser.

Link to new version of Script:
[Skipto 5.1.4](https://skipto-landmarks-headings.github.io/page-script-5/dist/skipto.min.js)

[More information on SkipTo 5.1.4](https://github.com/skipto-landmarks-headings/page-script-5)

**Comment by alflennik** [comment]
I opened a PR on the wai-aria-practices side which updates the library and will close this issue: https://github.com/w3c/wai-aria-practices/pull/217 Thank you Jon for raising this and implementing the fix!

**Comment by mcking65** [comment]
@alflennik 

I commented in #2682 that I think it is best to continue sourcing skipto.js from content/shared/js in aria-practices. Merging #2680 should be the resolution to this issue of upgrading skipto.js.

At this point, I'm confused about the best strategy for eliminating duplication. Clearly, there is something about the build I don't yet sufficiently understand.
