### ISSUE TITLE
Grid cell content can be actionable and editable

### ISSUE THREAD

**Issue by curtbellew** [w3c/aria-practices#2678]
The grid pattern currently suggests 3 different methods of accessing actionable and/or editable cell content.  The F2 key, the Enter key, and Alphanumeric keys.  The F2 key and Enter key have very similar functionality. We're looking for guidance on how to handle a situation where the grid cell contains one or more elements such as links that are clickable and also editable.  A simple example might be a user grid where the first column is a user name that is clickable - taking you to a user detail page - and is also an updatable field.
https://www.w3.org/WAI/ARIA/apg/patterns/grid/#gridNav_inside

**Comment by mcking65** [comment]
Closing based on meeting discussion
