### ISSUE TITLE
Simplify build of patterns and practices pages

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2702]
#### The problem

Currently the [patterns](https://www.w3.org/WAI/ARIA/apg/patterns/) and [practices](https://www.w3.org/WAI/ARIA/apg/practices/) pages are built by scripts that process the content of all the individual pattern and practice pages. This auto-generation adds complexity and constrains editorial control.

The complexity of auto-generation sometimes leads to build failures, such as the failure mentioned in [this comment by James on PR 2670](https://github.com/w3c/aria-practices/pull/2670#issuecomment-1550188786).

Because the patterns and practices pages are built by scripts, editors can't control some important aspects of the content. They can't manipulate the order in which practices are presented. They also have limited control of the abstract that describes each pattern and practice on the patterns and practices pages. The abstract is pulled  from the first sentences of the about section of a pattern or practice. Generally, this works well, but there are times when the abstract could be improved by highlighting information that that can't be easily crammed into the first sentence without degrading readability.

The patterns and practices pages do not need to be updated frequently. So, the effort and time saved by auto-generation is fairly small.

Simplifying the build process will improve the long term sustainability of the APG by reducing the need for engineering support.

#### Solution Proposal

1. Source patterns page content from content/patterns/patterns.html
2. Source practices page content from content/practices/practices.html
3. Make the build of home, patterns, practices, and about as simple and consistent as is reasonable.
4. Document a clear set of classes and DOM structure requirements that editors can use when building and revising content for those pages.

#### Proposal for approach

* Start small and iterate
* Draft a PR that moves the practices page content into practices.html. This should also ensure that all images used on the practices page are sourced from content/images.
* After practices build is working well, repeat with another PR for the patterns page.
* Look for opportunities to simplify by better aligning the way home, patterns, practices, and about are coded and processed.

**Comment by ccanash** [comment]
We will triage this task this week.

**Comment by ccanash** [comment]
Hi @mcking65 , we triage this and the next step is clear for us but we won't work on this until we reprioratize APG work

**Comment by ccanash** [comment]
Closing as this was deployed to prod on dec 12 https://github.com/w3c/wai-aria-practices/pull/280
