### ISSUE TITLE
Select-Only Combobox Example - listbox closes when clicking on scrollbar

### ISSUE THREAD

**Issue by LukaszJaro** [w3c/aria-practices#2719]
The following example https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

When the select only combo box is open/expanded, and you attempt to click on the scrollbar, it causes the listbox to close preventing the user from scrolling with mouse to see more options.

It looks like this is to do with the blur event handler "this.comboEl.addEventListener('blur', this.onComboBlur.bind(this))". When combobox loses focus, it closes the listbox which is fine in every case except when attempting to scroll by dragging the scroll bar with a mouse.

This "Editable Combobox With List Autocomplete Example" is actually working correctly and allows scrolling with mouse.

**Comment by andreancardona** [comment]
Current working PR in draft: https://github.com/w3c/aria-practices/pull/2723
