### ISSUE TITLE
aria-expanded attribute is needed or not

### ISSUE THREAD

**Issue by AccessibilityEnthusiastic** [w3c/aria-practices#2730]
Hi Everyone,

I have a scenario where the 'About' button expands automatically when the keyboard focus moves to the 'About' button(I do not need to press Enter key to expand the 'About' button)
In this case, do we still need an aria-expanded attribute in the 'About' button?

![image](https://github.com/w3c/aria-practices/assets/115781693/3e5ee566-58d9-4959-8911-ad353077a80c)

**Comment by mcking65** [comment]
Yes. It is important to communicate the expanded state of a disclosure or menu. Obviously, if you activate the "About" button, that will collapse the "About" disclosure or menu, an the state change is important information.

**Comment by mcking65** [comment]
If you need further clarification, please feel free to re-open this issue.
