### ISSUE TITLE
Editable Combobox examples not respecting Required Owned Element

### ISSUE THREAD

**Issue by sinap-fb** [w3c/aria-practices#2743]
Per https://github.com/dequelabs/axe-core/issues/2339#issuecomment-1608408177, it seems like the following APG examples for editable comboxes don't satisfy the [ARIA's Required Owned Element requirement](https://www.w3.org/TR/wai-aria-1.2/#mustContain) for listboxes have at least one descendant that is a Required Owned Element (`role="optoin"` or `role="group"`) when typing in a query that has no results.  Instead, the listbox is a `<ul>` with no children.

Violating examples:
- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/
- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/
I believe this also applies to the `role="grid"` example:
- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/grid-combo/

Thanks

**Comment by mcking65** [comment]
@sinap-fb Yes, per ARIA 1.2, there would be bugs. In practice, there aren't any negative consequences, and consequently, the ARIA requirements are changing.

ARIA 1.3 is replacing the concept of required owned elements with [Allowed Accessibility Child Roles](https://w3c.github.io/aria/#mustContain).

The new wording in the definition of [listbox](https://w3c.github.io/aria/#listbox) is:

>List boxes contain children whose role is option or elements whose role is group which in turn contain children whose role is option.
