### ISSUE TITLE
Incorporate/embed Feed example into APG Pattern Page

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#2747]
[Feed example](https://www.w3.org/WAI/ARIA/apg/patterns/feed/examples/feed-display.html) is currently located at a separate page. It would be great if we can embed the Feed example inside of [APG Feed pattern page](https://www.w3.org/WAI/ARIA/apg/patterns/feed/examples/feed/).

**Comment by mcking65** [comment]
@ariellalgilmore 

As a member of the GitHub ARIA Contributors team, you can create a branch in the aria-practices repo rather than work off of a fork like you did in #2723. Using a branch in this repo makes it easier to collaborate and keep the branch current.
