### ISSUE TITLE
wrong link in tab example

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/aria-practices#276]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs.html

"The below example section demonstrates a tabs widget that implements the [design pattern for tabs](https://www.w3.org/TR/wai-aria-practices-1.1/#checkbox)."

It links to the design pattern for checkbox instead of tabs. Correct url should be [https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel) I suppose?

**Comment by mcking65** [comment]
@Veyfeyken, You are right. Thank you for catching this!

**Comment by mcking65** [comment]
@Veyfeyken, 

The fix for this is now published in the latest editor's draft of this example at 
http://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html

Closing the issue.
