### ISSUE TITLE
Combobox example's text doesn't fit in its input element on Safari iOS

### ISSUE THREAD

**Issue by mxmason** [w3c/aria-practices#2778]
## Summary

Just as it says on the tin! In Safari iOS, the combobox input's text is too tall for the combobox input. One solution might be to stop manually setting the height of the input to 24px, allowing the input to occupy the height it needs. It then has plenty of room for the cursor. I'm happy to submit a PR to fix this!

## Screenshots

The screenshots in this table compare the current state of the combobox with one possible fix.

| Current (has explicit `height`)                                                                                                                       	| Possible fix (no explicit `height`)                                                                                                        	|
|--------------------------------------------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| ![The APG combobox with text partly obscured by the input](https://github.com/w3c/aria-practices/assets/13525251/3fa44a4c-b67e-4620-8145-e3e96bb3fa91) 	| ![A taller version of the APG combobox, text inside fully visible](https://github.com/w3c/aria-practices/assets/13525251/e77c6cc3-2a5a-4337-ae26-db4364beb0b2) 	|

**Comment by mcking65** [comment]
@mxmason Thank you for reporting this bug. The fix has landed via PR #2780 and will be in tomorrow's publication.

Thank you @andreancardona and @ariellalgilmore for working on the fix!!
