### ISSUE TITLE
Document APG build process in wai-aria-practices repo ReadMe

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#2781]
- Transfer APG deployment Information in [APG redesign issue 13](https://github.com/w3c/wai-aria-practices/issues/13) to Wiki documentation
- Add created wiki page to Readme documentation

**Comment by mcking65** [comment]
@a11ydoer 

I think this info belongs in the [wai-aria-practices repo readme](https://github.com/w3c/wai-aria-practices), not one of the wikis. There is out of date info in that readme that also needs to be revised.

**Comment by howard-e** [comment]
https://github.com/w3c/wai-aria-practices/pull/356 should address this once merged

**Comment by ccanash** [comment]
Closing as https://github.com/w3c/wai-aria-practices/pull/356 was mereged
