### ISSUE TITLE
Fix links from ARIA 1.1 specification to ARIA Authoring Practices

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#280]
As we are working on reorganizing and restructuring the authoring practices, some links from the ARIA spec to practices may be effected.

We will work on keeping fragment IDs the same to minimize broken links.

**Comment by mcking65** [comment]
@rodrigoprestesmachado reported the following as a comment to issue 65, and I created this issue and moved the feedback here.

The aria-live session (http://w3c.github.io/aria/aria/aria.html#aria-live) in WAI-ARIA 1.1 document there is a link to Live Region properties in WAI-ARIA Authoring Practices 1.1 document. The link is "Please refer to Live Region Properties and How to Use Them ([WAI-ARIA-PRACTICES], Section 5.2.1)." (http://w3c.github.io/aria-practices/#liveprops). However, the session 5.2.1 doesn`t exist in WAI-ARIA Authoring Practices 1.1.

**Comment by mcking65** [comment]
@Joanmarie, even though this is a to-do on the spec, I am tracking here because we have work to do in the practices document before we can fix the links in the spec. The goal, of course, is to have the structure and sections in place before the next publication of the spec.  If we miss that target, the fall back is to simply remove the links from the spec. I will do all I can to make sure that is not necessary.

**Comment by mcking65** [comment]
@rodrigoprestesmachado, thank you for the feedback. Our plan is to have guidance on live regions in the next couple of months or so.

**Comment by MichielBijl** [comment]
Related: https://github.com/w3c/aria-practices/issues/351

**Comment by mcking65** [comment]
Verified all links from ARIA 1.1 to the practices are good.

Some improvements to link to specific sections could be made. Listed them in a comment on w3c/aria#328.
