### ISSUE TITLE
 Clarification on aria-haspopup and aria-expanded Attributes

### ISSUE THREAD

**Issue by AccessibilityEnthusiastic** [w3c/aria-practices#2808]
I am reaching out to seek clarification on the usage of the aria-haspopup attribute in combination with the aria-expanded attribute.

My specific question pertains to whether it is still necessary to include the aria-expanded attribute with a value of "false" in the default state of the element when aria-haspopup is used. To provide some context, I am wondering if the presence of aria-haspopup alone adequately conveys the intended user interaction, or if aria-expanded must be used.

With aria-haspopup indicating the presence of a popup and aria-expanded providing its state (open or closed). However, I'm seeking clarification on whether aria-expanded with a default value of "false" is redundant when aria-haspopup is present.

**Comment by mcking65** [comment]
@AccessibilityEnthusiastic wrote:

> I am reaching out to seek clarification on the usage of the aria-haspopup attribute in combination with the aria-expanded attribute.
> 
> My specific question pertains to whether it is still necessary to include the aria-expanded attribute with a value of "false" in the default state of the element when aria-haspopup is used.

We have some precedent for considering it optional. However, people have found this confusing and potentially problematic for users. See #697.

>To provide some context, I am wondering if the presence of aria-haspopup alone adequately conveys the intended user interaction, or if aria-expanded must be used.

Problems arise for users of touch-based screen readers. If aria-expanded is not set, then it may not be clear to users whether a menubutton is expanded or collapsed. By consistently specifying both states, the user can easily determine which button will close a currently expanded menu and which buttons will not.

> With aria-haspopup indicating the presence of a popup and aria-expanded providing its state (open or closed). However, I'm seeking clarification on whether aria-expanded with a default value of "false" is redundant when aria-haspopup is present.

Net: experience is telling us aria--expanded=false is not redundant when aria-haspopup is true.

I'm closing this issue, but please feel free to re-open if you believe the issue deserves more discussion.

I'm also going to resurrect work on #697.

**Comment by mcking65** [comment]
@AccessibilityEnthusiastic, as a follow up, the task force has decided to move forward with #2829 and update the 3 menu button examples accordingly.

**Comment by mcking65** [comment]
Change to be published on December 19, 2023
