### ISSUE TITLE
link-checker incorrectly says a fragment does not exist

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2809]
In #2734, the link-checker is failing on the link:

https://github.com/w3c/aria-practices#code-conformance

It says the fragment `#code-conformance` was not found. I wonder if it is added dynamically and the link-checker is getting incomplete content?

this test failure is blocking progress on #2734.

**Comment by howard-e** [comment]
Something interesting I noticed after looking through the page ids exposed by this repo's link-checker solution, is that for a GitHub page, almost every element on the page has an id so it can be navigated to and focused. So https://github.com/w3c/aria-practices#issues-tab or https://github.com/w3c/aria-practices#fork-button focuses onto the `Issues Tab` and the `Fork Button` respectively.

That would mean the chance of id name clashes increases with those reserved names, so the ids of the heading elements in the README are actually prepended with `user-content-`. So for example, `user-content-code-conformance`. This makes it possible to navigate to https://github.com/w3c/aria-practices#user-content-code-conformance as well as https://github.com/w3c/aria-practices#code-conformance. I suppose GH does some intelligent matching in JS when navigating with the stripped version (as long as there's no clashes with their reserved ids?). But the link checker is explicitly checking for `code-conformance`. 

So I think this means that the [check for the "hashes"](https://github.com/w3c/aria-practices/blob/7b0b4d39986424deb062b3e3487c233b9da797e8/scripts/link-checker.js#L277) could maybe be relaxed to something like the following instead:

```javascript
ids.some(id => id.includes(hash));
```
