### ISSUE TITLE
Combobox VoiceOver announced value text, text is cut into one letter by one

### ISSUE THREAD

**Issue by theniceangel** [w3c/aria-practices#2813]
![Screenshot2023_09_26_112309](https://github.com/w3c/aria-practices/assets/25956811/50b8fbc1-4712-4341-a9f8-3c6e401f36b5)

only reproduce it when value is a number which smaller than 10, if greater than 10, no issues.

**Comment by mcking65** [comment]
Related to https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/

**Comment by mcking65** [comment]
Hi @theniceangel

I've verified that when single digits are typed into the combobox that voiceOver spells out the word "s t a t e" after reading the value. That is a VoiceOver behavior that is not related to the validity of the combobox example code. In other words, it is not a bug in the APG combobox example. You could raise the issue with Apple.
