### ISSUE TITLE
Update regression test report to work with new repo structure

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2837]
[test/util/report.js](https://github.com/w3c/aria-practices/blob/7fb7c8e28b55a2804bda682c36945a1154d1096a/test/util/report.js) does not work with the content refactor completed by #2417.

This could be included in a refactor of #2291, which addresses #959.

**Comment by howard-e** [comment]
@mcking65 @a11ydoer I can go ahead with updating the #2291 PR to support this.

**Comment by a11ydoer** [comment]
Thanks so much! @howard-e

**Comment by a11ydoer** [comment]
@mcking65 this issue was fixed by the branch, bocoup/fix-issue-959. We can close this issue.
