### ISSUE TITLE
Source "Read This First" heading from aria-practices repo

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#2838]
The example pages all have an `h2` element with content"Read This First". This element is apparently being added during the build process. In line with our repo design objective of sourcing all content that is not part of the WAI template system from the aria-practices repo, include the `h2` element in the file [content/shared/templates/example-usage-warning.html](https://github.com/w3c/aria-practices/blob/7fb7c8e28b55a2804bda682c36945a1154d1096a/content/shared/templates/example-usage-warning.html) and remove the code that is adding it during build.

**Comment by ccanash** [comment]
Closing as in production
