### ISSUE TITLE
"Back to Top" link obscures modal action buttons on mobile

### ISSUE THREAD

**Issue by emamoah** [w3c/aria-practices#2842]
This is from the [Modal Dialog Example](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/) in the APG.

It may require an increase in the bottom padding on all modals (for uniformity)

![Screenshot_20231025_171503_Firefox.png](https://github.com/w3c/aria-practices/assets/42612171/d2b68954-a7ca-4823-96ad-cd97520340ae)

**Comment by mcking65** [comment]
Thank you @emamoah for raising and providing the fix for this issue!!!!

I just merged #2843, and it will be included in our next site update, which is scheduled for tomorrow.
