### ISSUE TITLE
[Select-Only Combobox] Clicking the label behaviour

### ISSUE THREAD

**Issue by silviuaavram** [w3c/aria-practices#2859]
Hello everyone!

A user of `downshift` useSelect hook asked about the lack of action when you click on the label corresponding to a select element. At the moment, the example for ARIA 1.2 performs no action when clicking the label.

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

Since Downshift follows the ARIA 1.2 pattern, we also don't perform any action when the label is clicked. However, should this behaviour be changed?

According to the MDN HTML `<select>`, when clicking the label, the select element is focused.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

Should we also do the same and update the 1.2 pattern? Also, should we also add the `htmlFor` attribute again for the `<label>` pointing to the select?

Thank you very much and looking forward to your thoughts on this!

The issue we are tracking in downshift: https://github.com/downshift-js/downshift/issues/1557

**Comment by mcking65** [comment]
@silviuaavram, thank you for raising this issue. The fix will be live in production on April 9.
