### ISSUE TITLE
Tabs examples do not correctly place focus after deleting a tab

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#286]
In the 
[Example of Tabs With Automatic Activation](http://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html) and the 
[Example of Tabs With Manual Activation](http://w3c.github.io/aria-practices/examples/tabs/tabs-2/tabs.html),
after the "Joke" tab is deleted, focus is placed on the first tab. It should be placed on the tab just before the one that was deleted.

**Comment by MichielBijl** [comment]
This is fixed in https://github.com/w3c/aria-practices/commit/47b9529f9f07ec37ce9b08a941eaab5b66648466. 

It now sets focus to the tab directly before the deleted one. Unless the first tab is deleted, then it’ll set focus to the tab that is now the first one.
