### ISSUE TITLE
Naming Form Controls with the Label Element recommends incorrect technique

### ISSUE THREAD

**Issue by dotjay** [w3c/aria-practices#2870]
On the [Providing Accessible Names and Descriptions](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/) practices page under the heading [Naming Form Controls with the Label Element](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#naming_with_labels), the text describes two techniques, commonly known to accessibility professionals as implicit and explicit labeling.

Implicit:

> Wrapping the checkbox and the labeling text in a `label` element as follows gives the checkbox an accessible name.

Explicit:

> A form control can also be associated with a label by using the `for` attribute on the `label` element.

The guidance goes on to state the following, which I believe to be incorrect:

> When possible, use the above encapsulation technique for association instead of the following for attribute technique.

However, _explicit_ labeling using `for` and `id` attributes has [long been established as the preferable technique](https://www.tpgi.com/html5-accessibility-chops-form-control-labeling/) due to better support in browsers and assistive technology software, which is echoed by the WAI's own [tutorial on Labeling Controls](https://www.w3.org/WAI/tutorials/forms/labels/) (with my emphasis):

> Associating labels implicitly
> In some situations, form controls cannot be labeled explicitly. For example, a content author might not know the id of a form field generated by a script, or that script might not add an id at all. In this case, the label element is used as a container for both the form control and the label text, so that the two are associated implicitly. Generally, _explicit labels_ are better supported by assistive technology.

This is backed up by experts [reporting issues with voice control software like Dragon Naturally Speaking](https://a11ysupport.io/tech/html/label_element) not working with implicit labeling techniques, and [more recent testing with screen readers](https://dev.to/thejaredwilcurt/the-truth-behind-implicitexplicit-form-labels-2e10).

I suggest that the advice on the [Providing Accessible Names and Descriptions](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/) page be reworded to something like:

> When possible, use the following `for` attribute technique for association instead of the above encapsulation technique.

**Comment by patrickhlauke** [comment]
Pull request submitted here @dotjay https://github.com/w3c/aria-practices/pull/2871

**Comment by mcking65** [comment]
PR #2882, which resolves this issue is merged. The change is scheduled for publication tomorrow, December 19.

Thank you @dotjay and @patrickhlauke for raising the issue and shaping the resolution.
