### ISSUE TITLE
Treegrid example should use the hidden attribute rather than a hidden class

### ISSUE THREAD

**Issue by jcoyne** [w3c/aria-practices#2881]
The `hidden` attribute is more semantically meaningful and would make the code less complex:
https://github.com/w3c/aria-practices/blob/main/content/patterns/treegrid/examples/js/treegrid-1.js#L351-L354

I've written the issue title as a statement, but it's actually a bit of a question.  Is my assertion correct?  My supposition is that when this was written 5 years ago, the hidden attribute was not as widely supported as it is now.  Can or should the example be updated to use the `hidden` attribute?

**Comment by mcking65** [comment]
Based on discussion in today's meeting, the task force believes code can be equally clear regardless of whether the HTML hidden attribute or CSS is used. Obviously, class name affects clarity.

While sometimes influenced by external factors, this choice is largely stylistic, and the task force doesn't have a case for modifying the treegrid examples, the other examples, or the APG code guide.

@jcoyne, please feel free to re-open this issue if you would like to continue the discussion by sharing reasons that support task force adoption of a different path.
