### ISSUE TITLE
Tabs widgets unusable in High Contrast Mode

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#289]
In its current state it’s utterly impossible to see which tab is active or has focus with Windows High Contrast Mode activated. This is due to the state only differentiating in colour.

Related to https://github.com/w3c/aria-practices/issues/279 and https://github.com/w3c/aria-practices/issues/278

- [x] Review by @jnurthen

**Comment by MichielBijl** [comment]
To tackle this problem I’ve redesigned the tabs widget 🌟.

Let’s see if everyone can guess the different states now, answers in the alt text ;).

<img src="https://cloud.githubusercontent.com/assets/5457769/23048577/aee0461c-f4ae-11e6-8f45-48bb98bdea9c.png" alt="Tabs widget in its default state, current tab’s top border is thick and blue. There is no border on its bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048619/0933ea1a-f4af-11e6-8b12-7b61f592033d.png" alt="Tabs widget with an active tab and another tab that has focus. The focused tab’s top border is medium and orange and it has a border along the bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048698/79ede3b4-f4af-11e6-80f4-a322e789968d.png" alt="Tabs widget with an active tab that has focus. Its top border is medium and orange. There is no border on its bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048759/e97fe01a-f4af-11e6-81ac-53b4d5f4dbd4.png" alt="Tabs widget with focus set to the tab panel. The panel border colour is changed to orange and the bottom border width is changed to medium." width="297">

In Windows High Contrast Mode this looks like:

<img src="https://cloud.githubusercontent.com/assets/5457769/23048803/2c854e22-f4b0-11e6-9687-b186b6b39b5a.png" alt="Tabs widget in its default state in High Contrast Mode, current tab’s top border is thick and there is no border on its bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048828/5e37bcb6-f4b0-11e6-8e48-4b2645f931af.png" alt="Tabs widget in High Contrast Mode, current tab’s top border is thick and there is no border on its bottom. Another tab has focus whose top border width is medium and it has a border along the bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048925/dcd7fcb6-f4b0-11e6-8131-fb1a3b6b8de9.png" alt="Tabs widget in High Contrast Mode, there is an active tab that has focus. Its top border is medium in width. There is no border on its bottom." width="297">

<img src="https://cloud.githubusercontent.com/assets/5457769/23048950/fa372e6c-f4b0-11e6-88c5-4650f94b2964.png" alt="Tabs widget with focus set to the tab panel. The panel bottom border width is changed to medium." width="297">

One can easily differentiate between the states because the border width differs between current, in-active, and focus.

***

These changes are made in: https://github.com/w3c/aria-practices/commit/1b7de6b37781a5035fd5e501292aee0efb5baabe

Changes made in this commit:

- Changed design to work independent of colour
- Changed content of second tab (panel)
- Both examples now use the same CSS file
- Removed a duplicated “Accessibility features” heading in the manual tabs example

**Comment by MichielBijl** [comment]
This new design doesn’t change anything on the HTML side.

**Comment by mcking65** [comment]
In commit b5c5b615c0c4f6352af664f083857d431efead1a, 
I fixed the link to the .css file in the source code section.

**Comment by MichielBijl** [comment]
@mcking65 Ah, yes, I forgot about that, thanks for fixing that.

**Comment by jnurthen** [comment]
I'm not sure how easily the distinction can be made - but it is at least different and we are illustrating that it is important that there be a difference. I'm fine with the change.

**Comment by mcking65** [comment]
OK, we have adequate review. Looks like we can close this issue. Thank you again @MichielBijl!

**Comment by MichielBijl** [comment]
@jnurthen I’m open to suggestions on how to improve on this.
