### ISSUE TITLE
2.13 Grid (Simple Data Tables) - changes

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#29]
_From @jnurthen on April 11, 2016 18:1_

_Copied from original issue: w3c/aria#323_

**Comment by MichielBijl** [comment]
_From @jnurthen on April 18, 2016 18:6_

* Re-title to "Grid"
* Have 2 sub-sections within the description for "Data Grids" and "Layout Grids"
* Keyboard Section
  * Need to add something about navigating to the cell or the content (Matt to write)
* Re-write description section to remove information which is no longer relevant in ARIA 1.1 and to add content about new features in ARIA 1.1

**Comment by MichielBijl** [comment]
Do we also have Complex Data Tables? i.e. why is simple in there?

**Comment by mcking65** [comment]
First draft is in the following commit.

commit 900ed0283c390a8f3af8dd6ed93e2e3d7f248f57
Author: Matt King <a11ythinker@gmail.com>
Date:   Mon Jul 11 01:06:39 2016 -0700

    New grid design pattern replaces 2 patterns
    
    This new grid pattern replaces the prior grid pattern plus the actionable sortable column header section that followed it.
    It covers both data grids and layout grids and refers to a new placeholder table design pattern as well.
    Separate subsections for data and layout grids are included with their own keyboard interaction subsections.
    Following the data and layout grid subsections, is a keyboard interaction subsection   with factors that are common to both.
    
    The roles, states, and properties subsection is updated to also cover ARIA properties for
    label, labelledby, describedby, sort, owns,
    colcount, colindex, rowcount, rowindex, HTML colspan, and HTML rowspan.
    
    This revision also adds a placeholder appendix section about screen reader reading modes.

**Comment by annabbott** [comment]
Typo in the following (set should have only one t):
Note
    When the above grid navigation keys move focus, whether the focus is sett on an element

**Comment by annabbott** [comment]
Typo in the following (Right, as in Shift + Right, should have only one t):
Fourth bullet under "If a grid supports selection of cells, rows, or columns, the following keys are commonly used for these functions."
Shift + Rightt Arrow: Extends selection one cell to the right.

**Comment by annabbott** [comment]
Typo in the following (Right, as in Shift + Right, should have only one t):
Fourth bullet under "It would be unusual for a layout grid to provide functions that require cell selection. If it did, though, the following keys are commonly used for these functions."
Shift + Rightt Arrow: Extends selection one cell to the right.

**Comment by mcking65** [comment]
@annabbott, thank you for your feedback!! Pushing an update with corrected typos in commit 1689c5a45a7764cca0f09bfede463f4f3710c490
