### ISSUE TITLE
Deprecation of the `meter` pattern

### ISSUE THREAD

**Issue by Sereza7** [w3c/aria-practices#2905]
Hello!

When looking for information on how to make sure my `meter` element is sufficiently accessible, I stumbled on [this pattern](https://www.w3.org/WAI/ARIA/apg/patterns/meter/) in the APG. From what I understand, it goes against [the first rule of ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/meter/examples/meter/), because [HTML](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element) now supports `<meter>` with `min`, `max` and `value` attributes.
From what I could see, the support is also pretty good on browser. 
I am not sure of the state of things for screen readers and other assistive technologies though.

With a confirmation of correct support on ATs, I think it would make sense to remove, deprecate or at least put a warning on this pattern and the example going alongside it.

Thank you!

**Comment by JAWS-test** [comment]
> or at least put a warning on this pattern 

The warning is at every detail page, e.g.: https://www.w3.org/WAI/ARIA/apg/patterns/meter/examples/meter/#support-notice-header (Please press the button "The code in this example is not intended for production environments. Before using it for any purpose, read this to understand why." to open the warning)

**Comment by mcking65** [comment]
@Sereza7 

This is a good question.

Per discussion in today's meeting, we do not plan to deprecate meter or add additional warnings at this time.

Why not deprecate?

APG teaches how to appropriately use ARIA, which includes the meter role. ARIA also includes button, radio, and several other roles that are also exactly replicated in HTML. 

Appropriate usage does include not using those roles unless there is legitimate need as described by the first rule of using ARIA that you reference. That does not mean never use them, so the APG is keeping meter, radio, button, and others in scope.

Why not add another warning?

The [Read Me First](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/), which is prominently placed on multiple pages, covers this. In addition, every example page includes a warning at the top that covers the first rule of using ARIA. For now, the task force believes this is sufficient.

For more information on the purpose and goals of the APG, see [Introduction | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/about/introduction/).

Note also that the APG task force backlog includes:
1. Integrating more of "Using ARIA" into APG (#2675)
2. Start adding examples of patterns that use minimal ARIA

These are longer term goals that currently do not have timelines.

If this does not fully address your question, feel free to re-open the issue with additional comments.

**Comment by Sereza7** [comment]
Thank you very much for your in-depth answer!

I agree with your logic and look forward to evolutions of the APG :)
