### ISSUE TITLE
No accessibility API in text input element "Editable Combobox With Both List and Inline Autocomplete Example" pettern.

### ISSUE THREAD

**Issue by TokugawaTakeshi** [w3c/aria-practices#2933]
I has been complained by [pa11y](https://www.npmjs.com/package/pa11y) accessibility checker about `input` element of [Editable Combobox With Both List and Inline Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/) patten:

> This text input element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
> This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.

If something wrong with **pa11y**, I'll open the issue in **pa11y** and mention this one.

**Comment by stevefaulkner** [comment]
The automated tool is incorrect. The example has an accessible name provided by a label element


```
<label for="cb1-input">State</label>
<div class="combobox combobox-list">
  <div class="group">
    <input id="cb1-input"
```

**Comment by TokugawaTakeshi** [comment]
I am sorry, it was neither because of your example not because of accessibility checker.
I have not use the `label` and thought that some attribute is missing at `input`.  

I apologize for the trouble.
