### ISSUE TITLE
Should radio buttons activate with Enter key when focused?

### ISSUE THREAD

**Issue by ckundo** [w3c/aria-practices#2954]
With regards to https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio/, currently the[ `Enter` key activates the control](https://github.com/w3c/aria-practices/blob/main/content/patterns/radio/examples/js/radio.js#L85) with initial focus. Per the [whatwg spec on implicit submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission), `Enter` key should submit a form. It's confusing then, and maybe incorrect, to capture `Enter` keypress to activate the radio button.

For what it's worth, the default behavior in with native radio buttons -- Chrome at least -- is to only activate on `Space`, whereas `Enter` does submit. See https://codepen.io/ckundo-the-styleful/pen/YzMwPPY

**Comment by mcking65** [comment]
@ckundo, thank you for observing this inconsistency between the example and the pattern and calling it to our attention.

Pull request #2964  removed Enter key handling for checking the radio. It will be live in production on April 9.
