### ISSUE TITLE
Define content for About section that explains how to interpret and use the AT support tables

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-practices#2970]
As part of the improvement to the APG support tables we will include a link to explain the data displayed in the table.

This tasks is to define:
- The location of the link
- The text to be displayed for the link
- The text that will a explain the data displayed on the table.  

Some ideas shared by @mcking65 : 

-  include a link above or below the table to “What does this data mean?” or “How to interpret this data” 
- link should be outside of the iframe, i.e., not part of the content returned by the aria-at query. The link could be to a page in the APG about the specific data surfaced in APG and written to address the APG audience with its specific aims. That page could an APG page

**Comment by boazsender** [comment]
I've written a draft proposal for this language @mcking65: https://docs.google.com/document/d/1QwFgvDYBGGBgMmJCDUUcLdXBWerEmXpKAwFv1_QkMFY/edit

**Comment by boazsender** [comment]
@mcking65 I pushed a new commit on [PR #300](https://github.com/w3c/aria-practices/pull/3000) with an updated draft. You can read it from the [deploy preview](https://deploy-preview-318--aria-practices.netlify.app/aria/apg/about/at-support-tables/).

I'm hoping to work on this a bit more this week and add further guidance, but wanted to push something up and get a gut check. Let me know what you think.
