### ISSUE TITLE
Auditing and merging of relevant dependabot and dependencies related updates

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-practices#2987]
Auditing and merging of relevant dependabot and dependencies related updates.   [practices](https://github.com/w3c/aria-practices/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)

**Comment by ccanash** [comment]
https://github.com/w3c/aria-practices/pull/3022

**Comment by Tlyons46** [comment]
- [x] []()@evmiguel ****
