### ISSUE TITLE
Missing a navigation menu

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#299]
I think a mega navigation menu and hamburger menu, as well as single level drop down navigation menus need to be included. I agree they were way too complicated in the previous version, and understand why they were removed... but it is a huge hole right now in the document, unless I'm missing something.

**Comment by mcking65** [comment]
@DavidMacDonald, 

We already have:

1. [Navigation Menubar Example](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html)
2. issue #159 to Develop navigation menubar example that overloads parent menuitems with a navigationn target.
3. For hamburger type of interactions, we have the [Navigation Menu Button Example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-2/menu-button-2.html)

The guide has not had a mega menu example. We could consider adding one to the release 2 plan. 

One challenge is that mega menus are not really a very well defined concept. Basically, from an ARIA perspective, they are a menubar or toolbar that contains menuitems or buttons that open dialogs that could contain just about anything. In my experience, the dialogs  most commonly contain links. I would recommend the links be in a grid. 

Do you think that we should have a mega menu pattern and example?

**Comment by mcking65** [comment]
@DavidMacDonald, I am closing this as complete based on our work on the menu button and menubar examples for navigation. If you believe these are not adequate and would like to provide more color, please feel free to reopen this issue with more details or raise a new issue with such details.

**Comment by DavidMacDonald** [comment]
The examples provided recommend role="menu" or "menubar", and role="menuitem" which will override the traditional link role. This is a lot of extra code, and a big departure than what users will expect... 

Is this really the direction we want to go? Why not a simple <nav> wrapped around a bunch of links?

**Comment by Decrepidos** [comment]
This thread helps explains the accessibility issues and reasons for consideration.  @DavidMacDonald

https://github.com/accdc/Accessible-Mega-Menu/blob/master/README.md

**Comment by DavidMacDonald** [comment]
Right... here is what they said.
>  The accessible mega menu models its use of WAI-ARIA Roles, States, and Properties after those described in the WAI-ARIA Menu or Menu bar (widget) design pattern with some notable exceptions, so that it behaves better with screen reader user expectations for global navigation. We don't use role="menu" for the menu container and role="menuitem" for each of the links therein, because if we do, assistive technology will no longer interpret the links as links, but instead, as menu items, and the links in our global navigation will no longer show up when a screen reader user executes a shortcut command to bring up a list of links in the page.

. We also want to maintain the semantic structure of the submenu panels in our mega menu; our links are organized into lists and separated by headings. Omitting role="menu" and role="menuitem" for the global navigation seems the safer way to go.

**Comment by Decrepidos** [comment]
A menubar serve a specific purpose in that a menu bar is used to create a consistent set of frequently used commands similar to the typical menu bar interaction in a desktop GUI and the widget as a whole is one tab stop. 

What would be useful is some examples of where a menu of this type may be used as opposed to a standard <nav> with a list of focusable elements generally used for site navigation.
