### ISSUE TITLE
Combobox + Tree Combination Recommendations missing

### ISSUE THREAD

**Issue by dtarjeft** [w3c/aria-practices#2990]
I have a tree structure with nested elements, and each element is eligible for selection. I also need to filter/search those elements. Due to limited space for this control on my site, I thought to do this via a Combobox with a Tree in the dropdown. Unfortunately, there do not appear to be any documented aria standards for this situation. Is this a scenario that we should develop standards for, or should I consider a different approach?

Here is [a Stackblitz](https://stackblitz.com/edit/fb1qcv?file=src%2Fexample.tsx) using Fluent v9, for context.

**Comment by JAWS-test** [comment]
You can combine combobox with tree as described in [ARIA 1.3](https://www.w3.org/TR/wai-aria-1.3/#combobox)

**Comment by dtarjeft** [comment]
Several keys perform actions in both controls. Do you have any recommendations for how these should behave?

**Comment by JAWS-test** [comment]
See chapter "Tree Popup Keyboard Interaction" at https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

**Comment by dtarjeft** [comment]
Perfect! Not sure how I missed this earlier.. thank you.

**Comment by smhigley** [comment]
@dtarjeft that section in the APG is not user-tested and I would not recommend following it in a real-world app without extensive testing. Based on the user testing I've already done on combobox keyboard patterns, my suspicion is that a combobox-tree hybrid is not a practically tenable pattern.

**Comment by mcking65** [comment]
@smhigley  did you re-open this to suggest changes to the pattern?

**Comment by smhigley** [comment]
ah oops, sorry @mcking65 I didn't intend to re-open it. The original poster just mentioned Fluent, so I dropped in just to clarify that I recommend against doing that pattern even in Fluent v9 :D.
