### ISSUE TITLE
Consider autofill

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#300]
These not very good for a11y in the wild ... suggest the Goggle search type autofill

**Comment by mcking65** [comment]
@DavidMacDonald, please edit your comment and add more specifics.

Are you asking for a pattern?

Autocomplete will be covered by the combobox example.

I would also like to include an autocomplete example for completion of terms in a multi-line text field similar to tag completion in this github composer. However, that is not in the scope of our first release.

**Comment by mcking65** [comment]
@DavidMacDonald, closing since there isn't enough detail here. We are working on autofill now in the combobox work. Please reopen and refine if you see fit.
