### ISSUE TITLE
Tab navigation disabled in skip link menu

### ISSUE THREAD

**Issue by iadawn** [w3c/aria-practices#3111]
The skip link menu includes a dropdown menu with additional navigation options.

<img width="259" alt="dropdown menu" src="https://github.com/user-attachments/assets/c1496a61-469d-485a-ac73-f4800fe424ff">

This menu is made available either by pressing the quick key for the Skip link or by pressing the down arrow key when the skip link has focus.

Navigation within the dropdown menu is only possible using the arrow keys.

This goes against the keyboard guidance in the [example disclosure navigation menu](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/#kbd_label) which does not indicate that Tab, Shift + Tab navigation is optional.

**Comment by JAWS-test** [comment]
No bug, it is a menu, navigation is correct: https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/

**Comment by iadawn** [comment]
As a menu, it is quite correct that arrow keys are used for moving through menu items. However, I think menu is the wrong pattern to use for this. It is an in-page navigation aid not an application menu. As such the disclosure navigation menu is much more appropriate to use.

Beyond this, it seems to be a much more involved way to meet 2.4.1 for the user. The terminology on the button is "skip to content". However, that isn't what happens. The button opens a menu that allows the user to skip to parts of the content. And rather than just tab, activate, get to main content the user needs to tab, activate, down arrow, activate, to get to the main content. Perhaps not much but, I would argue, more convoluted. Unless this was tested with users and found to be a much more useful approach?

**Comment by JAWS-test** [comment]
I don't know if it has been tested with users, but I personally find it perfect because I can jump not only to the main content, but to any page area.

**Comment by daniel-montalvo** [comment]
> I don't know if it has been tested with users, but I personally find it perfect because I can jump not only to the main content, but to any page area.

You'd still be able to jump to all of this areas, but instead you would use the tab key, just like in any other navigation menu.

I also find this skip link menu very "screen reader oriented". Screen reader users (especially on Windows) are so used to pressing the down arrow key irrespective of the context. But if you look at this from a keyboard-only user, I totally understand why they find it disconcerting.

**Comment by mcking65** [comment]
It is a menu. first-letter navigation works in it. That is possible only in composite widgets, not in a disclosure. That is an essential feature.

The jump to main item is focused when it opens, so it is not necessary to use the arrow key to jump to main. Just tab and press enter twice instead of once. So, for the "price" of one extra press of enter, you get a ton of additional functionality, including the ability to access it from anywhere on the page with alt+0.

**Comment by mcking65** [comment]
oops, didn't mean to close. If my comment hasn't resolved the issue, please re-open.
