### ISSUE TITLE
Data Grids: keyboard navigation of focusable headers when there are a large number of rows

### ISSUE THREAD

**Issue by craigkovatch** [w3c/aria-practices#3117]
The current [Keyboard Interaction For Data Grids section](https://www.w3.org/WAI/ARIA/apg/patterns/grid/#datagridsforpresentingtabularinformation) makes no particular mention of handling navigation into/out of [columnheader](https://w3c.github.io/aria/#columnheader) cells.

In the [second example of this grid type](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/#ex2_label), focus simply moves from the first data row up into the headers on ArrowUp, and back into the first data row from the header on ArrowDown.

However, in a data grid with a large number of (presumably scrollable) rows, this pattern breaks down. If the user is on row 300 of a 1000-row grid, surely we cannot expect the user to ArrowUp 300 times or ArrowDown 701 times?

How should we handle this case? Perhaps a function key to move up into focusable headers, pressing the same key again to return to the previously-focused cell? Or perhaps both the header row and the grid body should both implement a separate roving tab index pattern, i.e. the grid itself has two tab stops: first for headers, and second for content?

**Comment by mcking65** [comment]
@craigkovatch 

There are commands for going to the top and bottom (ctrl+home and ctrl+end) as well as scrolling by multiple rows.

The TF discussed this today. Minutes above. Net: Building in a function to jump to a specific row would be application specific.

I'm closing the issue, but please feel free to re-open if you think the topic deserves further discussion.

**Comment by craigkovatch** [comment]
Reopening because I think this topic deserves further discussion :) Sorry for late reply, was sick last week.

It seems like the discussion may have misunderstood the issue. I'm not suggesting there's a function to scroll to a specific row. I'm suggesting that's it's incredibly user-unfriendly to have to lose context of the currently-focused row in order to interact with column headers, if there are many rows. A shortcut to jump between headers and "most recently focused non-header cell" should be standardized, even if it's only optional.

Expecting the user to jump tens,hundreds,thousands of rows to get to headers is bad. Also, the discussion assumed that the only interactive function headers will ever have is "sort". This is not the case in our app, where header cells might have an interactive context-menu button inside the cell. Decisions about this proposal should not assume the interactive function of header cells or their content.

Please let me know if any further information, detail, clarification, etc. from me would be helpful.
