### ISSUE TITLE
Adding the the tabs with the action pattern link to tab patten

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#3121]
How about adding exploring [tabs with action pattern ](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-actions/)to [tabs]([url](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)) pattern so that it can be accessible and findable easily from APG site?

**Comment by mcking65** [comment]
@a11ydoer 

The example is experimental. It is not included in the pattern or regular sections of index by design. We don't want it easily discoverable.
