### ISSUE TITLE
Bug: First element in listbox should receive focus

### ISSUE THREAD

**Issue by wagnermaciel** [w3c/aria-practices#3138]
The [Scrollable Listbox Example](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-scrollable/) does not match the behavior described by the [Listbox Pattern Keyboard Interaction](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#keyboardinteraction) docs.

## Expected

According to the docs, "When a single-select listbox receives focus, if none of the options are selected before the listbox receives focus, the first option receives focus."

## Actual

In the example, the listbox itself receives focus.

**Comment by wagnermaciel** [comment]
Fixed by #3139

**Comment by wagnermaciel** [comment]
@mcking65 Are there scenarios where the listbox itself should receive focus instead of the items?

I ask this because while tidying up https://github.com/w3c/aria-practices/pull/3139, I noticed that this behavior was explicit/intentional in some examples.

**Comment by mcking65** [comment]
@wagnermaciel  asks ...

>Are there scenarios where the listbox itself should receive focus instead of the items?
> 
> I ask this because while tidying up #3139, I noticed that this behavior was explicit/intentional in some examples.

This example uses aria-activedescendant, so the `ul` with role `listbox` is the active element, i.e., the listbox is the focused element. There is documentation about aria-activedescendant linked in the table of states and props below the example.

Is that what you were asking about?
