### ISSUE TITLE
[en] Button Pattern - Feedback from APG List

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-practices#3153]
"Hi W3C organization

I am working and researching about web accessibility for 4 years now. I would like to inform you guys that there are no direct indication about button look or appearance. Default buttons styles are not followed by almost all origination. Buttons are very essential for everyday users and strongly focusing on that will be my humble request. I would strongly expect a improvement following the list down below - 
- Buttons should have some indication that it's a button
- Indication of button or the border should have minimum contract ratio, I will suggest same for the link underline.
- Only use of color shouldn't be acceptable if it doesn't pass the minimum contract ratio.

I would love to see changes made for this purpose and if not I will request to have a explanation about that for my learning development. I can provide explaination for my request requirements if needed."

**Comment by mcking65** [comment]
Closing as won't fix.

To summarize the APG task force  position on this issue, the task force considers providing basic accessible visual design guidance for the patterns to be outside the scope of the APG. Visual design guidance is included in the APG only in cases where visual design considerations are a necessary element of an in-scope APG objective and are not provided by another W3C resource that can be referenced by the APG.

The reasoning for this position is partially explained in the [Important Prerequisite Knowledge section of the APG Intorduction](https://www.w3.org/WAI/ARIA/apg/about/introduction/#importantprerequisiteknowledge), which says in part:

>some important aspects of creating accessible experiences fall outside the scope of the APG. This section describes the types of prerequisite knowledge and supporting resources that may enable readers to derive maximum benefit from the APG.


@lolaodelola  please reply to the email thread with this answer.
