### ISSUE TITLE
Review updates to button examples

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#316]
Significant changes to the 
[button example page](http://w3c.github.io/aria-practices/examples/button/button.html) 
were made for issue #189. It is ready for review.

#### Reviews Requested as of March 14, 2017

- [x] Review by @a11ydoer 
- [x] Review by @annabbott 
- [x] Review by @jnurthen

**Comment by annabbott** [comment]
Copied in from issue #189.
Under Toggle Button, the following statement is present:
Mute button uses a a element.
Suggested edit:
Mute button uses an a element.

**Comment by jnurthen** [comment]
Looks good

**Comment by a11ydoer** [comment]
This example looks clear and simple.

**Comment by mcking65** [comment]
Task force reviews are complete for this example. Thank you team! Closing!
