### ISSUE TITLE
Why dialog-modal pattern  don't use HTML <dialog> tag ?

### ISSUE THREAD

**Issue by kult0922** [w3c/aria-practices#3160]
It seems that dialog-modal pattern is not using <dialog> tag.
Is there any reason not to use <dialog> tag?

https://github.com/w3c/aria-practices/tree/main/content/patterns/dialog-modal

**Comment by kult0922** [comment]
I understand, thank you very much!

**Comment by mcking65** [comment]
@kult0922 

Notethat in the case of html dialog element, browsers do not trap focus. So, it does not yet give you the option of creating an actual modal. This is particularly problematic for screen reader users as it is unexpected and confusing to leave a dialog with the tab key. It also reduces navigation efficiency by making the tab ring unnecessarily long.

**Comment by JAWS-test** [comment]
> Note that in the case of html dialog element, browsers do not trap focus.

This sounds as if the keyboard focus goes to the rest of the page outside the modal dialog. However, this is not the case. The focus only goes to the browser and then back to the modal dialog. I don't think this is so problematic - and as far as I know, it was a conscious decision to implement it this way. F6 can also be used to quickly switch between the browser and modal dialog.
