### ISSUE TITLE
breadcrumbs inclusion of the current page

### ISSUE THREAD

**Issue by WW3** [w3c/aria-practices#3189]
Many breadcrumbs' implementations do not include the current page in the trail list, just the parent hierarchies. 
The current breadcrumbs pattern does not address this concern - must a breadcrumbs pattern include the current page?

**Comment by mcking65** [comment]
See #3047 

Closing as duplicate. Feel free to re-open if you think the issue needs additional attention.

**Comment by WW3** [comment]
@mcking65 I don't have the permissions to reopen the issue. 
while https://github.com/w3c/aria-practices/issues/3047 addresses the question how to structure the breadcrumbs' item of the current page - with/out a wrapping anchor, this issue addresses a different question - whether the pattern should assert that the item of the current page is mandatory in the breadcrumbs trail, or not.
