### ISSUE TITLE
Editor Menu Bar Example: Space key does not work correctly for menuitemradio and menuitemcheckbox

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#324]
In the [editor menubar example](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html), 
when focus is on a menuitemradio or menuitemcheckbox and the Space bar is pressed, the state is changed and the menu closes. 

According the to the [menu design pattern](http://w3c.github.io/aria-practices/#menu), 
the menu should close if Enter is pressed, but not if space is pressed. The design pattern says:

* Enter: 
    * When focus is on a menuitem that has a submenu, opens the submenu and places focus on its first item.
    * Otherwise, activates the item and closes the menu.
*  Space: 
    * When focus is on a menuitemcheckbox, changes the state without closing the menu.
    * When focus is on a menuitemradio that is not checked, without closing the menu, checks the focused menuitemradio and unchecks any other checked menuitemradio element in the same group.
    * (Optional): When focus is on a menuitem that has a submenu, opens the submenu and places focus on its first item.
    * (Optional): When focus is on a menuitem that does not have a submenu, activates the menuitem and closes the menu.

**Comment by jongund** [comment]
I made pull request with the updated code that fixes the closing behavior.

One question, should "mouse" clicks on menuitemradio or menuitemcheckbox have the same behavior of not closing the menu, or doesn't the ARIA practices care about mouse interaction?

**Comment by mcking65** [comment]
With merge of pull #340, this issue is now resolved. Thank you @jongund! Closing!
