### ISSUE TITLE
Fix underlining on the treeitems 

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#330]
http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html has underlining on the tree items in the tree (which span all the way across to the edge of the tree).

The CSS was attempting to remove these with 
```
[role="treeitem"],
[role="treeitem"] span {
  margin: 0;
  padding: 0;
  border: 2px transparent solid;
  padding: 0.125em;
  display: block;
}
```
But the CSS in base.css was overriding as the selector was more specific
```
	a[href] {
		color: #034575;
		text-decoration: none;
		border-bottom: 1px solid #707070;
		/* Need a bit of extending for it to look okay */
		padding: 0 1px 0;
		margin: 0 -1px 0;
	}
```

I propose simply adding 2 more specific selectors to the treeitems.css so we would have 

```
a[role="treeitem"],
a[role="treeitem"] span,
[role="treeitem"],
[role="treeitem"] span {
  margin: 0;
  padding: 0;
  border: 2px transparent solid;
  padding: 0.125em;
  display: block;
}
```

**Comment by jongund** [comment]
I fixed this in the latest pull request, now links have simple underlines

**Comment by MichielBijl** [comment]
Fixed per https://github.com/w3c/aria-practices/issues/330#issuecomment-296696436
