### ISSUE TITLE
Remove dependencies on table.css removed in commit 5ea0e2ba10054c6af9aa36491e4fecc0b2aab511

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#338]
@MichielBijl removed redundant css files in commit 5ea0e2ba10054c6af9aa36491e4fecc0b2aab511.
However, there are still references to these files in some examples.
Ensure there are not dependencies and remove any remaining references.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria-practices/commit/b5ba28c893896235299a5274d179d83ce7282514
