### ISSUE TITLE
Open menu should close when user tabs out of menubar

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#346]
- Go to [Navigation Menubar Example](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html)
- Tab to menubar to give focus to About menu item
- Type down arrow to open About menu and give focus to first item, Overview
- Type right arrow to close About menu and give focus to Admissions menu item in menubar
- Type tab. Focus goes to the example 2 menubar's Research menu item, but the Admissions menu stays open.

**Comment by carmacleod** [comment]
Same problem in [Editor Menubar Example](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html)

**Comment by mcking65** [comment]
@jongund verified fixed in Firefox, Chrome, on Mac OS, Firefox on Windows, Chrome on Windows.

**Comment by mcking65** [comment]
Verified fixed in IE as well. Closing.

**Comment by mcking65** [comment]
Issue has re-appeared; re-opening.

**Comment by mcking65** [comment]
Now fixed with commit 2549421. Thank you @jongund!
