### ISSUE TITLE
Update patterns that prescribe use of aria-haspopup to include appropriate mentions of new token values

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#347]
It appears the latest wai-aria spec has changed aria-haspoup="true" to more granular values: 

>... Authors must ensure that the role of the element that serves as the container for the popup content is menu, listbox, tree, grid, or dialog, and that the value of aria-haspopup matches the role of the popup container...To provide backward compatibility with ARIA 1.0 content, user agents must treat an aria-haspopup value of true as equivalent to a value of menu. https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

So shouldn't we provide those values for aria-haspopup?

**Comment by MichielBijl** [comment]
We discussed this during last week’s conference call. Although for some reason I missed the last sentence in your post.

The `true` value isn’t deprecated. Although I do agree that we should at least mention the new values if not replace the old with the new.

Will bring up again now that I’ve actually read your post.

**Comment by mcking65** [comment]
Change title of this issue to reflect needed action.

Following updates are needed:

1. [ ] button design pattern mentions only boolean; should also mention menu token.
2. [ ] Menu and menubar pattern mentions only boolean; should also mention menu token.
3. [ ] Menu button pattern mentions only boolean; should also mention menu token.
4. [ ] Tabs pattern mentions only boolean; should also mention menu token.

Note: combobox pattern already describes use of new token values.

**Comment by mcking65** [comment]
@DavidMacDonald, This is resolved with commit 878d9b7.
