### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#351]
In the section on [live regions] (https://www.w3.org/TR/wai-aria-1.1/#dfn-live-region) there is a link to special cases of live regions which is dead.

**Comment by MichielBijl** [comment]
@DavidMacDonald thank you for the report. Although I’d argue this is one for the [ARIA repo](https://github.com/w3c/aria/issues).

**Comment by MichielBijl** [comment]
Duplicate of https://github.com/w3c/aria-practices/issues/280
