### ISSUE TITLE
menu item widths inconsistent

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#355]
feedback from @carmacleod in #144 

Looking at http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html

Checked items in the menu do not have the same width as non-checked items.
They are missing a rectangular piece from the right hand side of the item that seems to have about the same width as the (left-aligned) checkmark.
This makes a dropped-down menu look "staggered", like a vertical stack of 2 x 4 Lego bricks that has some (left-aligned) 2 x 3 Lego bricks in it.

**Comment by jongund** [comment]
Creating the branch menubar-issue324 and having me pull that into my clone of aria-authoring practices has got me very confused on what the state of my repository is and how I get things back into the w3c repository.   Can you clear all my pull requests as soon as possible and I will start again on fixing the remaining menubar issues.   I will gut checkout a new copy so I can get reoriented to how to get code back into the w3c repository.

**Comment by carmacleod** [comment]
@jnurthen I believe the previous comment re "clearing Jon's pull request backlog" was meant for you.

**Comment by mcking65** [comment]
@jongund, sorry that was somehow confusing.

The issue #324 changes are now merged into master, and I have deleted the menubar-issue324 branch.

If you just update your fork and make a new branch from master for your issue 355 changes, you will be building on the latest.

Then, when you submit a PR for issue 355, choose w3c/aria-practices/master as the base branch for the pull request.

Update your fork as described on our 
[wiki page about pull requests](https://github.com/w3c/aria-practices/wiki/Submitting-Pull-Requests) 
under the "Synnc Your Fork" heading:

1. git fetch -p w3c 
2. git checkout master 
3. git merge w3c/master 
4. git push origin 

This assumes the remote for your fork is named "origin" and the remote for the w3c repo is named "w3c". The wiki page describes those assumptions in more detail.

**Comment by mcking65** [comment]
@jnurthen, @carmacleod, 

With the latest commit, is this issue resolved?

**Comment by carmacleod** [comment]
Yes, the menus are the correct width now. You can close this issue. Thanks!

**Comment by mcking65** [comment]
Excellent, thanks @carmacleod! Closing.
