### ISSUE TITLE
bin/generate <name> produces error

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria-practices#358]
According to the readme we should be able to do:
```bin/generate treegrid```

But I get this error:
```cp: examples/coding-template/template3.html: No such file or directory```

**Comment by aleventhal** [comment]
@mcking65 We need to update the instructions?

**Comment by mcking65** [comment]
The way we are working now, there is not much utility in the bin/generate script. I am removing it.

**Comment by mcking65** [comment]
Resolved with commit 155605d; removed the script.
