### ISSUE TITLE
Revise menu button pattern guidance for aria-expanded based on resolution of feedback issue 326

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#362]
Per conclusions reached in issue #326, revise the 
[menu button pattern](http://w3c.github.io/aria-practices/#menubutton) 
text to recommend that:

1. When the menu is not displayed, do not apply aria-expanded to the button.
2. When the menu is displayed,  set aria-expanded to true. 

#### Revision Status 

As of April 26, 2017 with commit dc12564, the [menu button pattern](http://w3c.github.io/aria-practices/#menubutton) 
is revised per the above.

#### Reviews requested as of April 26, 2017

- [x] Review by James (@jnurthen) 
- [x] Review by Ann (@annabbott)

**Comment by annabbott** [comment]
See comment in  #326

**Comment by mcking65** [comment]
Resolved feedback from @annabbott in 4db52a2 . Thank you for reviews. Closing
