### ISSUE TITLE
Revise menu button examples to implement updated guidance for aria-expanded that resulted from feedback in issue 326 

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#363]
Per issue #326, Revise the [actions menu button example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-1/menu-button-1.html) 
and the [navigation menu button example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-2/menu-button-2.html) 
so that they implement aria-expanded as follows:

1. When the menu is not displayed, do not apply aria-expanded to the button.
2. When the menu is displayed,  set aria-expanded to true.

**Comment by jongund** [comment]
Updated the examples to remove aria-expanded when menu is closed in latest pull request

**Comment by mcking65** [comment]
Commit 35cd0b9 resolves this issue. Closing.
