### ISSUE TITLE
Navigation Tree View examples: enter key and modifier keys are not correctly handled

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#364]
Resolve the following bugs in the handleKeydown function in treeview/treeview-2/js/treeitemLinks.js:

1. It incorrectly captures printable char keys that are pressed in combination with ctrl, alt, or meta modifiers. Such key events should be allowed to propagate.
2. It should allow any keydown event where alt or meta modifier is pressed to propagate.
3. At least in Firefox and Chrome, the enter simulation of click does not work.
4. It does not support ctrl+enter or shift+enter functionality (ctrl+click or shift+click) for opening in new tab or new window.

**Comment by jongund** [comment]
Fixed this bug and is part of current pull request

**Comment by mcking65** [comment]
Thank you @jongund! 
Left arrow and most modifier key issues are fixed now with pull #374.

It still appears to me that enter, ctrl+enter, and shift+enter do not work in Firefox Or Chrome.

Also, if Shift is typed with a printable char, the key press is ignored. I believe that we should be allowing shift with printable chars so that if a tree item starts with a cap or with something like $ that the typeahead will still work.

**Comment by jongund** [comment]
Matt,

I will look into this issue.

Jon

**Comment by jongund** [comment]
Matt,

I think I got the following link features working for treeview for enter, ctrl+enter, and shift+enter.

I will go back and check updates for the menu button and menubar examples related to links.

Jon

**Comment by jongund** [comment]
Matt,

In the current menu button pull request I have also fixed the same problems found with treeview for ignoring certain combinations of modifier keys and for following links with the return key + modifier keys.

Jon


Jon Gunderson, Ph.D.
Coordinator
Accessible IT Group
Disability Resources and Education Services
College of Applied Health Sciences
University of Illinois at Urbana-Champaign

E-mail: jongund@illinois.edu
WWW: http://disability.illinois.edu/academic-support/aitg

**Comment by mcking65** [comment]
With pull 377, this issue is now fixed. Thank you @jongund!
