### ISSUE TITLE
Tree View Examples: Fix Incorrect Left Arrow Behavior

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#365]
In all four treeview examples, if focus is on a child node and left arrow is pressed, focus moves to the parent and the parent node is closed. In this circumstance, the focus should move but the parent node should remain open. A parent node should close only if focus is on the parent node when left arrow is pressed.

**Comment by jongund** [comment]
I made a pull request this morning that I believe fixed the bug with left arrow key collapsing the leaf when not on an expandable treeitem.

**Comment by mcking65** [comment]
@jongund, this bug is indeed fixed with pull #374. Many thanks!!

**Comment by mcking65** [comment]
@jongund, Oops, this issue is not quite resolved. 

If the focus is on a level two or deeper parent node that is closed, pressing left arrow moves to the parent of the parent node and closes the branch. For example, in the 
[file viewer tree](http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html), 
navigate to reports, expand with right, move down to the first child (reports-1), then press left arrow. Focus moves to the reports parent, like it should. However, the reports branch also closes, which it should not.

**Comment by jongund** [comment]
Matt,

I used the left arrow key to move focus from one of the lowest level treeitems to its parent treeitem and it just moved focus to the parent for me and did not close the leaf with the child treeitems.

I press left arrow again then it closed the leaf.

I tired if for all the examples:
http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html
http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html
http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html
http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html


Jon

**Comment by mcking65** [comment]
@jongund, the problem only occurs if the focus is on a level 2 or greater parent node that is closed as I described above. In the structures we have in the examples, this condition only exists for the immediate children of the reports and letters branches in the file viewer trees.

**Comment by jongund** [comment]
Matt,

I see it now and will fix it.

Jon

**Comment by jongund** [comment]
Matt,

I understand the bug now and it should be fixed in the latest pull request.

Jon

**Comment by mcking65** [comment]
@jongund, thank you!! this is now fixed.
