### ISSUE TITLE
File Directory Tree View examples: modifier keys are not correctly handled

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#367]
Resolve the following bugs in the handleKeydown function in treeview/treeview-1/js/treeitem.js:

1. It incorrectly captures printable char keys that are pressed in combination with ctrl, alt, or meta modifiers. Such key events should be allowed to propagate.
2. It should allow any keydown event where alt or meta modifier is pressed to propagate.

**Comment by mcking65** [comment]
Thank you @jongund! This bug is almost fixed.

The one issue that remains is that if only shift is held when typing a printable char, the key press is ignored. This breaks typeahead for chars like !, @, #, $, ., etc.

**Comment by jongund** [comment]
Matt,

It should be fixed now.

Jon

**Comment by mcking65** [comment]
With pull 377, this issue is now fixed. Thank you @jongund!!
