### ISSUE TITLE
Review revised Actions Menu Button Example Using element.focus()

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#382]
The 
[actions button menu example using element.focus()](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html) 
has been significantly revised and needs additional task force review

#### Reviews requested as of April 26, 2017

- [ ] Review by @a11ydoer (Jemma)
- [x] Review by @annabbott (Ann)
- [x] Review by  @jnurthen (James)
- [ ] Review by @shirsha (Siri)

**Comment by jnurthen** [comment]
I was going to comment on the fact that you don't set tabindex=0 on the focused node as normally needed when using roaming tabindex but realized that this is completely unnecessary in this example. Looks good.

**Comment by annabbott** [comment]
Keyboard support > Menu: Space does not perform as documented. It does activate the menu item, causing the "Last Action" textbox to be updated, then momentarily closes and reopens the menu with focus set to Action 1.

**Comment by annabbott** [comment]
Keyboard support > Menu: A-Z or z-a A-Z and a-z does not perform as expected and there is a typo in the first bullet:
    Moves focus to the next menu item with a lable (typo: should be label) that starts with the typed character if such an menu item exists.
    Otherwise, focus does not move.

Pressing A-Z and/or z-a does move focus to the typed character, but closes the menu. Same issue as in #384

**Comment by annabbott** [comment]
"Menu Button Design Pattern in WAI-ARIA Authoring Practices 1.1" has incorrect target. Should be http://w3c.github.io/aria-practices/#menubutton and not https://w3c.github.io/#menubutton

**Comment by mcking65** [comment]
All feedback has been addressed. The outstanding space key bug is tracked in issue 403. In the mean time, space key documentation has been removed since supporting it is optional in the menu. Closing the issue.
