### ISSUE TITLE
Review revised Actions Menu Button Example Using aria-activedescendant

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#383]
@jongund added a third menu button example:
[actions menu button example using aria-activedescendant](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html) 
that is now ready for task force review.

#### Reviews requested as of April 26, 2017

- [x] Review by @annabbott (Ann)
- [x] Review by @a11ydoer (Jemma)
- [ ] Review by @shirsha (Siri)
- [x] Review by @jnurthen (James)

**Comment by a11ydoer** [comment]
@mcking65 
Review is done.

**Comment by annabbott** [comment]
Keyboard support > Menu: Space does not perform as documented. It does activate the menu item, causing the "Last Action" textbox to be updated, then momentarily closes and reopens the menu with focus set to Action 1.

Tested using Win10/FF 53.0

**Comment by mcking65** [comment]
All feedback has been addressed except for the space key bug, which is being tracked by issue 403. In the mean time, documentation of space key functionality is removed since support for it is optional in the menu. Closing this review.
