### ISSUE TITLE
Treeview Examples: fix incorrect right arrow behavior

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#385]
In all four treeview examples, if focus is on a parent node and the parent node is expanded, pressing right arrow does nothing. Focus should move to the first child. Right arrow should do nothing only if focus is on an end node.

This is related to issue #365.

**Comment by jongund** [comment]
This should be fixed now in all three examples

**Comment by mcking65** [comment]
@jongund, thank you! Your changes in pull #390 are great. I merged; closing.
