### ISSUE TITLE
A button-example needs a moment's attention.

### ISSUE THREAD

**Issue by wetlife** [w3c/aria-practices#393]
- The print button has no tabindex attribute specified as claimed.
  - Insert the text ''' role="button" '''' and reflect this in the html-source shown on the page to fix this bug.
  - [Here is the page I refer to.](https://www.w3.org/TR/wai-aria-practices/examples/button/button.html)

**Comment by mcking65** [comment]
@wetlife, Thank you for the feedback.

Significant work has been done to the 
[button example page](http://w3c.github.io/aria-practices/examples/button/button.html) 
in the editors' draft, and this problem was addressed.
