### ISSUE TITLE
Using aria-label in treeview-1a is not necessary according to spec and Firefox implementation

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria-practices#395]
Regarding this example:
https://rawgit.com/w3c/aria-practices/master/examples/treeview/treeview-1/treeview-1a.html 

Quick version: the aria-label is extraneous and is hiding a bug in Chrome.

Long version:
The example says that using this tree allows the browser to compute the level, setsize and posinset automatically for you. However, this type of tree should also auto compute the treeitem names.

The treeitem names should be computed from descendants that have nameFrom: contents.

Indeed, if you take the aria-label attributes out, the example still works in Firefox, which gets the name calculation correct. However, in Chrome, there is a bug, and the name of tree items includes descendant treeitem text. The name calc is not supposed to walk into those descendants where nameFrom != contents. Therefore, anything inside the role="group" element is supposed to be ignored when computing the name.

Was the aria-label included to work around current user agent bugs?

**Comment by mcking65** [comment]
The name calc does not say anything about excluding groups from the name from content. This is intentional as required by the spec.

The bug is related to owned, not contained.

**Comment by aleventhal** [comment]
@mcking65, thanks for looking into this. in my reading of the name calc it covers this case. Here's where: F.iii talks about accumulating text of children. However, to get to F.iii you have to pass through F, which says "Otherwise, if the current node's role allows "Name From: contents", or if the current node is referenced by aria-labelledby, aria-describedby, or is a native host language text alternative element:"
A <div role="group"> is none of those things, because it is NameFrom: auth

Historical note: I actually wrote the initial draft of the name calc to match the initial ARIA implementation in Firefox. The specs, name calc and Firefox implementation were designed to handle this use case. And we had a tree example that took advantage of it.

Also, what do you mean by, "The bug is related to owned, not contained." -- I didn't understand that bit.

**Comment by jnurthen** [comment]
@aleventhal see related aria issue https://github.com/w3c/aria/issues/538 and chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=702811
I think your input would be very valuable in both of those.

**Comment by mcking65** [comment]
If stopping at a contained group when gathering content for a name is the intention, I like that. I need to read the algorithm again.

**Comment by jongund** [comment]
Removed aria-label from menubar examples

**Comment by mcking65** [comment]
@aleventhal, thank you for raising this issue. 

With the above listed commits, we have made appropriate updates to the menu and tree patterns and examples. Guidance to add aria-label to parent nodes is removed and the code is updated.
