### ISSUE TITLE
Work on orientation for tabs

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#40]
As discussed during telecon.

Also, when working on this, fix up/down arrow key problem described in issue #14.

**Comment by mcking65** [comment]
This issue is addressed in commit 424776b and can now be viewed in master at:
http://w3c.github.io/aria-practices/#tabpanel

Feedback is welcome!

**Comment by mcking65** [comment]
Change 2nd bullet:
"When focus is on a tab element: "
To
"When focus is on a tab element in a horizontal tab list: "
And then separate the non-arrow key bullets out from that sublist.

**Comment by mcking65** [comment]
This issue is now fully resolved with the addition of commit aeab2e1457868976c6b7f09a3b183410dc364ff5
