### ISSUE TITLE
Accordion Example: Ctrl-PageUp and Ctrl-PageDown do not work and unused modified keys are trapped

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#400]
In the [accordion example](http://w3c.github.io/aria-practices/examples/accordion/accordion.html):
- [x] ctrl-PageUp and ctrl-PageDown are not captured by the JavaScript so focus moves to a different browser tab.
- [x] Modifiers are not handled correctly so unused keys are being captured. For instance, alt+left/right do not work when focus is in the accordion. Only keys that are used should be captured.

@gerardkcohen, I am hoping you can help resolve this issue.

**Comment by gerardkcohen** [comment]
@mcking65 I can most certainly take care of this

**Comment by gerardkcohen** [comment]
@mcking65 I have been working to get the ctrl-pageup/down combination to work and I am finding that it does not fire consistently across browsers. Testing against other examples that have attempted to implement this combination as well as generic keyboard event libraries and seeing the same thing. Chrome, for example, does not even fire the event for me to capture. As long as this combination has been part of the pattern, not sure it can be changed but the difficulties across browsers/ platforms may be the reason while it is rarely adopted. I did test with adding SHIFT, e.g. CTRL+SHIFT+PAGEUP/DOWN and that does fire properly. Thoughts?

**Comment by DaveBagler** [comment]
@mcking65, @gerardkcohen, have you found a solution for ctrl-page up/down or do you think it's best to use the SHIFT workaround?

**Comment by mcking65** [comment]
@DaveBagler, we've pushed this to the back burner for now. Those keys are marked optional. That said, we could at least figure out the eventual way forward.

One problem with patterns like this one is that there is no native desktop equivalent of an accordion. So, for the type of functionality we are talking about in this issue, there are no existing conventions.

Part of the rationale for ctrl-pgup/down was that it is a familiar key command for moving among tab panels, and accordions are kind of like tab panels. While it conflicts with browser tab commands, browsers have duplicate keys for that command, e.g., ctrl+tab moves focus among browser tabs.

Some implementations of accordions in the wild use ctrl+up/down arrows for this function. However, that doesn't work if focus is in a text area inside the accordion panel.

We could consider using ctrl+shift+pgup/down or possibly alt+pgup/down. Neither has the advantage that users may discover it via experimentation. They'll always drive documentation of some kind. There isn't even a good place to reveal the key assignment for this function with aria-hotkeys.


As always, the task force is open to ideas. I can add this to our meeting agenda for next week so we at least get a plan in place and edit the pattern accordingly.

**Comment by DaveBagler** [comment]
Thanks for the update @mcking65. I think I'll end up needing to pick something.  I'll report back if we end up with something that works well.

**Comment by mcking65** [comment]
Retested alt+left, alt+right, alt+d, and all work correctly when focus is inside accordion, either on headers or in the input elements.

Tested in both Firefox and Chrome.

Closing as resolved.
