### ISSUE TITLE
Actions Menu Button Examples: Space key does not work correctly in Firefox

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#403]
Per feedback from @annabbott in issues #382 and #383, when using Firefox 53, space key does not work correctly in the action menu button examples:
1. [Actions Menu Button Example Using element.focus](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html)
2. [Actions Menu Button Example Using aria-activedescendant](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html)

When focus is on a menu item, pressing space performs the action but then focus is placed on action 1 instead of on the menubutton and the menu does not close.

Space key support should be either removed or made to be the same as enter key.

If space key support is made to be the same as enter, then restore the documentation for it that was removed in commits fcb8d0a and 6e2f217.

**Comment by jongund** [comment]
It seems that this problem has already been fixed.  If the problem still exists, what exactly is the SPACE key doing or not doing in the examples.   I cannot tell from the documentation in the issue.   As far as a I can tell the SPACE and the ENTER key are behaving the same in the Menu Button and the Menu.   What is suppose to be different in the SPACE key?

**Comment by mcking65** [comment]
@jongund commented:

> It seems that this problem has already been fixed. 
> If the problem still exists, what exactly is the SPACE key doing or not doing in the examples. 
> I cannot tell from the documentation in the issue. 
> As far as a I can tell the SPACE and the ENTER key are behaving the same in the Menu Button and the Menu. 

Jon, Space does not work correctly in Firefox 56. Enter and Space work the same in IE and in Chrome on both Win and Mac.

I adjusted the title of the issue accordingly.

**Comment by jongund** [comment]
The problem with Firefox is related to changing the state of aria-expanded on the menu button.  For some reason when you change the value of aria-expanded it generates an onclick event on the menu button which in the case of this bug opens the menu.

Not sure what to do about this for the example, but it is certainly a bug in Firefox.

**Comment by mcking65** [comment]
Resolved with commit bc0416e and thanks to @jongund!!
