### ISSUE TITLE
Tree view examples: Disable default focus ring and implement hover and focus states in css

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#404]
In the four tree view examples:

1. Disable default custom focus indicator
2. Per [May 8, 2017 comment by Michiel in issue 223](https://github.com/w3c/aria-practices/issues/223#issuecomment-299937648), instead of applying classes with js, use :hover and :focus to implement the custom focus and hover styling.
3. Update documentation in the accessibility features section of the example pages.

**Comment by jongund** [comment]
Removed default keyboard focus styling when focus is on a tree item

**Comment by mcking65** [comment]
With commits ba5cf02 and b5400fb, this issue is now resolved.
