### ISSUE TITLE
Navigation tree view examples: Plus/Minus characters are being read by screen readers

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#406]
In the navigation tree examples:
1. [Navigation Treeview Example Using Computed Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html)
2. [Navigation Treeview Example Using Declared Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html)

The generated content used to display plus and minus symbols is being read by screen readers. It comes from the css content properties:
* content: "\00229E \0000A0";
*   content: "\00229F \0000A0";

Another method, such as that used in the accordion and breadcrumb examples, or an image is needed so the visual indicators are not read.

**Comment by jongund** [comment]
Fixed in lastest pull request

**Comment by mcking65** [comment]
Thank you @jongund, this issue is resolved by commit ba5cf02.
