### ISSUE TITLE
Include aria-labelledby on the tabpanel

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#41]

**Comment by mcking65** [comment]
Work on this with issue #41.

**Comment by mcking65** [comment]
This issue is addressed in commit 424776b and can now be viewed in master at:
http://w3c.github.io/aria-practices/#tabpanel

Feedback is welcome!

**Comment by mcking65** [comment]
Closed pre review in the August 22, 2016 meeting.
