### ISSUE TITLE
KeyBoard navigation for xOS

### ISSUE THREAD

**Issue by jivanova** [w3c/aria-practices#413]
Currently, my team is working to improve the keyboard navigation for our web component based on w3c standards. I have a question regarding a note we saw in your documentation: 

[https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex)

The note is about the usage of **Control** key instead of **Cmd** under Mac OS. However, our products have shortcuts like **_Control + ArrowRight_** which in MAC is reserved shortcut for switching between desktops. According to your guidelines, should we use **Cmd** key for this scenario or **Control** and modify our shortcuts? So, what's your advice about how to proceed with such scenarios?

**Comment by mcking65** [comment]
@jivanova, in the above listed commits, I have made several changes that I hope adequately address this issue.

I am closing as resolved. Please feel free to reopen if you do not see the resolution as adequate. You may also provide feedback in issue 484.
