### ISSUE TITLE
ARIA 1.1 ALERT EXAMPLE

### ISSUE THREAD

**Issue by zbolena** [w3c/aria-practices#414]
Hello,

Using JAWS 18 & IE v11/Chrome v59.

ARIA 1.1 Alert Example: [http://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/alert/index.html](url)

When the "Trigger Alert" button has been activated with the enter key the alert messaging is not read until the enter key is pressed again. 

The focus does not immediately redirect to the alert container after the button has been activated so the alert messaging is not read by the screen reader. 

I added the following code which enables JAWS to immediately read the alert dialog after the "Trigger Alert" button has been activated since the alert container is focusable and a focus method has been added into the JavaScript.

**HTML:** Added a tabindex="0" to the "id=example" alert container to make it focusable. 

`<div tabindex="0" id="example" role="alert"></div> `

**JavaScript:** Added a new line using focus() method using document.getElementById('example') after "example.innerHTML = template;"

`document.getElementById('example').focus();`

**Comment by mcking65** [comment]
Hi @zbolena 
zbolena,

Thank you for the feedback. 

I think you may be confusing alert with alert dialog. They are separate patterns.

The alert design pattern describes the purpose of the alert role:

> An alert is an element that displays a brief, important message in a way that attracts the user's attention without interrupting the user's task. Dynamically rendered alerts are automatically announced by most screen readers, and in some operating systems, they may trigger an alert sound.

The pattern also includes the following:

> Because alerts are intended to provide important and potentially time-sensitive information without interfering with the user's ability to continue working, it is crucial they do not affect keyboard focus. The > alert dialog is designed for situations where interrupting work flow is necessary.

The first paragraph of all the example pages includes a link to the corresponding design pattern documentation.

We have an issue for enhancing this example to make it a little more realistic with respect to how the alert is triggered.

If this does not address your question or concern, please feel free to re-open the issue.
