### ISSUE TITLE
Menu button: and aria-haspopup suggestion for clarity and improved implementation

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#415]
**Menu button:** as described in the menu button pattern, a button is revealed to assistive technologies as a menu button if it has the property aria-haspopup set to true.

I recommend adding:

_aria-haspopup must be implemented on the triggering element._ 

**Reason:** A common mistake I see repeatedly is the attribute being placed on the parent of the triggering element..

**Comment by mcking65** [comment]
@Decrepidos, in the most recent version of the [menu button pattern](http://w3c.github.io/aria-practices/#menubutton),
under roles, states, and properties, it says:

> * The element that opens the menu has role button.
> * The element with role button has aria-haspopup set to either menu or true.

Does this adequately address your concern?

I see you were quoting the [button pattern](http://w3c.github.io/aria-practices/#button), where it says:

> * Menu button: as described in the [menu button pattern](http://w3c.github.io/aria-practices/#menubutton), a button is revealed to assistive technologies as a menu button if it has the property aria-haspopup set to either menu or true.

In that text, there is a link to the above mentioned menu button pattern that clearly states the requirements. Also, the antecedent of "it" is clearly the button element itself. It seems awkward to change it to:

> * Menu button: as described in the [menu button pattern](http://w3c.github.io/aria-practices/#menubutton), a button is revealed to assistive technologies as a menu button if the button element has the property aria-haspopup set to either menu or true.

We wouldn't add another sentence that essentially says not to put the aria-haspopup on an element other than the button element. As an editorial practice, we are careful to avoid anti-patterns as they tend to lead to bottomless pits that end up substantially weighing down the guide.

Does this seem reasonable to you?

**Comment by Decrepidos** [comment]
Yes it does. Thank you.

**Comment by mcking65** [comment]
YW! And, thank you for the feedback.
