### ISSUE TITLE
Breadcrumb mark-up clarification

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#416]
**Breadcrumbs**
WAI-ARIA Roles, States, and Properties

**In response to:** Breadcrumb trail is contained within a navigation landmark region.
The landmark region is labelled via aria-label or aria-labelledby.
The link to the current page has aria-current set to page

The current statement implies that aria-current=page is the only option for a breadcrumb trail. This is a. incorrect. and b. I do not believe the page value is the best option in this case.

**Reason:** The breadcrumb trail's original purpose, and I do not believe this is changed, is to give the user a sense of location in the site in relation to the landing page. This may be the site home page; however, it could as easily be the trail path to the landing page of the section.

Because of this I suggest using aria-current=location for breadcrumbs. aria-current=page is more suited to navigation blocks.

Additional thought: Although this depends on the interpretation of the `<nav>` element, I would not wrap a breadcrumb in a nav and neither would I add a label. 
This is overkill - was expressed in a conversation I had recently with a blind developer on this topic.

**Comment by MichielBijl** [comment]
We [discussed this on Twitter](https://twitter.com/MichielBijl/status/902854363617656837). Current implementation is fine.

If you still think this is an issue please let me know.
