### ISSUE TITLE
Accordion triggering element (Button)

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#417]
A couple of thoughts:

**Accordion triggering element (Button)**
WAI-ARIA Roles, States, and Properties

In response to: If the button is a toggle button, it has an aria-pressed state. When the button is toggled on, the value of this state is true, and when toggled off, the state is false.

Reason: aria-pressed is not included in the accordion design pattern.

I suggest the following be added to the spec for clarity.

The difference between a button that toggles and does nothing else, like Enable Cookies, where the value is true or false, as opposed to a button that expands or collapses another visible section on the page. The first would be best suited to use aria-pressed, whereas the second is best suited to use aria-expanded. Therefore, if a toggle button contains a mechanism to convey the state of the button to the user i.e. aria-expanded, aria-pressed can be omitted.

**Comment by mcking65** [comment]
@Decrepidos, your suggestion is not clear to me.  

Currently, the accordion pattern does not mention aria-pressed.  Are you suggesting that we say why not to use aria-pressed?

The task force has made a decision to avoid anti-patterns and guidance on what not to do in design patterns. 

However, our road map does include a plan to write guidance for the use of each state and property. That section will be all about decision making, e.g., which property is most appropriate when considering similar properties. We do not yet have a draft of that section.

**Comment by Decrepidos** [comment]
Sorry for late reply just got home from holiday to Italy and France. The suggestion was because pressed and expanded used to be recommended. However, avoiding anti-patterns seems a better idea. I look forward to the draft when it is complete.

**Comment by mcking65** [comment]
Thank you @Decrepidos, we will address this when working on issue 254, referenced above. Closing this issue; feel free to reopen if this is not adequate.
