### ISSUE TITLE
Under Accordion:  landmark region proliferation

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#418]
More thoughts ...

In regards to: Avoid using the region role in circumstances that create landmark region proliferation, e.g., in an accordion that contains more than approximately 6 panels that can be expanded at the same time.

Running JAWS on the accordion example I notice that the labelledby panel regions are only announced if the panel is expanded because of the hidden="" on the panel container which contains the region. This voids the ‘region’ proliferation statement.

**Comment by jnurthen** [comment]
In the example only 1 accordion panel can be open at a time. The statement

> Avoid using the region role in circumstances that create landmark region proliferation, e.g., in an accordion that contains more than approximately 6 panels that can be expanded at the same time.

is to avoid using region IF there are more than 6 panels AND then can be expanded at the same time. if multiple panels are expanded they would NOT have hidden applied.

I don't think a change is needed here but if you disagree please suggest something to resolve to your satisfaction.
