### ISSUE TITLE
Complete editorial updates to Dialog (Modal) design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#42]
- [x] Rewrite second sentence of first paragraph
- [x] Clarify "trap" focus; replace with more clear language about tab sequence.
- [x] Remove bullet for enter key from keyboard interaction
- [x] Remove note on pressing the escape key
- [x] Fix editorial consistency issues in sections on keyboard and roles/states/properties.
- [x] Add further guidance about initial focus. Address when content is large and first focusable element would cause top of content to scroll out of view. Possibly include note stating initial focus should go to the least destructive action, e.g., like in confirmation dialogs.

**Comment by mcking65** [comment]
This work is now complete and the review process is started in issue 325.
