### ISSUE TITLE
Add paragraph discussing implications for Mobile

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#420]
My understanding is that although some (or many) of these pattern may work for mobile, they have not been tested or designed with mobile in mind. This is important because most sites these days are responsive, and authors may wrongly assume that if they use these patterns for their mobile break points they will work on VoiceOver or TalkBack.

I also think these patterns should be tested on both iOs with VoiceOver and Android with TalkBack, and add a field to each pattern that basically says "Tested and works for mobile break points: YES" or "NO".

**Comment by mcking65** [comment]
We have included a paragraph about this in the read me first section and the idea of marking each example with some kind of mobile compatibility information is covered by #8. Closing as duplicate.
