### ISSUE TITLE
Landmark AT Example page using percentage based image widths

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#427]
Found this running the Nu validator https://travis-ci.org/w3c/aria-practices/builds/253487231#L418
Looks like those widths need to be in pixels in HTML5 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-width

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria-practices/commit/e3547be1243455697e6dfac62a21a96112e97d5e

**Comment by nschonni** [comment]
Technically the PR hasn't landed, but the changes look 💯

**Comment by MichielBijl** [comment]
Discussed the change I made yesterday with @jnurthen and he approves.
