### ISSUE TITLE
Menu Button examples using role=none on `<li>` elements flagged by the Nu Validator

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#432]
https://github.com/w3c/aria-practices/blob/master/examples/menu-button/menu-button-links.html#L59-L84
Not sure if this is a Validator issue, or an issue with the examples

**Comment by jnurthen** [comment]
Logged https://github.com/w3c/html-aria/issues/78 against HTML in ARIA which the validator uses for its rules

**Comment by mcking65** [comment]
I see that w3c/html-aria#78 is closed. Has the validator been updated?

**Comment by nschonni** [comment]
The spec commit https://github.com/w3c/html-aria/commit/f36423affee6ed698976565a821bcb17879a2ae1 landed at the end of September, but I don't see anything in the validator commits that seem to corrispond

**Comment by jnurthen** [comment]
https://github.com/validator/validator/issues/581 logged against validator

**Comment by mcking65** [comment]
Closing with assumption that @sideshowbarker will update validator accordingly.

**Comment by sideshowbarker** [comment]
I’ve fixed this in the HTML checker and pushed the fix to https://validator.w3.org/nu/
