### ISSUE TITLE
Marquee information at http://w3c.github.io/aria-practices/#chobet is incorrect

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#44]
Marquee implicit live value does not reflect the spec at http://w3c.github.io/aria/aria/aria.html#marquee

**Comment by jnurthen** [comment]
Status looks like it needs checking too.

**Comment by mcking65** [comment]
This issue is resolved by previous commit. 

Additionally, commit eabf6ca5a102af42f876ff4856e92c85b735cecd removed the section on live regions until it can be rewritten per issue #78 .
