### ISSUE TITLE
Spinbutton Pattern does not state home and end are not needed when min and max are not known

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#446]
Per feedback from @MichielBijl in today's Practices teleconference, The [Spinbutton pattern](http://w3c.github.io/aria-practices/#spinbutton) 
keyboard guidance says home set the min and max value, but do not state that this is not needed if the spinbutton does not have a min or max value.

**Comment by mcking65** [comment]
Resolved with commit f492516.

**Comment by MichielBijl** [comment]
That was a quick fix, nice work 👍
