### ISSUE TITLE
Site Navigator section seems convoluted...

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#45]
The site navigator is overly complicated... It recommends nesting sub widgets such as a tree (for a leftnav) or a role=menu (top nav) in the main navigation dropdown, with aria-owns. 
http://w3c.github.io/aria/practices/aria-practices.html#Site_Navigator_General 

"Navigation container widget: the navigation items need to be contained in an appropriate widget, such as a tree, menubar, toolbar, or listbox. "

Here are my concerns:
- I'm nervous about this level of complexity. It requires a lot of Assistive technology computing power ... especially aria-owns.

- The WAI ARIA Authoring Best Practices 1.0 Site Navigator, did not receive high uptake... neither did the 1.0 ARIA tree widget and 1.0 menu items outside of academic discussion and experimentation, in the 6 years they have existed. The navigator requires considerable learning for developers and a lot of expertise from a screen reader user who is inevitably going to become confused...

- Consider simplifying the requirements. Consider straight forward lists (and sublists) of links wrapped in a `<nav>` with aria-expanded. Let's not drown the menu in roles that override the `<ul><li>` semantics, which have been an understood convention for groups of links for 20 years and which natively gives hierarchy, eliminating the need for aria-owns, which saves AT computing power. Consider a realistic construct that is achievable and which can gain community momentum, consensus and uptake ... 

**Note regarding keyboard interaction:** I think trapping the right/left arrow keys for navigation inside the widget is probably the way to go, but we need to understand that some users will become confused for the next few years. Radio buttons have been around for 20 years and still 20% of screen reader users don't know that they should use the arrow keys once they tab into a radio group. I doubt aria widgets will be much different. I wish I had a solution for that... I don't, but I'm afraid we're headed for the same type of problems if we get too many sub widgets inside `<nav>` elements.

**Comment by mcking65** [comment]
@DavidMacDonald,

Thank you very much for the feedback. I agree with quite a bit of it. I have added your comment to issue #89 and will close this issue.

I am removing The site navigator design pattern for now; I don't think we will have time to update and correct it in time for the 1.1 version of the APG that will be published when ARIA becomes a proposed recommendation. I have added it to our milestone for a release that will follow soon after the proposed recommendation.

One think to keep in mind, however, is that we would not recommend implementing arrow key navigation unless the navigator is in a widget, like a tree or grid, where assistive technologies can recognize the fact that arrow key behavior is present. If you use UL for example, then every link must be in the tab sequence. Of course, you could use expanding and collapsing techniques to mitigate that, but it would nonetheless be a tab through it all type of experience.

When it comes to navigating with arrow keys on the web, there is still a lot of room for improving experiences, especially for people who can see. Visual designs to-date have not been at all helpful, for example.

There is definitely not a one-size-fits-all kind of answer here. The APG will stimulate ideas and give people ideas based on appropriate use of ARIA.
