### ISSUE TITLE
2.9 Dialog (Modal)

### ISSUE THREAD

**Issue by zbolena** [w3c/aria-practices#461]
I feel that role=dialog should relay the same information to the screen reader user as "region" as far as defining the end of the modal's content. I think this really helps the screen reader user to know where the content ends. 

I know the modal is the only active container on the page but this still does not explicitly define the containers end point. 

Thank you

**Comment by jnurthen** [comment]
I'm not sure what to do with this. Is this a comment on the ARIA spec or the Authoring Guidance about Modal dialogs?

**Comment by mcking65** [comment]
@zbolena, it seems that you are making a suggestion to screen reader developers with your comment and that it is not directed at authoring practices or the ARIA specification. Is that correct?

BTW, I think there is some merit to your suggestion for the circumstance where the screen reader user is allowed to move the reading cursor outside the dialog while the dialog is open. For example, if using JAWS with a dialog where the background is not inert, and if the user presses insert+r, then the user would be able to discern the edges of the dialog when the reading cursor is outside the dialog content.

I am closing this issue as not relevant to the authoring practices. Please feel free to re-open if I have misunderstood your comment.
