### ISSUE TITLE
aria-* and grid with filtering

### ISSUE THREAD

**Issue by knoobie** [w3c/aria-practices#465]
I hope it's allowed to ask such questions here. 

The  [documentation for aria-rowcount](https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount) states the following:

 > If all of the rows are present in the DOM, it is not necessary to set this attribute as the user agent can automatically calculate the total number of rows. However, if only a portion of the rows is present in the DOM at a given moment, this attribute is needed to provide an explicit indication of the number of rows in the full table.

> Authors MUST set the value of aria-rowcount to an integer equal to the number of rows in the full table. If the total number of rows is unknown, authors MUST set the value of aria-rowcount to -1 to indicate that the value should not be calculated by the user agent.

The 'full table' kinda raises questions for me. 

How do we proceed if the table can be filtered? Should the aria-rowcount be changed depending on the applied filter by the user or should it always remain where it was without a filter added? 

The same goes for aria-rowindex, should it be re-calculated after a filter was applied? Or should the aria-rowindex change depending on the aria-sort? Should rows in the header and footer included in this as well? 

Thank you for your time! I would love to implement it 'right' so it won't cause problems for our sightless users.

**Comment by jnurthen** [comment]
> How do we proceed if the table can be filtered? Should the aria-rowcount be changed depending on the applied filter by the user or should it always remain where it was without a filter added?

It should be the number of rows which are in the set of results which are "displayed" in the table - so the filtered set.

> The same goes for aria-rowindex, should it be re-calculated after a filter was applied? Or should the aria-rowindex change depending on the aria-sort? Should rows in the header and footer included in this as well?

It should be re-calculated.

Good question about the header and footer. Header rows should be included. See Example 3 at https://w3c.github.io/aria-practices/examples/grid/dataGrids.html

**Comment by knoobie** [comment]
Thank you!
