### ISSUE TITLE
Many internal links on http://w3c.github.io/aria-practices/ are broken

### ISSUE THREAD

**Issue by cordeliadillon** [w3c/aria-practices#467]
http://w3c.github.io/aria-practices/ uses anchors/hash navigation to navigate around the page, but many of them don't work anymore as the ids for many sections have a space in them while the links in the sidebar and elsewhere do not.

For example, http://w3c.github.io/aria-practices/#menu should go to the "Menu or menu bar" section, but does not as the section has `id="menu "` rather than `id="menu"`. This appears to be a recent change, as I don't recall seeing this bug a week or so ago and the previous ARIA practices doc does not have spaces in the ids: https://www.w3.org/TR/wai-aria-practices-1.1/#menu

**Comment by jnurthen** [comment]
Thanks. We noticed this today during our meeting.

**Comment by jnurthen** [comment]
Thanks @cordeliadillon 
This should be fixed.
