### ISSUE TITLE
"Site Navigator" seems convoluted

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#47]
http://w3c.github.io/aria/practices/aria-practices.html#Site_Navigator_General

For the name of this section, at least put the word (menu) somewhere in brackets... it is hard to find in the table of contents... no developers are looking for a "site navigator", they are looking for a main menu, mobile menu, mega menu, etc.

This document is supposed to be for "real" web developers, not just accessibility insiders, please give the standard language somewhere so they can find the section. 

How about "Site Navigation Menu" or simply "Navigation menu", I think that is sufficiently distinct from the "menu" item which also has a confusing name. 

How about this?
Distinguish the "Menu" and "Site Navigator" as two types menus:
-"Application Menu" 
-"Navigation Menu" 
Both of which are easily understood. Currently both "Menu" and "Site Navigator" are confusing.

**Comment by MichielBijl** [comment]
I like this idea!

**Comment by mcking65** [comment]
I added this feedback to issue #89. Closing this issue.
