### ISSUE TITLE
Ensure sufficient guidance regarding impact of roles on semantics associated with elements

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria-practices#474]
Some concrete examples and related discussions/concerns:
* `<table role="log">...</table>` will stop being a table (and thus lose screen-reader table presentation and navigation commands): [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1305446), [related public-aria list thread starter](https://lists.w3.org/Archives/Public/public-aria/2017Aug/0000.html), and [Matt's on-list response, with a proposed solultion](https://lists.w3.org/Archives/Public/public-aria/2017Aug/0003.html).
* "Weak" landmarks in Gecko in order to ensure scenarios like `<ul role="navigation">...</ul>` remain exposed as a list (i.e. and NOT exposed as a landmark, contrary to what is stated as the mapping in the Core AAM 1.1): [Mozilla bug with thoughts from James Teh and me](https://bugzilla.mozilla.org/show_bug.cgi?id=1407287).

The solution which strikes me as the best way to ensure interoperability as well as buy-in from user agent and screen reader implementors is to ensure authors don't apply roles to elements with associated semantics and screen reader presentation/navigation. In other words, as Matt had suggested in his on-list response:

> If an author wants to make a log table use `<div role="log"><table></table></log>`.

Seems like a job for Authoring Practices. :smile:

**Comment by mcking65** [comment]
I have been planning on adding an introductory section that could some of the most important fundamentals/dangers of ARIA ... I will accelerate in response to this need.

**Comment by mcking65** [comment]
@joanmarie, @jcsteh, @MarcoZehe,

Today I added a proposed draft of a new 
[Read Me First](http://w3c.github.io/aria-practices/#read_me_first) 
section to APG. I am curious to know if it adequately addresses concerns expressed in 
[Mozilla bug 1407287](https://bugzilla.mozilla.org/show_bug.cgi?id=1407287).

**Comment by mcking65** [comment]
Work on this is complete and has been reviewed in issue 482. If the resolution is not adequate, please feel free to reopen.
