### ISSUE TITLE
Accordion Example: Roles, States, and Properties table incorrectly says the header control uses an `<a>` element

### ISSUE THREAD

**Issue by pudgereyem** [w3c/aria-practices#475]
> **DISCLAIMER**  
> This is my first contact with this repository. Please correct me if I'm missunderstanding stuff. :)
> It would be nice to contribute, and this seems like a good start.

## Issue
The [Accordion Example](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html) uses `<button/>`, but the documentation tells us that it uses an `<a/>` (anchor) element

## Solution
Change the Documentation in https://github.com/w3c/aria-practices/blob/master/examples/accordion/accordion.html to use `<button>` instead of `<a>`.

> I would like to open up a PR for this, but please answer to this issue if you'd like.

## Background / Discussion
I looked through the activity in this github project to understand the current status. Below is what I found. I wrote this down for myself to get a bit of context.

- Discussion about wether or not to use `<button>` or `<a>` element.
- 2017-02-16: @mcking65 writes in https://github.com/w3c/aria-practices/issues/210#issuecomment-280441653  that `<a>` element should be used
- Issue https://github.com/w3c/aria-practices/issues/158 that has todo that `<button>` element should be used
- 2017-06-17: Pull Request Merged https://github.com/w3c/aria-practices/pull/397 that now uses `<button>` component

**Comment by mcking65** [comment]
@pudgereyem commented:

> This is my first contact with this repository. Please correct me if I'm missunderstanding stuff. :)
> It would be nice to contribute, and this seems like a good start.

Victor, thank you for both catching this error and offering to help!!

I haven't put this in the readme yet, but it is a good idea to raise an issue or comment in an issue, as you did, before going through the work of changing code and submitting a PR. That will help ensure you aren't working on something that someone else is already in the process of changing. It can also make sure that your fix is aligned with the spec, task force objectives, etc.

That said, if you see anything in our [current milestone](https://github.com/w3c/aria-practices/milestone/6) 
that might interest you, please comment in the issue and say so!

> The Accordion Example uses  <button/> , but the documentation tells us that it uses an  <a/>  (anchor) element.

Excellent catch!

**Comment by pudgereyem** [comment]
Hey @mcking65, thanks for the warm welcome!

I will definitely check out https://github.com/w3c/aria-practices/milestone/6, and see if I can be of any help. I'm not that "experienced" with a11y, so contributing to this project would be a great learning experience for me.

Cheers!

**Comment by mcking65** [comment]
Fixed with 424facf. Thank you @pudgereyem!

**Comment by pudgereyem** [comment]
@mcking65 I'm using this issue to ask two questions. 

1. When using the Accordion Example, I don't experience the expected behaviour of `Control + Page Down` and `Control + Page Up` in Chrome. What happens is that it switches to the Next / Previous Tab in Chrome instead. It works in Safari. Nothing happens in Firefox for me. What should I make of this? What browser is best to test my work on?

2. The other question is a bit noobish, maybe I should find this information by googling. What "command" would someone using a screen reader use, if he or she would like to read the text in a panel that he or she just opened?

Cheers!
