### ISSUE TITLE
Review changes to improve compatibility of keyboard guidance with Mac OS conventions

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#484]
Review the following set of changes made to resolve issue #413 and other problems related to appropriateness of APG keyboard guidance for Mac OS.

1. Modified the beginning of the [design patterns section](http://w3c.github.io/aria-practices/#aria_ex):
    * Removed note about control key being used instead of Mac command key.
    * Moved global keyboard recommendations section to new section [5.8 Key Assignment Conventions for Common Functions](http://w3c.github.io/aria-practices/#kbd_common_conventions).
2. Revised the keyboard interaction guidance for patterns that include textbox functionality to state that the textbox keys need to be platform appropriate and added notes for how to achieve this. Keyboard guidance for two patterns is revised:
    * [Combobox](http://w3c.github.io/aria-practices/#combobox)
    * [Spinbutton](http://w3c.github.io/aria-practices/#spinbutton)

Note: The 4 commits related to the above changes are all associated with issue #413.

#### Task Force Reviews requested as of October 16, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by James (@jnurthen)

**Comment by jnurthen** [comment]
I think there might be some more to change. There are other patterns where we recommend
 control + (something) for a function. We should probably modify those too.

## Accordion

- control + page up/down (mac keyboards don't have page up/down). While I don't think this will conflict with anything as it is a pretty contrived keystroke it is certainly not natural for a mac user

## Grid Popup, Feed, Data Grids
- control + Home/End (mac keyboards don't have home/end). Again - probably won't conflict but fn+control+left/right arrow is a pretty tricky shortcut.

## Data Grids
- Control + space - I don't think I have seen this conflict. We definately don't want to suggest using command + space as that conflicts with selecting alternate keyboard layouts which is essential for anyone using a language that uses an IME.
- Control + A - this seems to conflict with "Move to the beginning of the line or paragraph." which probably isn't a big deal in a web document as all it seems to do it scroll up. Command + A would be the mac way of doing select all.

## Listbox (multiple selection) & Multi-select Trees.
- Control + Shift + Home/End - becomes Fn+Control+Shift+left/right arrow - probably not practical
- Control + A - as before
- Control + Down Arrow: This needs fixing as this does an OS function (application windows)
- Control + Up Arrow: This needs fixing as this does an OS function (Mission control)
- Control + Space As above

**Comment by mcking65** [comment]
@jnurthen, I am unsure about some of those.

All the Mac keyboards I have around me have home, end, page up, and page down. And, the Mac keyboard help includes those keys:
https://support.apple.com/en-us/HT201236

That said, I did consider having a table listing alternatives for some of those and then adding a note to those patterns. But, I was thinking that I was not aware of any circumstances where those specific key assignments would be problematic ... even if they are not ideal. So, I didn't make it a priority. You think we should?

**Comment by annabbott** [comment]
I have no knowledge of Mac OS keyboard conventions, so will pass on reviewing this.

**Comment by mcking65** [comment]
@annabbott, you could look over the changed sections just for editorial errors. You have a great eye for that! Especially the keyboard interaction in combo and spinbutton and the new section 5.8.

**Comment by annabbott** [comment]
@mcking65 Will do! I should have some time later on today...

**Comment by annabbott** [comment]
@mcking65 Will do! I should have some time later on today...

**Comment by annabbott** [comment]
3.7 Combo Box > Textbox Keyboard Interaction > Down Arrow > first hollow bullet:
"If the autocomplete behavior hautomatically..."
Typo: change "hautomatically" to "automatically".

**Comment by annabbott** [comment]
Didn't spot anything amiss in 5.8 Key Assignment Conventions for Common Functions or Spinbutton.

**Comment by mcking65** [comment]
@jnurthen, I captured your feedback for future improvements in issue #506.

**Comment by mcking65** [comment]
Closing as sufficiently reviewed for this release. This topic will get more attention in the next release starting with issue 506.

**Comment by 8slashes** [comment]
@mcking65 Fn + (up/down) accomplishes the page up and page down functionality on my Macbook but in your [accordion example](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/accordion/accordion.html) the control + (page up/page down) keyboard functionality doesn't work because that key combination is a [Firefox shortcut for moving left or right through browser tabs](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs).
