### ISSUE TITLE
Remove references to xHTML

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria-practices#49]
When ARIA 1.0 and the APG 1.0 were released, xHTML was the intended host language. This is now out of date. Suggest updating the prose to either reference HTML or use the phrase "host language".

**Comment by MichielBijl** [comment]
A quick search shows 33 mentions of xHTML.

**Comment by mcking65** [comment]
Completed with commit eabf6ca5a102af42f876ff4856e92c85b735cecd
