### ISSUE TITLE
When an option is selected, set the combo value on blur in the ARIA 1.1 Combobox with Listbox Popup Examples

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#495]
In example 1 and example 2 on the page for the 
[ARIA 1.1 Combobox with Listbox Popup Examples](http://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html), 
if an option is selected in the listbox, tabbing or clicking out does not set the value of the combobox to the selected option. 

The expected behavior is that tabbing or clicking out sets the value of the textbox if an option is selected.

**Comment by jnurthen** [comment]
Thanks. This seems to be resolved.
