### ISSUE TITLE
In ARIA 1.1 Combobox with Grid Popup, Left and Right Arrow do not wrap to previous/next row in grid popup.

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#499]
In the [ARIA 1.1 Combobox with Grid Popup ](http://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/grid-combo.html), when focus is in the grid popup, left and right arrow do not follow the grid pattern.

The focus is staying in one row and wrapping back and forth in the same row. The expectation is that focus either keeps moving through the grid to the previous or next row when the end of a row is reached or focus does not wrap.

**Comment by gerardkcohen** [comment]
@mcking65 I can take this if you want

**Comment by mcking65** [comment]
@gerardkcohen, sure, that would be very helpful.

**Comment by gerardkcohen** [comment]
@mcking65 Fixed with #530

**Comment by mcking65** [comment]
@gerardkcohen, thank you! With commit 691269e, this is now resolved.
