### ISSUE TITLE
Automate snapshot generation to gh-pages

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#5]

**Comment by michael-n-cooper** [comment]
Progress, I have a build that's working in the Travis-CI_Test branch. It's building to gh-pages_test to avoid breaking things until I'm sure it works. While it successfully builds and commits, it relies on the W3C spec generator https://github.com/w3c/spec-generator to create the static doc. That service seems to be down more often than not, and if it's down returns a simple error page which this build would overwrite the editors' draft with. I'm trying to figure out how to run the spec generator without relying on a flakey web service, or find way to generate, or detect that it returned an error page and not commit in that case. Also the script may need to post-process relative URIs in the generated doc to make them correct, e.g., s|../common/|| or something. Or have a respec extension running that converts them to absolute or something.

**Comment by mcking65** [comment]
now that examples are getting copied over, are we ready to close tis?

**Comment by michael-n-cooper** [comment]
Yes, sorry, I had forgotten that there was a gh issue associated with my action item.
