### ISSUE TITLE
Remove reference to xHTML access module

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria-practices#50]
In <a href="https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/#AuthDefKeys">4.2.6 author defined shortcuts</a> the reference to the access module being developed by the xHTML2 WG should be removed. It has no implementations AFAIK.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria-practices/commit/266a63d64094a409cc7b05e7c8ee3b64ff4491bd
