### ISSUE TITLE
Review ARIA 1.1 Combobox with Grid Popup Example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#500]
The [ARIA 1.1 Combobox with Grid Popup Example](http://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/grid-combo.html)
is ready for task force review. 

#### Known Issue

**NOTE**: There is one known defect. Left and right arrow do not behave as described in the pattern. This is issue #499.

#### Reviews Requested as of October 25, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Bryan (@accdc)
- [x] Review by Jemma (@a11ydoer)
- [x] Review by James (@jnurthen)

**Comment by annabbott** [comment]
Sorry - this doesn't appear ready for review...
Says "NOTE: This page is work in progress; it is not ready for review. "

**Comment by mcking65** [comment]
@annabbott, Sorry Ann, there was an error in the build process and it didn't get pushed out to github.io. It is fixed now.

**Comment by annabbott** [comment]
Role, Property, State, and Tabindex Attributes > Textbox:
Table has different format than the other two tables for Combobox Container and Grid Popup.

**Comment by jnurthen** [comment]
@annabbott What do you mean by different format? Do you mean the column widths are different or are you talking about something else?

**Comment by annabbott** [comment]
@jnurthen Correct, column widths are different.

**Comment by jnurthen** [comment]
@annabbott this is because the content in the cells is different. there are no widths specified on the tables. At this stage I certainly don't want to change all the tables to force column widths. 
Can you log a new issue about the role/state property tables looking inconsistent that we can look at post this release?

**Comment by annabbott** [comment]
@jnurthen As the difference in column width is due to cell content, I'm ok with that.

**Comment by a11ydoer** [comment]
The review is done.

**Comment by accdc** [comment]
My apologies, I commented on the wrong issue. The keyboard functionality looks good to me from my testing as with the prior listbox 1.1 design pattern.

**Comment by mcking65** [comment]
This review is complete; thank you all for the feedback.
