### ISSUE TITLE
Accordion Pattern: Review Proposed Revision to First Paragraph

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#501]
3.1 Accordion (Sections With Show/Hide Functionality)

_"An accordion is a vertically stacked set of elements, such as labels or thumbnails, that allow the user to toggle the display of sections of content. Each labeling element can be expanded or collapsed to reveal or hide its associated content. Accordions are commonly used to reduce the need to scroll when presenting multiple sections of content on a single page._"

I think this lead paragraph on accordions may be confusing for some who will associate labels with form fields. I also find it slightly disjointed.

I suggest something like this:

An accordion is a vertically stacked set of triggering elements, for example, a label or a thumbnail. Each triggering element can be toggled expanding or collapsing to reveal or hide its associated content. Accordions are commonly used to reduce the need to scroll when presenting large amounts of content on a single page.

I left in label, although, it does not feel right.

The work you all put in is phenomenal and I, for one, would like to let you know it is appreciated by this developer.

Regards
Laurence

**Comment by mcking65** [comment]
@Decrepidos, what do you think of ...

> An accordion is a vertically stacked set of interactive headings that each contain a title, content snippet, or thumbnail representing a section of content. The headings function as controls that enable users to reveal or hide their associated sections of content. Accordions are commonly used to reduce the need to scroll when presenting multiple sections of content on a single page.

Notice that this wording carefully avoids saying that each heading works as a toggle. In accordions where one section must always be expanded, the heading of the currently expanded section cannot be used to collapse the content. In such accordions, the headings are not toggles.

**Comment by Decrepidos** [comment]
Perfect. Case closed 😁

**Comment by mcking65** [comment]
@jnurthen, @accdc, @a11ydoer, @MichielBijl, @sh0ji,

Do any of you have any problems with me changing the first paragraph of the accordion pattern to:

> An accordion is a vertically stacked set of interactive headings that each contain a title, content snippet, or thumbnail representing a section of content. The headings function as controls that enable users to reveal or hide their associated sections of content. Accordions are commonly used to reduce the need to scroll when presenting multiple sections of content on a single page.

**Comment by mcking65** [comment]
Reviewed during Nov 27 TF meeting; team agrees with new wording. I will make the change.

**Comment by mcking65** [comment]
@Decrepidos, Per discussion in today's meeting, I Made the proposed changes in commit a6dd28d. They are visible in the [accordion pattern in the master branch](http://w3c.github.io/aria-practices/#accordion).

Closing as resolved.
