### ISSUE TITLE
Review aria-modal notes added to dialog example page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#503]
For issue #480, added some notes following the roles, states, and properties table on the 
[modal dialog example page](https://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html).

Please review for editorial issues.

**Comment by annabbott** [comment]
For "End of the Road!" dialog, tab key only goes to the first Close button and the buttons at the bottom of the dialog cannot be reached via keyboard.

**Comment by annabbott** [comment]
Address Added dialog > using FF (unfinished comment so I can install latest FF and come back to finish)

**Comment by annabbott** [comment]
I don't see any issues in the text following the roles, states, and properties table.

**Comment by mcking65** [comment]
annabbott commented:
> For "End of the Road!" dialog > using FF 56.0.2 with JAWS 18.0.4350 on Win10:
> TAB key only goes to the first Close button and the buttons at the bottom of the dialog cannot be reached via keyboard.
> It is confusing for an example to not place focus via the TAB key on what appears to be functional buttons.
> Suggest, at a minimum, those buttons at bottom of dialog should display as disabled buttons.

Ann, those buttons are in a dialog that is under the "end of the road" dialog. That entire underlying dialog should be grayed out. I raised issue 523 to address that.

> Address Added dialog > using FF 56.0.2 with JAWS 18.0.4350 on Win10:
> JAWS announces paragraph but, on initial pass, does not identify "your profile" as a link (does announce "OK" as a button).
> When I Shift-TAB back to "your profile", it is announced as a link.
> Unsure whether this is a code bug or a JAWS bug, however for a JAWS user this would be very confusing.

This is not a bug. When the dialog opens, most screen readers simply read out the accessible name and description for the dialog. The name and description are fed to the screen reader as flat strings. Those strings cannot contain semantic information like which part of the descriptive information is a link.

Since IA2 provides an accessible relation for content referenced by aria-describedby that is present in the DOM, JAWS and NVDA could potentially utilize that relationship and read directly from the describing content rather than spitting out the flat string. That would open up the possibility of reading it with semantics. I am guessing that would be a nontrivial change. Although, if feasible, it would definitely be a good one for them to make.

Ann, thank you for the thorough review! We have achieved the objective of this issue. So, closing it.
