### ISSUE TITLE
TreeView: missing [role="none"] attributes

### ISSUE THREAD

**Issue by geppy** [w3c/aria-practices#514]
Let me know if this is as intended, but [these two list items](https://github.com/w3c/aria-practices/compare/master...geppy:add-missing-role-none?expand=1) seem to be missing `[role="none"]`.  I don't believe they're intended to be exposed as list items: their children are `a[role="treeitem"]`, and without this change Narrator doesn't treat them how I'd expect.

**Comment by geppy** [comment]
Opening an issue rather than a PR, per comments in #497.  Let me know if I should document the unexpected screenreader behavior.

**Comment by mcking65** [comment]
@geppy, thank you for catching this!! It was such a simple change that I just made the changes in master and pushed them out. This issue is resolved with commit 77e9f5d.
