### ISSUE TITLE
Datepicker requirements no longer available due to 1.0 page redirection

### ISSUE THREAD

**Issue by gilesedinburgh** [w3c/aria-practices#516]
I am not exactly sure if the issue is that 1.0 w3 pages are now redirecting to the working draft of 1.1 or that the 1.1 working draft is missing content from 1.0

Currently, the aria 1.0 page redirects users to the latest 1.1 working draft version.
However, 1.1 is missing some key pieces, such as the date picker requirements.

Page reference:
https://www.w3.org/TR/2009/WD-wai-aria-practices-20090224/#datepicker

Therefore, it appears there are no longer standard requirements for those datepicker controls. However, this is a pretty popular control with assistive technology expectations on keyboard navigation.

**Comment by mcking65** [comment]
@gilesedinburgh,

The content in 1.0 was never finalized and din't have consensus or adequat peer review. I do not recommend referencing it.

We are working hard to get the first actual release of ARIA Practices done for ARIA 1.1.

It will not be complete and will not include a date picker pattern or examples in the first release. They are in our plan. See issues #57 and #34.

Right now, our goal is to get consensus around the more basic patterns. And, this has been quite a long road. But, we are getting there. 

You can see our plans under the milestones and projects in this repo. There is also roadmap info on the wiki.

Sorry about that.

If you are in a position to contribute, please let me know. Help is good.

**Comment by mcking65** [comment]
Closing as addressed. Feel free to reopen if the above response is inadequate.
