### ISSUE TITLE
Menuitems duplicated in Editor Menubar Example

### ISSUE THREAD

**Issue by weboverhauls** [w3c/aria-practices#521]
In the Editor Menubar Example, the menuitem elements are duplicated.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html

`<li role="menuitem" aria-haspopup="true" aria-expanded="false">
  <span tabindex="0" role="menuitem" aria-haspopup="true" aria-expanded="false">Font</span>`

I assume LI should only have role="none".

Twitter references:
https://twitter.com/jnurthen/status/930852962582151169
https://twitter.com/jnurthen/status/930872266664984576

**Comment by mcking65** [comment]
@weboverhauls, good catch Dennis.

At oen time there was a version where the JS was inserting the ARIA markup. We opted to get rid of that in favor of putting as much of the ARIA as is reasonable in the static HTML. Looks like some of that old JS was not cleaned up.

@sh0ji, is this something you might have time to take on?

**Comment by mcking65** [comment]
Thank you to @sh0ji! This is now fixed with commit ba84ee6.
