### ISSUE TITLE
Modal Dialog Example: Dialogs underneath other dialogs are not grayed out

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#523]
In the [modal dialog example](https://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html),
when a dialog appears on top of another dialog, the lower z dialog is not grayed out and is not inert.
For example,  open the "add delivery address" dialog. Then activate the "Verify Address" button. Then, activate the "accepting an alternative form" button, which opens the "end of the road" dialog. When the "end of the road" dialog is displayed, the underlying content from the "verify address" dialog is not grayed out and is still active.

The lower z dialog should always be grayed when another modal is opened on top of it. And clicking outside the currently active dialog should either do nothing or cancel the currently active dialog.

This was raised by @annabbott in a [comment on issue 503](https://github.com/w3c/aria-practices/issues/503#issuecomment-340482191).

**Comment by mcking65** [comment]
@annabbott, @jnurthen,

You can see and test Evan's proposed fix in his repo here:
https://rawgit.com/sh0ji/aria-practices/523-fix/examples/dialog-modal/dialog.html

Compare to what is in master now:
http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html

Given the amount of back and forth we had on this example, I want to be thorough in our testing before merging.

If you find problems with the fix, please comment in pull #549.

**Comment by annabbott** [comment]
Comments added in pull #549.

**Comment by mcking65** [comment]
Fixed with commit fdf51a2.
