### ISSUE TITLE
Review revised browser and assistive technology support wording

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#529]
The section of the read me first addressing [browser and assistive technology support](http://w3c.github.io/aria-practices/#browser_and_AT_support) is now revised based on feedback from @accdc at TPAC.
It is now ready for review.

#### Task Force Member Reviews Requested as of Nov 18, 2017

- [x] Review by Bryan (@accdc)
- [x] Review by Ann (@annabbott)

**Comment by annabbott** [comment]
No issues noted.

**Comment by accdc** [comment]
Looks great to me.

**Comment by mcking65** [comment]
Excellent, thank you for the feedback. Glad we are in a good place with this.
