### ISSUE TITLE
Draft Accordion design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#53]
When working on this issue, there is some old content that may be useful in the file aria-practices-DeletedSectionsArchive.html.
The relevant section can be seen here:
https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#accordion

> An accordion component is a collection of expandable panels associated with a common outer container.

**Comment by mcking65** [comment]
I added a first draft of the design pattern and integrated Bryan's example code in commit 1ecb9be.

I published it in the master branch, so it can be viewed at:
http://w3c.github.io/aria-practices/#accordion
