### ISSUE TITLE
Layout Grid Examples: Keyboard Tutorial NUX does not close when using IE 11.

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#531]
@shirsha [commented in issue 227](https://github.com/w3c/aria-practices/issues/227#issuecomment-340527273)
that when using IE 11, the keyboard NUX does not close with either keyboard or mouse.

We might want to consider using a button element instead of `<a`.

**Comment by mcking65** [comment]
@gerardkcohen  has volunteered to submit a PR for this issue.

**Comment by gerardkcohen** [comment]
@mcking65 Took a look, there are issues with focus management along the usage of JS API's not available for IE. There is a focus listener on the "ARIA 1.1 Specification" control (using the `once` parameter which is not supported by IE11) that produces the Grid instructions. Invoking the "Close" control hides the instructions and then sets focus on the "ARIA 1.1 Specification" control again causing an endless loop. The fact that `once` is used means that, for browsers that do support, the instructions will only popup once. I will need to fix all the unsupported IE issues, take care of this focus loop causing the noted issue, as well as address some Ux. Stand by.

**Comment by gerardkcohen** [comment]
@mcking65 Fixed via #548

**Comment by mcking65** [comment]
Fixed in commit a1de1af with many thanks to @gerardkcohen!
