### ISSUE TITLE
Add feedback, compatibility, project, and pattern links to the top of all example pages

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#536]
Per feedback at TPAC, add the following links to each example page:

1. Report Issue: link to github new issue page for the repo
2. History and Plans: link to the github project for the example
3. Browser and AT Support: Link to browser and assistive tech section of read me first
4. Design Pattern: link to the design pattern for the example

#### Plan

- [x] Matt make branch with proposed links for at least one example page
- [x] James develop CSS to place links
- [x] Review wording and placement with task force
- [x] Matt finish creating projects for examples that do not yet have an associated project
- [x] Matt: add links to remaining example pages
- [x] Matt: Merge into master

**Comment by mcking65** [comment]
@jnurthen, I added proposed nav links to the top of the [accordion example page in the example_nav branch](https://rawgit.com/w3c/aria-practices/example_nav/examples/accordion/accordion.html).

I think it would be good to duplicate this nav at the bottom, but didn't do that yet. Figured we should settle on ordering, link text, and styling first.

Please take a look and figure out what to add to the core.css.

**Comment by jnurthen** [comment]
I have no idea what people think about it but I made a change to core.css in this branch which displays them fixed at the top right of the screen so they are always visible with a viewport > 1300px. When less than this they just fall back to being at the top of the screen.

I do not think we should duplicate them at the bottom. 

I came up with a 2nd proposal I put in the alert example - https://rawgit.com/w3c/aria-practices/example_nav/examples/alert/ which hides these links within a details. I don't know whether this is a good idea or not. I'm open to comments 1 way or the other.

**Comment by sh0ji** [comment]
I prefer the simple list design (accordion example) to the details (alert example). It took me longer than I care to admit to actual find both, though, since the "top-right fixed" pattern isn't used elsewhere in this project (AFAIK).

And this is more of a wishlist item, but it would be great if we displayed a very prominent notice if there are issues with the "Browser and AT Support", similar to how MDN displays a notice for experimental or unsupported features (e.g. [CSS fit-content](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content)).

**Comment by annabbott** [comment]
I vote for upper LEFT corner wrapped in role="complementary" and formatted as in Alert Example.

**Comment by mcking65** [comment]
A set of links like this, even if the links are related links, still belong in a navigation region, not complementary. Right now it is `<nav aria-label="Related Links">...</nav>`.

Per discussion on list, I am not a fan of placing them after the H1and before the description. Right now, the H1 is the first thing in main. I don’t think these links should be part of the main content.

If we were going to put them after the H1, then I would want to move the H1 into a banner that contains the H1 and the nav. Then, we would need to add an H2 at the start of main of something like "Overview" or "Description".

**Comment by mcking65** [comment]
@sh0ji, some sort of can i use or support level info is on my longer term wish list too. It is not in our current scope.

**Comment by mcking65** [comment]
Complete with commit ab0343e.
