### ISSUE TITLE
Draft Alert Dialog or Message Dialog design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#54]
> A dialog with the primary purpose of communicating a message and acquiring a user response to that message. 

[Alert Dialog or Message Dialog in the APG](http://w3c.github.io/aria-practices/#alertdialog)

**Comment by mcking65** [comment]
Remove the role="document" requirement from the message. It is unnecessary. 

Note: this was also noted by feedback provided in issue #48.

**Comment by mcking65** [comment]
Proposed text for resolving this issue can be seen in the editors draft at:
http://w3c.github.io/aria-practices/#alertdialog

**Comment by jasonjgw** [comment]
The implication is that a typical alert dialog with a "close" button will have focus initially set to the button, but aria-describedby will encourage AT to read the alert message. I think this will be clearer to developers when the example is in place.

**Comment by mcking65** [comment]
@jasonjgw, that is correct.

**Comment by mcking65** [comment]
Closing issue based on review in September 12, 2016 APG meeting.
