### ISSUE TITLE
Toolbar Example: Use button elements and add other types of elements, such as link and checkbox

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#541]
In the [toolbar example](http://w3c.github.io/aria-practices/examples/toolbar/toolbar.html),
make the following enhancements:

- [x] replace some of the buttons with other types of elements, such as link, checkbox, toggle button, and switch.
- [x] For the link and buttons, provide some indication of activation when activated, e.g., popup a window alert.
- [x] Change `<div role="button">` to HTML `<button>` elements.

**Comment by mcking65** [comment]
@gerardkcohen is working on this issue.

**Comment by gerardkcohen** [comment]
Yes, I still intend in finishing this. It is very close to being done.

**Comment by mcking65** [comment]
With commit 599d2de from pr #887, the issue541-toolbar-redesign feature branch now contains all changes needed to resolve this issue. Further review will be managed in issue #539.
