### ISSUE TITLE
ARIA 1.0 Combobox Examples: Escape key does not behave correctly when focus is in the textbox

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#559]
The [combobox with both list and inline autocomplete](http://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html) does not process the escape key correctly when focus is in the textbox.

When focus is in the textbox, if the popup is displayed, Escape should collapse it. Optionally, it can clear the value. It does neither.

### Fix Preview Link

Proposed fix can be previewed in the [issue559-combo1.0-escape branch](https://rawgit.com/w3c/aria-practices/issue559-combo1.0-escape/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html).

**Comment by jongund** [comment]
This should be fixed in pull request 717

**Comment by mcking65** [comment]
Proposed fix can be previewed in the [issue559-combo1.0-escape branch](https://rawgit.com/w3c/aria-practices/issue559-combo1.0-escape/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html).branch.

**Comment by mcking65** [comment]
OK, this is confusing. I have not yet merged Jon's fix in pull #734, but I cannot repro the bug on the [latest version in master](http://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html). However, I can repro in the [published version on w3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html). Yet, In the [history of the js for this example](https://github.com/w3c/aria-practices/commits/71ac6f6aec342f92dafe5b08d4d2dcb8603d58ed/examples/combobox/aria1.0pattern/js), there have not been any changes since before we published.

Use the following procedure and observe the difference between the published version on w3.org and the current version in master. Note, if using JAWS, press insert+z to disable VC.
1. Type "c" in the combobox.
2. Press Delete to delete the "alifornia" that appeared inline.
3. Press escape.

Behavior on w3.org: Nothing happens when escape is pressed.

Behavior on master: When escape is pressed, the listbox collapses and the "c" in the textbox is cleared.

So, something has fixed master without merging the fix. I don't want to merge #734 if it is not necessary.

**Comment by mcking65** [comment]
Fixed with commit efcd04e.
