### ISSUE TITLE
Generated anchors make them unreliable for deep-linking

### ISSUE THREAD

**Issue by slauriat** [w3c/aria-practices#570]
For instance:
- https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-4 previously linked to the keyboard interactions for buttons, but now points to keyboard interactions for checkboxes.
- https://www.w3.org/TR/wai-aria-practices-1.1/#h-note3 previously linked to focus management requirements for modal dialogs, but no longer links to anything.

For longer descriptions, like for combobox and grid, these links help direct people to the content in question, rather than having to also write "and scroll down to the section on [specific thing]."

Suggestion: #button-keyboard-interaction or something similar to ensure links remain valid.

**Comment by mcking65** [comment]
Unfortunately, respec is getting rid of IDs we manually add so we can link from the examples. Then, it generates all its own. We don't have a work around or fix to respec yet.

**Comment by jnurthen** [comment]
@halindrome Do you happen to know if there is a respec issue about this - I couldn't find one but it seems like the kind of thing that should be an issue for all specs using respec.

**Comment by mcking65** [comment]
This issue was resolved by the redesigned site launched in May 2022; we no longer have respec generating anchors!!
