### ISSUE TITLE
Missing role=none in menu

### ISSUE THREAD

**Issue by StommePoes** [w3c/aria-practices#572]
On this page https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html#
I noticed that NVDA calls the first set of submenu items under "About" as 3 items, though there are four. The first three are one of three, two of three, three of three, the last item is one of one.

I think this might be because the last li element in the list doesn't have the role=none.

**Comment by jnurthen** [comment]
Good catch. Looks to be a simple fix.
