### ISSUE TITLE
Menu Button Shift + Tab behavior when menu is open

### ISSUE THREAD

**Issue by brooksienoodlesoup** [w3c/aria-practices#577]
I'm trying to understand the intended interaction pattern for Menu Buttons, as described in the ARIA Authoring Practices 1.1.  In particular, I'm referring to the following statement that is included in the 3.14 Menu or Menu Bar under the bullet for "Shift+Tab":

"Shift + Tab: Moves focus to the previous element in the tab sequence, and if the item that had focus is not in a menubar, closes its menu and all open parent menu containers."

I interpreted this as meaning that if a user has opened a menu for a menu button, and focus/selection is on a menuitem, a press of Shift+Tab will close the open menu and shift focus to the previously focusable item in the page focus order before the menu button itself.  However, when I observe the behavior of what happens in this context using the Menu Button examples, I observe that the open menu stays open, and that the input focus is shifted up to the menu button.  Can you help me reconcile the instructions for "Shift+Tab" behavior in the 3.14 Menu or Menubar interaction definitions with the interaction behavior that is currently in place on the Menu Button examples?  Should I just mimic the behavior as is currently demonstrated in the Menu Button examples as means of conforming with ARIA Authoring Practices for Menu Buttons? If so, I think the "Shift+Tab" instructions should be made a bit more clear. Thanks for your help!

**Comment by mcking65** [comment]
Menu Button Examples: Shift+Tab from menu does not close menu

In the following 3 menu button examples, when focus is in the open menu, pressing shift+tab should close the menu and refocus the button. The button gets focus, but the menu remains open.

1 [Navigation Menu Button Example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-links.html)
2. [Action Menu Button Example Using element.focus()](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html)
3. [Action Menu Button Example Using aria-activedescendant](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html)
