### ISSUE TITLE
Draft Dialog (modal) design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#58]
> A dialog is a window overlayed on the primary window.

[Dialog (Modal) in the APG](http://w3c.github.io/aria-practices/#dialog_modal)

**Comment by mcking65** [comment]
The initial revisions were discussed, and there are still changes needed. This was discussed in an APG TF meeting. I need to find the minutes and record the changes that were discussed here. I am putting a link to the issue into the APG section and stating that review is in process and to leave comments in this issue.

**Comment by mcking65** [comment]
Since review feedback and additional changes will be capture by issue #42, closing this issue.
