### ISSUE TITLE
Radio groups: Clarify what "only one" means

### ISSUE THREAD

**Issue by 0ddfell0w** [w3c/aria-practices#585]
It can be gleaned indirectly from the APG that some radiogroups will be initially unchecked, but can this be made more explicit?

> "A radio group is a set of checkable buttons, known as radio buttons, where only one button in the set may be in a checked state."

The word "only" in this sentence could be interpreted as "the only valid state is when one value is checked" or it could mean "no more than one value may be checked" -- it would be nice if we could state this more clearly.

**Comment by mcking65** [comment]
@0ddfell0w,

If we were to change:

> A radio group is a set of checkable buttons, known as radio buttons, where only one button in the set may be in a checked state.

to something like:

> A radio group is a set of checkable buttons, known as radio buttons, where no more than one of the buttons can be checked at a time.
> Some implementations may initialize the set with all buttons in the unchecked state in order to force the user to check one of the buttons before moving past a certain point in the workflow.

Would that resolve the issue?

**Comment by 0ddfell0w** [comment]
@mcking65 Absolutely! Looks much improved
