### ISSUE TITLE
Menu Button Examples: Shift+Tab from menu does not close menu

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#588]
As pointed out in issue #577 by @brooksienoodlesoup, in the following 3 menu button examples, when focus is in the open menu, pressing shift+tab should close the menu and refocus the button. The button gets focus, but the menu remains open.

1 [Navigation Menu Button Example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-links.html)
2. [Action Menu Button Example Using element.focus()](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html)
3. [Action Menu Button Example Using aria-activedescendant](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html)

**Comment by Owlbertz** [comment]
If there isn't already someone taking care of this I would like to tackle this one and get in touch with this project.

**Comment by mcking65** [comment]
@Owlbertz, are you still interested in helping with this? Very sorry that I did not ask sooner.

**Comment by jongund** [comment]
Should be fixed in pull request 716

**Comment by jongund** [comment]
Should be fixed in pull request 716

**Comment by mcking65** [comment]
Thank you @jongund, this is now fixed in commit 8bc433e.
