### ISSUE TITLE
aria-selected mistakenly listed as required for option role?

### ISSUE THREAD

**Issue by kbae00** [w3c/aria-practices#594]
Currently aria-selected is listed in the Characteristics table as a required attribute for the option role: https://www.w3.org/TR/wai-aria-1.1/#option. But the description says "Elements with the role option have an implicit aria-selected value of false." Should aria-selected be listed as a supported attribute instead of required?

**Comment by mcking65** [comment]
@kbae00, this is a question for the spec, not the practices. I moved it to the w3c/aria repo.
