### ISSUE TITLE
Do we need more W3C bits in the read me?

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#6]
Current read me contains some basic info, but nothing much. Is there something we absolutely need to have in there?

**Comment by michael-n-cooper** [comment]
I can't think of anything specific that is needed. We may want some of the documentation that's in the ARIA readme, though probably by reference rather than copy. That's partly a question for the larger repository split project, but for now I'll add a link.

**Comment by michael-n-cooper** [comment]
Oh, I meant to add that I added the w3c.json in response to this question as well. It's supposedly a machine readable way to say "other w3c organization administrators, don't screw around with this repository if you haven't checked with the repository owner", which surprisingly and unfortunately experience showed was a needed statement. I have no idea if this machine readable thing is used in anything, but somebody minted it so I'm using it.

**Comment by MichielBijl** [comment]
Thanks Michael!
