### ISSUE TITLE
Develop examples of Menu and Menu bar

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#60]
> A menu is a widget that offers a list of choices to the user, such as a set of actions or functions.

[Menu or Menu bar in the APG](http://w3c.github.io/aria-practices/#menu)

**Comment by mcking65** [comment]
The [Navigation Menubar Example](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html) 
and [Editor Menubar Example](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html) 
developed by @a11ydoer are the deliverables needed to close this issue.
