### ISSUE TITLE
Tablist: Unclear where focus goes when deleting the last tab

### ISSUE THREAD

**Issue by 0ddfell0w** [w3c/aria-practices#602]
"Delete (Optional): If deletion is allowed, deletes (closes) the current tab element and its associated tab panel. **If any tabs remain, sets focus to the tab following the tab that was closed and activates the newly focused tab.** Alternatively, or in addition, the delete function is available in a context menu."
- https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel

Notice that no guidance is given for the situation where the last of several tabs is deleted. Should the new last tab be activated?

**Comment by 0ddfell0w** [comment]
Also, it's not specified where focus goes when the last tab is deleted (perhaps that was left intentionally ambiguous)

**Comment by mcking65** [comment]
Yes, if the last of several tabs is deleted, the focus would go to the tab that preceded the tab that was deleted (the new "last tab).

Thanks for catching the omission.

**Comment by mcking65** [comment]
@jnurthen, In commit 8c19170, I revised the proposal so that the text for delete would be:

>Delete (Optional): If deletion is allowed, deletes (closes) the current tab element and its associated tab panel, sets focus on the tab following the tab that was closed, and optionally activates the newly focused tab. If there is not a tab that followed the tab that was deleted, e.g., the deleted tab was the right-most tab in a left-to-right horizontal tab list, sets focus on and optionally activates the tab that preceded the deleted tab. If the application allows all tabs to be deleted, and the user deletes the last remaining tab in the tab list, the application moves focus to another element that provides a logical work flow. As an alternative to Delete, or in addition to supporting Delete, the delete function is available in a context menu. 

Is this OK?

**Comment by jongund** [comment]
Seems OK to me, but if you can delete all tabs, will there typically be a button to add a new tab somewhere in the vicinity of the tablist?   Maybe the recommendation should include focusing the add tab button, if it exists, before looking for other items to focus.

Jon

**Comment by mcking65** [comment]
@jongund, I don't want to make any assumptions about the UI, e.g., there might be an add tab function ... that will add more words. Instead the wording assumes that the reader would consider "add tab" as a candidate for what might make a logical workflow.

**Comment by mcking65** [comment]
@0ddfell0w,

Thank you for providing feedback with this issue.

It is resolved with commit 94ed309. If the fix is not adequate, please feel free to re-open this issue and let us know why.
