### ISSUE TITLE
Menubar examples: Draft note about mouse hover behavior

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#603]
In the menubar examples, add information under accessibility features describing the mouse hover behaviors, comparing and contrasting with desktop.

Some web menus open automatically on hover. In contrast, in the editor menubar example, users have to click a menubar item first. Once a menu has been opened, exploration is aided by opening subsequent menus on hover. This behavior can help users who may be exploring the screen by moving a mouse pointer, e.g., with a magnifier, and who would have a hard time seeing elements that the submenus would cover if simply passing the mouse over the menubar always triggered display of submenus.

**Comment by carmacleod** [comment]
Before making any specific recommendations about hover in menubars or menu buttons, please also read some of the opposing views out there.
- This blog describes [why hover menus are problematic](https://medium.com/simple-human/why-hover-menus-are-problematic-b21d6c7de91c).
- I opened this [issue requesting that menus not open on hover](https://github.com/w3c/wai-website/issues/14) in the [new draft WAI web site](https://www.w3.org/WAI/beta/), and they said that user testing showed that their users expected navigation menus to open on hover (which I can't really understand, to be honest - those nav menubars go right across the page from the far left to the far right, and you can't get the mouse past them without having a menu slap you in the face - it's highly annoying).

The discussion in the WAI issue discusses a "hover intent pattern", which, if your users really-truly want hover to automatically open menus, then I would say that you MUST wait for them to show hover intent, like pausing over the button just long enough to indicate that they want a menu to open.

The other point noted in the WAI issue is that apparently users expect to have to click (or type space or enter) to open a menu button's menu. So menu buttons should not open on hover. (Note that the APG menu button examples do open on hover, so perhaps they should be changed).

Anyhow, I'm just saying that this is not a straightforward thing. We should research it, sure, but we may end up simply saying, "Do your user testing".

One thing that is clear is that true "application" menus, like the ones in Google docs, etc., are expected to require a click initially (i.e. to essentially give the menubar focus), and from then on, hover is expected to open other menus automatically, which is what we are doing for the APG's example application menu.

**Comment by annabbott** [comment]
"Accessibility Features" > items 4 and 5 look good.
Found one nit: "Accessibility Features" > item 2: remove extra space after last word of sentence and the period.
Also added this comment to #711  (instructions were confusing).

**Comment by mcking65** [comment]
Fixed with commit eafc098.

**Comment by carmacleod** [comment]
Looks good @mcking65 - thank-you. This really helps explain the thinking behind the application menubar example.
