### ISSUE TITLE
Looks like the the code for the modal is chopped off

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#613]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

Scroll to the bottom for the html code section

**Comment by jnurthen** [comment]
looks to have been caused by #549 which removed dialog_layer which was the part which got referenced in as the source code.

**Comment by sh0ji** [comment]
I'll submit a hotfix for this--not sure how we missed it back in #549!
