### ISSUE TITLE
multi-select accordion implementation

### ISSUE THREAD

**Issue by devarshipant** [w3c/aria-practices#616]
Consider giving an example of a multi-select accordion implementation. The [current example](http://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) is based on the requirement: 
 
> one panel of the accordion is always expanded, and only one panel may be expanded at a time. 
 
A multi-select example will be useful for users who would like to compare contents of two panels simultaneously opened.

**Comment by carmacleod** [comment]
See also https://github.com/w3c/aria-practices/issues/304#issuecomment-281832939
