### ISSUE TITLE
How to supply the accessible name for tabs (tab panel) widget

### ISSUE THREAD

**Issue by brooksienoodlesoup** [w3c/aria-practices#620]
Hi,
This is Brooks Newton writing to suggest an addition to the design pattern definition of 3.21 Tabs in the ARIA Authoring Practices 1.1.  Specifically, I think there needs to be guidance on how content authors should label a tabs widget as a whole, so that it is identifiable to assistive technology users.  My suggestion would be to advise content authors to supply a label for the element with `role="tablist"` via `aria-labelledby` or `aria-label` markup.  The working tabs examples you link to in 3.21 Tabs (automatic and manual activation) employ this tab list naming technique, however the design pattern instructions for WAI-ARIA Roles, States, and Properties doesn't mention providing an accessible name for the element with `role="tablist"`.

Thanks for Your Consideration,
Brooks

**Comment by mcking65** [comment]
This is resolved in commit 55b113f, which adds the language:

>If the tab list has a visible label, the element with role tablist has aria-labelledby set to a value that refers to the labeling element. Otherwise, the tablist element has a label provided by aria-label.
