### ISSUE TITLE
Example of error handling (validation) managed using ARIA attributes

### ISSUE THREAD

**Issue by devarshipant** [w3c/aria-practices#624]
1. There is a need of an example illustrating error handling (error prevention / validation) using varying combinations of:
1.1. aria-describedby; aria-labelledby
1.2. aria-invalid; aria-required
1.3. aria-live support
1.4. Focus management

**Comment by MichielBijl** [comment]
Thank you for the suggestion, I would like to see this too.

**Comment by mcking65** [comment]
This is issue #252, and it has work in progress. Closing as duplicate.
