### ISSUE TITLE
Navigation Menubar Example: the HTML standard contradiction

### ISSUE THREAD

**Issue by aristov** [w3c/aria-practices#628]
[The a element uses the menuitem role](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html). But this is [not allowed by the HTML standard](https://www.w3.org/TR/html/textlevel-semantics.html#ref-for-allowed-aria-role-attribute-values%E2%91%A2%E2%93%AA).

**Comment by jnurthen** [comment]
I recommend looking at https://www.w3.org/TR/html-aria/ which is more up to date.

menutiem is explicitly allowed on a elements with href.
