### ISSUE TITLE
For Navigation Menubar Example, aria-expanded should go on menu, not menuitem

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-practices#630]
I think there is a problem with the technique demonstrated on your [Navigation Menubar Example page](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html). Based on the [WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded) and [1.0](https://www.w3.org/TR/wai-aria/#aria-expanded) Recommendations, `menuitem` is not a role that uses the `aria-expanded` state.  The [SVG of the RDF model](https://www.w3.org/TR/wai-aria-1.1/img/rdf_model.svg) makes clear, visually, what roles are supported.  From my reading, `aria-expanded` should actually go on the `menu` that is being controlled itself, as that supports `aria-expanded` through inheritance from the `section` role.

**Comment by jnurthen** [comment]
This is due to an issue in ARIA 1.1 and is resolved by https://github.com/w3c/aria/issues/454 in ARIA 1.2
