### ISSUE TITLE
Figures in code guide on wiki have incorrect indentation

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#644]
The figures in the [code guide](https://github.com/w3c/aria-practices/wiki/Code-Guide) on the wiki have 4-space indentation instead of 2-space.

**Comment by MichielBijl** [comment]
In a previous issue we actually [decided on 4 spaces/1 tab](https://github.com/w3c/aria-practices/issues/19#issuecomment-226752006) to improve code readability.

**Comment by jnurthen** [comment]
@MichielBijl I don't know the history but you changed it back to 2 spaces in Sept. The entire doc is 2 spaces. I do not want to change this.
