### ISSUE TITLE
Code Guide uses 4 instead of the recommended 2 spaces for indentation

### ISSUE THREAD

**Issue by kleinfreund** [w3c/aria-practices#647]
This is a minor issue.

The [Code Guide](https://github.com/w3c/aria-practices/wiki/Code-Guide) consistently indents code examples by 4 spaces while recommending 2 spaces. This is contradicting and the examples should be updated to reflect the recommendation of 2 spaces as this is already the practice in the code examples in the actual repository.

**Comment by mcking65** [comment]
Dupe of #644.

**Comment by kleinfreund** [comment]
Oh, right. I simply did not search the existing issues. My bad.
