### ISSUE TITLE
what is purpose of Combo box autocomplete example button

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#648]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html

![image](https://user-images.githubusercontent.com/2365411/38886414-df1571ac-4243-11e8-99cf-b66b15492872.png)

There is a ```<button>``` element with ```tabindex="-1``` on it. Most of these these autofills in the wild don't have a button like that and I don't know what its value is.

**Comment by mcking65** [comment]
David, is it the down-arrow icon that mouse users can click to open the full list of possible values?

**Comment by DavidMacDonald** [comment]
yup, closing issue.
