### ISSUE TITLE
The 1.1 combobox examples don't read with JAWS 2018/Chrome or NVDA 2018.1.1

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#649]
However, the legacy drop down combo boxes read fine from ARIA 1.0.

https://www.w3.org/TR/wai-aria-practices-1.1/#combobox

to reproduce, load Chrome and JAWS or NVDA. tab to the combo, type the letter A to get a list of three items. Press down error.
None of the items in the list read.

**Comment by mcking65** [comment]
David, please raise screen reader and browser bugs with the screen reader and browser vendors.

We will soon have a place for this kind of assessment in the w3c/aria-at repo, but we have quite a bit of work to do yet at getting that project spun up.

**Comment by mcking65** [comment]
Closing as not an APG issue. If you find errors in the APG code that are responsible for the behavior, please re-open.
