### ISSUE TITLE
Draft guidance section for table properties (colspan, colindex, etc)

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#65]
Complete this section 
http://w3c.github.io/aria-practices/#gridAndTableProperties

[placeholder ]. This section will cover colcount, rowcount, colindex, rowindex, colspan, rowspan, and sort. It will explain when they are useful and how to use them. It is referenced by the grid and table design patterns. This section will refer readers to the grid and table design patterns for the basics of grid and table.

**Comment by rodrigoprestesmachado** [comment]
The aria-live session (http://w3c.github.io/aria/aria/aria.html#aria-live) in WAI-ARIA 1.1 document there is a link to Live Region properties in WAI-ARIA Authoring Practices 1.1 document. The link is "Please refer to Live Region Properties and How to Use Them ([WAI-ARIA-PRACTICES], Section 5.2.1)." (http://w3c.github.io/aria-practices/#liveprops). However, the session 5.2.1 doesn`t exist in WAI-ARIA Authoring Practices 1.1.

**Comment by mcking65** [comment]
With the above commits, this section is now complete.
