### ISSUE TITLE
The navigation button works great with VoiceOver, but the listbox is clunky

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#679]
The navigation menu button
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html

Works great with VoiceOver....user can tab to button, activate it and press down arrow through the choices. The virtual cursor on VO follows the arrow key.

The listbox on the other hand 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html

Requires the VO user to "interact" with it. So the VO user has to activate the button then press Shift+Control+Option+Downarrow, then Press CONTROL+OPTION+DOWN/UP ARROWS through the items. 

Listbox seems a lot more work for the end user and more room for confusion than the menu button.
Adding
@cookiecrook 
to conversation.

**Comment by DavidMacDonald** [comment]
Closing issue... Works in Safari, not in Chrome...

**Comment by cookiecrook** [comment]
Did you file a Chrome bug? cc @minorninth
