### ISSUE TITLE
Small typo, and recommendation to avoid using italics for blocks of text.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#682]
On the  disclosure widget
https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-img-long-description.html

there is a large amount of italicized text in the figcaption. I recommend regular text for that, its hard to read italics when its more than a few words.

Also small typo spelling of 
"wikipeedia" should be wikipedia.

**Comment by jnurthen** [comment]
Fixed Typo. If you want to to log the italics issue separately please do so but I'd prefer to keep separate issues in separate issues :)
The typo is easy to fix, the styling may impact more areas so will take longer to decide if it is something we want to do.
