### ISSUE TITLE
Immutable or conventional？Names of roles and states.

### ISSUE THREAD

**Issue by Wykay-z** [w3c/aria-practices#684]
Hello, I wonder whether names of roles and states of aria are immutable or conventional? 
For example, should a tab's role be only named by 'tab', or should a modal's role be only named by 'modal'? I realize that in the examples of modal and tab, the functional and keyboard are all written by pure javascript. Changing the role name or aria-controls name can also work.
So I wonder if the names are certain and will browser and screen reader need these certain attributes name to do something.
Thank you very much.

**Comment by jnurthen** [comment]
The available roles are defined in the aria specification. You need to use the roles and properties defined as they are used to map to the accessibility APIs.

**Comment by patrickhlauke** [comment]
you can change the javascript however you want. rewrite it from scratch, rework it in jquery. the important thing is that is has the same effect (sets the same attributes in the HTML, updates them appropriately, does the same keyboard handling, etc)

**Comment by Wykay-z** [comment]
@patrickhlauke I see, thank you.
