### ISSUE TITLE
Accordion Arrow Key Navigation

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria-practices#69]
Should accordions have an aria-orientation set to vertical for their tabs?

I ask because of the update to the tabpanel rule stating that "Horizontal tabs should not consume the up/down arrow as this will prevent users scrolling the page." But for tabs with vertical orientation, the up and down arrows can be used if aria-orientation is set to vertical.

Context: 
In testing an accordion component with users primarily using voice over and NVDA, their initial feedback primarily focused on confusion they had that the down arrow moved them to the next accordion tab, rather than moving them into the tab panel's content.

cc @MichielBijl

**Comment by mcking65** [comment]
We are replacing the accordian design pattern with one that does not use the tab or tabpanel roles.

**Comment by scottaohara** [comment]
Thanks @mcking65 looking forward to the new pattern
