### ISSUE TITLE
Menu button doesn't close on iOS with VO

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#695]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html

Running VoiceOver in iOS swipe to button, double tap to open. Then tried to double tap to close. Nothing I found works to close it.

PS. I know that mobile is not a priority this iteration of the document, but it's good to log issues for when it is.

**Comment by patrickhlauke** [comment]
it's also flawed on desktop. while just hovering over/out opens/closes the menu, if you actually click on the menu button it remains open. if you move the mouse away from it, click anywhere else on the page (to unfocus it), the menu still remains open, until you hover over it and then back out.

**Comment by robfentress** [comment]
See pull request #731

**Comment by mcking65** [comment]
@DavidMacDonald, thank you for raising the issue. @robfentress, thank you for submitting the fix. Our community is making progress together! This fix will be in release 2, which will be finished up this week and published on w3.org in mid July.
