### ISSUE TITLE
Example.js: HTML source display  for Modal Dialog Example is broken

### ISSUE THREAD

**Issue by aristov** [w3c/aria-practices#699]
I use Chrome Version 66 on Mac OS X.
When I go to the [Modal Dialog Example page](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) and open the developer console, I see the following error:

> Uncaught TypeError: Cannot read property 'childNodes' of null

The "HTML Source Code" section at the bottom of the example's page is displayed incorrectly.

**Comment by mcking65** [comment]
@aristov, this is fixed in the latest editor's draft. See:
http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html

If the resolution is not sufficient, please re-open with a comment.
