### ISSUE TITLE
Develop example that uses reflected properties from IDL section of ARIA 1.2 draft spec

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria-practices#701]
As a result of https://github.com/w3c/aria/issues/691, a new IDL section was added to the ARIA spec: https://w3c.github.io/aria/#idl-interface. If authoring guidance is deemed necessary, please add it. If not, please state so in this issue and close it. Thanks!

**Comment by mcking65** [comment]
Initial cut complete with commit 738eaa6.
