### ISSUE TITLE
Multi-select tree aria-selected="false" for all other nodes?

### ISSUE THREAD

**Issue by katiehockman** [w3c/aria-practices#702]
https://www.w3.org/TR/wai-aria-practices/#tree_roles_states_props

"If the tree does not support multiple selection, aria-selected is set to true for the selected node and it is not present on any other node in the tree.

if the tree supports multiple selection:
  - All selected nodes have aria-selected set to true.
  - All nodes that are not selected have aria-selected set to false."

Does this mean that every treeitem in a multi-select tree must have aria-selected="false" explicitly set? Or does the default value of "false" being set implicitly suffice?

**Comment by mcking65** [comment]
The default value of [aria-selected](http://w3c.github.io/aria/#aria-selected) is undefined, not false. So, this does mean explicitly setting aria-selected on all selectable treeitem elements in a multi-select tree.

**Comment by katiehockman** [comment]
Got it, thanks @mcking65
