### ISSUE TITLE
Spinbutton: Behavior when initial value, min and max are not on the same interval

### ISSUE THREAD

**Issue by 0ddfell0w** [w3c/aria-practices#706]
Looking for clarification on the behavior when a spinbutton is defined with a maximum or minimum value that is not reachable with up and down arrows.

E.g. initial value of 1, maximum value of 100, step_size of 10. Should hitting the End key bring me to 90 or 100?

The APG says
"End: If the spinbutton has a maximum value, sets the value to its maximum."

Perhaps we could amend this to say the greatest valid value in the range? Or we could specify that maximum and minimum should be on the same interval as the initial value?

**Comment by jnurthen** [comment]
I think this is an implementation decision. In some implementations the only valid values might be those which the step size allows. In others the step might be a convenience to allow quicker operations of a spinbutton where the exact value isn't so important.

As such either or both might be allowable. I don't think this needs specifying in the APG.

**Comment by mcking65** [comment]
0ddfell0w
@0ddfell0w, I agree with @jnurthen. Feel free to re-open if you do not feel your question is adequately answered.
