### ISSUE TITLE
Tree View multi-selection model questions

### ISSUE THREAD

**Issue by iannightingale** [w3c/aria-practices#708]
[https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView)

A few of questions surrounding the recommended Tree View multi-selection model:

1. > Shift + Space (Optional): Selects contiguous nodes from the last selected node to the current node.

Does this refer to the _most recently selected node_ or the node that is farthest down the list?

I ask because I believe that _most recently selected_ makes more sense, but in other locations this is explicitly stated, such as `Shift + Space` for Tree View's alternative selection model, or `Shift + Space` for both of [ListBox's](https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction) multiple selection models.

2. > Control + Shift + Home (Optional): Selects the node with focus and all nodes up to the first node.
Control + Shift + End (Optional): Selects the node with focus and all nodes down to the last node

Should focus remain unchanged in this instance, or should focus switch to be the first node and the last node, respectively?

**Comment by mcking65** [comment]
@iannightingale commented:

>1. > Shift + Space (Optional): Selects contiguous nodes from the last selected node to the current node.
>
>Does this refer to the _most recently selected node_ or the node that is farthest down the list?

Most recent.

>2. > Control + Shift + Home (Optional): Selects the node with focus and all nodes up to the first node.
>Control + Shift + End (Optional): Selects the node with focus and all nodes down to the last node
>
>Should focus remain unchanged in this instance, or should focus switch to be the first node and the last node, respectively?

I've seen it both ways. Windows Explorer moves focus. I don't recall where I've seen it remain unchanged, but there is some application I use where it does not move.

I made commit 3dab932 to clarify these questions for tree view.

I made commit 18158ea to make listbox consistent with changes to ctrl-shift-home and ctrl-shift-end in tree view.

@iannightingale, thank you for providing feedback with this issue. If the fixes are not sufficient, please feel free to re-open it.
