### ISSUE TITLE
Code examples with aria-live are doing weird things to VoiceOver

### ISSUE THREAD

**Issue by robdodson** [w3c/aria-practices#715]
I noticed if I have the ARIA authoring practices open in a separate tab, and I go to read a different page, VoiceOver will start announcing a bunch of HTML. It looks like all of the code examples have `aria-live` on them for some reason? For example, they all live inside of a `pre` element that looks like this:

```
<pre aria-busy="false" aria-live="polite" class="hljs xml">
```

We're filing a bug on the Chrome side, but I was wondering if it would make sense to remove those ARIA live regions because they don't seem to offer much value?

**Comment by jnurthen** [comment]
This was respec bug https://github.com/w3c/respec/issues/1456
The issue should be fixed in the editor's draft but we don't have any way of republishing.

The ARIA spec has the same issue.
