### ISSUE TITLE
Tabs Examples: UP and DOWN Arrows

### ISSUE THREAD

**Issue by AmyLiNow** [w3c/aria-practices#726]
Hi there!

The current WAI-ARIA [Tabs](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel) recommendation and example do not account for Up and Down arrow navigation for horizontal tabs. The current recommendation states that "If the tab list is horizontal, it does not listen for Down Arrow or Up Arrow so those keys can provide their normal browser scrolling functions even when focus is inside the tab list." 

This is an issue because it is impossible for a non-sighted user to reliably know in advance what the visual screen layout is for a widget, and such a user cannot be expected to use Left/Right arrow without textual instruction to do so. 

Providing Up and Down arrow navigation between horizontal tabs should be considered for non-visual users to navigate between tabs (and not scroll the page). See [ARIA Tab example](http://whatsock.com/tsg/Coding%20Arena/ARIA%20and%20Non-ARIA%20Tabs/ARIA%20Tabs%20(Internal%20Content)/demo.htm) by @accdc  (Bryan Garaventa)

**Comment by juanca** [comment]
Is this a good use case for [aria-orientation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-orientation_attribute)?

**Comment by jnurthen** [comment]
This is exactly the use of aria-orientation. Tabs are assumed to be horizontal unless aria-orientation="vertical" is specified. When this is added AT should add information to tell the user that the tab is vertical. JAWS at least does this. I haven't tested other screen readers.

**Comment by AmyLiNow** [comment]
@jnurthen If it is assumed that tabs are horizontal when not aria-orientation is specified, is it also assumed that the Left/Right keys are to be used to navigate between tabs? 
Or will instructions have to be provided to indicate that Left/Right keys must be used in a horizontal tab?

**Comment by accdc** [comment]
Though it is true that aria-orientation is implicitly horizontal, and that that this can be overridden by setting this to vertical, screen reader support for this is still limited and unreliable when combined with the roving tabindex model, and thus needs to be addressed before it can be recommended within enterprize production environments that require high levels of accessibility support. This issue is compounded by the continued public use of ARIA Tab markup within accordions as was the prior guidance of the 1.0 APG, as still exists in jQuery UI, which is always vertical.

I asked Amy to file this here to put this on the radar, because it came to my attention that people are blindly following the guidance here without doing as instructed in the Read Me section and actually testing them first for accessibility support before adding them to public facing sites.

**Comment by jnurthen** [comment]
Trapping up and down has negative consequences for magnification users who need to scroll the tab area. Adding these to the example would make the situation much worse for them.

**Comment by mcking65** [comment]
@AmyLiNow,

In this case, I think it is safe to say that we do not have 100% agreement among experts as to what is ideal for optimal accessibility. The APG task force attempts to represent the broadest consensus possible.

With arrow key navigation in a tablist, there are trade-offs between sighted keyboard and blind screen reader users. In previous discussions of this topic, such as issue #14, we have received feedback about the other side of this issue.

While deciding which way to go with the example, some things we consider:

1. Heuristic estimates of impact on various user groups based on things like browser behaviors, screen reader behaviors, etc.
2. Alignment with desktop conventions for the similar native widget
3. Community feedback

In this case, the impact of disabling scroll with up/down on sighted keyboard users is pretty high. The tabs and the rest of the web page are far more useable when scrolling works as expected.

However, the impact of supporting a single directional set of arrow keys on screen reader users is likely extremely low. Most tab lists both on native and web are horizontal, and most screen reader help defaults to horizontal instructions. Discovering that one type of arrow key works and the other does not is trivial given the assumption that the user expects to use arrow keys. I would be more concerned that a screen reader user would think that vertical tablist is broken when pressing right arrow than vice versa.

Just remember ... it is very rare that there is one perfect solution. And, the APG examples are not a standard; they are illustrations of one version of consensus best practice for ARIA implementation. What's most important about the APG examples is that they demonstrate correct ways of using ARIA to represent the semantics of a UI. The examples do not necessarily claim that the UI represented by the ARIA is itself a standard.
