### ISSUE TITLE
Review 1.2 IDL(Interface Definition Language) button example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#727]
The APG 1.2 [IDL Button Example](https://rawgit.com/w3c/aria-practices/apg-1.2/examples/button/button_idl.html) developed for issue #701 is ready for task force review.

**Comment by annabbott** [comment]
No issues noted in [APG 1.2 IDL Button Example](https://rawgit.com/w3c/aria-practices/apg-1.2/examples/button/button_idl.html).

**Comment by jnurthen** [comment]
In order to test this you need to run Chrome Canary and use the --enable-blink-features=AccessibilityObjectModel flag.

**Comment by scottaohara** [comment]
Testing this today with Firefox, Safari and Chrome on macOS.

Both buttons work as expected with Safari and Chrome with VoiceOver on or off.  

The mute button does not change state when mouse clicked with Firefox.
The SVG changes when using space or enter to toggle the button, though aria-pressed does not change.  It doesn't matter if i've turned on the AOM flag in firefox or not.

**Comment by mcking65** [comment]
Resolved with commit 3d83acd.
