### ISSUE TITLE
Tabs Pattern: Question about navigating to tabpanel from tablist

### ISSUE THREAD

**Issue by Decrepidos** [w3c/aria-practices#728]
When testing using the keyboard for navigation and I encounter a 'Tab Control', once I have read the tab panel/s I need to tab again the get out of the control. If the next focusable element is down the page I then need to arrow up the page to get back to after the Tab Control. It would be far more efficient if a global key (ESC) could be used to move the focus outside the Tab area.

**Comment by Decrepidos** [comment]
Answering my own question. This is why the tab panel needs to be focusable. Once I tab to the tab panel I can then just arrow down the page.

**Comment by jnurthen** [comment]
Can we close this?

**Comment by MichielBijl** [comment]
Arrow Up/Down should always work unless the tabs are vertical.

Or am I missing the point here?

**Comment by mcking65** [comment]
@Decrepidos, your answer to this is the same I would have provided. Closing, but feel free to re-open if any further clarification is needed.
