### ISSUE TITLE
Create utility to index the roles, properties and states used in examples

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#752]
Create a script to index the roles, properties and states used in the examples and generate a table of the results.

**Comment by mcking65** [comment]
@jongund, per our discussion today:

1. Create a shell file in the root directory named reference-tables.html
2. In reference-tables.html:
    1. at the top and bottom, include a link to "WAI-ARIA Authoring Practices  1.1"
    2. Include `<h1>Index</h1>`
    3. Include section "Design pattern examples by role"
    4. Include section "Design pattern examples by property and state"
3. In the aria-practices.html file:
    1. In the appendix section, create a section titled "Index"
    2. Ad links to each of the index tables

**Comment by mcking65** [comment]
This issue was closed when pull request #951 was merged to master in commit 5ec6c8f.
