### ISSUE TITLE
File directory treeview example doesn't populate edit field correctly in FF

### ISSUE THREAD

**Issue by jkshapiro** [w3c/aria-practices#760]
Steps to replicate:
1. Visit https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1b.html, using Firefox on Windows
1. Note that the "File or Folder Selected" field is blank.
1. Select the "Projects" folder in the example

Expected:
The "File or Folder Selected" field contains "Projects"

Observed
The "File or Folder Selected" field contains the following:
`<span class="focus">              Projects            </span>            <ul role="group">              <li role="treeitem" aria-level="2" aria-setsize="5" aria-posinset="1" class="doc" tabindex="-1">                project-1.docx              </li>              <li role="treeitem" aria-level="2" aria-setsize="5" aria-posinset="2" class="doc" tabindex="-1">                project-2.docx              </li>              <li role="treeitem" aria-level="2" aria-setsize="5" aria-posinset="3" aria-expanded="false" tabindex="-1">                <span>                  project-3                </span>                <ul role="group">                  <li role="treeitem" aria-level="3" aria-setsize="3" aria-posinset="1" class="doc" tabindex="-1">                    project-3A.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="3" aria-posinset="2" class="doc" tabindex="-1">                    project-3B.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="3" aria-posinset="3" class="doc" tabindex="-1">                    project-3C.docx                  </li>                </ul>              </li>              <li role="treeitem" aria-level="2" aria-setsize="5" aria-posinset="4" class="doc" tabindex="-1">                project-4.docx              </li>              <li role="treeitem" aria-level="2" aria-setsize="5" aria-posinset="5" aria-expanded="false" tabindex="-1">                <span>                  project-5                </span>                <ul role="group">                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="1" class="doc" tabindex="-1">                    project-5A.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="2" class="doc" tabindex="-1">                    project-5B.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="3" class="doc" tabindex="-1">                    project-5C.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="4" class="doc" tabindex="-1">                    project-5D.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="5" class="doc" tabindex="-1">                    project-5E.docx                  </li>                  <li role="treeitem" aria-level="3" aria-setsize="6" aria-posinset="6" class="doc" tabindex="-1">                    project-5F.docx                  </li>                </ul>              </li>            </ul>`

**Comment by mcking65** [comment]
@jkshapiro, thank you for the detailed bug report. I can reproduce the problem both in the published version and in the latest editor's draft in github.

**Comment by mcking65** [comment]
Thank you @carmacleod for the fix!
