### ISSUE TITLE
vnu checker not working from command line

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#763]
@nschonni, @jnurthen,

When I run npm test from command line, I'm not getting vnu errors. But, there are errors showing up in travis-ci when looking at a pr for the same branch I tested locally.

For example, working on treegrid branch, the validator is kicking out errors on pr 762 for aria-posinset and aria-setsize on tr elements. But, here is what I get when I run locally.

~~~
mck@MCK--243 MINGW64 ~/git/APG/main (treegrid)
$ npm test

> aria-practices@0.0.0 test C:\Users\mck\git\APG\main
> npm run lint && npm run vnu-jar


> aria-practices@0.0.0 lint C:\Users\mck\git\APG\main
> eslint .


> aria-practices@0.0.0 vnu-jar C:\Users\mck\git\APG\main
> java -jar node_modules/vnu-jar/build/dist/vnu.jar --errors-only --filterfile .vnurc --no-langdetect examples/**/*.html


mck@MCK--243 MINGW64 ~/git/APG/main (treegrid)
$
~~~

**Comment by nschonni** [comment]
Not a solution, but when I run `chcp.com 65001` to set the code page to UTF-8, the quotes work but the filtering still doesn't

**Comment by mcking65** [comment]
no longer an issue
