### ISSUE TITLE
Editor menubar example: menuitem, group, and separator errors in roles, states, and props table in menubar/menubar-2/menubar-2.html

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#781]
In [menubar/menubar-2/menubar-2.html](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html):
- [ ] In the "Role, Property, State, and Tabindex Attributes" table for "Menubar" -- role="menuitem" will be found on a `a` element not an `li` element
- [ ] the `aria-label` attribute exists on the `role="group"` elements -- potentially this should be documented in the  "Role, Property, State, and Tabindex Attributes" table for "Submenu"?
- [ ] The role separator is used on a `li` element and should be documented.

**Comment by nschonni** [comment]
I'm also seeing the `rel` stuff flagged too https://github.com/w3c/aria-practices/pull/779#issue-201835246
