### ISSUE TITLE
examples.js: Closing `li` tag omitted from HTML source display when `li` is empty and has role separator

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#792]
The examples/js/examples.js script leaves closing tags for `li` elements with role separator out of the HTML source display  for 
the [editor menubar example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html).

Instead of:

~~~
<li role="separator"></li>
~~~

It shows:

~~~
<li role="separator">
~~~

**Comment by mcking65** [comment]
A second thought is that if the problem is that the `li` is empty, perhaps a better way to code the menu would be:

`<li role="presentation"><span role="separator"></span></li>`

**Comment by kleinfreund** [comment]
I cannot reproduce the initial report. This was behaving as reported before #653. Both on the live example page and the current state of the master branch, the `li` tag is properly closed.

**Comment by mcking65** [comment]
Verified no longer an issue.
