### ISSUE TITLE
aria1.0 combobox autocomplete both example: When edit not empty and matches appear, Up Arrow  does not set activedescendant to last match in list

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#821]
Hey all, there is a bug with aria-activedescendent in the aria [1.0 combobox-autocomplete-both example](https://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html).

To replicate:
1. focus on the textbox
2. Type "a"
3. Press "up arrow"
   a. Notice that aria-activedescendent is not set on the textbox although the first entry is highlighted and autocompleted in the textbox. It looks as if visual focus is on the textbox still as well

Note that "down arrow" works if you use it instead of up arrow in step 3 above.

This bug was caught by writing tests! :)

**Comment by mcking65** [comment]
Interesting ... The value changes to Arkansas, but activedescendant is not set to point to Arkansas.

Unlike down arrow, I also see that the keyboard table entry for up arrow only describes what happens when the text box is empty, it does not say anything about what will happen when it is not empty. That implies nothing would happen. However, the current behavior of moving to the last value in the popup seems reasonable.

@jongund, @accdc, do you have thoughts on this?

**Comment by jongund** [comment]
Just so I understand the aria-activedescendant should point to any exact match of an option in the list with the textbox value?

Jon

**Comment by mcking65** [comment]
>Just so I understand the aria-activedescendant should point to any exact match of an option in the list with the textbox value?

No ... there are times where there is a match but focus is in the textbox. We don't want to change that.

This is only about whether up arrow sets activedescendant if it was not previously set. It is happening when the textbox is empty, but not when the textbox contains a matching substring.

The question is whether we think up arrow should do that. It seems logical to me; it would be the inverse of down arrow, which seems appropriate given that up/down mirror each other when the textbox is empty. So, why not mirror each other when the textbox contains a string that matches a set of one or more options.

**Comment by jongund** [comment]
I will look into adding up arrow

**Comment by mcking65** [comment]
@jongund, thank you for your help with this.
@spectranaut, is there any f/o action on the test side here?
I'm closing this one as it is resolved.
