### ISSUE TITLE
Collapsible Dropdown Listbox Example mobile VO bug

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria-practices#836]
Hey there,

I was [reviewing the listbox example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html) today and tried to interact with it on my iPhone with VoiceOver. (latest iOS on iPhone 7 Plus).

When double tapping to open, the listing of options displays for a brief moment before immediately closing again, rendering the options unreachable.

I'm going to poke around with this some more.  If I can find anything else that could be helpful, I'll post back.

Thanks

**Comment by scottaohara** [comment]
Doing some more tests on this today, TalkBack + Android Chrome (on Android 8.1.0) doesn't experience this issue.

It appears that it may be partially due to the VoiceOver bug where VO focus won't move to an element that was previously set to `display: none` unless there's a short delay added, or instead of `display: none`, `visibility: hidden` is used to hide the element.

For instance, changing the `.hidden` class to use `visibility: hidden`, VoiceOver did move focus to the first element in the drop down.  Unfortunately this didn't solve the issue of the drop down still disappearing (which then created a situation where VO was focused on an element that had then been hidden).  This makes me wonder if it's something with how Safari is handling blur.

Anyway, I can't look into it much more now, but I hope this is at least somewhat helpful.

Thanks

**Comment by mcking65** [comment]
closing as won't fix since we have deprecated collapsable dropdown listbox in favor of select-only combobox.
