### ISSUE TITLE
Lorem ipsom in alert dialog example

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#840]
Currently this example has a little Lorem ipsom text https://github.com/w3c/aria-practices/blob/c57878b239666a80b2cf82f38b0858a82655042a/examples/dialog-modal/alertdialog.html
I think maybe that should be avoided, but maybe it's a legitimate use.

**Comment by mcking65** [comment]
I agree that this example would be better with english instead of the lorem ibsom.

Thank you @nschonni for the suggestion and @patrickhlauke for the PR.
