### ISSUE TITLE
Listbox Examples - Dependencies - Utils.js?

### ISSUE THREAD

**Issue by gmize** [w3c/aria-practices#842]
**Collapsable List Box**
It appears that utils.js is a dependency of the list box examples ( after going through source code ), however, unless I missed it somewhere, its not specified as such.  ( the main issue with it was `aria.KeyCode = ...` was missing, then I noticed other references to utils.js ).

I'm still getting erratic behavior such as, although it now sort of works, it allows "enter" or "down arrow" to activate/expand the list box and allows use of arrows to move to an item in the list, however, **on the second press of the down arrow it collapses the list box and focus goes to top of the page** ( latest Chrome browser ).

Wanted to throw this out there to see if I'm missing something else? Otherwise I will proceed to "debug" and "fix" it as is.

**using these resources:**
utils.js
listbox.js
listbox-collapsable.js 

listbox.css

**Comment by jnurthen** [comment]
utils.js is used by other examples too:
feed/feedDisplay.html
grid/advancedDataGrid.html
toolbar/toolbar.html
dialog-modal/alertdialog.html
listbox/listbox-scrollable.html
listbox/listbox-collapsible.html
combobox/aria1.1pattern/grid-combo.html
dialog-modal/dialog.html
grid/dataGrids.html
listbox/listbox-rearrangeable.html
combobox/aria1.1pattern/listbox-combo.html
grid/LayoutGrids.html

@mcking65 Should this dependency be added to each of the examples or should we add a more general notice that other dependecies may exist?

**Comment by gmize** [comment]
Follow up to original post:

Although I wasn't able to get the example working quite right locally on its own ( obviously works on the aria practices site so I must still be missing something ) I was able to implement it and easily make it work in an actual implementation on our own sites.  Tweaked it a bit for our needs as well and working great!  

Thanks much

**Comment by willthemoor** [comment]
Hello! Came to report the same: https://www.w3.org/TR/wai-aria-practices-1.1/examples/js/utils.js is required for the listbox examples to work. Would be good to include a link to it in the "Javascript and CSS Source Code" section.

I tried dumping the content of all three links from that section into codepen and kept getting `Cannot read property 'addClass' of undefined`. Had to inspect the source/network on the demo page to learn that it was because `aira.Utils` didn't exist.

**Comment by mcking65** [comment]
This dependency should be listed in the source code section of the example page. Also, we need to make sure that it is loaded into codepen by the script developed for #1102.

**Comment by spectranaut** [comment]
If we add it to the source doe section, it will be automatically loaded. I think we might want to just add it to the source code section manually.
