### ISSUE TITLE
 Bug in documentation combobox/aria1.0pattern/combobox-autocomplete-list.html: "enter" key when focus is on textbox

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#855]
Hey @mcking65 -- I believe the documentation for "enter" key in the "Textbox Keyboard Support" table is misleading for [this example](https://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html).

I'm working from the following assumption, which I've made for all the combobox example keyboard support table and I'd like if you could confirm for me:
  1. The "Textbox Keyboard Support Table" indicates the behavior of the widget if the key is sent to the textbox while the visual focus is on the textbox (aria-activedescendent is not set)
  2. The "Listbox Keyboard Support Table" indicates the behavior of the widget if the key is sent to the textbox while the visual focus is on the listbox (the dom focus is still on the textbox in these cases, as these widgets all use aria-activedescendent to indicate the visual focus)

About the potential bug:

The documentation for "enter" key for the "Textbox" table says: "Sets the textbox value to the content of the selected option. Closes the listbox." 

In this example, however, it is not possible for visual focus to be on the textbox while an option is selected. So sending "enter" to the textbox never changes the  value of the textbox. It does close the listbox, however. Should the table be update to reflect this?

**Comment by mcking65** [comment]
Yes, the documentation on the example page is wrong. For this case, since there is no automatic selection, the pattern does not specify a behavior for enter. So, the behavior of collapsing the listbox is not specified by the pattern. That does not mean it is a problem to have it in the example though.

We may want to add the behavior that is in the example as an optional behavior in the pattern.

For now, I will just correct the documentation on the example page.

**Comment by spectranaut** [comment]
Hi @mcking65 -- there is also an entry for "enter" in the textbox keyboard interaction table in the [combobox-autocomplete-none example](https://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-none.html). Sounds like this entry should be removed as well.
