### ISSUE TITLE
Bug in documentation combobox/aria1.1pattern/grid-combo.html: "aria-selected" on row or gridcell?

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#859]
On the [grid-combo example](https://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/grid-combo.html), the "Grid Popup" attribute table describes the "aria-selected" attribution as:
* Specified on a row in the grid when it is visually indicated as selected.
* Occurs only when a cell in the grid is referenced by aria-activedescendant.

However, in the example, "aria-selected" is on the gridcell. The attribute is always on the first gridcell (of the gridcell pairs in a single row), so it always indicates the string that will be selected with an "enter" key. Both implementations of "aria-selected" seem valid (the example and the documentation), which on is preferred?

**Comment by mcking65** [comment]
Resolved with #2139
