### ISSUE TITLE
Bug in examples treeview/treeview-2/*: key "left arrow" does not move to parent folder

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#866]
To replicated:

* Open the "Fruit" folder
* Move focus to the "Bananas" link
* Press `arrow left` key
  * Bug: Focus moves to the "Apples" folder instead of the parent "Fruit" folder

In all other instances, the `arrow left` key works as expected.

**Comment by mcking65** [comment]
This example was removed and replaced by the nav tree example with #1558 
Closing.
