### ISSUE TITLE
Add example on how to use landmarks in skip to links

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#868]
The landmark practices talk about the capability to use landmarks for supporting skip to links.  Include a code example to illustrate how this may be done.

**Comment by carmacleod** [comment]
Here's the sentence in the [Landmark Regions section of the APG](http://w3c.github.io/aria-practices/#aria_landmark):
> Landmark regions can also be used as targets for "skip links" and by browser extensions to enhanced keyboard navigation.

(Nit Note: need to change "enhanced" to "enhance" in that sentence)

**Comment by mcking65** [comment]
Don't we already demonstrate this on every [landmark example page](http://w3c.github.io/aria-practices/examples/landmarks/banner.html)? We have a skip-to keyboard menu that uses landmarks for targets.
