### ISSUE TITLE
ARIA practices spec and examples are not aligned on ARIA 1.1 combobox labelling

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria-practices#886]
The ARIA 1.1 spec says, "If the combobox has a visible label, the element with role combobox has aria-labelledby set to a value that refers to the labeling element. Otherwise, the combobox element has a label provided by aria-label."  
https://www.w3.org/TR/wai-aria-practices-1.1/#combobox

However, the ARIA practices combobox (https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html#ex1) with listbox example does not do this:
- It assigns a label to the textfield and not the combo box. 
- Also, it uses `<label for>` even though the spec says to use aria-labelledby to label the combobox with visible text.

If the ARIA spec were followed by the example, then NVDA would get it right, but not JAWS or ChromeVox. I'm not near my Mac, so I'm not sure about VoiceOver.

We need to know what's correct, the example or the ARIA practices spec?

**Comment by aleventhal** [comment]
Attaching example using aria-labelledby on the role="combobox" object:
[combo-labelledby.html.gz](https://github.com/w3c/aria-practices/files/2381030/combo-labelledby.html.gz)

**Comment by accdc** [comment]
Support should always follow the spec, because that is the only normative document.

**Comment by devarshipant** [comment]
@aleventhal -- Something related; in [Example 1: List Autocomplete with Manual Selection](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html), the acc name of combobox is derived from for / id on label and input elements respectively. 

This requirement is helpful as it ensures larger click area.

![for-id label input](https://user-images.githubusercontent.com/7377040/45637588-e70c8780-ba78-11e8-863a-cfc612fb31b9.png)


Examples 2 and 3 implement it differently via aria-labelledby on input. 

`<label id="ex2-label" class="combobox-label">
          Choice 2 Fruit or Vegetable
        </label>`
...
`<input type="text" aria-autocomplete="list" aria-controls="ex2-listbox" aria-labelledby="ex2-label" id="ex2-input" aria-activedescendant="" class="">`

**Comment by carmacleod** [comment]
@accdc said:
> Support should always follow the spec, because that is the only normative document.

Agree completely, but the [ARIA 1.1 spec for combobox](https://www.w3.org/TR/wai-aria-1.1/#combobox) doesn't really say where to put the label, although Example 5 does show it on the combobox element and not on the textbox. Are examples normative?

@aleventhal I think you meant "practices guide" and not "spec" in your opening sentence.  :)

**Comment by carmacleod** [comment]
Related ARIA issue: https://github.com/w3c/aria/issues/893

**Comment by aleventhal** [comment]
Related ARIA issue: 1776

**Comment by mcking65** [comment]
This has been resolved with the APG 1.2 pattern and combobox examples. The combobox wrapper is now gone so the label belongs on the input, which is now also the combobox element.
