### ISSUE TITLE
In the role=search example the role is on the form element

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#893]
http://w3c.github.io/aria-practices/examples/landmarks/search.html

Would it be better to put that on a ```div``` or a ```span```  around the input? I'm concerned about overriding the ```form``` element.

**Comment by jnurthen** [comment]
Does https://github.com/w3c/html-aria/issues/18 answer your question

**Comment by mcking65** [comment]
This is allowed per referenced issue. Closing.
