### ISSUE TITLE
Bug in example menu-button/menu-button-actions-active-descendant.html: tabindex

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#894]
In the documentation for example [menu-button/menu-button-actions-active-descendant.html](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html):

The `tabindex` row of the "Role, Property, State, and Tabindex Attributes" table for the `menu` element claims the `tabindex` of the menu element should be `-1`. It is actually set to '0'. I'm not sure if the documentation or the example is correct.

**Comment by jongund** [comment]
This issue can be close, this issue was resolved long ago.
