### ISSUE TITLE
Draft disclosure (show/hide) design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#9]
_From @stevefaulkner on May 25, 2015 13:31_

expand/collapse or disclosure pattern is common on the web (HTML native UI is details/summary), but there is no design pattern. Suggest adding one
a few examples:
http://thepaciellogroup.github.io/disclosure-button/
http://codepen.io/stevef/pen/jiCBE
http://webcloud.se/jQuery-Collapse/

_Copied from original issue: w3c/aria#61_

**Comment by MichielBijl** [comment]
_From @jnurthen on July 8, 2015 16:28_

Agree - we will get this done.

**Comment by MichielBijl** [comment]
Work on this can be done in the [details branch](https://github.com/w3c/aria/tree/details).

**Comment by mcking65** [comment]
The [disclosure design pattern in master](http://w3c.github.io/aria-practices/#disclosure)
 now includes:

* an outline of content.
* Initial draft of keyboard section.
* links to two example implementations.

This should now be a simple one for someone to pickup and complete. Takers??

**Comment by MichielBijl** [comment]
@mcking65 what is your question? Does this need review? Or maybe a code example?

**Comment by KimJaeGwan** [comment]
@MichielBijl 
 What is the difference between Accordion and Disclosure? In particular, the [jQuery-Collapse](http://webcloud.se/jQuery-Collapse/) example does not make a difference between Accordion and Disclosure.

**Comment by mcking65** [comment]
A disclosure is a button for showing and hiding a single container. You could think of a simple accordion as a set of 2 or more disclosures where each button is also wrapped in a heading.

If you read through the [accordion pattern](http://w3c.github.io/aria-practices/#accordion), you'll also find accordions can have a variety of features that make the set into an integrated component. Additionally, the collapsed state of each panel may show considerably more than just the expand/collapse control.

**Comment by KimJaeGwan** [comment]
@mcking65 Thank you. The question has been resolved.

**Comment by mcking65** [comment]
This work is now complete and the review process has been started in issue 493.
