### ISSUE TITLE
Bug in example: menubar/menubar-1/menubar-1.html (role="none")

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#906]
In the [menubar-2 example](https://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html#), the documentation in the "Role, Property, State, and Tabindex Attributes" table for "Menubar" has an entry for `role="none"` on `li` elements:
* Removes the implied listitem role of the li element.
* Necessary because the parent ul is serving as a menu so the li elements are not in their required list context.

There is also a `role="none"` entry in the "Submenu" table. I think this documentation SHOULD say:
* Removes the implied listitem role of the li element.
* Necessary because the parent ul is serving as a (EDIT menu to menubar) **menubar** so the li elements are not in their required list context.

Is this a bug in example?  If this is so, the `li` children of the `menubar` element should have `role="none"`, but they do  not, in which case this is a bug.

Or, is this bug in documentation?  If the `li` children of the `menubar` element do not need to have `role="none"`, this row should be removed, because the `role="none"` scenario is covered in the "Submenu" table.

**Comment by jnurthen** [comment]
Seems like #930 covers this. Please re-open if this is incorrect.
