### ISSUE TITLE
radio-2/radio-2.html example: Incorrect element information in attributes table

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#917]
There is one small book in the [radio/radio-2/radio-2.html](https://w3c.github.io/aria-practices/examples/radio/radio-2/radio-2.html) example in the 'Role, Property, State, and Tabindex Attributes' table:

The `radiogroup` role and the `aria-labelledby` attribute should both have `ul` in the Element column.

**Comment by mcking65** [comment]
Fixed with commit 30af679.
