### ISSUE TITLE
Bugs in example: listbox/listbox-rearrangeable.html (multiselect keyboard interactions)

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#919]
In chrome on linux, the following key commands do not work in the second example implementation on the example page [listbox/listbox-rearrangeable.html](https://w3c.github.io/aria-practices/examples/listbox/listbox-rearrangeable.html):
- Shift + Down Arrow
  - Instead, the behavior is the same as down arrow
- Shift + Up Arrow
  - Instead, the behavior is the same as up arrow
- Control + Shift + Home
  - Instead, the behavior is the same as home
- Control + Shift + End
  - Instead, the behavior is the same as end
- Control + A
  - Instead, all of the text on the web page is selected

**Comment by jnurthen** [comment]
(I can't get these keys to work in FF on Mac either)

**Comment by charmarkk** [comment]
I also had this issue recently with IE and Chrome on Windows 10, as well as Safari.

**Comment by shirsha** [comment]
Sorry, I could not get to updating this issue till now.
   Thanks Mark for updating it for me.

**Comment by charmarkk** [comment]
All - Chris Mills over at MDN says this isn't an issue on MacOS any longer. I'll check into it myself, but might be worth others checking too.

**Comment by a11ydoer** [comment]
The key commands issues still exist when I checked with **Chrome** on **MacOS**. I am assigning this bug to @jongund for him to review.

**Comment by smhigley** [comment]
Does this work in any browser? I don't see any code to handle it, so I'd be a bit surprised if it did 😄.

**Comment by charmarkk** [comment]
@smhigley it appears to work without fault in Firefox on Windows. 🤷‍♂

**Comment by JAWS-test** [comment]
> it appears to work without fault in Firefox on Windows

On my computer they do not work in Chrome and Firefox under Windows. But these access keys are only marked as optional.

**Comment by charmarkk** [comment]
` On my computer they do not work in Chrome and Firefox under Windows. But these access keys are only marked as optional.`

And so the plot thickens - good to know, thanks for that!

**Comment by smhigley** [comment]
@charmarkk you're talking about the shift + arrows/home/end and control + A, right? That doesn't work for me in any browser in Windows, including Firefox (which is my main browser) 😄.

I think the plot actually thins -- there is no script to implement those keys, so they don't work anywhere 😂

**Comment by carmacleod** [comment]
FF 73.0.1 and Chrome 80.0.3987.116 on Windows 10, [Example 2](https://w3c.github.io/aria-practices/examples/listbox/listbox-rearrangeable.html#ex2_label) does not work as advertised in the [Multiple selection keys supported in example 2](https://w3c.github.io/aria-practices/examples/listbox/listbox-rearrangeable.html#kbd_label_multiselect) table.

**Comment by charmarkk** [comment]
@smhigley @carmacleod you're correct - my poor brain this Monday morning. Those keys indeed **do not** work as written. Thank you~

**Comment by smhigley** [comment]
I'm working on an implementation now 👍
