### ISSUE TITLE
Add Landmarks browser extension to Landmarks example Resources page

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#935]
The [Landmarks browser extension](http://matatk.agrip.org.uk/landmarks/) by @matatk should be in the list of landmarks Tools on the [Landmarks example Resources page](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/index.html).

**Comment by carmacleod** [comment]
The PR adds this as the first tool in the list because it supports ARIA 1.1 landmark roles, HTML5 section elements that have implicit landmark roles, and Digital Publishing Landmarks.

**Comment by mcking65** [comment]
Thank you @carmacleod. Assuming that extension works as advertised, this is a good addition.

Side note (separate issue perhaps), I don't recall the task force conducting a thorough vetting of those resources when we made the giant merge of all the landmark pages. Given that these are external resources, there should probably be some kind of disclaimer note. Even if we vet them, they could change over time and we would not be part of that process. So, we should not imply endorsement.

**Comment by carmacleod** [comment]
Agree that we should not imply endorsement of the external resources, for the reasons you stated.

I will vouch for @matatk's Landmarks extension - it is excellent, and it keeps getting better.
@matatk is with TPG, and they have generously donated some time for him to work on it.

As a sighted developer, I use the extension to help me see (and design) the landmarks on our pages...
(and to peek at the landmark layout on other people's pages, too.  ;)
As a user, I use it to navigate to landmarks with the keyboard.

Here's a bit of background on some of the [past](https://developer.paciellogroup.com/blog/2017/05/improving-access-to-landmark-navigation/), [recent](http://matatk.agrip.org.uk/articles/landmarks-extension-dynamism-and-skip-to-main/), and [future work](http://matatk.agrip.org.uk/articles/reinventing-landmarks-at-glacial-speed/) on this extension.

**Comment by matatk** [comment]
It looks like this has begun to get merged, so just wanted to say thanks for the shout out and recommendation @carmacleod :-).

**Comment by mcking65** [comment]
This is merged to master and in the current publication.
