### ISSUE TITLE
Accordion uses roles to over ride definition list

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#940]
Is there any value in the `dl` and `dt` and `dd`? They are being overridden by a role, why not use divs or spans or headings etc... it seems to add a level of complexity which is not necessary... a fair number of Johnny lunch box devs will have to look up those elements even they they don't add value to a screen reader.

**Comment by jnurthen** [comment]
https://github.com/w3c/aria-practices/issues/815
