### ISSUE TITLE
ARIA 1.0 Combobox examples: duplicate IDs

### ISSUE THREAD

**Issue by afercia** [w3c/aria-practices#953]
In the legacy ARIA 1.0 Combobox examples, two State options have the same ID:

Both New Mexico and Northern Marianas Islands have the ID `lb1-nm`:

<img width="458" alt="screenshot of the options markup" src="https://user-images.githubusercontent.com/1682452/49685692-18c94380-fae8-11e8-8fda-590cae964ff6.png">

Thus, screen readers behavior is affected and unpredictable: sometimes they announce the selected option, sometimes the one with the first ID occurrence:

![Safari 12 and VoiceOver announcing New Mexico instead of Northern Marianas Islands](https://user-images.githubusercontent.com/1682452/49685722-de13db00-fae8-11e8-9308-10cf29276896.png)

Note: this applies also to the Authoring Practices 1.1 examples.

**Comment by nschonni** [comment]
This was fixed in #820, are you running an old fork?

**Comment by afercia** [comment]
Seems to me the examples on the draft are OK, the IDs are `lb1-nm` and `lb1-mp`. Thank you.

The examples in the practices 1.0 are affected too, should I create a separate issue somewhere or will they be fixed together with the new examples?

**Comment by mcking65** [comment]
1.0 examples have been sunset for APG 1.2. They are superseded by the 1.2 examples.
