### ISSUE TITLE
Consider creating a multi select list box.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#956]
Looking for a multi select list box.

**Comment by charmarkk** [comment]
You might check over here, under [listbox](https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox). Though, browser support can be spotty (see issue #919).

**Comment by mcking65** [comment]
Correct ... the multi-select example is here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-rearrangeable.html
