### ISSUE TITLE
Possible confusing language in Radio Group pattern section

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#96]
Copied from w3c/aria#426 raised by @macgyver.

I am implementing a radio button group and I was wondering about the instructions here
https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton

Specfiically this bit:
> Space selects the radio button with focus and de-selects other radio buttons in the group.

Slightly before that, it says that left/right/up/down keys should cycle through the options of a radio group by focusing and selecting them. Can you explain how it is possible to focus a radio option without selecting it, such that the `space` key would then be necessary to select it?

I hope this is the right place to raise a question like this, please let me know if you know of a better place, thank you!

**Comment by mcking65** [comment]
@macgyver, you are right; it is confusing. I will fix it.

The only time focus lands on a radio that is not selected is when you move focus inside of a group where none of the buttons are selected. In this case, space would focus the radio that has focus. It would not effect any other buttons. In all other circumstances, when you tab to a radio group, focus should land on the selected radio button.

**Comment by macgyver** [comment]
Thanks for the info! It makes sense now. In hindsight I think I could have figured it out from this section:
> Tab: Moves focus into and out of the toolbar. When focus moves into the toolbar, the first enabled control receives focus. Optionally, if the toolbar has previously contained focus, the control that last had focus may receive focus.

**Comment by mcking65** [comment]
@macgyver, an updated version of the radio group design pattern can be seen in the editor's draft at:
http://w3c.github.io/aria-practices/#radiobutton

It includes the changes in commit bab23225c3059da615afc7d2cde9993691d16da5.

**Comment by macgyver** [comment]
Very clear now, thanks!

**Comment by mcking65** [comment]
Closed based on feedback in August 29, 2016 APG meeting.
