### ISSUE TITLE
Should the listbox add keyboard command ALT+DOWNARROW to open

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#966]
Currently the ALT+DOWNARROW is not listed in the keyboard Interactions section
https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox

I understand this to be a standard way to open list boxes.
The example opens on ALT+DOWNARROW, but the keyboard section doesn't mention that interaction pattern either.
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html

**Comment by ZoeBijl** [comment]
Closed because this has been moved to combobox I reckon?
