### ISSUE TITLE
ARIA 1.1 Combobox with Listbox Popup Examples - issue with onBlur

### ISSUE THREAD

**Issue by gaurav5430** [w3c/aria-practices#982]
As i start typing 'A', the listbox appears with options Apple, Artichoke, Asparagus.
I press down, it selects Apple,
the listbox is still open,
now if i click on Artichoke 
the listbox closes, but the selection is Apple.
I would expect the selection to be Artichoke, since i clicked on it.

To me, the issue seems to be because of the blur event. 
the blur handler is called before the click handler in this case, and it selects the already selected item (which was selected by keyboard) and then the click handler is not called at all.

Though in the usual case, where we don't use keyboard selection, the blur and click events are fired one after another.

so possibly something to do with some kind of delay between blur and click ?
it seems that if blur event hides the clickable element , the click event does not go through.

**Comment by mcking65** [comment]
@gaurav5430 commented:

> As i start typing 'A', the listbox appears with options Apple, Artichoke, Asparagus.
> I press down, it selects Apple,
> the listbox is still open,
> now if i click on Artichoke
> the listbox closes, but the selection is Apple.
> I would expect the selection to be Artichoke, since i clicked on it.

I would expect the same, good catch!

**Comment by gaurav5430** [comment]
The way I handle it in my combobox is to prevent the blur from being fired if the click is from within the listbox, and manually fire the blur at the end of the click handler.
Is it ok if I create a PR for this fix?

**Comment by Abhishek-Kanitkar** [comment]
Thanks for giving at least some solution to this issue :+1:

**Comment by Abhishek-Kanitkar** [comment]
> The way I handle it in my combobox is to prevent the blur from being fired if the click is from within the listbox, and manually fire the blur at the end of the click handler.
> Is it ok if I create a PR for this fix?

@gaurav5430  do you know why the blur event is needed ?

**Comment by gaurav5430** [comment]
@Abhishek-Kanitkar The blur event is used in this case to hide the popup, when the user moves focus away from the input using a keyboard.
 Similar to how we have something like onClickOutside for checking an outside click which would mean focus has moved away from the input and we should hide the popup, this is for similar functionality when using a keyboard to move focus away from the input.

**Comment by jongund** [comment]
This issue should be fixed in [pull request 1276](https://github.com/w3c/aria-practices/pull/1276)

**Comment by carmacleod** [comment]
I can confirm that this issue will be fixed after PR https://github.com/w3c/aria-practices/pull/1276 is merged.

I tested with the following preview links, and the issue does not occur there:
* [Preview combobox autocomplete=both](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-both.html)
* [Preview combobox autocomplete=list](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-list.html)
* [Preview combobox autocomplete=none](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-none.html)

**Comment by mcking65** [comment]
Excellent, @carmacleod, thank you for the testing!

I'll use the cool new github issue/pr linking feature to link this issue to #1276.
