### ISSUE TITLE
Toolbar Example: Make clicking padding move focus into toolbar

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#987]
Per [comment in issue 539](https://github.com/w3c/aria-practices/issues/539#issuecomment-454870090)
by @sh0ji about the [toolbar example](http://w3c.github.io/aria-practices/examples/toolbar/toolbar.html),
make clicking the padding of the toolbar (the gray #ECECEA part) move focus into the toolbar.
This enables people to use their mouse to orient their focus and then use their keyboard to navigate inside the toolbar.

**Comment by ardnahcivar** [comment]
@mcking65 , could you please elaborate the issue,  i am unable to get it.

**Comment by sh0ji** [comment]
When a keyboard user first tabs into the toolbar, both the currently focused control AND the entire toolbar are visually focused via the dark blue outline. The entire toolbar gets a visual focus to convey to sighted users that it's a composite widget and that focus is managed within that larger container (arrow keys move focus inside of the toolbar).

This change would allow mouse users to set focus on the toolbar without having to actually click a control, something that's not currently possible.

**Comment by maschad96** [comment]
Hi @jongund, @sh0ji  , I submitted a PR for this. Would you mind reviewing and providing feedback when time allows? 😃
