### ISSUE TITLE
Combobox Example 3: List with Inline Autocomplete doesn't work with mouse

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#988]
[Combobox Example 3: List with Inline Autocomplete](http://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) doesn't work with mouse

It seems to be impossible to choose anything except "Apple".  :)

**Comment by jnurthen** [comment]
Reproduces on iOS with touch too.  Cannot select anything else.

**Comment by Abhishek-Kanitkar** [comment]
I am also observing the same issue.

**Comment by Abhishek-Kanitkar** [comment]
> [Combobox Example 3: List with Inline Autocomplete](http://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) doesn't work with mouse
> 
> It seems to be impossible to choose anything except "Apple". :)

@carmacleod  in this issue, the same thing is reported & see the solution proposed

https://github.com/w3c/aria-practices/issues/982#issuecomment-460583843

Do you know via we need blur event ?

**Comment by carmacleod** [comment]
I retested using the examples in PR https://github.com/w3c/aria-practices/pull/1276:
* [Preview combobox autocomplete=both](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-both.html)
* [Preview combobox autocomplete=list](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-list.html)
* [Preview combobox autocomplete=none](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-none.html)

This problem will be fixed after PR https://github.com/w3c/aria-practices/pull/1276 is merged.

**Comment by mcking65** [comment]
Thank you @carmacleod, linking to #1276.
