### ISSUE TITLE
Deployment is canceled because Regression Tests Coverage Report job fails

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#992]
Master has not been deployed since https://github.com/w3c/aria-practices/commit/ca78f0a602a80ba904f7b8a83c1d9fc2e461998c (15 Jan) - the next commit https://github.com/w3c/aria-practices/commit/a161bc69c17bad429253cf3b7c99986eeda1fa67 started failing the Regression Tests Coverage Report job. I believe https://github.com/w3c/aria-practices/issues/965 tracks this. The result is that http://w3c.github.io/aria-practices/ is missing changes (I noticed this because I found a broken link, which [has been fixed in master](https://github.com/w3c/aria-practices/commit/e040bfd4980e47f52b7274e828d1142bfeb444dd)).

See https://github.com/w3c/aria-practices/runs/50007038 for the Travis CI result of the change that regressed the build status.

Do we want to mark this job as [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail)?

Further, do we want to block merging PRs to master when checks have failed? This can be done in the project's settings (under Branches).

**Comment by mcking65** [comment]
@zcorpan commented:

>Further, do we want to block merging PRs to master when checks have failed? This can be done in the project's settings (under Branches).

I have enough confidence in our process now, especially with the fix in #993 that I agree this is a good idea. I'll ask Michael to make the change.

**Comment by zcorpan** [comment]
I believe this was fixed back in February.
